### ISSUE TITLE
Cloud Console: Prompt to create storage?

### ISSUE THREAD

**Issue by chrisdias** [Microsoft/vscode-azure-account#10]
In order to use a cloud console I have to set up storage account. In the portal, a "dialog" appears in the console prompting me for a subscription, or an advanced set up where I specify the resource group, etc.

If in VS code I don't have a storage account set up I'm assuming it will fail.  Is there some way to know when this happens and either create the storage account for them or send them to the portal?

**Comment by chrmarti** [comment]
We can probably create the storage account like the Portal does in the non-advanced settings mode. Users new to Azure are unlikely to have that initialized, would be nice if we didn't have to send them somewhere else first.

**Comment by chrmarti** [comment]
Following the advice of the Cloud Console team and avoiding the details of setting things up. Instead a message will be shown directing the user to go to the portal to open the Cloud Console/Shell once.

**Comment by chrmarti** [comment]
Done on the branch.
