### ISSUE TITLE
Add "Select Tenant" command

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode-azure-account#101]

**Comment by kilasuit** [comment]
Any updates on this @chrmarti 

As a consultant with access to many tenants I do not want my tooling to be opening access to all tenants at a time even if I am using the same AAD account to login to each tenant with.

**Comment by kilasuit** [comment]
Whilst I can get round this with the following in my settings.json file this only forces me into the current set tenant & and is not optimal for switching between tenants. 

```json
"azure.tenant": ""
```

**Comment by RMacfarlane** [comment]
@chrmarti Was the idea with this that we would show a quickpick with available tenants instead of having the user go find the tenant id themselves?

**Comment by chrmarti** [comment]
@RMacfarlane Yes, you could also allow for a custom tenant id because when listing tenants we don't necessarily get the complete list of tenants the user has access to. Not sure how important that is though, so having a QuickPick to choose from the known tenant ids might be the main improvement here.

**Comment by wwlorey** [comment]
This could help us set users back on track who are failing to list any of their subscriptions.

`SubscriptionClient` gives us the ability to list known tenants and we can aggregate those into the quick pick. Also, we should replace our guidance on the wiki for manually finding tenant IDs and direct users to use this command instead.

**Comment by wwlorey** [comment]
We shipped support for this command in [v0.10.0](https://github.com/microsoft/vscode-azure-account/releases/tag/v0.10.0).
