### ISSUE TITLE
Adding support for Azure Stack

### ISSUE THREAD

**Issue by sijuman** [microsoft/vscode-azure-account#105]
Hi, 

I hope all is going well! With this extension for VS Code, I would like for there to be support for Azure Stack. This will require a different way to authenticate, but will allow for consistent tooling between Azure and Azure Stack. In this way, other extensions such as Azure Storage would be able to work if Azure Account can be used for Azure Stack. Please feel free to reach out to Bala Ganapathy for assistance.

**Comment by sijuman** [comment]
Is it possible to have this feature by end of December atleast?

Thank you!

**Comment by chrmarti** [comment]
How is the login different? The only Node package I see shows an example where it logs in to public Azure: https://www.npmjs.com/package/azure-arm-azurestack

This is not on our plan at the moment.

**Comment by sijuman** [comment]
@bganapa @knithinc to discuss how the log in is different. 

Is it possible to include it in the plan for end of December?

**Comment by chrmarti** [comment]
Thanks @bganapa. Is there an Azure Stack I can use for testing?

We recently added support for sovereign clouds which has some similarity to supporting Azure Stack. For each sovereign cloud we have an "AzureEnvironment" bag of endpoints (these come with the Azure SDK) and the `/metadata/endpoints` API looks similar to that, but it doesn't have the same properties.

Is there a way to lookup these properties we have, e.g., for public Azure also for any Azure Stack:
```
  static readonly Azure: {
    name: 'Azure',
    portalUrl: 'https://portal.azure.com',
    publishingProfileUrl: 'https://go.microsoft.com/fwlink/?LinkId=254432',
    managementEndpointUrl: 'https://management.core.windows.net',
    resourceManagerEndpointUrl: 'https://management.azure.com/',
    sqlManagementEndpointUrl: 'https://management.core.windows.net:8443/',
    sqlServerHostnameSuffix: '.database.windows.net',
    galleryEndpointUrl: 'https://gallery.azure.com/',
    activeDirectoryEndpointUrl: 'https://login.microsoftonline.com/',
    activeDirectoryResourceId: 'https://management.core.windows.net/',
    activeDirectoryGraphResourceId: 'https://graph.windows.net/',
    batchResourceId: 'https://batch.core.windows.net/',
    activeDirectoryGraphApiVersion: '2013-04-05',
    storageEndpointSuffix: '.core.windows.net',
    keyVaultDnsSuffix: '.vault.azure.net',
    azureDataLakeStoreFileSystemEndpointSuffix: 'azuredatalakestore.net',
    azureDataLakeAnalyticsCatalogAndJobEndpointSuffix: 'azuredatalakeanalytics.net',
    validateAuthority: true
  };
```

Is there documentation on the `/metadata/endpoints` and related APIs?

**Comment by sijuman** [comment]
Hi @chrmarti . We can definitely get you an Azure Stack for testing. I will follow-up with the credentials and how to get started soon. I do not believe you can lookup all of those properties stated in the example, but there is a way to retrieve those values. The link to receive those values is: https://docs.microsoft.com/en-us/azure/azure-stack/user/azure-stack-rest-api-use

Please let me know what else we can do to help. @bganapa 

Thank you!

**Comment by chrmarti** [comment]
The latest update (0.8.1) has a check for ADFS for which it then uses http://127.0.0.1:9472 as the redirect URL instead of https://vscode-redirect.azurewebsites.net.

**Comment by wwlorey** [comment]
Azure Stack support was added in [0.9.5](https://github.com/microsoft/vscode-azure-account/releases/tag/v0.9.5)
