### ISSUE TITLE
URL handling does not work correctly for Azure SignIn in WSL

### ISSUE THREAD

**Issue by AceHack** [Microsoft/vscode-azure-account#110]
Please see
https://github.com/wslutilities/wslu/issues/39
https://github.com/WhitewaterFoundry/WLinux/issues/180#issuecomment-438327732

When you go to sign into Azure it has a button that says Copy and Open.  This button works on windows and opens the default browser, in WSL it does not.

![azuresignin](https://user-images.githubusercontent.com/578953/48424988-deab9280-e731-11e8-9d5f-eb815c9fced1.jpg)

**Comment by sirredbeard** [comment]
I can confirm this one too.

Background:

Code calls xdg-open (part of xdg-utils) which calls /usr/bin/x-www-browser which has been patched by wslview (part of wslu) to open a URL in the user's default Windows browser.

This works well in other apps and other parts of Code just fine. It does not seem to function in the Azure Account extension.

This may or may not be related to #109.

**Comment by chrmarti** [comment]
Could you retry with the latest update to the Azure Account extension? (Version 0.8.1 or later.)
