### ISSUE TITLE
AADSTS50000: There was an error issuing a token

### ISSUE THREAD

**Issue by programmersommer** [Microsoft/vscode-azure-account#120]
I understand, that it might be more related to AAD, but when I am using Azure Account extension from VS Code on Linux everything is working well. When I try to do the same on Windows machine then after visiting 

https://microsoft.com/deviceloginde

and entering code, I am receiving AADSTS50000: There was an error issuing a token

Sure I have tried different browsers and have tried to clear cache. May be I can't have multiple VS Code applications connected to same Azure account?

**Comment by chrmarti** [comment]
Are you trying to sign in to Azure Germany? Does signing in to normal Azure work? Does using a new "private"/"incognito" browser window work?

**Comment by chrmarti** [comment]
@programmersommer You might have accidentally switched to Azure Germany. devicelogin*de* is for Azure Germany, you can use the `Sign-In to Azure Cloud` command to switch back.

**Comment by programmersommer** [comment]
Right. Thank you, @chrmarti
