### ISSUE TITLE
How do I remove subscription and add new subscription in Azure Account extension?

### ISSUE THREAD

**Issue by kudlatiger** [Microsoft/vscode-azure-account#122]
How do I remove subscription and add new one Azure Account extension?

**Comment by chrmarti** [comment]
There is the 'Azure: Select Subscriptions' command to select from existing subscriptions. If you want to create a new subscription, you can do that from the Azure Portal: Go to the [subscriptions](https://portal.azure.com/#blade/Microsoft_Azure_Billing/SubscriptionsBlade) and click the Add button.

**Comment by kudlatiger** [comment]
I tried to run Azure: Select Subscriptions in terminal. but it says 

'Azure:' is not recognized as an internal or external command,
operable program or batch file.

**Comment by kudlatiger** [comment]
Please do not close until I confirm. I do not want to create new subscription. I want to associate different subscription to visual studio/azure account extension

**Comment by chrmarti** [comment]
You'll find that command in the command palette of VS Code (press F1). It will show you all subscriptions it finds for your current account.

**Comment by kudlatiger** [comment]
Resolved Thank you.   F1 key helped!!!

**Comment by chrmarti** [comment]
Great, thanks. Closing.

**Comment by davidorz** [comment]
run "Azure: sign out"  from  command palette of VS Code

**Comment by noah1234j** [comment]
Its saying this its deprecitated and doesn't seem to be working? is there a new way?

**Comment by alexweininger** [comment]
@noah1234j this is a really old issue. I'd encourage you to open a new one if you're having problems. This repo is the best place for issues related to the Azure extensions and authentication and subscription management: https://github.com/microsoft/vscode-azureresourcegroups
