### ISSUE TITLE
Question: How do I run command in 'Azure Account' extension?

### ISSUE THREAD

**Issue by kudlatiger** [Microsoft/vscode-azure-account#123]
I have installed Azure Account extension on Visual Studio Code. I have configured the subscription. Now I want to remove/disassociate from the extension. 

Where shall I run this command? I tried in terminal but not working

> Azure: Select Subscriptions

I get below error

> C:\DeviceSimulator\FunctionApps>Azure: Select Subscriptions
> 'Azure:' is not recognized as an internal or external command,
> operable program or batch file.

Please provide document for new bee like me! Please do not close the question.

**Comment by chrmarti** [comment]
I've reopened the original #122. Closing this one.

**Comment by kudlatiger** [comment]
Resolved Thank you.
