### ISSUE TITLE
sign in failure, redirected to http://127.0.0.1:7/callback?code=

### ISSUE THREAD

**Issue by liranms** [Microsoft/vscode-azure-account#129]
Issue Type: <b>Bug</b>

when signing in to my account, the server redirects to http://127.0.0.1:7/callback?code=AQABA....&session_state=7c58258e-f09c-4e59-9638-6d0a7a7e834e&state=59647%2CyI5sFkYvIs18JjUpZo3BGQ%3D%3D

VS Code is waiting for the response but its an endless wait

Extension version: 0.8.0
VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:20:54.427Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz (12 x 2904)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.74GB (13.61GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>

**Comment by liranms** [comment]
This is the URL that VS Code spawns the browser with:

https://login.microsoftonline.com/common/oauth2/authorize?response_type=code&client_id=aebc6443-996d-45c2-90f0-388ff96faa56&redirect_uri=https://vscode-redirect.azurewebsites.net/&state=59743,LuDSB6UCCLFQhJZuF8AbHA==&resource=https://management.core.windows.net/&prompt=select_account

**Comment by chrmarti** [comment]
@liranms I'm surprised it uses port 7 in your first URI, does it always end there? The second URI shows it should end up at port 59743, does it do that?

**Comment by liranms** [comment]
Yes it's always 7
If I manually change the the port in the failed URL to the one mentioned on "state" variable, it completes the handshake

**Comment by chrmarti** [comment]
Which browser are you using? Could you check in its developer tools what the redirect header looks like that redirects to 127.0.0.1?

**Comment by sdjnaik** [comment]
Hi,

Any updates on above mentioned issue? I am also facing same issue during sign in.

**Comment by chrmarti** [comment]
@sdjnaik Could you open a new issue for us to investigate? Thanks.

**Comment by sdjnaik** [comment]
I am able to get it work through Azure App Services. No-longer facing this issue

**Comment by voltes-7777** [comment]
had the same issue and issue was fixed after setting "http:proxy support" in settings to off.
