### ISSUE TITLE
Create tags for releases

### ISSUE THREAD

**Issue by rcjsuen** [Microsoft/vscode-azure-account#13]
According to [CHANGELOG.md](https://github.com/Microsoft/vscode-azure-account/blob/1f351339da5f39755dcd4fe107de2da6bcebe10d/CHANGELOG.md), there has been a 0.1.0 and a 0.1.3 release. However, there doesn't appear to be any tags in the repository.

I think tags should be created so that it's easier to diff between releases for finding bugs and regressions.

**Comment by chrmarti** [comment]
Added 0.1.3 and 0.2.0 tags.
