### ISSUE TITLE
Signin not Working: timed out

### ISSUE THREAD

**Issue by hempe** [Microsoft/vscode-azure-account#131]
When I try to login, everything seems _normal_
The browser opens, I can select the azure account I want and get redirected to, for example http://127.0.0.1:37723, telling me:
> You are signed in now and can close this page.

But in VS code nothing happens. It stays on 

> Waiting for Azure sign-in...

And after some time I get a timeout in the dev console: 
> console.ts:134 [Extension Host] Error: Error calling StartServiceByName for org.freedesktop.secrets: GDBus.Error:org.freedesktop.DBus.Error.TimedOut: Failed to activate service 'org.freedesktop.secrets': timed out (service_start_timeout=120000ms)

I'm running on linux, using:
- VSCode 1.31.1
- Azure Account 0.8.0
- Node v11.8.0

The account I'm using has multiple directories and subscription.

**Comment by chrmarti** [comment]
We should not wait on `keytar` returning from writing the credentials.

**Comment by chrmarti** [comment]
@hempe Do you have `gnome-keyring` installed? I see a different error when that is missing.

**Comment by hempe** [comment]
@chrmarti Yes I have gnome-keyring installed. Is there some way to get more logs I could provide you with?

**Comment by hempe** [comment]
@chrmarti I checked my keyring, I had a credential called "VS Code Azure/Azure", I deleted this and logged in with vscode again (the cred was added back) and now it seems to work.

**Comment by chrmarti** [comment]
Looks like an issue upstream. I'll close the issue here. Let me know when you see this again.
