### ISSUE TITLE
Extension icon no longer shows up

### ISSUE THREAD

**Issue by heaths** [Microsoft/vscode-azure-account#132]
The following happens across multiple machines. Was working fine at least a few weeks ago, last I noticed:

![image](https://user-images.githubusercontent.com/1532486/53535456-bdd83480-3ab7-11e9-82c1-1cef0d03ab30.png)

VSCode version is the latest on the stable channel:
```
Version: 1.31.1 (system setup)
Commit: 1b8e8302e405050205e69b59abb3559592bb9e60
Date: 2019-02-12T02:20:54.427Z
Electron: 3.1.2
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17763
```

**Comment by chrmarti** [comment]
Fixed as https://github.com/Microsoft/vscode/issues/69376.
