### ISSUE TITLE
Azure Account Windows Credentials Taken By Browser on Matching Account Domain

### ISSUE THREAD

**Issue by trevorNgo** [Microsoft/vscode-azure-account#134]
When running Azure: Sign In, then choosing "Use another account" option, and choosing a matching domain as Windows Account (in example, fakeAccount**@microsoft.com**), it will automatically log into Azure-Account with windows credential.
![image](https://user-images.githubusercontent.com/23327878/54380598-19262d00-4649-11e9-96b2-35eef4f24d57.png)
![image](https://user-images.githubusercontent.com/23327878/54380668-4672db00-4649-11e9-9520-c70523668983.png)
![image](https://user-images.githubusercontent.com/23327878/54380735-74f0b600-4649-11e9-91b6-02f6cc4b5d97.png)

**Comment by chrmarti** [comment]
I guess you are redirect to the Microsoft login page after entering `anything@microsoft.com` and that the reuses the existing session. 🤔

**Comment by hpsin** [comment]
Thanks for the report. Unfortunately this is a known issue with federated IDPs that we are working to improve. ADFS (or other federated IDPs such as Google) don't fully support login hints and prompt= arguments, so they often default to signing in the existing user that's in session.

Our options in Azure are somewhat limited - effectively, always trigger a login prompt at the on-premises IDP and ignore what you typed in. This would result in a significant number of prompts for the user, so we're investigating better ways of handling this behavior.

**Comment by chrmarti** [comment]
Thanks @hpsin. Closing as upstream.
