### ISSUE TITLE
Not able to sign in Azure, have Hyper Switch networks

### ISSUE THREAD

**Issue by manish-sh** [Microsoft/vscode-azure-account#135]
Issue Type: <b>Bug</b>

Code is not able to connect (says internet unavailable) when trying to sign in Azure. I have Hyper V network switch created on my machine, configured for Wireless network.

Extension version: 0.8.0
VS Code version: Code 1.32.3 (a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4, 2019-03-14T22:49:40.955Z)
OS version: Windows_NT ia32 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5300U CPU @ 2.30GHz (4 x 2295)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.60GB (5.68GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>

**Comment by chrmarti** [comment]
Looks like #121. Do you have a proxy configured?

**Comment by manish-sh** [comment]
No, I do not have any proxy. I checked from multiple ISPs (corpnet, home) and same issue.

Additionally, I have Hyper-V VM, connected via a virtual switch.  Not sure if that has an impact.
Is there a way, where I can access the logs which can tell the exact reason. There is no error displayed, just "Waiting for Azure Sign-in" and nothing happens.

Issue:
![image](https://user-images.githubusercontent.com/36769945/55075996-54e5db80-50ba-11e9-8921-8d2f55f6dc20.png)
Proxy:
![image](https://user-images.githubusercontent.com/36769945/55076045-70e97d00-50ba-11e9-914e-6de29a248a47.png)

**Comment by chrmarti** [comment]
Does running `nslookup login.microsoftonline.com` on the command line give you the hosts IP address?

**Comment by manish-sh** [comment]
I am able to run nslookup. Below is the output:
<<My machine details>>
Non-authoritative answer:
Name:    gwmigprda.aadg.windows.net.nsatc.net
Addresses:  _**<<I deleted the address, to mask IP address, there are 6 IPs starting from 40.12*.>>**_
Aliases:  login.microsoftonline.com
          www.prdtm.aadg.akadns.net

**Comment by chrmarti** [comment]
Could you retry with the latest update to the Azure Account extension? (Version 0.8.1 or later.)

**Comment by manish-sh** [comment]
Updated and checked, still getting error that I am offline:
![image](https://user-images.githubusercontent.com/36769945/55476575-99cabe80-5634-11e9-9072-50ac0b9632eb.png)

**Comment by chrmarti** [comment]
Please check your 'Azure: Cloud' setting is set to 'Azure':
![image](https://user-images.githubusercontent.com/9205389/55481707-41d78c00-5623-11e9-8167-6c92928afb00.png)

**Comment by manish-sh** [comment]
Some progress post changing settings. Now, it is asking me to open browser and enter some code. Issue is, post entering the code it is not reflected back to VS Code. It is asking again and again to open browser and enter the code:
![image](https://user-images.githubusercontent.com/36769945/55626779-10e58b80-57ca-11e9-90ac-34113330cad3.png)

**Comment by chrmarti** [comment]
After entering the code, the browser should take you through the sign-in and finally tell you that you are signed-in. Shortly after that, VS Code should update its status bar and show the email address you used for logging in.

Is that not the case? Are there any errors in the DevTools (Help > Toggle Developer Tools)?
