### ISSUE TITLE
Detect when local server cannot be connected to

### ISSUE THREAD

**Issue by barde** [Microsoft/vscode-azure-account#136]
Issue Type: <b>Bug</b>

When running in a container all login methods for Azure (Device Code and the default way with redirect to localhost:37207) fail. There is no error message and the GUI offers me to log in.

This can be tested by running in a ChromeOS crostini environment.

VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:49:48.319Z)
OS version: Linux x64 4.14.74-07776-gac52e5f750c8

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|06/8e (4 x 1607)|
|GPU Status|2d_canvas: unavailable_software<br>checker_imaging: disabled_off<br>flash_3d: unavailable_software<br>flash_stage3d: unavailable_software<br>flash_stage3d_baseline: unavailable_software<br>gpu_compositing: unavailable_software<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled_readback<br>webgl2: unavailable_off|
|Load (avg)|0, 0, 0|
|Memory (System)|10.63GB (6.40GB free)|
|Process Argv||
|Screen Reader|no|
|VM|100%|

</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-azureappservice|ms-|0.11.0
vscode-azurefunctions|ms-|0.13.1
vscode-azurestorage|ms-|0.5.0
azure-account|ms-|0.8.0
azurecli|ms-|0.4.2
vscode-node-azure-pack|ms-|0.0.5
team|ms-|1.144.1
azurerm-vscode-tools|msa|0.4.2
vscode-docker|Pet|0.5.1

</details>

**Comment by chrmarti** [comment]
Does your system have `gnome-keyring` installed?

**Comment by barde** [comment]
`~ gnome-keyring
fish: Unknown command 'gnome-keyring'`

No.

**Comment by barde** [comment]
I suppose the redirect does not work as the launched browser from Crostini is the "native" one from ChromeOS which does not find the opened port on the crostini VM as it is probably not redirected to the ChromeOS host.

**Comment by chrmarti** [comment]
@barde Could you try the device code sign-in? That is less convenient, but should work in this case.

![image](https://user-images.githubusercontent.com/9205389/55708462-4961b100-59e6-11e9-94f2-9d266c217f84.png)

**Comment by barde** [comment]
After confirming the device code VS Code shows a non-logged in interface.

**Comment by chrmarti** [comment]
Did the website ask you to pick an account and sign-in to that? Is there anything in the console (Help > Toggle Developer Tools)?

**Comment by barde** [comment]
After deleting all cookies from Azure, updating VS Code and trying to do the device-login it works. :)

Still, the issue with the original callback method is somewhat annoying. Maybe it could be deactivated on VS Code running in a Chromebook emulation without real localhost passthrough?

**Comment by chrmarti** [comment]
I have seen deletion of cookies help before. 👍 

We rely on the keytar NPM package which needs gnome-keyring for storing tokens. Not sure what we can do there. (https://github.com/atom/node-keytar/issues/74)

If we can detect that the local server won't be reachable from the browser, we can automatically fall back to the device code sign-in. Unfortunately I don't know of a way for doing that.

**Comment by chrmarti** [comment]
We can open the browser on the local server first (and immediately redirect) and show a message suggesting to use device login when that request doesn't come through within 10 seconds.
