### ISSUE TITLE
Cannot connect to 127.0.0.1

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode-azure-account#138]
I am having a similar issue
VS Code 1.32.
Azure Account Extension
When I try to Azure: Sign In, I select my email from the web page and then get 127.0.0.1 could not connect. I am not behind a firewall (that I know of).

_Originally posted by @chr1s3sw0rthy in https://github.com/Microsoft/vscode-azure-account/issues/109#issuecomment-479642157_

**Comment by chrmarti** [comment]
@chr1s3sw0rthy Which port is it trying to connect to?

Maybe your local firewall is preventing the browser from connecting to that temporary local port that is waiting for a response?

**Comment by chr1s3sw0rthy** [comment]
plausible. I moved to Spain and dont know enough about firewalls or spanish
to solve that problem.

I was able to get in using a Device Code.

Thank you.

**Comment by chrmarti** [comment]
Not sure where Spanish gets into the picture. I will then close this issue if you are fine with using the device code flow.
