### ISSUE TITLE
Azure signs out on reload

### ISSUE THREAD

**Issue by shsuman** [microsoft/vscode-azure-account#139]
OS: Ubuntu 18.04 LTS
VScode :1.33.1
 Every time I reload window the Azure signs out of VSCode

**Comment by chrmarti** [comment]
Do you have gnome-keyring installed?

**Comment by shsuman** [comment]
No. I do not

**Comment by chrmarti** [comment]
We should maybe detect this case and show a notification that gnome-keyring is currently needed on Linux.

Let me know if you still see issues after installing that.

**Comment by wwlorey** [comment]
Assuming this is no longer an issue, please let us know otherwise
