### ISSUE TITLE
Cache subscriptions

### ISSUE THREAD

**Issue by chrisdias** [Microsoft/vscode-azure-account#14]
Maybe we can cache the list of subscriptions?  When I do F1 | Select Subscriptions it takes a long time for the list to show up. And, when i query for the subscriptions from my extension it can take 10s for them all to return.

my guess is that subscriptions don't change very often, so if we cached that would be ok.  if the subscriptions changed, the user would need to reload.

**Comment by chrmarti** [comment]
@chrisdias Just pushed this to master. There might have been shortcuts, but I opted for an API change that plays well with the existing API and also updates the list of subscriptions when you sign out.
