### ISSUE TITLE
Azure SSO issues in VS Code?

### ISSUE THREAD

**Issue by billbliss** [microsoft/vscode-azure-account#144]
In the MS Teams documentation, where we walk through how to use VS Code to deploy Teams apps to Azure, a user ran into what looks like an SSO issue. See here: https://github.com/MicrosoftDocs/msteams-docs/issues/737

Anyone on this repo able to give some pointers? It has nothing to do with Teams, obviously.

@azzurolilc

**Comment by chrmarti** [comment]
The description of the issue indicates that this is a problem with the web-based login flow, not the VS Code extension.

Does clearing cookies for the login site help?
