### ISSUE TITLE
Azure Account Sign-In does not work in VSCode  Complains About Nonexistent Proxy

### ISSUE THREAD

**Issue by klawrawkz** [microsoft/vscode-azure-account#145]
I'm mystified by this.  The Azure Account Extension is complaining about a proxy that does not exist seemingly because it is setting up a return call to my box with a proxy inserted.  To add to the confusion, I'm already on Azure, so why do I need to login again?  Here is the flow:

1. vs code command palate: Azure sign in (cloud or um... azure)
![image](https://user-images.githubusercontent.com/48074223/60538693-11ae9080-9cd9-11e9-9b65-5a61d353bf53.png)

2. browser opens with login "pick an account" thingy UI:
![image](https://user-images.githubusercontent.com/48074223/60538949-9f8a7b80-9cd9-11e9-9f6d-68bbf96ab7f0.png)

3. select the account you are already signed in on... and Blam! Bizarre proxy error!  My interpretation is this is baked in the URL cake that Account bundled with the original request.  Weird?  YUP.
![image](https://user-images.githubusercontent.com/48074223/60539278-453dea80-9cda-11e9-9ae2-99c4ad012b73.png)

What's the deal?  What am i missing here?  I have no proxy in place...
![image](https://user-images.githubusercontent.com/48074223/60539727-69e69200-9cdb-11e9-9127-28b994e10416.png)

Is there some **super-secret proxy** behind the scenes?  Or is it a lord of the proxies deal with one proxy _to BIND them??_

Here's the entire url that is produced leading to the "proxy" failure report:
```http://127.0.0.1:3979/callback?code=AQABAAIAAADCoMpjJXrxTq9VG9te-7FXXOLPEPwGfradKtd52ERp40wkIsYfAuFO0c7rDwSCKA3JXxNXjcCm4d9wJka5tm0iot49j5mMCP7nyr_F9PavgiTlgtYXu-8OtTWQ3HZHjqc38KvY-Xumac4jK9WPd1oTJ-KzVgTN57dauBYe1obMnLl3lFHEm3bx0nusjW-hV1v6T90BRL7LukYMpYGgR9ir-_k3atnk3sB-6OqUuTKbxkh7OxuYMipwmxWN4VGvg9xIhrPqeI3yzFhcvpVfZ2HIaXWbmD9HzwISprdd3cQOBoPrnakeHswRWEnhfvbS3IiMCTYfHk4i2KnPIhw-cv7jhtAMh2f4c2YgWhVxx6UtAYeL5snkCUORf699e1V-Wgqe5nHjvkA_osxc0QFDQNY4m9rVhPYdA2HGPr9hglexrpuqF1xIlu9xzwJ38KgBPWdZnJZIIsMdbDJ7etNkjfvN8AyQ_qmcNRzRRxxjo2q1pBHej2mDp6CJ6es-dQS54aI1PeWIn_h46rL2d1w8NMLbpggbnmKeuyu-50FzmYBt1Aj6FMzDyYqy2NYYUvG9t36W-Ly_kzsME4P87n5BMJlifYiBLz6AvSclSkytUU58bCAA&state=3979%2cI%2fISfFxwhMVwtxKGXfCw0g%3d%3d&session_state=6c1e2e8a-2fa9-42f7-b943-d35864072fd0```

![image](https://user-images.githubusercontent.com/48074223/60540107-60115e80-9cdc-11e9-8f22-82e6376079c3.png)

What say you?

**Comment by tillik** [comment]
Why do you think this is related to a proxy?
The extension ms-vscode.azure-account tries to create a local socket for your browser to call back to after successfull login and thus notify the extension (my interpretation).
Can you run code --verbose and see if an error comes up when trying to log into Azure telling you that a tunneling socket could not be established?

**Comment by chrmarti** [comment]
Could you retry? This looks like it might have been a service issue.
