### ISSUE TITLE
Azure Account Sign-In is stuck in loading state if login window is closed in browser

### ISSUE THREAD

**Issue by dikhakha** [microsoft/vscode-azure-account#148]
Steps to repro:
1. Execute command Azure Sign-In
2. Login window opens in browser. 
3. Close the window
4. Come back to VS code, the extension pane shows 'Waiting for Azure to Sign-in'

We are consuming this extension to let the user sign-in to azure. However, the command does not send any event for above scenario. What is the recommended way to react to this scenario when consuming azure account extension api ?

![image](https://user-images.githubusercontent.com/21305620/63862749-b5ab7400-c9ca-11e9-85e2-53d66027f9fa.png)

**Comment by chrmarti** [comment]
We don't get an event when the browser window/tab closes. There is a timeout timer, but that is 5 minutes to allow for the login to finish (and that might be too early in rare cases).

**Comment by chrmarti** [comment]
I will close this since it is a limitation of the approach of using a separate browser and we are unlikely to change this.
