### ISSUE TITLE
Azure Account extension cannot work in Remote-WSL.

### ISSUE THREAD

**Issue by dilin-MS** [microsoft/vscode-azure-account#152]
Hi, we found that the `Azure Account` extension does not support [remote-wsl](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-wsl). All extension commands cannot work properly. Since we have extension use `Azure Account` as a dependency extension, out extension cannot work properly too in remote-wsl mode. We wonder will `Azure Account` support remote-wsl mode.

Reproduce:
1. Install VS Code and install Remote-WSL extension.
2. under `myproject` folder, run `code .` to open `myproject` in remote-wsl mode.
3. Install `Azure IoT Hub Tookit` extension which use `Azure Account` as a dependency extension. Both extensions can be installed successfully, but can not work showing `command not found`. Error message in developer tools is as follow.
![image](https://user-images.githubusercontent.com/41713563/65653646-a1e64280-e048-11e9-8680-90a097418009.png)

`Azure Account` seems to have a different release for wsl mode: `Azure Account Workspace API 0.9.0(ms-vscode.azure-account)`. Is this special version have special usage? Did we miss something?

Thanks for help.

**Comment by chrmarti** [comment]
You seem to be using an experimental version of Azure Account. Could you uninstall all Azure Account extensions and then install the current version (0.8.4)?

**Comment by dilin-MS** [comment]
My extension use `Azure Account(ms-vscode.azure-account)` as dependency extension and does not denote version. In remote-wsl mode, when try to install my extension, VS Code will install the dependent extension and VS Code install the `Azure Account Workspace API`. Why is that? How to auto-install the right version?

**Comment by chrmarti** [comment]
Which version of VS Code are you running? Note that you need to restart VS Code after uninstalling the extensions before reinstalling.

**Comment by dilin-MS** [comment]
VS Version:1.38.1
OS: Windows_NT x64 10.0.18362

I retried just now and I can install the right Azure Account and extensions work properly now. 
![image](https://user-images.githubusercontent.com/41713563/65738976-54d0a200-e116-11e9-8a23-1fb9a665f9b4.png)

Thanks for the help!

**Comment by chrmarti** [comment]
Great, thanks.
