### ISSUE TITLE
Incompatible version 0.8.10 vsix downloaded from marketplace

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode-azure-account#153]
**Repo**
1. Go to extension page on marketplace: https://marketplace.visualstudio.com/items?itemName=ms-vscode.azure-account
1. Click the `download extension` link to get the vsix

**Bug**
This downloads a version 0.8.10 that cannot be installed on any VS Code version as it has 

```
  "engines": {
    "vscode": "^1.999.0"
  },
```

Here's the download link: https://marketplace.visualstudio.com/_apis/public/gallery/publishers/ms-vscode/vsextensions/azure-account/0.8.10/vspackage

**Comment by chrisdias** [comment]
i can confirm i see this in the vsix:

``` json
  "engines": {
    "vscode": "^1.999.0"
  },
```

**Comment by chrisdias** [comment]
But the downloaded .vsix for 0.8.6 that is installed locally looks fine.

**Comment by chrmarti** [comment]
Wrote the marketplace team.

**Comment by RMacfarlane** [comment]
This issue has been fixed by the marketplace team
