### ISSUE TITLE
Azure login forwards to localhost

### ISSUE THREAD

**Issue by FelschR** [microsoft/vscode-azure-account#155]
When I try to login to my Azure account it opens the following localhost URL in the browser instead of an Azure website:
`http://localhost:41567/signin?nonce=[x]`

The used ports seem to be different each time.

Using the "Sign in with Device Code" option works though.

I'm on a Linux system.

**Comment by chrmarti** [comment]
This is by design. There should be a temporary server listening on that port to help with the sign-in flow. Does that not work?

**Comment by poiu2131** [comment]
@FelschR  Hi, I have a same issue as your. did you already fix it? can you share the solution? thanks

**Comment by FelschR** [comment]
I didn't find a solution but I just checked it again and it's working for me now.

**Comment by poiu2131** [comment]
@FelschR did you change anything?

**Comment by FelschR** [comment]
Well, nothing except installing updates for VS Code & its extensions.
I actually had the Azure extensions uninstalled for a while, but I doubt that reinstalling would've fixed it somehow.

**Comment by poiu2131** [comment]
@FelschR I see. I just tried reinstall/check upgrade for the all but it still not work. But it can work after I downgrade "Azure Account" from 0.8.11 to 0.8.1

**Comment by LucaColonnello** [comment]
Having the same issue on VS Code here!
Trying to sign in with Microsoft to turn on the sync but it does not work...

**Comment by lasyan3** [comment]
I disabled the extension "Cloud Explorer for VS 2019 Preview" and it worked after restart VS (not sure it's related).

**Comment by klaydze** [comment]
I have the same issue lately. I found [this comment](https://github.com/Azure/azure-cli/issues/10426#issuecomment-528308713). Hope this will help you.
