### ISSUE TITLE
Quesiton: How to acquire refresh token for customized resource?

### ISSUE THREAD

**Issue by t-rufang** [microsoft/vscode-azure-account#158]
After user sign in, we can get access token and refresh token from `AzureSession.credentials`. This refresh token is for resource `https://management.core.windows.net/`. However, refresh token what we need is for another resource. My question is do we have some api like `fun getToken(resourceID: String): String` to get refresh token for our customized resource?
BTW, a workaroud we take now is to send a POST request to use access token to access customized resource which is based on [this doc](https://docs.microsoft.com/en-us/azure/active-directory/develop/v1-protocols-oauth-code#use-the-access-token-to-access-the-resource)

FYI, please find our the VSCode extension repo at https://dev.azure.com/bigdatabj/HDInsightVSCodeExtension

**Comment by chrmarti** [comment]
There is no API, but you could use the code here: https://github.com/microsoft/vscode-azure-account/blob/f4d255f913d78ad4f69eb67cc8ae0b1972082e39/src/azure-account.ts#L788 to do that.

We use that to get tokens for other resources (e.g., KeyVault and Graph) here: https://github.com/microsoft/vscode-azure-account/blob/f4d255f913d78ad4f69eb67cc8ae0b1972082e39/src/cloudConsole.ts#L382
