### ISSUE TITLE
Connect-AzAccount doesn't work from VS Code

### ISSUE THREAD

**Issue by JacksReacher** [microsoft/vscode-azure-account#161]
Hey guys;

After the last update, the device authorization within VS Code no longer works. In the PowerShell console, the command works. I get the authorization message, the link opens the browser (Chrome) and I am able to supply the code and the browser notifies me that I'm logged in, but VS Code throws the following error:

WARNING: To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code BMFK5Z4HG to authenticate.
[12/19/2019 10:21:50]: [Error occurred during New-FeatureTeamSQLManagedInstanceFull function.] Exception: [AADSTS50097: Device authentication is required.
Trace ID: 3012303b-a268-4ad2-9d5a-3a8294891300
Correlation ID: 2ca939c0-3836-4f8d-bb3c-be01517867ef
Timestamp: 2019-12-19 18:21:49Z: Response status code does not indicate success: 401 (Unauthorized).]\r\n[[AADSTS50097: Device authentication is required.
Trace ID: 3012303b-a268-4ad2-9d5a-3a8294891300
Correlation ID: 2ca939c0-3836-4f8d-bb3c-be01517867ef
Timestamp: 2019-12-19 18:21:49Z]\r\n[[Response status code does not indicate success: 401 (Unauthorized).]\r\n[[{"error":"invalid_grant","error_description":"AADSTS50097: Device authentication is required.\r\nTrace ID: 3012303b-a268-4ad2-9d5a-3a8294891300\r\nCorrelation ID: 2ca939c0-3836-4f8d-bb3c-be01517867ef\r\nTimestamp: 2019-12-19 18:21:49Z","error_codes":[50097],"timestamp":"2019-12-19 18:21:49Z","trace_id":"3012303b-a268-4ad2-9d5a-3a8294891300","correlation_id":"2ca939c0-3836-4f8d-bb3c-be01517867ef"}: Unknown error]]]]

**Comment by chrmarti** [comment]
Cannot reproduce. @JacksReacher Could you try again to check if this was a temporary issue? Please again post the error message, if there is one. (The correlation id might help us track down the root cause.)
