### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by chonthichayaver** [microsoft/vscode-azure-account#162]
- Issue Type: `Bug`
- Extension Name: `azure-account`
- Extension Version: `0.8.7`
- OS Version: `Windows_NT x64 6.1.7601`
- VSCode version: `1.42.0-insider`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by chonthichayaver** [comment]
good

**Comment by chrmarti** [comment]
Details are missing.
