### ISSUE TITLE
Mac: Code Helper (Renderer) wants to use your confidential information

### ISSUE THREAD

**Issue by foucdeg** [microsoft/vscode-azure-account#163]
Since recently, when I open VS Code with my usual extensions, I get a system password prompt with the following message:

> Code Helper (Renderer) wants to use your confidential information stored in "VS Code Azure" in Keychain.

This thread https://github.com/microsoft/vscode/issues/84932#issuecomment-554865071 had me disable my extensions one by one until I was able to single out the Azure Functions extension. When it is disabled, the behaviour doesn't happen. This is new behaviour (I've used the extensions since June and the issue happened two weeks ago).

I posted an issue with the Azure Functions extension https://github.com/microsoft/vscode-azurefunctions/issues/1759 where they told me it was probably an issue with the Azure accounts extension.

How can I avoid this password prompt?

**Comment by chrmarti** [comment]
Is there an "Always Allow" option on the dialog? The Azure Account extension will always attempt to read from the keychain when activated and the Azure Functions extension appears to activate it in your case.

**Comment by foucdeg** [comment]
How could I miss the "Always Allow" option? 🙄
