### ISSUE TITLE
Unable to switch directories

### ISSUE THREAD

**Issue by owingruters** [microsoft/vscode-azure-account#166]
Hi,

It seem that there is (or I am missing) a pallet command to switch directories.
Currently when I sign in and want to select subscriptions, I can only see the subscribtions of 1 directory. So it seems there should be a possibility to switch these, like that is also possible in the Azure portal.

Thanx

**Comment by chrmarti** [comment]
We try to discover all tenants. If that doesn't work in your setup, you can set the current tenant with `"azure.tenant"` setting. Having a command for doing that might still makes sense.

**Comment by owingruters** [comment]
In my case it only lists the subscriptions of 1 tenant. All would be fine for me, but might not for people taht have even more tenants than me. 

How can I set that azure.tenant setting?

**Comment by chrmarti** [comment]
Go to `File > Preferences > Settings` and search for 'azure tenant'. Enter the tenant's id there (long, of the format: 6ef302f8-ede7-48b2-9660-ba17f9d98a9e):
![image](https://user-images.githubusercontent.com/9205389/72719683-94fdd980-3b78-11ea-8722-427611e530c0.png)

**Comment by owingruters** [comment]
Thanx for this feedback, that works like a charm.
But indeed is not a very userfriendly way of doing it, so I'd love to see that addition.

After realizing tat Directory and Teant is the same thing, this one and https://github.com/microsoft/vscode-azure-account/issues/101 are probably duplicates

**Comment by chrmarti** [comment]
Indeed, thanks.

/duplicate #101
