### ISSUE TITLE
Not able to select subscription

### ISSUE THREAD

**Issue by frnk01** [microsoft/vscode-azure-account#169]
It`s not possible to select Azure subscription in VSCode. I get a list of my four available subscriptions where two are marked. Nothing happens when i select one of the other two. The next time I open the "Select subscription" list the check mark is gone.

I`ve tried the following:

- Selecting and then pressing tab or enter
- Tried two accounts
- Tried reinstalling all extensions
- Tried restarting

Any help would be much appreciated.

**Comment by chrmarti** [comment]
Tracked as https://github.com/microsoft/vscode/issues/90365. Pressing 'Enter' should accept your choice too.
