### ISSUE TITLE
Cloud Shell rendering issue with tmux

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode-azure-account#17]
- Open Bash in Cloud Shell
- Run tmux and split vertically (Ctrl + b, %)
- Switch between panels and add some output (Ctrl + b, o)
- Sometimes the vertical ruler between the panels disappears, sometimes parts of the text in one of the panels disappears

So far not reproduced with local tmux.

**Comment by wwlorey** [comment]
Closing as out of scope
