### ISSUE TITLE
Login-AzAccount : AADSTS50000: There was an error issuing a token or an issue with our sign-in service.

### ISSUE THREAD

**Issue by KasamShaikh** [microsoft/vscode-azure-account#171]
When trying to login using Window PowerShell ISE, Login-AzAccount command, I am being prompted to enter username and password, but then instead of prompting for Auth code, it throes the error,

Trace ID: 78a52fb1-6427-48db-9e07-6fa7c8faee00
Correlation ID: 75f55382-d7bc-43cd-93c5-ec9a28805aa6
Timestamp: 2020-03-03 15:44:47Z
At line:2 char:1
+ Login-AzAccount
+ ~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Connect-AzAccount], AdalServiceException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Profile.ConnectAzureRmAccountCommand\

Kindly help.

**Comment by RMacfarlane** [comment]
@KasamShaikh I'm not able to transfer this issue, can you please reopen it on https://github.com/Azure/azure-powershell?
