### ISSUE TITLE
[Question] How to get ADL access token

### ISSUE THREAD

**Issue by lzw-all-in** [microsoft/vscode-azure-account#172]
Hi teams, this is a question for details in login ADL because I'm facing the same scenario too. In my web application, I want to get every user's access token for ADL .So I need to mock the login flow just like your program. But I have some questions about it 
1. I saw the login url and found that the client_id=aebc6443-996d-45c2-90f0-388ff96faa56 and this is not ADL client_id . In my understanding If we need ADL access token we need to choose ADL client_id right ? I also know that we need to set redirect url but for ADL we're not admin so we can't do that. Could you tell me how to get ADL access token form other client_id ?
2. How to generate the login url ?

Thanks!

**Comment by chrmarti** [comment]
Is ADL = Azure Data Lake? This looks like what we do: https://docs.microsoft.com/en-us/azure/data-lake-store/data-lake-store-end-user-authenticate-rest-api

**Comment by lzw-all-in** [comment]
@chrmarti  Thanks for your help. Yes, ADL is Azure Data Lake.(Actually I'm an intern at Microsoft)
I'm fully understand this login flow but I need Admin to grant my app a permission to access ADL.

Do you know how to apply this permission ?  Thanks!

**Comment by chrmarti** [comment]
The VS Code app is a first-party app, that might make a difference here. Does it work when you use the VS Code app id?

The Azure Portal allows you to grant admin right to applications. There is a policy in place that disallows that for the Microsoft tenant, but maybe you are using a different tenant?

That's as much as I know, not an expert on this matter myself.

**Comment by lzw-all-in** [comment]
@chrmarti Thank you so much !  
I'm using a Microsoft tenant and I will check more docs on Azure.  : )

**Comment by chrmarti** [comment]
You might need a service principal then. Haven't tried that myself, hope it helps: https://docs.microsoft.com/en-us/azure/active-directory/develop/howto-create-service-principal-portal

Closing issue.
