### ISSUE TITLE
The access token has been obtained for wrong audience or resource 

### ISSUE THREAD

**Issue by pshukla03** [microsoft/vscode-azure-account#175]
Issue Type: <b>Bug</b>

Getting intermittent error for Azure CLI Scrapbook while running powershell in CloudShell

The access token has been obtained for wrong audience or resource 'https://graph.windows.net/'. It should exactly match with one of the allowed audiences 'https://management.core.windows.net/','https://management.core.windows.net','https:ement.core.windows.net','https://management.azure.com/','https://management.azure.com'.
InvalidOperation:

Extension version: 0.5.0
VS Code version: Code 1.43.2 (0ba0ca52957102ca3527cf479571617f0de6ed50, 2020-03-24T07:38:38.248Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.84GB (6.20GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by chrmarti** [comment]
@pshukla03 Could you attach a screenshot to make sure we understand the setup?
