### ISSUE TITLE
Error accessing registry "aad retrieve token failed"

### ISSUE THREAD

**Issue by aelray** [microsoft/vscode-azure-account#183]
Hi,

I'm having problem accessing a registry in azure through this plugin. When using docker on command line I can login and pull images without problems from the registry. But when accessing through this plugin I obtain: "Error: aad retrieve token failed"

**Comment by RMacfarlane** [comment]
@aelray Can you include the code you're using to access the registry?

**Comment by aelray** [comment]
@RMacfarlane I did not really code anything here. I just installed the plugin and it recognized the registry, I think because I accessed it beforehand using docker CLI.

**Comment by RMacfarlane** [comment]
@aelray Is this view within the "Docker" view container? I believe this is actually coming from that extension if so

**Comment by aelray** [comment]
@RMacfarlane Oh you're probably right. So I'll close it here.
