### ISSUE TITLE
Sign in page still has the old VS Code product icon

### ISSUE THREAD

**Issue by chryw** [microsoft/vscode-azure-account#184]
Repro:
1. Ctrl/Cmd + Shift + P
2. Azure: Sign in
3. Sign in via browser
4. Land on this page -
![image](https://user-images.githubusercontent.com/7075677/81980576-b8dfa200-95e3-11ea-93ad-43a78962f87e.png)

Not sure if this image is from VS Code or this extension. Please use the new product icon.

[BrandVisualStudioCode2019.zip](https://github.com/microsoft/vscode-azure-account/files/4630636/BrandVisualStudioCode2019.zip)
PS: Actually you should be getting this asset from Brand Central but the brand guideline and product icon assets are still WIP. I just attached the files here.

**Comment by RMacfarlane** [comment]
Thanks for catching this!
