### ISSUE TITLE
How to  connect azure powershell using visaul  studio code

### ISSUE THREAD

**Issue by Ashumishra14** [microsoft/vscode-azure-account#185]
Please provide some steps to follow  to  connect azure powershell using visual  studio code

**Comment by RMacfarlane** [comment]
You can use the "Azure: Open PowerShell in Cloud Shell" command by hitting F1 and searching for the command within the command palette. Is that what you're looking for?

**Comment by Ashumishra14** [comment]
@RMacfarlane thanks this has been accomplished . I am new to this azure thing so i was unable to connect my visual studi code to azure . I finally downloaded ythe azure account and then node.js and i am able to connect .
