### ISSUE TITLE
Use cloud metadata for discovering clouds

### ISSUE THREAD

**Issue by fiveisprime** [microsoft/vscode-azure-account#188]
Internal request:

> For better customer experience and to ensure parity across all clouds, Azure tools/SDK's should leverage the cloud metadata discovery pattern as opposed to hard-coding metadata. Also, hard coding metadata in open source is prohibited for LX.

**Comment by RMacfarlane** [comment]
@fiveisprime Is there additional documentation on this somewhere? I'm not sure what's meant by "cloud metadata discovery pattern", what metadata is this referring to?

**Comment by fiveisprime** [comment]
I sent you email with more context 👍
