### ISSUE TITLE
After successfully logging in redirecting to 1270.0.1:63803. getting "cant reach this page" error

### ISSUE THREAD

**Issue by satyamnijam** [microsoft/vscode-azure-account#189]
http://127.0.0.1:63803/callback?code=<SOMECRAZYCODE>&state=63803%2c2UbECkUOcsjYAoP0tMmdRw%3d%3d&session_state=9be1a6cd-34dd-47a9-b968-219306f64930

**Comment by wwlorey** [comment]
Hi @satyamnijam, are you still running into this error using the latest version (0.9.8)?
