### ISSUE TITLE
Unable to sign in to ADFS based Azure Stack environment

### ISSUE THREAD

**Issue by rakku-ms** [microsoft/vscode-azure-account#190]
Using below JSON snippet to sign in to Azure Stack environment from Azure Account VS Code extension

```
{
    "azure.tenant": "81cfafcd-8b9a-4419-9c85-823b54076b55",
    "azure.ppe": {
        "activeDirectoryEndpointUrl": "https://adfs.redmond.azurestack.corp.microsoft.com/adfs/",
        "activeDirectoryResourceId": "https://management.adfs.redmond.selfhost.local/81cfafcd-8b9a-4419-9c85-823b54076b55",
        "resourceManagerEndpointUrl": "https://management.redmond.azurestack.corp.microsoft.com/",
    },
    "azure.cloud": "AzurePPE",
    "workbench.settings.editor": "json"
}
```

I see "You are signed in now and can close this page." message in my browser
However, VS Code still shows "Azure: Signing in..."

**Comment by bganapa** [comment]
This is a regression, The scenario used to work with AzureStack ADFS, Please ping us for AzureStack Environment access. Thanks for looking in to this issue!

**Comment by RMacfarlane** [comment]
I haven't made any significant changes to the extension recently, can you please try to identify the last working version of it? You can use the "Install Another Version" option to do this from the extensions viewlet:
![Screen Shot 2020-06-11 at 11 12 16 AM](https://user-images.githubusercontent.com/3672607/84424125-7bffce80-abd4-11ea-970b-951d475e1473.png)

**Comment by RMacfarlane** [comment]
[azure-account-0.8.12.zip](https://github.com/microsoft/vscode-azure-account/files/4867166/azure-account-0.8.12.zip)
