### ISSUE TITLE
Docs about usage from own extension

### ISSUE THREAD

**Issue by tfenster** [microsoft/vscode-azure-account#192]
In issue #91, more specifically [the last comment](https://github.com/microsoft/vscode-azure-account/issues/91#issuecomment-423988753), some documentation on using the authentication information in an own extension is mentioned. I searched but couldn't find anything. Was that documentation created and if yes, where can I find it?

**Comment by wwlorey** [comment]
Hi @tfenster, is this sample helpful? https://github.com/microsoft/vscode-azure-account/tree/main/sample

Or did you have other documentation in mind that you need?

**Comment by tfenster** [comment]
Hi @wwlorey thanks for your feedback. We used `vscode.commands.executeCommand('azure-account.login')` instead of `vscode.commands.executeCommand('azure-account.askForLogin')`, but that seems to be a minor implementation detail? 

However we are using `session.credentials` instead of `sessions.credentials2`. Do you have any insight into how long that will be supported or what the roadmap is there? We need tokens for different audiences (management.core.windows.net, vault.azure.net, graph.windows.net among others) and were only able to make that work with `credentials`, but not with `credentials2`

**Comment by wwlorey** [comment]
> We used vscode.commands.executeCommand('azure-account.login') instead of vscode.commands.executeCommand('azure-account.askForLogin'), but that seems to be a minor implementation detail?

@tfenster, [`azure-account.askForLogin`](https://github.com/microsoft/vscode-azure-account/blob/685823af1274a6227660d61606d241a97aacd5df/src/login/AzureLoginHelper.ts#L467-L474
) just calls `azure-account.login` after a prompt, so either one is fine depending on the functionality you need.

> were only able to make that work with credentials, but not with credentials2

We are currently working on support for MSAL (`credentials2` uses ADAL today) which may work for your situation. At this time we don't have a concrete timeline on support for `credentials` but I'll make a note that you're still relying on it.

**Comment by tfenster** [comment]
@wwlorey great, thanks
