### ISSUE TITLE
Error accessing registry "aad retrieve token failed"

### ISSUE THREAD

**Issue by ww201782** [microsoft/vscode-azure-account#194]
Hi,

I'm having problem accessing a registry in azure. I succfully pushed the image. When I want to deploy my image Azure App Service, it show me: 
![1](https://user-images.githubusercontent.com/46827922/84189060-00364280-aa6b-11ea-84fd-9f85dbbe9de8.PNG)

**Comment by ww201782** [comment]
I think it should be perfomed like this
![image](https://user-images.githubusercontent.com/46827922/84189304-720e8c00-aa6b-11ea-8501-921ad1cf6045.png)

**Comment by RMacfarlane** [comment]
@ww201782 Please file this on the docker extension: https://github.com/Microsoft/vscode-docker Thank you!
