### ISSUE TITLE
Sign In multifactor authentication does not work.

### ISSUE THREAD

**Issue by angelcervera** [microsoft/vscode-azure-account#200]
When I Sign in, It is opening the sign-in window and asking for the password. But it never asks for the MTA.

VS looks logged, but when trying to select a subscription, a message "No subscriptions were found. Set up your account...."

Checking the console, this is the hidden error I can read:
```
Error: Get Token request returned http error: 400 and server response: {"error":"interaction_required","error_description":"AADSTS50076: Due to a configuration change made by your administrator, or because you moved to a new location, you must use multi-factor authentication to access ............
```

VS Code:
```
Version: 1.46.1
Commit: cd9ea6488829f560dc949a8b2fb789f3cdc05f5d
Date: 2020-06-17T21:13:08.304Z
Electron: 7.3.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 5.4.0-39-generic snap
```

OS: Ubuntu 20.04 LTS

**Comment by wwlorey** [comment]
Hi @angelcervera, sorry for the late response. Are you still running into this error using the latest version of the extension (0.9.8)?

**Comment by angelcervera** [comment]
Hi @wwlorey  I created this issue one year ago. 10 months ago, I moved back to Amazon AWS.
Thanks anyway.

**Comment by kraakman** [comment]
I am facing the same issue as @angelcervera , what changes do I need to make (either in Azure or in Visual Studio Code itself) in order to be able to log-in into Visual Studio Code with my Azure accounts that requires MFA (set in Security DefaultS)?

**Comment by michaeldaw** [comment]
I'm running in to this now to. Was there a recent change. I'm pretty sure this used to work. Can it fixed please? Need it.

**Comment by nturinski** [comment]
Hate to suggest this, but could you try downgrading the Azure Account extension to 0.9.11? A lot of users running into authentication issues have been able to bypass the problems by doing so.

**Comment by michaeldaw** [comment]
Thank you. I saw this same suggestion in another thread. It did work, yes.

**Comment by itimgit** [comment]
Thank you so much, also worked for me.

**Comment by Seesi** [comment]
Yeah, downgrading worked for me also.

**Comment by maykonrds** [comment]
I had a similar issue, I have several tenants with MFA enabled for my account, and when I sign in just tenants without MFA show up for me. 
For me worked when I configured the Extension Settings and specify the tenant that I want to connect to, after that, I was able to connect to the tenant that I want.
