### ISSUE TITLE
Azure signin misbehaves in VSCode 2017

### ISSUE THREAD

**Issue by samanthpulluru** [microsoft/vscode-azure-account#202]
Team,

I tried to install VSCode 2017 community edition and signin to Azure subscription from it. The signin prompt comes up, asks me to signin for 2-3 times and closes after. However, the account details on the server explorer behaves differently. One time, it shows the App Service Plan well, but the other time, it goes off.

I creared a simple ASP.Net Web App with a default.aspx having a header. When I try to publish it to the app service plan by selecting "Existing", the form having subscription and appservice plan details populate for a second and goes off immediately redirecting me to the login prompt in that dialog again.

Some help here is much appreciated.

**Comment by samanthpulluru** [comment]
This is on 2016 Datacenter VM

**Comment by RMacfarlane** [comment]
>VSCode 2017 community edition 

It sounds like you are using Visual Studio, not Visual Studio Code. Is that correct? This repository is meant to track issues with a Visual Studio Code extension, so I think this is the wrong place for this issue

**Comment by samanthpulluru** [comment]
> > VSCode 2017 community edition
> 
> It sounds like you are using Visual Studio, not Visual Studio Code. Is that correct? This repository is meant to track issues with a Visual Studio Code extension, so I think this is the wrong place for this issue

Thanks @RMacfarlane . Seems I posted in the wrong forum indeed. I will try finding out the right forum and seek help out there. Thanks for attending this.
