### ISSUE TITLE
Azure Account not listing subscription for ADFS based AzureStack

### ISSUE THREAD

**Issue by rakku-ms** [microsoft/vscode-azure-account#207]
Repro steps:

Connect to `http://rr1masd.corp.microsoft.com/` vpn

Use following User Settings:
```
{
    "azure.tenant": "ec5f4d14-6087-4cc8-aab2-9e41a1e44f06",
    "azure.ppe": {
        "activeDirectoryEndpointUrl": "https://adfs.northwest.azs-longhaul-03.selfhost.corp.microsoft.com/adfs/",
        "activeDirectoryResourceId": "https://management.adfs.azs-long03-int.selfhost.corp.microsoft.com/ec5f4d14-6087-4cc8-aab2-9e41a1e44f06",
        "resourceManagerEndpointUrl": "https://management.northwest.azs-longhaul-03.selfhost.corp.microsoft.com/",
    },
    "azure.cloud": "AzurePPE"
}
```

Issue: Sign in is successful but not able to see subscription
![image](https://user-images.githubusercontent.com/53540553/87608558-19a75b80-c6b5-11ea-8517-31bec88322d5.png)

**Comment by wwlorey** [comment]
@rakku-ms has this been resolved with the latest Azure Stack changes?

**Comment by rakku-ms** [comment]
yes, this issue has been fixed with the latest Azure Stack changes
