### ISSUE TITLE
Add setup explanation (-> tenantid)

### ISSUE THREAD

**Issue by LucasHunold** [Microsoft/vscode-azure-account#21]
//Running the sign in command starts a task in the bottom left, but never actually does anyting. 

Unless you enter the tenantid in the settings, which is never explained anywhere

**Comment by chrmarti** [comment]
The sign-in command has no setting. Sign-in should show a message at the top of the window asking you to sign in through a website. Does that message not show? Is there anything in the console (Help > Toggle Developer Tools)?

**Comment by LucasHunold** [comment]
That message was correctly shown after i entered my tenantid. Before doing that, entering the command would start the signin process (shown at the bottom left) but nothig else. 

I removed the tenantid to try and reproduce the error, but stayed signed in. The setting i'm referring to is "azure.tenantId". It may have been coincidence, but only after entering the tenantid there, i was shown the prompt to sign in through the website.

**Comment by chrmarti** [comment]
"azure.tenantId" might be from this extension: https://marketplace.visualstudio.com/items?itemName=bradygaster.azuretoolsforvscode

The Azure Account extension does not have such a setting.

**Comment by LucasHunold** [comment]
Coincidence then. I guess this can be closed, though i still don't know why the sign-in message only came after i entered the tenantid.

**Comment by chrmarti** [comment]
Thanks.
