### ISSUE TITLE
Takes few second to update extensionVariables.azureAccountExtensionApi.subscriptions after Azure login

### ISSUE THREAD

**Issue by vineetmimrot** [microsoft/vscode-azure-account#210]
Hey,
I am developer of "Deploy to Azure" extension and we are using "Azure Account" extension to login to Azure. I have found there is a lag of few milliseconds between executing "azure-account.login" command and updation of the value of extensionVariables.azureAccountExtensionApi.subscriptions.
So I have to add null check retries over the above variables, to make it work. If it is not a bug, what is the best way to do the  Azure account login?
 
This is the [PR](https://github.com/microsoft/vscode-deploy-azure/pull/141/files) that I have to. raise for temporary fixing the issue.

**Comment by RMacfarlane** [comment]
This is expected, the extension doesn't block on loading subscription information during login. You should listen to the `onSubscriptionsChanged` event to know when the subscriptions value has been updated.
