### ISSUE TITLE
Is it possible to programmatically authenticate a user against the Azure Account extension without redirecting to the browser?

### ISSUE THREAD

**Issue by SiddhanthUnnithan** [microsoft/vscode-azure-account#211]
The Azure Machine Learning extension team is exploring a scenario in which a user navigates from their Studio UI (ml.azure.com) directly to VS Code. When in VS Code the user should be automatically authenticated against their Azure Account so they can use features of the AML extension.

We don't want users to come to VS Code, install the AML extension, and then get prompted again to sign-in. We were wondering whether was a way to programmatically authenticate a user using the Azure Account extension?

Let me know if anything needs to be clarified!

**Comment by RMacfarlane** [comment]
Hi @SiddhanthUnnithan, no, there is currently not a way of adding authentication information to the extension from an external source

**Comment by SiddhanthUnnithan** [comment]
Thanks for letting me know @RMacfarlane! Have other extensions inquired about whether this is possible? If so, do you know if there's any planned work to enable this?

**Comment by RMacfarlane** [comment]
This is the first request for this, work is currently not planned for it

**Comment by wwlorey** [comment]
As of right now we don't have plans to add this feature due to security concerns.
