### ISSUE TITLE
vscode cannot connect China Azure Account

### ISSUE THREAD

**Issue by cici-zhang** [microsoft/vscode-azure-account#214]
1.The environment variable is set to Azure China in the setting
2.click on sigh in ,and then jump to global Azure verify

![image](https://user-images.githubusercontent.com/69502113/90363227-e3367500-e094-11ea-9cf4-fa8917b346da.png)
![image](https://user-images.githubusercontent.com/69502113/90363280-fe08e980-e094-11ea-9a66-11ed2b548d17.png)

**Comment by wpaladins** [comment]
I encountered the same problem

**Comment by roccoren** [comment]
Check the settings.json and append "azure.cloud": "AzureChinaCloud". 

I think there might be something wrong with the parameter setting. It should be AzureChinaCloud instead of AzureChina.

**Comment by cici-zhang** [comment]
Thanks, this problem has been solved

**Comment by 123Jun321** [comment]
Hi team,

we found that when we append "azure.cloud": "AzureChinaCloud", there was some issue that we can't see the services of subscription.it seems that this solution is not stable.
