### ISSUE TITLE
Command descriptions don't show localized strings in vscode

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode-azure-account#22]
![image](https://user-images.githubusercontent.com/323878/33223389-c812472e-d113-11e7-8d13-bcc3133b0c57.png)

**Comment by chrmarti** [comment]
I'm using a `package.nls.json`, that should be used to show the correct descriptions in the extension editor. @dbaeumer Anything else I need to do to make this work?

**Comment by chrmarti** [comment]
(Submitted a PR.)
