### ISSUE TITLE
Get stuck on "Select Directory" when open bash in Cloud Shell

### ISSUE THREAD

**Issue by sakanamax** [microsoft/vscode-azure-account#220]
OS: openSUSE Leap 15.2
vscode: 1.48.2
Azure Account extension: v0.9.2
https://shell.azure.com is  work

Steps to Repro:

Launch vscode
Open command palette with Ctrl-Shift-P
Select "Open Bash in Cloud Shell"
Redirected to AAD "Sign in to your account" AAD page
Pick my credentials
Redirected to Visual Studio Code Page that states "You are signed in now and can close this page"
Change focus back to vscode
Open command palette with Ctrl-Shift-P
Select "Azure: Open Bash in Cloud Shell"
"Select directory"  is opened but no option to select

setting mycompany.onmicrosoft.com in azure.tenant
But still doesn't work

![a](https://user-images.githubusercontent.com/5405809/92380569-fdb3b980-f13b-11ea-84c4-2307729fa8d6.png)

@chrmarti suggest me open a new issue

**Comment by sakanamax** [comment]
I try the same step in Mac too.
But still stuck on "Select Directory"

**Comment by ltlg** [comment]
same as me..

**Comment by pradeepmore12** [comment]
In my case issue resolved by reverting  Azure Account extension version to 0.8.11.
Look like some issue with Azure Account extension version 0.9.0 and above

**Comment by zarchigl** [comment]
> In my case issue resolved by reverting Azure Account extension version to 0.8.11.
> Look like some issue with Azure Account extension version 0.9.0 and above

Can you please share how to install the old version

**Comment by zarchigl** [comment]
it works for me with Azure Account extension version 0.8.11 and it is available in the below link.

https://marketplace.visualstudio.com/items?itemName=ms-vscode.azure-account

**Comment by gerwine** [comment]
same here also on Mac OS

**Comment by dmsadek** [comment]
Just go go to the extension "azure account" **settings** and enter your tenant.

**Comment by woutervanranst** [comment]
indeed install an older version like this
![image](https://user-images.githubusercontent.com/6490925/99519082-afb7ff00-2991-11eb-8ca3-c8344529fd04.png)

**Comment by sakanamax** [comment]
OS: openSUSE Leap 15.2
vscode: 1.51.1
Azure Account extension: v0.9.4

Still not work

**Comment by andreabragantini** [comment]
Hi all! It's a bug. If you have multiple azure directories (for some reasons) in your azure account than it's not able to give you a list of possible directories.
Just delete additional directories in your azure account and remain with the default one. Then it works smoothly.

**Comment by KyleLJohnson** [comment]
I ran into this bug also.

**Comment by Marc013** [comment]
I also ran into this same issue. Using the solution @pradeepmore12 and @woutervanranst provided 'solved' it. I see this as a workaround. It would be great if this bug can be fixed asap as this functionality is also used by other vscode extensions (e.g. Azure Terraform) so it's quite a big impact.

**Comment by KyleLJohnson** [comment]
I ended up installing the earlier version.

**Comment by al-n** [comment]
I experience this as well. 
Windows 64bit
VSCode 1.52.1 (User setup)
Azure Account v0.9.4

**Comment by sakanamax** [comment]
OS: openSUSE Leap 15.2
vscode: 1.52.1
Azure Account extension: v0.9.4

Still not work

**Comment by tsrimahesh** [comment]
Does not work for me as well in macos bigsur.

**Comment by daniel-refahi** [comment]
> > In my case issue resolved by reverting Azure Account extension version to 0.8.11.
> > Look like some issue with Azure Account extension version 0.9.0 and above
> 
> Can you please share how to install the old version

![image](https://user-images.githubusercontent.com/5209991/104871559-19a35380-5997-11eb-8fde-705d675fa7ad.png)

**Comment by DanielMOliveira** [comment]
For me worked with version 0.94.
The problem occour if you have more than tennant.

I did this steps to resolve:
1. Go to portal.azure
2. Open cloud shell (first icon after search box)
3. type az account list
4. Copy tennantID from account you want to connect
5. Open VS Code
6. Go to extensions
7. Select Azure Account Extension
8. Click in Extension Settings
9. In Azure Tennat past Tennant ID past in step 4

**Comment by sakanamax** [comment]
@DanielMOliveira Thanks It work in Mac, I will try linux tonight when I come back home

OS: Mac Mojave (10.14.6)
VScode: 1.52.1
Azure Account extension: 0.9.5

Work with DanielMOliveira method.

**Comment by sakanamax** [comment]
OS: openSUSE Leap 15.2
VScode: 1.52.1
Azure Account extension: 0.9.5

Work with DanielMOliveira method.

**Comment by PStoner3** [comment]
For those reading this in 2023 and beyond, Azure Account v0.11.5, one can select a subscription using the command palette (win: Ctl + Shift + P). At the prompt (>) type `azure: select subscription`. This will pull up a multi select drop down list all available subscriptions. Select those subscriptions necessary. That's it.

This has been available for quite a while, I think since v0.4.0.
