### ISSUE TITLE
not able to see subscriptions and also not to open bash shell

### ISSUE THREAD

**Issue by rohan619** [microsoft/vscode-azure-account#225]
Issue Type: <b>Bug</b>

not able to see the subscriptions and not able to open bash shell in cloud

Extension version: 0.9.3
VS Code version: Code 1.49.0 (e790b931385d72cf5669fcefc51cdf65990efa5d, 2020-09-10T13:22:08.892Z)
OS version: Windows_NT x64 10.0.18362

**Comment by wwlorey** [comment]
Hi @rohan619, sorry for the late response. Are you able to login and view subscriptions using the latest version of the extension (0.9.8)?

**Comment by bwateratmsft** [comment]
Please disregard the bot's comment.

This issue has been closed because it needs more information and has not had recent activity. See also our [issue reporting](https://aka.ms/azcodeissuereporting) guidelines.

Happy Coding!
