### ISSUE TITLE
Mock Azure Sign-In for VSCode extension test

### ISSUE THREAD

**Issue by vineetmimrot** [microsoft/vscode-azure-account#226]
Hey,
I am from the vscode-deploy-azure extension team and this extension uses Azure Account extension for Azure Sign-In. Currently, we are writing E2E tests for our extension, and for that, we need to somehow mock/store credentials for the Azure Sign-In process as the Azure Sign-In command opens up the browser to provide credentials. 
Can you please tell how can we mock the Azure Sign-in process for test?

cc: @bishal-pdmsft

**Comment by RMacfarlane** [comment]
Hi @vineetmimrot, this extension doesn't provide any capability of returning mock credentials currently. My recommendation would be to use something like https://github.com/sinonjs/sinon to mock the calls to get the credentials, filling them in with data from KeyVault, or to mock the API calls you're making

**Comment by vineetmimrot** [comment]
Yeah, I ended up using sinon only. Thanks for the response.
