### ISSUE TITLE
You appear to be offline

### ISSUE THREAD

**Issue by abhijitnathwani** [microsoft/vscode-azure-account#227]
Hi,

Out of the blue, from today, the extension cannot connect to Azure and throws the "You appear to be offline error". I can confirm the internet is working absolutely fine. I'm running this on VS Code WSL: Ubuntu -18.04. Azure IoT Hub seems to be able to send messages.

I see users reporting similar issues on Marketplace review.

Let me know any logs that need to be attached. 

Abhijit

**Comment by adamfaryna** [comment]
The same here.

I use macOS 10.15.7.

VSC:
Version: 1.50.0
Commit: 93c2f0fbf16c5a4b10e4d5f89737d9c2c25488a3
Date: 2020-10-07T06:00:00.397Z (1 wk ago)
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 19.6.0

**Comment by abhijitnathwani** [comment]
Hi @RMacfarlane 
Any update on this issue? Facing the same issue on a fresh new setup on a new laptop.

**Comment by marcoboffi** [comment]
+1

**Comment by abhijitnathwani** [comment]
I conclude this was due to the DNS settings on WSL. Somehow, WSL cannot reach the internet with the default DNS nameservers. Changing `nameserver` to `8.8.8.8` in the `/etc/resolv.conf` resolved my issue.
