### ISSUE TITLE
remove the need of validateAuthority flag AzureStack ADFS environment

### ISSUE THREAD

**Issue by bganapa** [microsoft/vscode-azure-account#228]
To connect to AzureStack ADFS, the user is required to specifify cusom settings like below. 

The setting validateAuthority should not needed as it can be inferred from the activeDirectoryEndpointUrl value.
if the value ends with /adfs/ , the validateAuthoirty would be false

 "azure.tenant": "adfs.bala.selfhost.local",

    "azure.ppe": {

        "activeDirectoryEndpointUrl": "https://adfs.bala.azurestack.corp.microsoft.com/adfs/",

        "activeDirectoryResourceId": "https://management.adfs.bala.selfhost.local/asdfd-8b9a-xxxx-9c85-823b54076b55",

        "resourceManagerEndpointUrl": "https://management.bala.azurestack.corp.microsoft.com/",

        "validateAuthority": false

    },

    "azure.cloud": "AzurePPE",

**Comment by wwlorey** [comment]
Hi @bganapa, has this been resolved with the latest Azure Stack changes?

**Comment by bganapa** [comment]
Yes. We made the needed changes to remove this flag. closing it now
