### ISSUE TITLE
Support signing into national Azure

### ISSUE THREAD

**Issue by whiskeyjay** [Microsoft/vscode-azure-account#23]
Such as Azure US Gov, Azure China and Azure Germany.

An ideal entry point would be a command like "Switch to ..." then the user picks the Azure environment they want to sign into.

**Comment by voidfunction** [comment]
I have the same requirement for our extension. Any update?

**Comment by marcvaneijk** [comment]
Adding Azure Stack endpoints to the request

**Comment by petkahl** [comment]
#43

**Comment by chrmarti** [comment]
Available in 0.5.1.
