### ISSUE TITLE
Writing login information to the keychain failed

### ISSUE THREAD

**Issue by ramki88** [microsoft/vscode-azure-account#230]
Writing login information to the keychain failed with error 'The stub received bad data.'.

Name: Azure Account
Id: ms-vscode.azure-account
Description: A common Sign-In and Subscription management extension for VS Code.
Version: 0.9.3
Publisher: Microsoft
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=ms-vscode.azure-account

Version: 1.51.0-insider (user setup)
Commit: f5d3ba4d61146b78f0c75c82f3f85232d3409bc1
Date: 2020-10-09T05:34:54.647Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19041

**Comment by wwlorey** [comment]
Hi @ramki88, sorry for the late response. Does this still reproduce for you using the latest version of the extension (0.9.8)?

**Comment by ramki88** [comment]
@wwlorey, Nope.. not with the recent version.
