### ISSUE TITLE
Free/legacy/MSDN account object contains 2 sessions, only second works

### ISSUE THREAD

**Issue by mentat9** [microsoft/vscode-azure-account#232]
After logging in to an MSDN subscription, the account object returned by the extension contains two sessions for two different tenants. My extension was previously always using the first session creds (```account.sessions[0]```), but when the logged-in account is an MSDN account, using the first one fails when attempting to access Azure resources with this message:

*"The access token is from the wrong issuer 'https://sts.windows.net/f8cdef31-a31e-4b4a-93e4-5f571e91255a/'. It must match the tenant 'https://sts.windows.net/44e3a5dc-e96b-41af-8d1d-4ac87f23fb72/' associated with this subscription. Please use the authority (URL) 'https://login.windows.net/44e3a5dc-e96b-41af-8d1d-4ac87f23fb72' to get the token. Note, if the subscription is transferred to another tenant there is no impact to the services, but information about new tenant could take time to propagate (up to an hour). If you just transferred your subscription and see this error message, please try back later.*

Using creds from the second session (```account.sessions[1]```) in this situation works fine.

Obviously, I can hack around this behavior, but I don't understand the behavior which means I don't trust the hack. Questions:
1. Is it expected to get multiple sessions in the account object?
2. If so, what is the invalid one for?
3. What is the correct way of consuming session objects that works for all subscription types?

**Comment by RMacfarlane** [comment]
@chrmarti Do you have any insights here?

It seems intentional that we return sessions from all tenants related to a subscription, but if there is a specific tenant associated with a subscription, I'm not sure what the purpose of these other sessions is.

Instead of choosing based on order, it might be better to look at the tenantId of the sessions and find the matching one.

**Comment by mentat9** [comment]
Agree, that's more robust. Worked out an implementation that filters on tenantId and it's working. Thanks for your help.

**Comment by chrmarti** [comment]
That's correct. Each subscription has a specific tenant and the tokens are scoped to the tenant. (Some tokens can be used across tenant if I remember correctly, but that is not under our control.)

**Comment by mentat9** [comment]
Got it. I guess the result I didn't expect is that accounts are associated with multiple tenants, so subscriptions need to be matched by tenant ID. Thanks for clarifying.
