### ISSUE TITLE
Can't find private subscriptions on VSCode

### ISSUE THREAD

**Issue by davidmrdavid** [microsoft/vscode-azure-account#237]
Hi folks!

I'm a member of the Azure Functions group. I'm signed in on my personal laptop with my microsoft account and trying to deploy an Azure Functions application using the azure functions VSCode plugin. That requires me to be signed in to azure with this plugin.

However, it appears that the azure account plugin cannot find my subscriptions, so I'm unable to deploy.  The error I receive is:

```
No subscriptions were found. Set up your account at https://azure.microsoft.com/en-us/free/.
```

But of course, I'm a member of a lot of subscriptions. I believe this works on my work pc, so I'm unsure what's different about my laptop. How can I get past this? Are there maybe some directories that got into a bad state? Thanks!

**Comment by davidmrdavid** [comment]
The following command `az account list --output table` does succeed in showing my subscriptions

**Comment by nturinski** [comment]
Have you ever set your `azure.tenant` in your settings.json?  You may have to clear that out in order to see your subscriptions again.

**Comment by davidmrdavid** [comment]
Hi @nturinski,
Indeed that's what was missing :) 
It would be neat if this value could be set automagically, or the VSCode plugin could warn me about it, spent quite a bit of time figuring this one out. Thank you though, really appreciate it!

**Comment by nturinski** [comment]
Sorry for all the pain and delay 😬 We are tracking this issue here though https://github.com/microsoft/vscode-azure-account/issues/243
