### ISSUE TITLE
How can we create token for first party Data Plane service using vscode-azure-account extension. Any references would help 

### ISSUE THREAD

**Issue by DivyeshTikmani-MSFT** [microsoft/vscode-azure-account#238]
How can we create token for first party Data Plane service using vscode-azure-account extension. Any references would help

**Comment by wwlorey** [comment]
Right now this isn't possible in the extension. I'd recommend reaching out to the [sdk team](https://github.com/Azure/azure-sdk-for-js) for more help with that
