### ISSUE TITLE
Stuck after opening first file

### ISSUE THREAD

**Issue by amesser** [microsoft/vscode-azure-account#239]
Since today's upgrade of code I observe it to become stuck after opening the first file. Upgrade log from dpkg:

2020-11-26 12:56:16 upgrade code:amd64 1.47.2-1594837870 1.51.1-1605051630

Since I thought it is somehow related to an extension in the first place, I have removed all extensions and user configuration to get a fresh start. But the problem still ocurs as follows:

1. Start Visual Code
2. Open Folder
3. Click on single file within folder
4. GUI becomes stuck, after a while popup occurs

This version seems to be unusable to me at the moment

**Comment by RMacfarlane** [comment]
I don't think this is related to the Azure Account extension, so going to close this.
