### ISSUE TITLE
Azure Account Extension can't sign in to Azure Germany account

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azure-account#246]
**OS:** Windows 10
**VS Code Version:** 1.54.0-insider (user setup)

**Repro steps:**
1. Install extensions: Azure Account, and Azure VM (for convenience to check whether signed in)
2. Open command palette, enter command "Azure: Sign In to Azure Cloud" -> Azure Germany -> Sign in with Azure Germany account and password.

**Expect:**
Succeed to sign in with Azure Germany account.

**Actual:**
An error occurs.
![image](https://user-images.githubusercontent.com/45614674/107141960-d4ce6500-6923-11eb-9c7a-c39e08dd8392.png)

**More Info:**
Succeed to sign in Azure Germany account in portal.

**Comment by nturinski** [comment]
@v-ruizh Do you know if this is still reproducing?  I thought that Mooncake/BlackForest was working with our extensions.

**Comment by v-ruizh** [comment]
@nturinski This issue does not reproduce now. I will close this issue.
