### ISSUE TITLE
Azure Account Sign-In has been broken since release 0.9.5 on Windows 10 platform

### ISSUE THREAD

**Issue by mariusz-marius** [microsoft/vscode-azure-account#250]
I can not sign in to Azure with release 0.9.5 and 0.9.6 .

I have tried two commands:

* Azure: Sign In
* Azure: Sign In with Device Code

but nothing happens, sign in window do not open. When I looked at developer console I have found as following:

`TypeError: Cannot read property 'endsWith' of undefined	at c:\Users\mariusz\.vscode\extensions\ms-vscode.azure-account-0.9.6\dist\extension.js:243:54619	at Generator.next (<anonymous>)	at c:\Users\mariusz\.vscode\extensions\ms-vscode.azure-account-0.9.6\dist\extension.js:243:52202	at new Promise (<anonymous>)	at r (c:\Users\mariusz\.vscode\extensions\ms-vscode.azure-account-0.9.6\dist\extension.js:243:51947)	at c:\Users\mariusz\.vscode\extensions\ms-vscode.azure-account-0.9.6\dist\extension.js:243:54505	at c:\Users\mariusz\.vscode\extensions\ms-vscode.azure-account-0.9.6\dist\extension.js:243:55576	at Generator.next (<anonymous>)	at c:\Users\mariusz\.vscode\extensions\ms-vscode.azure-account-0.9.6\dist\extension.js:243:52202	at new Promise (<anonymous>)	at r (c:\Users\mariusz\.vscode\extensions\ms-vscode.azure-account-0.9.6\dist\extension.js:243:51947)	at C (c:\Users\mariusz\.vscode\extensions\ms-vscode.azure-account-0.9.6\dist\extension.js:243:53748)	at c:\Users\mariusz\.vscode\extensions\ms-vscode.azure-account-0.9.6\dist\extension.js:243:53674	at Generator.next (<anonymous>)	at c:\Users\mariusz\.vscode\extensions\ms-vscode.azure-account-0.9.6\dist\extension.js:243:52202	at new Promise (<anonymous>)	at r (c:\Users\mariusz\.vscode\extensions\ms-vscode.azure-account-0.9.6\dist\extension.js:243:51947)	at j (c:\Users\mariusz\.vscode\extensions\ms-vscode.azure-account-0.9.6\dist\extension.js:243:53568)	at t.AzureLoginHelper.<anonymous> (c:\Users\mariusz\.vscode\extensions\ms-vscode.azure-account-0.9.6\dist\extension.js:243:61001)	at Generator.next (<anonymous>)	at c:\Users\mariusz\.vscode\extensions\ms-vscode.azure-account-0.9.6\dist\extension.js:243:52202	at new Promise (<anonymous>)	at r (c:\Users\mariusz\.vscode\extensions\ms-vscode.azure-account-0.9.6\dist\extension.js:243:51947)	at t.AzureLoginHelper.login (c:\Users\mariusz\.vscode\extensions\ms-vscode.azure-account-0.9.6\dist\extension.js:243:60876)	at c:\Users\mariusz\.vscode\extensions\ms-vscode.azure-account-0.9.6\dist\extension.js:243:59578	at b._executeContributedCommand (c:\Users\mariusz\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:86:88517)	at b.$executeContributedCommand (c:\Users\mariusz\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:86:88849)	at p._doInvokeHandler (c:\Users\mariusz\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:89:10276)	at p._invokeHandler (c:\Users\mariusz\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:89:9968)	at p._receiveRequest (c:\Users\mariusz\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:89:8638)	at p._receiveOneMessage (c:\Users\mariusz\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:89:7440)	at c:\Users\mariusz\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:89:5568	at v.fire (c:\Users\mariusz\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:55:1836)	at d.fire (c:\Users\mariusz\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:63:15515)	at c:\Users\mariusz\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:104:29104	at v.fire (c:\Users\mariusz\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:55:1836)	at d.fire (c:\Users\mariusz\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:63:15515)	at t._receiveMessage (c:\Users\mariusz\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:63:20765)	at c:\Users\mariusz\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:63:17659	at v.fire (c:\Users\mariusz\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:55:1836)	at u.acceptChunk (c:\Users\mariusz\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:63:12880)	at c:\Users\mariusz\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:63:12228	at Socket.m (c:\Users\mariusz\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:104:12375)	at Socket.emit (events.js:315:20)	at Socket.EventEmitter.emit (domain.js:483:12)	at addChunk (_stream_readable.js:295:12)	at readableAddChunk (_stream_readable.js:271:9)	at Socket.Readable.push (_stream_readable.js:212:10)	at Pipe.onStreamRead (internal/stream_base_commons.js:186:23)
b @ console.ts:137
$logExtensionHostMessage @ mainThreadConsole.ts:35
_doInvokeHandler @ rpcProtocol.ts:409
_invokeHandler @ rpcProtocol.ts:394
_receiveRequest @ rpcProtocol.ts:310
_receiveOneMessage @ rpcProtocol.ts:237
(anonymous) @ rpcProtocol.ts:105
fire @ event.ts:623
fire @ ipc.net.ts:468
_receiveMessage @ ipc.net.ts:821
(anonymous) @ ipc.net.ts:660
fire @ event.ts:623
acceptChunk @ ipc.net.ts:241
(anonymous) @ ipc.net.ts:202
I @ ipc.net.ts:32
emit @ events.js:315
addChunk @ _stream_readable.js:295
readableAddChunk @ _stream_readable.js:271
Readable.push @ _stream_readable.js:212
onStreamRead @ internal/stream_base_commons.js:186`

When I try to open Bash in Cloud Shell, I get pop-up window with information "You are not signed in. Sign in to continue." with "Sing In" button. When I press "Sing In" button, Bash in Cloud Shell terminal is closed and there is no sign in web browser window. When I looked at developer console I have found as following:

`TypeError: Cannot read property 'endsWith' of undefined	at c:\Users\mariusz\.vscode\extensions\ms-vscode.azure-account-0.9.6\dist\extension.js:243:54619	at Generator.next (<anonymous>)	at c:\Users\mariusz\.vscode\extensions\ms-vscode.azure-account-0.9.6\dist\extension.js:243:52202	at new Promise (<anonymous>)	at r (c:\Users\mariusz\.vscode\extensions\ms-vscode.azure-account-0.9.6\dist\extension.js:243:51947)	at c:\Users\mariusz\.vscode\extensions\ms-vscode.azure-account-0.9.6\dist\extension.js:243:54505	at c:\Users\mariusz\.vscode\extensions\ms-vscode.azure-account-0.9.6\dist\extension.js:243:55576	at Generator.next (<anonymous>)	at c:\Users\mariusz\.vscode\extensions\ms-vscode.azure-account-0.9.6\dist\extension.js:243:52202	at new Promise (<anonymous>)	at r (c:\Users\mariusz\.vscode\extensions\ms-vscode.azure-account-0.9.6\dist\extension.js:243:51947)	at C (c:\Users\mariusz\.vscode\extensions\ms-vscode.azure-account-0.9.6\dist\extension.js:243:53748)	at c:\Users\mariusz\.vscode\extensions\ms-vscode.azure-account-0.9.6\dist\extension.js:243:53674	at Generator.next (<anonymous>)	at c:\Users\mariusz\.vscode\extensions\ms-vscode.azure-account-0.9.6\dist\extension.js:243:52202	at new Promise (<anonymous>)	at r (c:\Users\mariusz\.vscode\extensions\ms-vscode.azure-account-0.9.6\dist\extension.js:243:51947)	at j (c:\Users\mariusz\.vscode\extensions\ms-vscode.azure-account-0.9.6\dist\extension.js:243:53568)	at t.AzureLoginHelper.<anonymous> (c:\Users\mariusz\.vscode\extensions\ms-vscode.azure-account-0.9.6\dist\extension.js:243:61001)	at Generator.next (<anonymous>)	at c:\Users\mariusz\.vscode\extensions\ms-vscode.azure-account-0.9.6\dist\extension.js:243:52202	at new Promise (<anonymous>)	at r (c:\Users\mariusz\.vscode\extensions\ms-vscode.azure-account-0.9.6\dist\extension.js:243:51947)	at t.AzureLoginHelper.login (c:\Users\mariusz\.vscode\extensions\ms-vscode.azure-account-0.9.6\dist\extension.js:243:60876)	at c:\Users\mariusz\.vscode\extensions\ms-vscode.azure-account-0.9.6\dist\extension.js:243:59578	at b._executeContributedCommand (c:\Users\mariusz\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:86:88517)	at b._doExecuteCommand (c:\Users\mariusz\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:86:87673)	at b.executeCommand (c:\Users\mariusz\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:86:87579)	at Object.executeCommand (c:\Users\mariusz\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:94:21781)	at t.AzureLoginHelper.<anonymous> (c:\Users\mariusz\.vscode\extensions\ms-vscode.azure-account-0.9.6\dist\extension.js:243:69549)	at Generator.next (<anonymous>)	at a (c:\Users\mariusz\.vscode\extensions\ms-vscode.azure-account-0.9.6\dist\extension.js:243:52004)	at runMicrotasks (<anonymous>)	at processTicksAndRejections (internal/process/task_queues.js:97:5)`

Release 0.9.4 is working as a charm.

VSCode info:

Version: 1.53.2 (user setup)
Commit: 622cb03f7e070a9670c94bae1a45d78d7181fbd4
Date: 2021-02-11T11:48:04.245Z
Electron: 11.2.1
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19041

**Comment by SikoSoft** [comment]
I KNEW IT

I've spent the last hour trying to get it to work... All the searches I found suggested proxy... that wasn't my issue.

One person recommended Help > Toggle Developer Tools and I see the same issue as you here with "endsWith".

I tried 0.9.4 and it worked perfectly for me as well. I'm glad you posted this and appreciate the help finding the correct version.
