### ISSUE TITLE
VSCode extension can not find subscriptions

### ISSUE THREAD

**Issue by Hugo-NF** [microsoft/vscode-azure-account#255]
I can login using the command `Azure: Sign In`, but after entering, the message always appears:

`No subscriptions were found. Set up your account at https://azure.microsoft.com/en-us/free/.`

I have already checked the directory issue, as I found in other discussions, but without success.

Anyway, this is the output of the `az account list` command:
`
[
  {
    "cloudName": "AzureCloud",
    "id": "47d28173-15ff-45d3-8b42-****************",
    "isDefault": true,
    "name": "N/A(tenant level account)",
    "state": "Enabled",
    "tenantId": "47d28173-15ff-45d3-8b42-****************",
    "user": {
      "name": "hugo********@hotmail.com",
      "type": "user"
    }
  },
  {
    "cloudName": "AzureCloud",
    "id": "ec359ba1-630b-4d2b-b833-****************",
    "isDefault": false,
    "name": "N/A(tenant level account)",
    "state": "Enabled",
    "tenantId": "ec359ba1-630b-4d2b-b833-****************",
    "user": {
      "name": "hugo********@hotmail.com",
      "type": "user"
    }
  }
]
`

**Comment by xxxprolapsexxx** [comment]
ms-vscode.azure-account[](url)

**Comment by xxxprolapsexxx** [comment]
- [ ]

**Comment by RMacfarlane** [comment]
@Hugo-NF Does changing the `azure.tenant` setting to your tenant id change this?

**Comment by nturinski** [comment]
Closing in favor of https://github.com/microsoft/vscode-azure-account/issues/101
