### ISSUE TITLE
Provide an api to get access token

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-azure-account#260]
Apologies of this is a duplicate.
Was looking for a way to get a token using this extension.

Basically a replacement for `az account get-access-token`
The token is to be used from another extension accessing azure resources.

Thanks

**Comment by RMacfarlane** [comment]
Hi @DonJayamanne, the extension exposes a `sessions` property in the API which you can use for this. If you're using either the `azure-sdk-for-node` or `azure-sdk-for-js` libraries, you can directly pass the `credentials` or `credentials2` object to those from the session. For just the access token, you should be able to do `(await session.credentials2.getToken()).accessToken`.

There's some sample code of using the extension API here: https://github.com/microsoft/vscode-azure-account/tree/main/sample

**Comment by RMacfarlane** [comment]
Hi @ruiminwang I no longer work on this, so I'm not sure. Maybe @bwateratmsft can help?

**Comment by bwateratmsft** [comment]
@alexweininger can you take a look?

**Comment by alexweininger** [comment]
> when I call `await session.credentials2.getToken()`, there's error showing ![image](https://user-images.githubusercontent.com/75243299/206621412-941440f0-384a-4ae2-851c-d2a4d6b58d41.png) Because in the new API the type of `credentials2` is now `TokenCredentialsBase | TokenCredential` instead of `TokenCredentialsBase`. Do you have any suggestion about this?

If you cast `credentials2 as TokenCredentialsBase`, does that fix your issue?
