### ISSUE TITLE
Adopt new proposed terminal profile contribution and TerminalOptions.iconPath 

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-azure-account#274]
Coming up in VS Code 1.57 is a new proposed API that allows contributing terminal profiles. This means that profiles can be surfaced into the new terminal dropdown/commands instead of having your own custom commands for creating new cloud shells:

<img width="275" alt="Screen Shot 2021-06-03 at 6 59 58 AM" src="https://user-images.githubusercontent.com/2193314/120657397-500ad800-c439-11eb-855f-b5500875b2bf.png">

Find the release notes, it's expected we'll stabilize this API in 1.58, you can test it in Insiders now.

### Terminal profile contributions

This API will enable extensions to contribute to the terminal profile system. A few things need to happen to get this to work, first contribute the profile in the package.json:

```json
"contributes": {
	"terminal": {
		"profiles": [
			{
				"title": "Profile from extension",
				"id": "my-ext.terminal-profile",
				"icon": "lightbulb"
			}
		]
	},
}
```

Then activate the extension on the new `onTerminalProfile` activation event:

```json
"activationEvents": [
	"onTerminalProfile:my-ext.terminal-profile"
]
```

Lastly register the provider in the activation event:

```ts
vscode.window.registerTerminalProfileProvider('my-ext.terminal-profile', {
	provideProfileOptions(token) {
		return {
      name: 'Profile from extension',
      shellPath: 'cmd.exe'
    };
	}
});
```

Provided proposed API is enabled the profile should show up in the profiles list:

![image](https://user-images.githubusercontent.com/2193314/120657551-7466b480-c439-11eb-8131-134c4c80f67e.png)

---

You'll also be able to set the icon of the profile which shows up in the new with profile command and another proposed API lets you set the iconPath on `TerminalOptions`/`ExtensionTerminalOptions`:

![image](https://user-images.githubusercontent.com/2193314/120657734-9d874500-c439-11eb-88c8-cc3ba661e54b.png)

These icons end up showing up in the new terminal tabs feature:

<img width="224" alt="Screen Shot 2021-06-03 at 7 02 49 AM" src="https://user-images.githubusercontent.com/2193314/120657833-b68ff600-c439-11eb-8e9c-3b47b7899c64.png">

**Comment by Tyriar** [comment]
Here's a more specific example of what this would look like for cloud shell:

In package.json

```json
"contributes": {
	"terminal": {
		"profiles": [
			{
				"title": "Azure Cloud Shell",
				"id": "vscode-azure-account.cloudShell",
				"icon": "azure"
			}
		]
	},
}
"activationEvents": [
	"onTerminalProfile:vscode-azure-account.cloudShell"
]
```

In extension:

```ts
vscode.window.registerTerminalProfileProvider('vscode-azure-account.cloudShell', {
	provideProfileOptions(token) {
		return {
			name: 'Azure Cloud Shell',
			iconPath: new ThemeIcon('azure'),
			// However you create the existing cloud shell terminal
		};
	}
});
```

**Comment by wwlorey** [comment]
We switched to using the terminal profile API in [v0.10.0](https://github.com/microsoft/vscode-azure-account/releases/tag/v0.10.0).
