### ISSUE TITLE
Can't connect to Azure Cloud Shell isolated VNET using Azure Account extension

### ISSUE THREAD

**Issue by dgaudette** [microsoft/vscode-azure-account#275]
I recently moved my Azure Cloud Shell into a VNET per MS Documentation:
https://docs.microsoft.com/en-us/azure/cloud-shell/private-vnet 

After the move, I attempted to connect to Cloud Shell in VS Code again but I get the output "Setup needed" with a pop-up in the lower right corner of the terminal that has a linked button to Cloud Shell in the browser. I click the button and Cloud Shell opens up in the browser without issue but does not open in VS Code.

I've attached an image to show the outcome.

![SetupNeeded](https://user-images.githubusercontent.com/85314625/120703922-ed8af980-c483-11eb-8c11-20f61d25c037.JPG)

**Comment by wwlorey** [comment]
If you're still seeing the "setup needed" dialog after completing the setup & reloading the extension it's possible the machine you're using doesn't have access to the cloud shell container. Can you verify that access has been granted?

**Comment by dgaudette** [comment]
Will,

Possibly. I was curious if there was existing case where a VS Code user was connecting to an Azure Cloud Shell that was moved into a private VNet. It makes sense that there is connection issue but I was hoping that the Azure relay might provide a seamless transition from VS Code’s perspective.


Dustin

**Comment by wwlorey** [comment]
> It makes sense that there is connection issue but I was hoping that the Azure relay might provide a seamless transition from VS Code’s perspective.

Unfortunately there isn't much we can do in the extension since the cloud shell is unreachable from the extension's perspective. I would recommend filing an issue with [Azure support](https://portal.azure.com/#create/Microsoft.Support) regarding that Azure relay feature request.

**Comment by dgaudette** [comment]
Right on. I wasn’t sure if there were any known issues that I was missing. Thanks!
