### ISSUE TITLE
[Codespaces] There is no device code copied after clicking "Copy & Open" button

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-azure-account#277]
**Environment:** Remote Codespaces
**Build Version:** 20210609.1

**Repro Steps:**

1. F1 -> Type and select "Sign In With Device Code" -> Click "Copy & Open" when prompting you to copy a code and navigate to the device login site.
    ![image](https://user-images.githubusercontent.com/62053665/121491929-f8f09e80-ca08-11eb-81dc-10ffcf0a8d17.png)
2. CTRL+V in the input box of the opened "Enter code" window.
3. Check whether there is a device code.

**Expect:**
There is a device code.

**Actual:**
There is no device code.

**Comment by nturinski** [comment]
Could you verify what browser/OS you are using?

Related: https://github.com/microsoft/vscode/issues/106997

**Comment by wwlorey** [comment]
This is blocked by Safari: https://github.com/microsoft/vscode-docker/issues/3012#issuecomment-873095184

**Comment by v-mengwe** [comment]
Verified on the latest build 20210815.1, this issue is reproduces using Microsoft Edge on the **Remote Codespaces** environment.
![account](https://user-images.githubusercontent.com/62053665/129540517-a46b4ba2-2c70-41b8-bd27-da03cb027491.gif)
This issue **doesn't reproduce** on **Local Codespaces** environment.

**Comment by wwlorey** [comment]
I'm not able to repro on Edge. Can you verify you're still running into this problem?

**Comment by v-mengwe** [comment]
Yes, verified on the latest build 20211007.1, this issue doesn't reproduce for now, so close it.

**Comment by wwlorey** [comment]
Since https://github.com/microsoft/vscode/issues/106997 was fixed this problem has likely been resolved in Safari.
