### ISSUE TITLE
Cache subscriptions across VS Code sessions

### ISSUE THREAD

**Issue by whiskeyjay** [Microsoft/vscode-azure-account#28]
To solve [this issue](https://github.com/Microsoft/vscode-azureappservice/issues/211) (https://github.com/Microsoft/vscode-azureappservice/issues/211), we need the account extension to cache subscriptions across VS code sessions.

**Comment by chrisdias** [comment]
@chrmarti is this possible?

**Comment by EricJizbaMSFT** [comment]
@JakeRadMSFT caches subscriptions for Storage Explorer - it should be possible

**Comment by chrmarti** [comment]
@whiskeyjay @EricJizbaMSFT I have pushed the change to GitHub, could you give it a try with your extensions?

**Comment by chrisdias** [comment]
i just did a quick test... brought tears to my eyes it was so fast.... :)

**Comment by EricJizbaMSFT** [comment]
Works for me as well 🎉
