### ISSUE TITLE
Prefixing interfaces with an "I"

### ISSUE THREAD

**Issue by neelip** [microsoft/vscode-azure-account#281]
Should we follow this rule of prefixing interfaces with an "I" given that eslint doesn't require this anymore?

If we plan to follow this, we should probably add this rule for eslint checks.
https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/naming-convention.md#enforce-that-interface-names-do-not-begin-with-an-i

**Comment by wwlorey** [comment]
Prefixing interface names with "I" is a common pattern in our other extensions and personally I like it. I'm open to adding a lint rule to enforce it
