### ISSUE TITLE
Cannot sign-in from VS Code

### ISSUE THREAD

**Issue by Holt59** [microsoft/vscode-azure-account#289]
I'm trying to sign-in through VS Code but cannot get it to work on my Ubuntu desktop. 

To reproduce:
- Run "Azure: Sign In"
- My web-browser opens and asks me to select the account I want to use (I'm already logged in)
- I select the account and then the page enter loading state and never finishes.

The procedure works fine on my W10 desktop, so I'm assuming it might be specific to my setup but since I have no clue where to look for logs I cannot do anything...

I tried going to 127.0.0.1:XXXXX (I looked up the port in the inspector), and I get the "You're now login" page but nothing change. If I copy paste the whole URL, the page never loads.

I'd be happy to provide more details if I can get directions on how to debug that problem.

**Comment by wwlorey** [comment]
Hi @Holt59, after you select your account and the browser window enters the loading state, does the account extension back in VS Code show that you have been signed in? Or is it stuck at the "Signing In..." state as shown here?

![Screen Shot 2021-07-06 at 10 54 58 AM](https://user-images.githubusercontent.com/22795803/124645753-a9a35f80-de48-11eb-9f5c-3fd155ae5c9d.png)

**Comment by Holt59** [comment]
@wwlorey Sorry for the delay, it started working but not it's broken again.

The left-panel in VS Code shows "Waiting for Azure sign-in... " but the status bar show my user account as "Azure: holt59@x.y.z".

**Comment by wwlorey** [comment]
@Holt59, when your account appears in the status bar, are you able to list subscriptions using the "Azure: Select Subscriptions" command via the [command palette](https://code.visualstudio.com/docs/getstarted/userinterface#_command-palette)?

Also, if you reload the window does the Azure view still show "Waiting for Azure sign-in..."?

**Comment by Holt59** [comment]
@wwlorey Reloading the Window did not work at first, but after a few hours it worked.

I am often switching network, and I noticed that the issue occurs after switching and for a few time before resolving itself, so I guess there is some cache issue with the connection?
