### ISSUE TITLE
Open bash in cloud shell no longer works

### ISSUE THREAD

**Issue by SteveCurran** [Microsoft/vscode-azure-account#29]
I have been using this extension all day. Now I get this error when opening a bash cloud shell.
Connecting terminal...
{ RequestError: Error: unable to verify the first certificate
    at new RequestError

**Comment by chrisdias** [comment]
@chrmarti I can repro this...

**Comment by chrmarti** [comment]
Does this still reproduce? It works for me right now.

**Comment by SteveCurran** [comment]
Working now. It appears to be a back end issue on Azure.

**Comment by Ar1702** [comment]
Hi everyone,

Can't see your pervious comment.
I'm looking for solution on this issue.
When opening Powershell in cloud shell i'm getting this error


Requesting a Cloud Shell...
Connecting terminal...
Error: Error: unable to verify the first certificate


Need help please.

**Comment by wwlorey** [comment]
Hi @Ar1702, sorry you're running into this problem.

This is a transient issue that likely has to do with Azure's backend. Unfortunately there isn't much we can do about it in the extension. It typically fixes itself after refreshing VS Code or after waiting some time before using the Cloud Shell feature again.

**Comment by saratona** [comment]
same here

**Comment by marco-svitol** [comment]
same here

**Comment by SteloNLD** [comment]
same here when using 'Azure: Open PowerShell in Cloud Shell'

`Requesting a Cloud Shell...
Connecting terminal...
Error: Error: unable to verify the first certificate`

**Comment by ashdhalama** [comment]
I am also getting the same error when try and open Cloud shells via vscode.

**Comment by dasalazar1** [comment]
Getting same issue as well with powershell terminal

**Comment by mrevros** [comment]
Have same issue as well
"Requesting a Cloud Shell...
Connecting terminal...
Error: unable to verify the first certificate"

Vscode Version 1.65.2
OS: Win 10 19044.1586

What I tried:
Countless times uninstall/install Azure Account extension
Uninstall VScode and install again

**Comment by dsajanice** [comment]
Duplicate and resolved in #394
