### ISSUE TITLE
Azure Key Vault data plane requires additional step?

### ISSUE THREAD

**Issue by iricigor** [Microsoft/vscode-azure-account#30]
Can you make this work also with Azure Key Vault data plane? As per [key-vault-node-getting-started](https://github.com/Azure-Samples/key-vault-node-getting-started): _"We then perform an authentication handshake with the KeyVault service before creating a KeyVaultClient object."_ If you just provide session credentials, you will get 401 unauthorized.

Otherways, this is an excellent extension. Good work!

I tried something like this:
```TypeScript
const client = new keyVault.KeyVaultClient(this.azureResourceFilter.session.credentials);
const secrets = client.getSecrets(uri).catch( (err) => {console.log(err.statusCode)});
```
which gives 401 in console.

The same approach on _keyVault**Management**Client_ works fine. Access rights on data plane in Azure is also fine, same user (me) has both management and data access.

**Comment by chrmarti** [comment]
The sample you link to shows:

```js
var kvCredentials = new KeyVault.KeyVaultCredentials(authenticator);
keyVaultClient = new KeyVault.KeyVaultClient(kvCredentials);
```

It seems you need that `authenticator` object. Not sure where that comes from.

**Comment by iricigor** [comment]
Here is what I found about it on  [key-vault node.js package page](https://github.com/Azure/azure-sdk-for-node/tree/master/lib/services/keyVault). 

Definition within KeyVaultCredentials class constructor:

```TypeScript
/**
 * An object that performs authentication for Key Vault.
 * @class
 * @param {KeyVaultCredentials~authRequest} authenticator  A callback that receives a challenge and returns an authentication token.
 */
export class KeyVaultCredentials implements msRest.ServiceClientCredentials {
  constructor( authenticator:  (challenge: any, callback: any) => any );
  signRequest(webResource: msRest.WebResource, callback: { (err: Error): void }): void;
}
```

Here is example fromthe same page. This example is not so good, as it also uses hardcoded credentials (acquireTokenWithClientCredentials), but I could not find any better example (i.e. something with acquireTokenWithDeviceCode).

```TypeScript
// Authenticator - retrieves the access token
var authenticator = function (challenge, callback) {

  // Create a new authentication context.
  var context = new AuthenticationContext(challenge.authorization);
  
  // Use the context to acquire an authentication token.
  return context.acquireTokenWithClientCredentials(challenge.resource, clientId, clientSecret, function (err, tokenResponse) {
    if (err) throw err;
    // Calculate the value to be set in the request's Authorization header and resume the call.
    var authorizationValue = tokenResponse.tokenType + ' ' + tokenResponse.accessToken;

    return callback(null, authorizationValue);
  });

};
```

**Comment by chrmarti** [comment]
You can get at the access token from the credentials object (link below). Not sure if that will be all you need since the `challenge` in the above example might be for a different resource. (I'm not sure about the significance of that though.) Maybe see what the `challenge` looks like and work from there?

https://github.com/Microsoft/vscode-azure-account/blob/c6cd6641dc23a71e19adfb0b8d704855b06d58ad/src/cloudConsole.ts#L175

**Comment by chrmarti** [comment]
I think you can:
1. Get the refresh token from the AzureSession (see https://github.com/Microsoft/vscode-azure-account/blob/4608c5bc3c8c1ecf5d16f7a00d5e6030ca4660d8/src/cloudConsole.ts#L263).
2. From the refresh token: Get an access token for the key vault resource (see https://github.com/Microsoft/vscode-azure-account/blob/4608c5bc3c8c1ecf5d16f7a00d5e6030ca4660d8/src/azure-account.ts#L631).
3. Use step 2 in the `authenticator` you show from https://github.com/Azure/azure-sdk-for-node/tree/master/lib/services/keyVault .
