### ISSUE TITLE
VSCode - updated subscription name doesn't reflect in AZ Extension after restart for some services

### ISSUE THREAD

**Issue by md-jan1983** [microsoft/vscode-azure-account#301]
After changing the subscription name, the updated subscription name doesn't appear in the VS code Azure extension for some services even after refreshing the service over multiple times. To be specific in this case, it's Azure Storage Service.
![image](https://user-images.githubusercontent.com/6066307/128804144-ca0f13cb-604d-4ec8-b4c7-f6e715ec6ee3.png)
In this case the updated name of the subscription is as below:
![image](https://user-images.githubusercontent.com/6066307/128804243-939e8a0e-bbb9-4855-9791-9b0e947ac04b.png)

**Comment by wwlorey** [comment]
This should be fixed by signing out then back in. Closing in favor of https://github.com/microsoft/vscode-azure-account/issues/262
