### ISSUE TITLE
Azure Account menu/button does not display on the left.

### ISSUE THREAD

**Issue by marqdouj** [microsoft/vscode-azure-account#307]
I have installed the latest VS Code (1.60.0) and Azure Account extension (v0.9.8) (and restarted VS Code) but there is no button/menu displayed on the left. I am however able to select my Azure subscription using the Azure: Select Subscriptions command.

![vscode_missing_azure_menu](https://user-images.githubusercontent.com/16510416/132137003-fa25e39d-cc75-4ba6-bd8f-ac11453f44b0.png)

**Comment by wwlorey** [comment]
Hi @marqdouj, the Azure Account Extension doesn't actually contribute the Azure View on the left pane. It just handles signing in/out and other basic account-related actions.

To get the Azure View, you can install the [Azure Resources Extension](https://marketplace.visualstudio.com/items?itemName=ms-azuretools.vscode-azureresourcegroups).

Please let us know if you run into any more issues.
