### ISSUE TITLE
VS Code doesn't find subscription when logged in

### ISSUE THREAD

**Issue by ChrisJohDev** [microsoft/vscode-azure-account#314]
Does this occur consistently? Yes
Repro steps:

1. Select subscription
2. No subscriptions found

Version: 0.23.0
![Azure problem in VSCode](https://user-images.githubusercontent.com/76600435/132983137-dff33662-4f32-4f37-8c1e-246a5dd809a0.PNG)

OS: win32
OS Release: 10.0.19042
Product: Visual Studio Code
Product Version: 1.60.0
Language: en

**Comment by wwlorey** [comment]
Hi @ChrisJohDev, can you verify that you have subscriptions on the [Azure Portal](https://portal.azure.com)? If not, you can create one there.

**Comment by ChrisJohDev** [comment]
Yes I have an account on Azure and I could log in but then VScode can’t find a subscription even though there is one. I find it when I log in through a browser of course.

For some strange reason VSC doesn’t find it.

 

Best regards / Med Vänlig Hälsning / Mit freundlichen Grüßen / Cordiali Saluti / Saludos,

-Chris Johannesson

 

 Web:  <https://www.chrisjohannesson.com/> https://www.ChrisJohannesson.com

**Comment by nturinski** [comment]
Hi @ChrisJohDev 

Is it possible that you're using a Pay-As-You-Go subscription? We have an issue logged here: https://github.com/microsoft/vscode-azure-account/issues/219 where a user is having a similar problem as yours.

**Comment by nturinski** [comment]
Another possible solution could be clearing your tenant id setting as discussed in this issue: https://github.com/microsoft/vscode-azure-account/issues/193

The following link can show you how to do that: https://github.com/microsoft/vscode-azure-account/issues/193#issuecomment-643975021
