### ISSUE TITLE
Request timeout

### ISSUE THREAD

**Issue by bowdenk7** [Microsoft/vscode-azure-account#35]
Trying to login to Azure from VS Code. 

I click "copy & open". Browser launches. I paste in code and get the following:

![image](https://user-images.githubusercontent.com/820883/35583531-17e6372a-05a7-11e8-953b-580a86586364.png)

Additional info:
Request Id: 1ddaf81e-366f-4610-b935-4a602e8b1000 
Correlation Id: 9b9479fe-83a5-40d4-a2cc-9b3a66859229 
Timestamp: 2018-01-30T18:18:21Z 
Message: AADSTS90012: This request has timed out

**Comment by bowdenk7** [comment]
Uninstalling and reinstalling the extension resolved the issue. (@chrisdias which is kind of a pain by the way... you have to go uninstall every other extension that depends on it first)

Any idea what might have caused this? At first glance I didn't attribute this to the extension so I'm not sure users would think to try reinstalling.

**Comment by chrmarti** [comment]
I don't know how the extension could cause this. Maybe it was a coincidence that it started working at the same time you reinstalled.

**Comment by bowdenk7** [comment]
Yeah fair point. I'll let you know if I see it again.

**Comment by chrmarti** [comment]
Opened a ticket since you already have the correlation id. Reopening to follow up.

**Comment by chrmarti** [comment]
Ticket timed out, should have gone through ICM it seems. Let me know when you see this again.
