### ISSUE TITLE
Unable to view my azure subscriptions

### ISSUE THREAD

**Issue by bandarupallibnk** [microsoft/vscode-azure-account#355]
Does this occur consistently? Yes
Repro steps:

1. Download vscode from internet
2. Login to my github account(which I use for azure) from vscode to sync settings
3. Try to view subscriptions, but shows as empty.

Version: 0.4.0
OS: darwin
OS Release: 20.5.0
Product: Visual Studio Code
Product Version: 1.62.1
Language: en

**Comment by wwlorey** [comment]
Hi @bandarupallibnk, are you able to see any subscriptions when you login to the [Azure portal](https://portal.azure.com)?

**Comment by bandarupallibnk** [comment]
Hi @wwlorey ,
Yes I have a pay-as-you-go subscription with cosmosdb & web app running.
I am trying to create a function now.

Thanks,

**Comment by wwlorey** [comment]
We are tracking issues with pay-as-you-go subscriptions here https://github.com/microsoft/vscode-azure-account/issues/219

Thanks for filing!
