### ISSUE TITLE
asar breaks finding keytar

### ISSUE THREAD

**Issue by chrisdias** [Microsoft/vscode-azure-account#36]
the change in VS Code to move to ASAR changes where to find `keytar`, line 27 of azure-account.ts:

	keytar = require(`${env.appRoot}/node_modules/keytar`)

should be

	keytar = require(`${env.appRoot}/node_modules.asar/keytar`)

**Comment by chrmarti** [comment]
1.20 will ship with ASAR turned off.

**Comment by chrmarti** [comment]
Fixed in #39
