### ISSUE TITLE
Fail to sign in again with an azure account

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-azure-account#364]
**OS:** Windows 10
**VS Code Version:** 1.62.3
**Build Version:** 20211122.1
**Regression:** Previous release

**Repro Steps:**

1. Install the Azure Account extension in VS Code -> F1 -> Azure: Sign In -> Select an existing account in the opened browser window.
2. F1 -> Azure: Sign Out -> F1 -> Azure: Sign In -> Select an existing account in the opened browser window.
3. Check whether succeed to sign in.

**Expect:**
Succeed to sign in.
![azure](https://user-images.githubusercontent.com/62053665/142986792-e80702a2-1f77-4cc9-be47-b89b927714e0.gif)

**Actual:**
Fail to sign in.
![azure1](https://user-images.githubusercontent.com/62053665/142986821-767927ae-7aa4-4256-a323-5e06f3b4627e.gif)

**Comment by wwlorey** [comment]
@v-mengwe, I'm not able to reproduce this on Mac or Windows 😕

I'm wondering if this is some sort of transient issue. Does the problem persist if you reload your VS Code window using the `Developer: Reload Window` command?

**Comment by wwlorey** [comment]
This repros for me using the latest build when I switch auth libraries then attempt to sign in again. So this problem appears to be related to the auth library changes.

**Comment by wwlorey** [comment]
Also a refresh fixes the problem.
