### ISSUE TITLE
The opened "Azure Cloud Shell (Bash)" terminal looks a little ugly after switching Authentication Library

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azure-account#380]
**OS:** All
**Build Version:** 20211130.7
**Regression:** Not a regression

**Repro Steps:**
1. Set the "Azure: Authentication Library" setting to "ADAL".
2. Open a "Azure Cloud Shell (Bash)" terminal.
3. Change the "Azure: Authentication Library" setting to "MSAL"
4. Click "Sign Out and Reload Window" button in the opened notification to take effect Authentication Library change.
5. Check the above opened "Azure Cloud Shell (Bash)" terminal.

**Expect:**
The opened "Azure Cloud Shell (Bash)" terminal looks well.

**Actual:**
The opened "Azure Cloud Shell (Bash)" terminal looks a little ugly.
![image](https://user-images.githubusercontent.com/45614674/144560345-8a9a04d7-70e0-474d-bbba-4047c0c98d6a.png)

**Comment by wwlorey** [comment]
Once VS Code supports opting out of persistent terminals we can fix this. We would just mark all of our terminals as non-persistent so when the window is refreshed that terminal is no longer shown. Tracking in https://github.com/microsoft/vscode/issues/118726

**Comment by wwlorey** [comment]
This is coming soon: https://github.com/microsoft/vscode/issues/139112
