### ISSUE TITLE
[Suggestion] It would be better to pop up the subscriptions list after signing in account successfully

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-azure-account#381]
**OS:** Mac
**Build Version:** 20211202.4
**Regression:** Not a regression

**Repro Steps:**

1. Sign out the azure account -> F1 -> Azure: Select Subscriptions -> Click "Sign In" when asking to sign in -> Select an account to sign in -> Back to VS Code after signing in successfully.
2. Check whether pop up the subscriptions list.

**Actual:**
No subscriptions list pops up after signing in account successfully.

**Suggestion:**
It would be better to pop up the subscriptions list after signing in account successfully.

**Comment by wwlorey** [comment]
The team discussed this design and we decided it doesn't fit into the experience flow. Thanks for the suggestion!
