### ISSUE TITLE
Azure App Service extension in VSCode can't show Subscriptions

### ISSUE THREAD

**Issue by gordon518** [microsoft/vscode-azure-account#383]
Does this occur consistently? Yes
Repro steps:

1. Sign in my account with account name: "gordon888@hotmail.com".
2. After sign in, there is no any Subscriptions available under "Select Subscription...". I have two Subscriptions, one is "Azure subscription 1"(subscription ID: c44c4eb3-37fe-49f3-a7f5-f1307f1d8529), another is "PasAsGo"(subscription ID: 26a2495a-ca86-4e89-b51a-5ec77b1b5675), the Azure App Service extension in VSCode can't show any of them. Without any Subscriptions available, I can't deploy anything with VSCode.

Version: 0.23.0
OS: win32
OS Release: 10.0.17763
Product: Visual Studio Code
Product Version: 1.62.3
Language: en

**Comment by wwlorey** [comment]
Hi @gordon518, thanks for filing this. 

Does your Azure account belong to more than one directory? You can view your directories [here](https://aka.ms/AAevnvr).

**Comment by gordon518** [comment]
Only one directory. The following is my directory in Azure portal.
![image](https://user-images.githubusercontent.com/25992646/145118559-e35391a5-9e8e-4d38-bebf-5d0ab28fc5b4.png)

**Comment by wwlorey** [comment]
@gordon518 What is the plan type for each of your subscriptions? You can find the plan in the below pane by clicking on your subscriptions found in [this list](https://portal.azure.com/?quickstart=True#blade/Microsoft_Azure_Billing/SubscriptionsBlade).

<img width="865" alt="Screen Shot 2021-12-08 at 1 12 08 PM" src="https://user-images.githubusercontent.com/22795803/145285234-d8535cdb-1355-4347-806a-fadf05cd19ca.png">
 
I'm doing my best to recreate your environment to reproduce this. As of right now I'm unable to repro with my Microsoft work account, my personal account linked to the "Visual Studio Enterprise" subscription provided by Microsoft, and with a different personal account that has a single "Azure Plan" subscription under a single directory.

**Comment by gordon518** [comment]
There is nothing in "PasAsGo" subscription. There are one "ASP-DefaultResourceGroupCCAN-86f4 (F1: Free)" as "App Service plan", and one "idate" as App Service under "Azure subscription 1". Please see the following:
![image](https://user-images.githubusercontent.com/25992646/145330726-1361057e-47c5-4518-8861-3fa7dbc81a1a.png)

App Service Plan: ASP-DefaultResourceGroupCCAN-86f4 (F1: Free)

**Comment by gordon518** [comment]
Your link for https://portal.azure.com/?quickstart=True#blade/Microsoft_Azure_Billing/SubscriptionsBlade shows the following:
![image](https://user-images.githubusercontent.com/25992646/145331400-3bd3fd2c-158c-4d2a-97fc-ac0df2dd71db.png)

**Comment by wwlorey** [comment]
Thanks for the info @gordon518. I believe this problem is related to tenants. Please follow these steps to set your tenant ID in the Account Extension: https://github.com/microsoft/vscode-azure-account/wiki/Troubleshooting#configure-your-tenant-in-the-azure-account-extension

**Comment by gordon518** [comment]
Yes, the problem solved. In VSCode, press Ctrl+Shift+P to show Command Palette, then input "Azure: Sign In"  in Command Palette to sign in again. After sign in again, All Subscriptions show up in Azure App Service extension. Thanks.

**Comment by wwlorey** [comment]
Hi @gordon518, glad to hear that fixed your problem. Please let us know if you run into any more issues.

**Comment by gordon518** [comment]
The purpose to use VSCode deploying codes is that only in "Code","Windows" mode, nodejs app can write Sqlite database. I tried "Code","Linux" mode, my nodejs app can't write Sqlite database.  Now my website at https://idate.azurewebsites.net can work normally. According to the document at https://docs.microsoft.com/en-us/answers/questions/346794/how-to-update-or-insert-sqlite-database-in-web-app.html , your linux server used CIFS filesystem which caused the problem. I think it is also a bug, and wrote my comments at that page. Thanks and regards.

**Comment by wwlorey** [comment]
Unfortunately that's not something my team can address but I recommend you submit that feedback via the [Azure portal](https://portal.azure.com) as well. The feedback pane is accessible by clicking the highlighted icon in the upper right-hand corner of the window.

<img width="384" alt="Screen Shot 2021-12-09 at 9 25 57 PM" src="https://user-images.githubusercontent.com/22795803/145522226-a88bc2cc-58cd-4ef9-8d0a-7aa9246aa216.png">
