### ISSUE TITLE
There is an error under the azure account registry when setting the "Azure: Authentication Library" setting to "MSAL"

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-azure-account#386]
**OS:** Windows 10
**Build Version:** 20211210.3
**Regression:** Not a regression

**Repro Steps:**

1. Set the "Azure: Authentication Library" setting to "MSAL".
2. Install the Docker extension in VS Code.
3. Expand the "REGISTRIES" node -> Create an azure account registry -> Expand the azure account registry.
4. Check whether there is no error under the azure account registry.

**Expect:**
There is no error under the azure account registry.

**Actual:**
There is an error under the azure account registry.
![image](https://user-images.githubusercontent.com/62053665/145786324-a796fe56-300d-4947-ae9a-dcc672b9859f.png)

**More Info:**
This issue doesn't reproduce when setting the "Azure: Authentication Library" setting to "ADAL"

**Comment by bwateratmsft** [comment]
Looks like the MSAL credentials aren't implementing [`AzExtServiceClientCredentials`](https://github.com/microsoft/vscode-azuretools/blob/main/ui/index.d.ts#L147-L155) quite right...
