### ISSUE TITLE
[Remote Codespaces] No notification "You are not signed in. Sign in to continue." pops up when executing command "Azure: Select Subscription" at the first time

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-azure-account#389]
**OS:** Remote Codespaces
**Build Version:** 20211228.1
**Regression:** Not a regression

**Repro Steps:**

1. Make sure the Azure account is signed in.
2. Set the "Azure: Authentication Library" setting to "MSAL" or "ADAL" -> Click the "Sign Out and Reload Window" button.
3. F1 -> Azure: Select Subscription.
4. Check whether the notification "You are not signed in. Sign in to continue." pops up.

**Expect:**
The notification "You are not signed in. Sign in to continue." pops up.

**Actual:**
No notification "You are not signed in. Sign in to continue." pops up.
![image](https://user-images.githubusercontent.com/62053665/147636978-81f7acc9-6872-4ae6-a8f2-0297c9d01395.png)

**More Info:**

1. The notification "You are not signed in. Sign in to continue." pops up when executing command "Azure: Select Subscription" again.
2. This is an unstable issue.

**Comment by wwlorey** [comment]
My best explanation for this behavior is that Codespaces takes its sweeet time to load (in my case it takes over 10 seconds once the VS Code-looking UI appears before the Account Extension even registers as installed). 

If you wait long enough for the "Azure: Select Subscription" command to execute, does the notification eventually appear? That was the case in my testing.

**Comment by v-mengwe** [comment]
Yes, thanks for your guidance. The notification appears if you wait long enough for the "Azure: Select Subscription" command to execute. I will close this issue.
