### ISSUE TITLE
Cannot sign in from VS Code

### ISSUE THREAD

**Issue by tgb1413** [microsoft/vscode-azure-account#396]
I'm trying to sign in Azure through VS Code Azure Account but did not work in my M1 mac book pro. (Monterey, 12.0.1)

My VS Code version is 1.52.1

I tried this in three different versions, 0.9.9 and 0.9.10 and 0.9.11

In 0.9.9, it opened login page properly.

But in 0.9.10 and 0.9.11, 

![스크린샷 2022-01-06 오후 4 03 36](https://user-images.githubusercontent.com/51379833/148342566-8e7a2e73-2666-4fe9-be65-069205b7532f.png)

VS Code showed a popup like this and nothing happened.

**Comment by tgb1413** [comment]
Hi @wwlorey , I updated only VS Code to 1.63.2 and it works.

Thanks for helping me !

**Comment by wwlorey** [comment]
Glad to hear that fixed your problem! Please let us know if you run into any more issues.
