### ISSUE TITLE
Unable to Sign In

### ISSUE THREAD

**Issue by rajivvishwa** [Microsoft/vscode-azure-account#40]
I'm getting the following error when trying to sign in (or try any other commands in the extension)

![azure extension signin issue](https://user-images.githubusercontent.com/125708/36888294-ad92f7bc-1da9-11e8-8157-7c3b1d422e32.jpg)

**Comment by chrmarti** [comment]
Is there anything in the console (Help > Toggle Developer Tools)?

**Comment by rajivvishwa** [comment]
Restarted VS code and pulled up Dev console. This is what I see after trying 'Sign In' command

![image](https://user-images.githubusercontent.com/125708/36888613-157792e2-1dab-11e8-9fb5-d1b9c2756665.png)

**Comment by chrmarti** [comment]
Could you try reinstalling the extension? That looks like it is incomplete. Which version of VS Code are you running?

**Comment by rajivvishwa** [comment]
I did. I reinstalled both 'Azure IoT Toolkit' and 'Azure Account'. My VS Code version is 1.20.1

**Comment by rajivvishwa** [comment]
I installed Insiders build 1.21.0 and the extension seems to work fine. I've not idea what the issue is.

**Comment by chrmarti** [comment]
In 1.20.1: Try uninstalling the extensions, then check they are gone from `%HOMEPATH%\.vscode\extensions` before reinstalling. (/cc @sandy081)

**Comment by sandy081** [comment]
To remove the extension and install - do following

- Uninstall extension
- Restart VS Code (Quit and Start)
- Install again

**Comment by rajivvishwa** [comment]
@chrmarti - That worked. After uninstalling from VSCode, I manually deleted extension folders (`ms-vscode.azure-account-0.3 and vsciot-vscode.azure-iot-toolkit-0.5`), from the path you have mentioned. @sandy081 - Thanks
