### ISSUE TITLE
Sign in does not open a web page now

### ISSUE THREAD

**Issue by xiaolang124** [microsoft/vscode-azure-account#411]
- VS Code Version: 1.63.2
- Azure Account Extension Version: 0.9.11
- OS Version: win10

Steps to Reproduce:

1. Open ```command palette``` -> use Azure: Sign in
2. Does not open web page but pops up an info to let me use device code login.
![image](https://user-images.githubusercontent.com/13211513/150925379-2de5aa0d-007a-4d5d-a4a0-ef0666c853fc.png)

**Comment by wwlorey** [comment]
Thanks for filing @xiaolang124. I was able to repro this in 0.9.9, 0.9.10, and 0.9.11. I didn't try any versions older than 0.9.9 but safe to say it's broken for those as well.

At first glance - it looks like the request we send to our redirect server (https://vscode-redirect.azurewebsites.net/) is returning a 403. So [checking the redirect server](https://github.com/microsoft/vscode-azure-account/blob/bf5343d9d986ef160b34e11bc7e0e4ad7d55c2b2/src/codeFlowLogin.ts#L28) always fails and the extension defaults to using the device code login.

**Comment by j-hulbert** [comment]
For organizations with Azure AD conditional access policies not allowing device code logins this prevents us from using the Azure extensions

**Comment by TylerLeonhardt** [comment]
Hi all, can you give this a try again? @wwlorey and I believe we got this working again. Apologies for the downtime.

**Comment by j-hulbert** [comment]
Working now

**Comment by TylerLeonhardt** [comment]
Great. Thanks!
