### ISSUE TITLE
Authentication/Connection failed for Azure Account Extension

### ISSUE THREAD

**Issue by TimFritVero** [microsoft/vscode-azure-account#424]
Issue Type: <b>Bug</b>

Hi,

I'm currently confronting an authentication problem in vscode via the Azure Account extension (Azure Machine Learning - remote).

__Expected Behaviour:__
1. Sign-In to Azure Machine Learning Workspace
2. Start the Compute Instance
3. Connect to the Compute Instance.

__Details__
After trying to sign-in due the Azure Machine Learning extension the process steps starts as expected via the device-login. After the successful  authentication via the web interface I receive a error message in vscode from the Azure Account Extension:   
ErrorMessage: *request to https://management.azure.com/tenants?api-version=2016-06-01 failed, reason: connect ECONNREFUSED "IP-Address":443* (IP-Address is available).  

__Further Information:__
I've tried different versions of the involved extension without any luck. Furthermore, I've tried to reproduce the failure with my colleague's system where no issues occurred.

If you need more information please ask.
Thanks in advance and kind regards.

Extension version: 0.9.11
VS Code version: Code 1.64.0 (5554b12acf27056905806867f251c859323ff7e9, 2022-02-03T04:22:20.678Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
pythonvspyl392cf:30425750
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30433059
pythonvs932:30410667
wslgetstarted:30433507
vscop940:30404999
vsrem710:30416614

```

</details>

**Comment by wwlorey** [comment]
Hi @TimFritVero, thanks for filing. I wonder if there's something about your machine configuration that could be blocking the request to https://management.azure.com/tenants?api-version=2016-06-01 from going through. Is it possible that the networking setup for the compute instance isn't allowing that request?

**Comment by aviita** [comment]
We are seeing similar issue at least with VPN. We do have a coporate proxy. Will need to study further, but seems that from powershell the same command goes through:
```powershell
$bearer = "<BEARER_TOKEN_FROM_ERROR_MESSAGE>"
$headers = @{
    "accept" = "application/json"
    "accept-encoding" = "gzip,deflate"
    "user-agent" = "azsdk-js-arm-resources-subscriptions/2.1.0 core-rest-pipeline/1.16.0 Node/20.15.1"
    "x-ms-client-request-id" = "abcdefed-092b-436e-b93c-a62cef7001b6"
    "authorization" = "Bearer $bearer"
}
```

I get our tenant details as a response.
