### ISSUE TITLE
Changing the auth library when the extension has yet to activate results in an error upon activation

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-azure-account#433]
**OS:** Win10/Mac
**Azure Account Build Version:** 20220210.28
**Azure Virtual Machine Build Version:** 20220208.7
**Regression:** Not a regression

**Repro steps:**

1. Make sure the "Azure: Authentication Library" setting is "ADAL".
2. Create a Linux VM with "Oracle Linux 8.4 (LVM)" image -> Right click the VM -> Connect to host via Remote SSH.
3. In the new opened VS Code window by the VM -> F1 -> Extensions: Install from VISX... -> Click "show Local" -> Select the visx file of Azure Account extension.
4. F1 -> Sign in -> Select an existing account.
5. Check whether there is no error.

**Expect:**
There is no error after signing in an existing account.

**Actual:**
There is an error after signing in an existing account.
![image](https://user-images.githubusercontent.com/62053665/153577499-1ee1290a-a3e9-4f1c-91c8-51cdf00aa41a.png)
Details of error:
```
Action: azure-account.login
Error type: SyntaxError
Error Message: Unexpected redacted:key in JSON at position 2
```

**More Info:**
The default value of "Azure: Authentication Library" setting is "MSAL" on the Remote setting after connecting successfully.

**Comment by bwateratmsft** [comment]
I reproduced this by chance through another means, and the way of doing so isn't obvious, so I wanted to record it here.

1. Start with the ADAL auth mode. Sign in.
2. Reload the window. _Before_ the Azure extension activates, change the auth mode to MSAL.
3. Run command "Azure: Sign In" and follow through with the sign-in. Upon the callback to the extension's listener, this error is thrown.

**Comment by bwateratmsft** [comment]
This issue could affect most customers that get assigned by the experimentation service into the treatment group (MSAL). Most likely, VSCode's experimentation client will alter the auth mode _before_ the Account extension has a chance to activate.
