### ISSUE TITLE
q

### ISSUE THREAD

**Issue by Trang2k2** [microsoft/vscode-azure-account#440]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azure-account.login
Error type: Error
Error Message: Timeout waiting for code

Version: 0.10.0
OS: win32
OS Release: 10.0.19044
Product: Visual Studio Code
Product Version: 1.64.2
Language: en

<details>
<summary>Call Stack</summary>

```
Timeout.<anonymous> extension.bundle.js:2:2321688
listOnTimeout timers.js:554:17
processTimers timers.js:497:7
```

</details>

**Comment by wwlorey** [comment]
Hi [Trang2k2](https://github.com/Trang2k2), thanks for filing.

Does your web browser open and present the login window when you execute the `Azure: Sign In` command? Or is this error thrown immediately?

Can you successfully sign in using the `Azure: Sign In with Device Code` command?

Also - what is the value of your `Azure: Authentication Library` setting?

**Comment by wwlorey** [comment]
[Trang2k2](https://github.com/Trang2k2) additionally please let us know the value of your `Azure: Cloud` setting.

**Comment by wwlorey** [comment]
Closing as duplicate of https://github.com/microsoft/vscode-azure-account/issues/442.

@Trang2k2 if you have more info to provide please do so in the linked issue.
