### ISSUE TITLE
Timeout waiting for code

### ISSUE THREAD

**Issue by feder011** [microsoft/vscode-azure-account#442]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azure-account.login
Error type: Error
Error Message: Timeout waiting for code

Version: 0.10.0
OS: win32
OS Release: 10.0.19044
Product: Visual Studio Code
Product Version: 1.63.2
Language: it

<details>
<summary>Call Stack</summary>

```
Timeout.<anonymous> extension.bundle.js:2:2321688
listOnTimeout timers.js:554:17
processTimers timers.js:497:7
```

</details>

**Comment by wwlorey** [comment]
Thanks for filing, [feder011](https://github.com/feder011).

Does your web browser open and present the login window when you execute the `Azure: Sign In` command? Or is this error thrown immediately?

Can you successfully sign in using the `Azure: Sign In with Device Code` command?

Also - what are the values of your `Azure: Authentication Library` and `Azure: Cloud` settings?

**Comment by wwlorey** [comment]
The work in https://github.com/microsoft/vscode-azure-account/pull/475 and https://github.com/microsoft/vscode-azure-account/pull/480 should help with the timeout errors. I'm also hopeful that https://github.com/microsoft/vscode-azure-account/pull/470 will lead to fewer sign in errors that eventually cause a timeout.

**Comment by wwlorey** [comment]
@feder011 please upgrade to [version 0.10.1](https://github.com/microsoft/vscode-azure-account/releases/tag/v0.10.1) and let us know if you're still running into this problem.

![Screen Shot 2022-03-23 at 10 08 54 AM](https://user-images.githubusercontent.com/22795803/159756540-6f5caff2-beee-4bd9-8617-63959f03e95b.png)
