### ISSUE TITLE
Unable to use azure signin with extension

### ISSUE THREAD

**Issue by smunning** [microsoft/vscode-azure-account#446]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azure-account.login
Error type: invalid_grant
Error Message: invalid_grant: redacted:id - [redacted:id redacted:id39Z]: AADSTS500202: User account '{EmailHidden}' from external identity provider redacted:url is not supported for API version '2.0'. Microsoft account pass-thru users and guests are not supported by the tenant-independent endpoint.
Trace ID: redacted:id
Correlation ID: redacted:id
Timestamp: redacted:id redacted:id39Z - Correlation ID: redacted:id - Trace ID: redacted:id

Version: 0.10.0
OS: darwin
OS Release: 21.3.0
Product: Visual Studio Code - Insiders
Product Version: 1.65.0-insider
Language: en

<details>
<summary>Call Stack</summary>

```
ServerError.AuthError [as constructor] extension.bundle.js:2:154585
new ServerError extension.bundle.js:2:210448
ResponseHandler.validateTokenResponse extension.bundle.js:2:229292
AuthorizationCodeClient.<anonymous> extension.bundle.js:2:235023
step extension.bundle.js:2:147853
Object.next extension.bundle.js:2:147958
fulfilled extension.bundle.js:2:146622
```

</details>

**Comment by wwlorey** [comment]
Apologies for this error, @smunning. We just onboarded a new authentication library ([MSAL](https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-overview)) in v0.10.0. Adoption of this new library by identity providers has been very slow so some accounts don't support it yet. 

Please manually set the `Azure: Authentication Library` setting to `ADAL` for now and let us know if you run into any more issues.
