### ISSUE TITLE
"No response from the server" logging in to Azure with v 0.10.0

### ISSUE THREAD

**Issue by anthonywhite** [microsoft/vscode-azure-account#447]
- VS Code Version: 1.64.2
- Azure Account Extension Version: 0.10.0
- OS Version: Windows 10 Enterprise 19042.1526

Steps to Reproduce:

1. VS Code with 0.9.11 extension
2. Sign out of Azure Account
3. Upgrade extension to 0.10.0
4. Sign in to Azure command
5. Authenticate in browser
6. Get this alert in VS Code "no response from the server"
7. In VS Code Output window for Azure Account extension:
```
OAuth2Client: ERROR: No response from the server
Stack:
Error: No response from the server
	at Logger.createError (c:\Users\******\.vscode\extensions\ms-vscode.azure-account-0.10.0\dist\extension.bundle.js:2:788524)
	at c:\Users\******\.vscode\extensions\ms-vscode.azure-account-0.10.0\dist\extension.bundle.js:2:801557
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
Error: No response from the server
Error: No response from the server
```

**Comment by wwlorey** [comment]
Thanks for filing, @anthonywhite. Does this issue persist when you revert to version 0.9.11 using the method demonstrated [here](https://code.visualstudio.com/updates/v1_30#_install-previous-versions)? And does this problem repeatably happen on version 0.10.0?

Please also try signing in with the `Azure: Sign In with Device Code` command and let us know if you run into the same issue.

**Comment by mwilsonray** [comment]
I have a similar issue with version 0.10.0, but the error I get is:

**Error: Could Not Connect
Description: Could not connect to the server \"login.microsoftonline.com\".**

Reverting to 0.9.11 works.  Going back to 0.10.0 and attempting Azure: Sign In with Device Code returns:

**Error: Could Not Connect
Description: Could not connect to the server \"login.microsoftonline.com\".

Error: Get Device Code request returned http error: 502 and server response: "<HTML>\n<HEAD>\n<TITLE>Could Not Connect</TITLE>\n</HEAD>\n\n<BODY BGCOLOR=\"white\" FGCOLOR=\"black\">\n<H1>Could Not Connect</H1>\n<HR>\n\n<FONT FACE=\"Helvetica,Arial\"><B>\nDescription: Could not connect to the server \"<EM>login.microsoftonline.com</EM>\".\n</B></FONT>\n<HR>\n</BODY>\n"
Error: Acquiring user code failed**

**Comment by wwlorey** [comment]
@mwilsonray the issue you mentioned is similar but I'm not convinced it's the same issue that @anthonywhite ran into. I filed a new issue to track it: https://github.com/microsoft/vscode-azure-account/issues/450

**Comment by anthonywhite** [comment]
> Thanks for filing, @anthonywhite. Does this issue persist when you revert to version 0.9.11 using the method demonstrated [here](https://code.visualstudio.com/updates/v1_30#_install-previous-versions)? And does this problem repeatably happen on version 0.10.0?
> 
> Please also try signing in with the `Azure: Sign In with Device Code` command and let us know if you run into the same issue.

@wwlorey Reverting to **0.9.11** all problems disappear. On **0.10.0**:
1. Sign In behaviour I described above
2. Sign In with Device Code does not even open a browser window and gives this error output:
```
OAuth2Client: ERROR: No response from the server
Stack:
Error: No response from the server
	at Logger.createError (c:\Users\*****\.vscode\extensions\ms-vscode.azure-account-0.10.0\dist\extension.bundle.js:2:788524)
	at c:\Users\*****\.vscode\extensions\ms-vscode.azure-account-0.10.0\dist\extension.bundle.js:2:803059
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
Error: No response from the server
Error: No response from the server
Error: Acquiring user code failed
```
3. All 0.10.0 errors reliably repeatable

**Comment by wwlorey** [comment]
@anthonywhite please upgrade to [version 0.10.1](https://github.com/microsoft/vscode-azure-account/releases/tag/v0.10.1) and let us know if you're still running into this problem.

![Screen Shot 2022-03-23 at 10 08 54 AM](https://user-images.githubusercontent.com/22795803/159756540-6f5caff2-beee-4bd9-8617-63959f03e95b.png)

**Comment by anthonywhite** [comment]
> @anthonywhite please upgrade to [version 0.10.1](https://github.com/microsoft/vscode-azure-account/releases/tag/v0.10.1) and let us know if you're still running into this problem.

Hi @wwlorey still getting same errors...🙁

**Comment by anthonywhite** [comment]
just an update to confirm latest version 0.11.0 makes no difference...sigh

- VS Code Version: 1.69.0
- Azure Account Extension Version: 0.11.0
- OS Version: Windows 10 Enterprise 19042.1526

Steps to Reproduce:

1. VS Code with 0.9.11 extension
2. Sign out of Azure Account
3. Upgrade extension to 0.11.0
4. `Sign in to Azure with Device Code` VS Code command

In VS Code Output window for Azure Account extension:
`Attempting to reach URL "https://login.microsoftonline.com/"...
Attempting to reach URL "https://login.microsoftonline.com/"...
Fri, 08 Jul 2022 09:16:53 GMT:883d31f8-d142-418a-9af9-30d869c28638 - OAuth2Client: ERROR: No response from the server
Stack:
Error: No response from the server
	at Logger.createError (c:\Users\******\.vscode\extensions\ms-vscode.azure-account-0.11.0\dist\extension.bundle.js:2:820398)
	at c:\Users\*******\.vscode\extensions\ms-vscode.azure-account-0.11.0\dist\extension.bundle.js:2:834933
	at processTicksAndRejections (node:internal/process/task_queues:96:5)
Error: No response from the server
Error: No response from the server
Acquiring user code failed`

Revert to trusty `0.9.11` version, Reload window and all is good again...

**Comment by jarach** [comment]
I'm facing the same issue (also the some outputs in log) - windows + corporate proxy + the same configuration as @seanstedor.
Microsoft Azure Storage Explorer  - connects to Azure account without problems (the same windows machine + corporate proxy).
Under linux (the same config but no proxy) - no problems.

**Comment by scottygarskipton** [comment]
Yep - Same issue here. Since 0.9.11 I can't login. Any news?

**Comment by alexweininger** [comment]
@jarach, @touchmii, @scottygarskipton 

Any chance you know what software your proxy server is running? (Forcepoint, Squid, etc.)

**Comment by lexusean** [comment]
I'm facing same error and behind corporate proxy, reverting to 0.9.11 solved problem.
