### ISSUE TITLE
azure access issue

### ISSUE THREAD

**Issue by thpolzer** [microsoft/vscode-azure-account#449]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azure-account.login
Error type: Error
Error Message: access_denied

Version: 0.10.0
OS: linux
OS Release: 5.13.0-28-generic
Product: Visual Studio Code
Product Version: 1.64.2
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:2:2322729
extension.bundle.js:2:2320416
b extension.bundle.js:2:2320102
callback extension.bundle.js:2:2322377
Server.<anonymous> extension.bundle.js:2:2322766
Server.emit events.js:315:20
parserOnIncoming _http_server.js:874:12
HTTPParser.parserOnHeadersComplete _http_common.js:126:17
```

</details>

**Comment by wwlorey** [comment]
Hi @thpolzer, thanks for filing. As a workaround please downgrade to version 0.9.11 using the method demonstrated [here](https://code.visualstudio.com/updates/v1_30#_install-previous-versions).

What are the values of your `Azure: Authentication Library` setting and your `Azure: Cloud` setting?

Also, have you modified the `Azure › Custom Cloud: Resource Manager Endpoint Url` setting?

**Comment by wwlorey** [comment]
@thpolzer please upgrade to [version 0.10.1](https://github.com/microsoft/vscode-azure-account/releases/tag/v0.10.1) and let us know if you're still running into this problem.

![Screen Shot 2022-03-23 at 10 08 54 AM](https://user-images.githubusercontent.com/22795803/159756540-6f5caff2-beee-4bd9-8617-63959f03e95b.png)
