### ISSUE TITLE
Could not connect to the server "login.microsoftonline.com"

### ISSUE THREAD

**Issue by wwlorey** [microsoft/vscode-azure-account#450]
Originally filed by @mwilsonray in https://github.com/microsoft/vscode-azure-account/issues/447#issuecomment-1042301980

> I have a similar issue with version 0.10.0, but the error I get is:
> 
> **Error: Could Not Connect 
> Description: Could not connect to the server "login.microsoftonline.com".**
> 
> Reverting to 0.9.11 works. Going back to 0.10.0 and attempting Azure: Sign In with Device Code returns:
> 
> **Error: Could Not Connect Description: Could not connect to the server "login.microsoftonline.com".
> 
> Error: Get Device Code request returned http error: 502 and server response: "\n\n<TITLE>Could Not Connect</TITLE>\n\n\n<BODY BGCOLOR="white" FGCOLOR="black">\n
> 
> # Could Not Connect
> \n
> \n\n<FONT FACE="Helvetica,Arial">\nDescription: Could not connect to the server "_login.microsoftonline.com_".\n\n
> \n\n"
> Error: Acquiring user code failed**

**Comment by wwlorey** [comment]
@mwilsonray what's the value of your `Azure: Authentication Library` setting? Also, do you have a particular tenant or cloud (other than default Azure) configured in the extension?

**Comment by mwilsonray** [comment]
`Azure: Authentication Library` is setup to ADAL and I'm using default Azure. Switching to MSAL resulted in this error:

`Error: endpoints_resolution_error: Error: could not resolve endpoints. Please check network and try again. Detail: ClientConfigurationError: untrusted_authority: The provided authority is not a trusted authority. Please include this authority in the knownAuthorities config parameter.`

I should note that I both cases I'm taken to the login page and receive the `You are signed in now and can close this page.` message on the 127.0.0.1:<port_number> HTML page.

**Comment by wwlorey** [comment]
@mwilsonray please upgrade to [version 0.10.1](https://github.com/microsoft/vscode-azure-account/releases/tag/v0.10.1) and let us know if you're still running into this problem.

![Screen Shot 2022-03-23 at 10 08 54 AM](https://user-images.githubusercontent.com/22795803/159756540-6f5caff2-beee-4bd9-8617-63959f03e95b.png)

**Comment by mwilsonray** [comment]
> @mwilsonray please upgrade to [version 0.10.1](https://github.com/microsoft/vscode-azure-account/releases/tag/v0.10.1) and let us know if you're still running into this problem.
> 
> ![Screen Shot 2022-03-23 at 10 08 54 AM](https://user-images.githubusercontent.com/22795803/159756540-6f5caff2-beee-4bd9-8617-63959f03e95b.png)

@wwlorey  I tried 0.10.1 and I'm still getting the following:
`\nCould Not Connect
\n


\n\n\nDescription: Could not connect to the server \"login.microsoftonline.com\".\n\n`

Reverting to 0.9.11 allowed it to work again

**Comment by alexweininger** [comment]
Are you behind a proxy of any kind? Proxies often cause issues with sign-in. See the [Unable to Sign In While Using a Proxy section of our wiki](https://github.com/microsoft/vscode-azure-account/wiki/Troubleshooting#unable-to-sign-in-while-using-a-proxy) for possible fixes.
