### ISSUE TITLE
Get Token request returned http error: 302 and server response: ""

### ISSUE THREAD

**Issue by aj0417704** [microsoft/vscode-azure-account#454]
Does this occur consistently? Yes
Repro steps:
I am trying to login from VS code to Azure with the commande Azure: Sign In
The MS Login page is display, i connect my account then i got the page You are signed in now and can close this page (http://127.0.0.1:60577/).
And when i come back in VS Code i have the error message :(
Could you help me how to solve this issue please.

Action: azure-account.login
Error type: Error
Error Message: Get redacted:key returned http error: 302 and server response: ""

Version: 0.10.0
OS: win32
OS Release: 10.0.18363
Product: Visual Studio Code
Product Version: 1.64.2
Language: en

<details>
<summary>Call Stack</summary>

```
Logger.createError extension.bundle.js:2:788524
extension.bundle.js:2:801409extension.bundle.js:2:801409
processTicksAndRejections task_queues.js:93:5
```

</details>

**Comment by aj0417704** [comment]
Ok i downgrade to version 0.9.11 and now it s working.

**Comment by wwlorey** [comment]
@aj0417704, glad to hear downgrading fixed your issue for now.

Are you using default Azure? If not, what is the value of your `Azure: Cloud` setting?

**Comment by josemariabaena** [comment]
> Ok i downgrade to version 0.9.11 and now it s working.

What tool did you downgrade ?

**Comment by wwlorey** [comment]
@josemariabaena downgrading the Azure Account Extension for VS Code from version 0.10.0 to 0.9.11 using the method demonstrated [here](https://code.visualstudio.com/updates/v1_30#_install-previous-versions) is a workaround for this problem.

**Comment by wwlorey** [comment]
@aj0417704, @nao000001 please follow these instructions to download a private build and let's see if that helps with the issue.

1. Download version `v0.10.1-alpha` of the extension [here](https://dev.azure.com/ms-azuretools/534e1e1c-b364-44d0-b5ee-dce879a5106e/_apis/build/builds/43867/artifacts?artifactName=vsix&api-version=7.0&%24format=zip).
2. Open VS Code and run the `Extensions: Install Specific Version of Extension...` command (accessible from the [command palette](https://code.visualstudio.com/docs/getstarted/userinterface#_command-palette)).
![Screen Shot 2022-02-28 at 10 19 15 AM](https://user-images.githubusercontent.com/22795803/156036649-2f02c066-7e89-470c-8300-1903fe16f563.png)
3. In the file picker: browse to the `.vsix` file you downloaded and select it.
4. After selecting the file, a notification should appear prompting you to reaload the VS Code window. Click "Reload Now".
![Screen Shot 2022-02-28 at 10 21 37 AM](https://user-images.githubusercontent.com/22795803/156037095-0e4830ed-f226-48d6-9bbd-1e2cbde08029.png)
5. Open the marketplace in VS Code. Verify that the Azure Account Extension version reads `v0.10.1-alpha`.
![Screen Shot 2022-02-28 at 10 23 32 AM](https://user-images.githubusercontent.com/22795803/156037379-8d6c1d6a-8ea6-428f-8fb8-8ca5446b7a5c.png)
7. Try signing in again and let us know if you still run into the "http error: 302" error.

**Comment by wwlorey** [comment]
@aj0417704, @josemariabaena please upgrade to [version 0.10.1](https://github.com/microsoft/vscode-azure-account/releases/tag/v0.10.1) and let us know if you're still running into this problem.

![Screen Shot 2022-03-23 at 10 08 54 AM](https://user-images.githubusercontent.com/22795803/159756540-6f5caff2-beee-4bd9-8617-63959f03e95b.png)
