### ISSUE TITLE
azure app service account login with no response.

### ISSUE THREAD

**Issue by jinghun1999** [microsoft/vscode-azure-account#458]
Does this occur consistently? 
Repro steps:

1.
2.

Action: updateSubscriptionsAndTenants
Error type: REQUEST_SEND_ERROR
Error Message: request to redacted:url failed, reason: getaddrinfo ENOTFOUND redacted:url

Version: 0.10.0
OS: win32
OS Release: 10.0.19043
Product: Visual Studio Code
Product Version: 1.64.2
Language: zh-cn

<details>
<summary>Call Stack</summary>

```
new RestError extension.bundle.js:2:65384
NodeFetchHttpClient.<anonymous> extension.bundle.js:2:46552
step extension.bundle.js:2:2171732
Object.throw extension.bundle.js:2:2171837
rejected extension.bundle.js:2:2170562
processTicksAndRejections task_queues.js:93:5
```

</details>

**Comment by wwlorey** [comment]
@jinghun1999 please upgrade to [version 0.10.1](https://github.com/microsoft/vscode-azure-account/releases/tag/v0.10.1) and let us know if you're still running into this problem.

![Screen Shot 2022-03-23 at 10 08 54 AM](https://user-images.githubusercontent.com/22795803/159756540-6f5caff2-beee-4bd9-8617-63959f03e95b.png)
