### ISSUE TITLE
Missing subscriptions in subscription list

### ISSUE THREAD

**Issue by tymtam2** [microsoft/vscode-azure-account#459]
Until today I could see all my subscriptions when working in VS Code. Now some of my subscriptions are not available. 

Does this occur consistently? Yes

* Repro steps:

1. In a browser, sign into Azure 
2. Go to the desired directory/subscription in portal.azure.com (Important because it confirms that I'm sign in to this specific subscription)
3. Open VS Code 
4. Command Palette: Azure: Sign In...
5. Select account in browser
6. :( The desired subscription is missing

Notes:
* Command Palette: Azure: Sign Out -> Azure: Sign Out does not help. 

Version: 0.10.0
OS: win32
OS Release: 10.0.22000
Product: Visual Studio Code - Insiders
Product Version: 1.65.0-insider
Language: en

**Comment by tymtam2** [comment]
When I specify the tenant in the Azure Account extension settings I can successfully sign in to it and see the subscription.

"azure.tenant": "...."

**Comment by wwlorey** [comment]
Glad to hear your problem has been resolved, @tymtam2. Please let us know if you run into any more issues.

**Comment by wwlorey** [comment]
@tymtam2 the `Azure: Select Tenant` command may be helpful for you. 

When you execute that command, the extension attempts to find all tenants associated with your account and displays them in a quick-pick list. You can also enter a custom tenant if the one you're looking for doesn't appear in the list.

Once you select a tenant, this notification saves you a step by allowing you to sign out by clicking a button:

<img width="455" alt="Screen Shot 2022-02-20 at 2 46 20 PM" src="https://user-images.githubusercontent.com/22795803/154867788-6f7fcfc6-0600-44a5-bf07-6e7c236672e3.png">

Unfortunately there isn't currently a way for your newly selected tenant to be picked up without signing out and back in. An authentication request must be made with the new tenant for it to be updated.
