### ISSUE TITLE
Azure Access on docker -- issus 

### ISSUE THREAD

**Issue by Dev71-HiLL** [microsoft/vscode-azure-account#465]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azure-account.login
Error type: Error
Error Message: Get redacted:key returned http error: 400 and server response: {"error":"interaction_required","error_description":"AADSTS53003: Access has been blocked by Conditional Access policies. The access policy does not allow redacted:key ID: redacted:id\r\nCorrelation ID: redacted:id\r\nTimestamp: redacted:id redacted:id33Z","error_codes":[redacted:id],"timestamp":"redacted:id redacted:id33Z","trace_id":"redacted:id","correlation_id":"redacted:id","error_uri":"redacted:url

Version: 0.10.0
OS: linux
OS Release: 4.19.0-18-amd64
Product: Visual Studio Code
Product Version: 1.64.2
Language: fr

<details>
<summary>Call Stack</summary>

```
Logger.createError extension.bundle.js:2:788524
extension.bundle.js:2:801409
processTicksAndRejections task_queues.js:93:5
```

</details>

**Comment by wwlorey** [comment]
@Dev71-HiLL what's the value of your `Azure: Authentication Library` setting in VS Code? 

The auth library MSAL is known to cause problems like this but I see you aren't on VS Code Insiders so I'm curious if you changed that setting.

**Comment by wwlorey** [comment]
@Dev71-HiLL please upgrade to [version 0.10.1](https://github.com/microsoft/vscode-azure-account/releases/tag/v0.10.1) and let us know if you're still running into this problem.

![Screen Shot 2022-03-23 at 10 08 54 AM](https://user-images.githubusercontent.com/22795803/159756540-6f5caff2-beee-4bd9-8617-63959f03e95b.png)
