### ISSUE TITLE
Cannot Sign into Azure Account from VSC 

### ISSUE THREAD

**Issue by leshicodes** [microsoft/vscode-azure-account#467]
Does this occur consistently? Yes
Repro steps:
[](https://user-images.githubusercontent.com/451638/154806472-ee279409-af60-4823-a2fe-8921c9731d01.png)cmd + shift + p -> Azure: sign in
image

browsers open
login -> "You are signed in now and can close this page."
go back to VSCode and I am not logged in

Action: azure-account.login
Error type: Error
Error Message: No response from the server

Version: 0.10.0
OS: darwin
OS Release: 19.6.0
Product: Visual Studio Code
Product Version: 1.64.2
Language: en

<details>
<summary>Call Stack</summary>

```
Logger.createError extension.bundle.js:2:788524
extension.bundle.js:2:801557
processTicksAndRejections task_queues.js:93:5
```

</details>

**Comment by wwlorey** [comment]
Hi @SaleenTheGod, what is the value of your `Azure: Authentication Library` setting in VS Code? Also, can you verify the `Azure: Tenant` setting is set properly (or left blank if that's what your configuration requires). Be sure to check both user and workspace settings:
![image](https://user-images.githubusercontent.com/22795803/154867208-18fb1cdc-ee67-40f4-a342-808cb3a64cde.png)

**Comment by SaleenTheGod** [comment]
Hello @wwlorey Here are what my setting look like.

![Screen Shot 2022-02-21 at 9 45 09 AM](https://user-images.githubusercontent.com/24516995/154987553-70be8b6c-f77b-428a-b7fc-d1f847d6807c.png)

here is the error and the sign in browser screen
![Screen Shot 2022-02-21 at 9 42 37 AM](https://user-images.githubusercontent.com/24516995/154987612-2a1c031f-eba2-4d96-b21d-4b230f46832f.png)
![Screen Shot 2022-02-21 at 9 42 40 AM](https://user-images.githubusercontent.com/24516995/154987613-6416cea5-795d-446d-b0f3-581db0cdf00f.png)

**Comment by wwlorey** [comment]
Thanks, @SaleenTheGod. When you run the `Azure: Sign In` command are you presented with a login screen in your browser that looks something like this?

<img width="735" alt="Screen Shot 2022-02-21 at 10 48 06 AM" src="https://user-images.githubusercontent.com/22795803/155011885-661437d8-1139-4793-bfa0-d9e860f58cb1.png">

Or does it go straight to the "You are signed in now and can close this page" message?

**Comment by wwlorey** [comment]
@SaleenTheGod please upgrade to [version 0.10.1](https://github.com/microsoft/vscode-azure-account/releases/tag/v0.10.1) and let us know if you're still running into this problem.

![Screen Shot 2022-03-23 at 10 08 54 AM](https://user-images.githubusercontent.com/22795803/159756540-6f5caff2-beee-4bd9-8617-63959f03e95b.png)
