### ISSUE TITLE
azure-account.login Time out for china azure cloud

### ISSUE THREAD

**Issue by TuYingfang** [microsoft/vscode-azure-account#469]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azure-account.login
Error type: Error
Error Message: Timeout waiting for code

Version: 0.10.0
OS: win32
OS Release: 10.0.19042
Product: Visual Studio Code
Product Version: 1.64.2
Language: zh-cn

<details>
<summary>Call Stack</summary>

```
Timeout.<anonymous> extension.bundle.js:2:2321688
listOnTimeout timers.js:554:17
processTimers timers.js:497:7
```

</details>

**Comment by wwlorey** [comment]
Thanks for filing, @TuYingfang. I'm trying to understand why this error is happening. When you run the `Azure: Sign In` command are you presented with the login window in the browser? Are you able to complete the auth flow and then this error is thrown?

Also, is your `Azure: Tenant` setting set either in you workspace or user configuration in VS Code?

In the meantime you can work around this problem by downgrading to v0.9.11 of the extension as demonstrated [here](https://code.visualstudio.com/updates/v1_30#_install-previous-versions).

**Comment by wwlorey** [comment]
@TuYingfang please upgrade to [version 0.10.1](https://github.com/microsoft/vscode-azure-account/releases/tag/v0.10.1) and let us know if you're still running into this problem.

![Screen Shot 2022-03-23 at 10 08 54 AM](https://user-images.githubusercontent.com/22795803/159756540-6f5caff2-beee-4bd9-8617-63959f03e95b.png)
