### ISSUE TITLE
Unavailiable options for me when opening cloudshell

### ISSUE THREAD

**Issue by sallyur** [Microsoft/vscode-azure-account#47]
Azure Account extension: 0.3.3
1. Install Azure account extension from the market place
2. Azure Sign in
3. After successful login, execute the command from Command palette: Azure: Open Bash in Cloud Shell

Result: pop up three options 
![image](https://user-images.githubusercontent.com/22470312/37894591-47af9722-3111-11e8-99c7-49bac9ae9c84.png)

- if I click Microsoft, works fine(con set up in the web application successfully and open the cloudshell ) 
- if I click WTETestAd06 or WTETestAd05, set up web application, shown as below  
![image](https://user-images.githubusercontent.com/28860891/37894966-860bae4c-3112-11e8-9d0d-d4321d2316cf.png)

I am very puzzled why I have two not available options: WTETestAd06 and WTETestAd05?

**Comment by chrmarti** [comment]
Your account is part of these two other tenants. Normally you would have at least one subscription in each tenant/directory and you could use that subscription to open a Cloud Shell for the tenant/directory. In your case the tenants might have been used for testing only which might explain why they have no subscriptions.
