### ISSUE TITLE
Azure Sign In failed on version 0.10.0

### ISSUE THREAD

**Issue by hispanico** [microsoft/vscode-azure-account#476]
Does this occur consistently? YES
Repro steps:
1. Azure: Sign In
2. Redirect to Azure Login Page
3. Login succeed on Azure page but got error in vscode

![image](https://user-images.githubusercontent.com/3329032/155498034-468876cc-2430-40f4-ae28-d94ff4a08122.png)

Action: azure-account.login
Error type: Error
Error Message: Get redacted:key returned http error: 503 and server response: "Connection reset by peer"

Version: 0.10.0
OS: darwin
OS Release: 19.6.0
Product: Visual Studio Code
Product Version: 1.64.2
Language: en

<details>
<summary>Call Stack</summary>

```
Logger.createError extension.bundle.js:2:788524
extension.bundle.js:2:801409
processTicksAndRejections task_queues.js:93:5
```

</details>

Installed the old version 0.9.11 and Azure Sign In works.

**Comment by wwlorey** [comment]
Sorry you're running into this problem, @hispanico.

I'm wondering if this is a service-side issue. It looks similar to https://github.com/Azure/azure-cli/issues/14285. 

I know you said it occurs consistently but can you try it again using version 0.10.0? If it's still reproducing there's a high likelihood that the problem here is with the extension and not with the service.

**Comment by hispanico** [comment]
@wwlorey I upgraded to version 0.10.1 and now I don't get the error anymore but still not logged in.

![image](https://user-images.githubusercontent.com/3329032/161614243-b428ea8b-4cc7-42cb-971a-d83b6f61060b.png)

**Comment by wwlorey** [comment]
@hispanico please share any logs you see in the extension's output channel
<img width="1111" alt="Screen Shot 2022-04-05 at 11 20 05 AM" src="https://user-images.githubusercontent.com/22795803/161823473-de22ff78-bb12-41e5-9dcc-deedb3a533cc.png">

**Comment by hispanico** [comment]
Got this error:
Get Token request returned http error: 503 and server response: "Connection reset by peer"

**Comment by wwlorey** [comment]
@hispanico what happens when you sign in using the `Azure: Sign In with Device Code` command?
