### ISSUE TITLE
Opening PowerShell in Azure Cloud Shell Emits Error

### ISSUE THREAD

**Issue by Vincent-Lz-Zhang** [microsoft/vscode-azure-account#477]
- VS Code Version: 1.64.2 (user setup)
- Azure Account Extension Version: v0.10.0
- OS Version: Windows_NT x64 10.0.19043

Steps to Reproduce:

1. Install PowerShell Core 7.2 from Microsoft Store
2. Follow the steps listed in my [blog ](https://medium.com/@thatindividual.zhang/as-a-geek-how-i-customize-my-visual-studio-code-terminal-in-windows-10-6d590b8befcb)to setup PowerShell Core and VS Code with Oh-My-Posh, please note that I also followed the YouTube video mentioned in the blog to install Ubuntu and Oh-my-zsh. Also, I had Docker Desktop installed long time ago, and I'm not sure if it is relevant.
3. Install Azure Account extension
4. Login to Azure
5. Install PowerShell extension, update settings. To me, the settings.json reads like
`{
    "mssql.connections": [
        {
            "server": "{{put-server-name-here}}",
            "database": "{{put-database-name-here}}",
            "user": "{{put-username-here}}",
            "password": ""
        }
    ],
    "editor.renderWhitespace": "all",
    "editor.renderControlCharacters": true,
    "files.trimTrailingWhitespace": true,
    "files.encoding": "utf8bom",
    "files.autoGuessEncoding": true,
    "security.workspace.trust.untrustedFiles": "open",
    "redhat.telemetry.enabled": true,
    "[json]": {
        "editor.defaultFormatter": "esbenp.prettier-vscode"
    },
    "terminal.integrated.defaultProfile.linux": "zsh",
    "terminal.integrated.defaultProfile.windows": "PowerShell",

    "terminal.external.windowsExec": "C:\\Program Files\\WindowsApps\\Microsoft.PowerShell_7.2.1.0_x64__8wekyb3d8bbwe\\pwsh.exe",
    "terminal.integrated.fontFamily": "CaskaydiaCove Nerd Font",

    "powershell.powerShellAdditionalExePaths": [
        {
            "exePath": "C:\\Program Files\\WindowsApps\\Microsoft.PowerShell_7.2.1.0_x64__8wekyb3d8bbwe\\pwsh.exe",
            "versionName": "PowerShell Core"
        }
    ],

    "powershell.powerShellDefaultVersion": "PowerShell Core",

    "vs-kubernetes": {
        "vscode-kubernetes.helm-path.windows": "C:\\Users\\OEM\\.vs-kubernetes\\tools\\helm\\windows-amd64\\helm.exe",
        "vscode-kubernetes.minikube-path.windows": "C:\\Users\\OEM\\.vs-kubernetes\\tools\\minikube\\windows-amd64\\minikube.exe"
    },
    "azure.resourceFilter": [
        "a1b03033-8a3d-4443-a90b-0f3298ffbf90/4b79d82a-5275-4f29-9743-1e25cf1115b7"
    ]
}`
8.  Go to Terminal, in the dropdown, select Azure Cloud Shell(PowerShell ), and Error message is displayed:
`c:\Users\OEM\.vscode\extensions\ms-vscode.azure-account-0.10.0\dist\cloudConsolelauncher.js:2 
(()=>{var e={29541:(e,t,r)=> {
  "use strict";
  r(98705);
  const a=r(73837).inherits,o=r(76021),i=r(82361).EventEmitter;
  function Agent(e,t) {
    if(!(this instanceof Agent)) return new Agent(e,t);
    i.call(this),this._promisifiedCallback=!1;
    let r=t;
    "function"==typeof e?this.callback=e:e&&(r=e),this.timeout=r&&r.timeout||null,this.options=r
  }
  e.exports=Agent,a(Agent,i),Agent.prototype.callback=function callback(e,t)(
  throw new Error('"agent-base" has no default implementation, you must subclass and override \`callback()\`')
}
,Agent.prototype.addRequest=function addRequest(e,t) {
const r=Object.assign({},t);null==r.host&&(r.host="localhost"),null==r.port&&(r.port=r.secureEndpoint?443:80);
const a=Object.assign({},this.options,r);let i;a.host&&a.path&&delete a.path,delete a.agent,
delete a.hostname,delete a._defaultAgent,
delete a.defaultPort,delete a.createConnection,e._last=!0,e.shouldkeepAlive=!1;let n=!1;const s=this.timeout,c=this.freeSocke 

SyntaxError: Unexpected token ... 

  at createScript (vm.js:56:10) 
  at Object.runInThisContext (vm.js:97:10) 
  at Module._compile (module.js:549:28) 
  at Object.Module._extensions..js (module.js:586:10) 
  at Module.load (module.js:494:32) 
  at tryModuleLoad (module.js:453:12) 
  at Function.Module._load (module.js:445:3) 
  at Module.require (module.js:594:17) 
  at require (internal/module. js:20:19) 
  at [eval]:1:1 `

**Comment by wwlorey** [comment]
Your local configuration shouldn't affect the Cloud Shell even though it bears the name "PowerShell". I wonder if this is a problem with how we changed token caching from v0.9.11 to v0.10.0.

@Vincent-Lz-Zhang can you please try downgrading to version 0.9.11 of the Azure Account Extension using the process outlined [here](https://code.visualstudio.com/updates/v1_30#_install-previous-versions) and see if you still run into this problem?
