### ISSUE TITLE
VScode Azure Account not authenticating

### ISSUE THREAD

**Issue by glxorlando** [microsoft/vscode-azure-account#478]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azure-account.login
Error type: Error
Error Message: wireResponse is missing token_type

Version: 0.10.0
OS: win32
OS Release: 10.0.17134
Product: Visual Studio Code
Product Version: 1.64.2
Language: en

<details>
<summary>Call Stack</summary>

```
Logger.createError extension.bundle.js:2:788524
OAuth2Client._validateTokenResponse extension.bundle.js:2:797919
OAuth2Client._handleGetTokenResponse extension.bundle.js:2:799154
extension.bundle.js:2:801085extension.bundle.js:2:801085
processTicksAndRejections task_queues.js:93:5
```

</details>

**Comment by wwlorey** [comment]
This is being thrown by [adal-node](https://www.npmjs.com/package/adal-node) in their OAuth client. 

@glxorlando does this error reproduce consistently for you?
