### ISSUE TITLE
Bug <!-- Please follow the steps on our troubleshooting page before filing an issue https://aka.ms/AAevvhr -->

### ISSUE THREAD

**Issue by Karingomrz** [microsoft/vscode-azure-account#479]
- VS Code Version: 
- Azure Account Extension Version: 
- OS Version: 

Does your account belong to more than one directory? (see your directories [here](https://aka.ms/AAevnvr)): 

Any other information about your Azure account that may be useful:

**Comment by wwlorey** [comment]
@Karingomrz please provide more info about the problem you're running into.
