### ISSUE TITLE
password process

### ISSUE THREAD

**Issue by Clutch0825** [microsoft/vscode-azure-account#481]
MYSHERWIN PASSWORD RESET? 
PASSWORD RESET STEPS AND PROCESS:

1.EMPLOYEE DETAILS
2. [https://github.com/users/Clutch0825/projects](url)

Action:  Check end-user in WEBESS
Error type:  Invalid Username Password
Error Message: Timeout waiting for code

</details>

**Comment by wwlorey** [comment]
This sounds like a problem with signing into Azure in general.

Are you able to sign into https://portal.azure.com?
