### ISSUE TITLE
[Suggestion] [Codespace] It would be better if the checkbox background color of the selected subscription is blue

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-azure-account#483]
**OS:** Codespaces
**Build Version:** 20220224.2
**Regression:** Not a regression

**Repro Steps:**

1. F1 -> Azure: Select Subscriptions -> Select a subscription.
2. Check the checkbox background color of the selected subscription.

**Actual:**
The checkbox background color of the selected subscription is grey.
![image](https://user-images.githubusercontent.com/62053665/155681495-13675f73-ba80-4337-8394-21927c195e0b.png)

**Suggestion:**
It would be better if the checkbox background color of the selected subscription is blue.
![image](https://user-images.githubusercontent.com/62053665/155682869-a190ee88-8740-414a-930e-20456c576774.png)

**More Info:**
The "Color Theme" of VS Code is "Dark+ (default dark)".

**Comment by wwlorey** [comment]
Strange, I'm not able to repro this. I selected "Dark+ (default dark)" and see the blue checks in Codespaces.

![Screen Shot 2022-02-25 at 11 15 07 AM](https://user-images.githubusercontent.com/22795803/155774450-6c4950d0-27ef-45b9-94af-8f1788e1eead.png)
![Screen Shot 2022-02-25 at 11 15 19 AM](https://user-images.githubusercontent.com/22795803/155774459-15f552b8-864b-4358-aa99-4186e35cc78a.png)

In any case, this was maybe a minor bug in theming that we unfortunately don't have control of in the extension so I'll close this for now.
