### ISSUE TITLE
azure subscription

### ISSUE THREAD

**Issue by otienomilcah** [microsoft/vscode-azure-account#486]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azure-account.login
Error type: REQUEST_SEND_ERROR
Error Message: request to redacted:url failed, reason: getaddrinfo ENOTFOUND redacted:url

Version: 0.10.0
OS: win32
OS Release: 10.0.19043
Product: Visual Studio Code
Product Version: 1.64.2
Language: en

<details>
<summary>Call Stack</summary>

```
new RestError extension.bundle.js:2:65384
NodeFetchHttpClient.<anonymous> extension.bundle.js:2:46552
step extension.bundle.js:2:2171732
Object.throw extension.bundle.js:2:2171837
rejected extension.bundle.js:2:2170562
processTicksAndRejections task_queues.js:93:5
```

</details>

**Comment by wwlorey** [comment]
@otienomilcah this type of error tends to be transient. Does it reproduce consistently for you?
