### ISSUE TITLE
[Suggestion] It would be better if adding the "leave the tenant ID blank" to the prompt information when typing the tenant id

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-azure-account#490]
**OS:** All
**Build Version:** 20220227.1

**Repro Steps:**

1. F1 -> Azure: Sign In to Azure Cloud -> Select "Azure China".
2. Check the prompt information in the input box.

**Actual:**
The prompt information doesn't contain "leave the tenant ID blank".
![image](https://user-images.githubusercontent.com/62053665/155966795-afe71150-24e7-4fc5-8ee6-42d0e985a43d.png)

**Suggestion:**
It would be better if adding the "leave the tenant ID blank".

**Comment by wwlorey** [comment]
We'll go with: "Enter your tenant id or leave it blank to use the default tenant"
