### ISSUE TITLE
Try setting the tenant id of your subscriptions in the settings:

### ISSUE THREAD

**Issue by FsocietyDewit62** [microsoft/vscode-azure-account#497]
Try setting the tenant id of your subscriptions in the settings:
![image](https://user-images.githubusercontent.com/9205389/84633276-7239dc00-aef0-11ea-9d2f-ced6127844c5.png)

We usually discover all tenants, but not all are necessarily listed.

Does that help?

_Originally posted by @chrmarti in https://github.com/microsoft/vscode-azure-account/issues/193#issuecomment-643975021_

**Comment by wwlorey** [comment]
@FsocietyDewit62 please provide more information about the issue you're running into.
