### ISSUE TITLE
Unable to login with an account with MFA enabled.

### ISSUE THREAD

**Issue by rdtechie** [Microsoft/vscode-azure-account#50]
When trying to start a cloud shell, I have to sign in with the code provided. When I do this, it doesn't work because my account has MFA enabled. Normally when I connect to Azure I'm using a service principal as a workaround. The account extension doesn't seem to accept this. So the question is, can the extension get enhanced with the possibility to sign in with a service principal please, so that the cloud shell can be used?

**Comment by chrmarti** [comment]
Does your MFA scheme no support "device login" (the web login we use)?

**Comment by rdtechie** [comment]
I'm using Azure AD. And that doesn't work.

**Comment by rdtechie** [comment]
Any update on this?

**Comment by chrmarti** [comment]
Not at the moment. https://github.com/Microsoft/vscode-azure-account/issues/75 is tracking the interactive sign-in option.

**Comment by chrmarti** [comment]
@rdtechie Is this working with the latest version?

**Comment by radikovo** [comment]
Still not working :(
