### ISSUE TITLE
Specified tenant identifier 'azurecloud' is neither a valid DNS name, nor a valid external domain.

### ISSUE THREAD

**Issue by burge80475** [microsoft/vscode-azure-account#504]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azure-account.login
Error type: Error
Error Message: Timeout waiting for code

Version: 0.10.0
OS: win32
OS Release: 10.0.19042
Product: Visual Studio Code
Product Version: 1.65.0
Language: en

<details>
<summary>Call Stack</summary>

```
Timeout.<anonymous> extension.bundle.js:2:2321688
listOnTimeout timers.js:554:17
processTimers timers.js:497:7
```

</details>

**Comment by wwlorey** [comment]
Thanks for filing, @burge80475. As a workaround, please clear the `Azure: Tenant` setting in VS Code settings (could be in either user settings or workspace settings) and try signing in again.

**Comment by wwlorey** [comment]
@burge80475 please upgrade to [version 0.10.1](https://github.com/microsoft/vscode-azure-account/releases/tag/v0.10.1) and let us know if you're still running into this problem.

![Screen Shot 2022-03-23 at 10 08 54 AM](https://user-images.githubusercontent.com/22795803/159756540-6f5caff2-beee-4bd9-8617-63959f03e95b.png)
