### ISSUE TITLE
Logging into Azure Account doesn't add the account to VSCode 

### ISSUE THREAD

**Issue by preethamrajk** [microsoft/vscode-azure-account#507]
Does this occur consistently? YES
Repro steps:
Login to Azure account using VSCode

1. Click here 
![image](https://user-images.githubusercontent.com/16648593/157175826-5388b998-86ca-4259-9575-58f77d3beab5.png)
2. Login with AAD creds
3. I get this error
No response from the server

Action: azure-account.login
Error type: Error
Error Message: No response from the server

Version: 0.10.0
OS: win32
OS Release: 10.0.19042
Product: Visual Studio Code
Product Version: 1.64.2
Language: en

<details>
<summary>Call Stack</summary>

```
Logger.createError extension.bundle.js:2:788524
extension.bundle.js:2:801557extension.bundle.js:2:801557
processTicksAndRejections task_queues.js:93:5
```

</details>

**Comment by wwlorey** [comment]
@preethamrajk as a workaround please downgrade to version 0.9.11 of the Azure Account Extension using the method demonstrated [here](https://code.visualstudio.com/updates/v1_30#_install-previous-versions).

**Comment by wwlorey** [comment]
@preethamrajk please upgrade to [version 0.10.1](https://github.com/microsoft/vscode-azure-account/releases/tag/v0.10.1) and let us know if you're still running into this problem.

![Screen Shot 2022-03-23 at 10 08 54 AM](https://user-images.githubusercontent.com/22795803/159756540-6f5caff2-beee-4bd9-8617-63959f03e95b.png)

**Comment by huaouo** [comment]
@wwlorey I have similar problems.

- For 0.10.1, when the login web page says successful login, vscode still shows the "Sign in to Azure Button".
- For 0.10.0, I get <img width="348" alt="image" src="https://user-images.githubusercontent.com/19972269/162589140-e03e2e11-e4c6-4089-8c06-ce695c555323.png">
- For 0.9.11, login is successful, but it shows: <img width="200" alt="image" src="https://user-images.githubusercontent.com/19972269/162589089-3b8954f2-e824-4ad5-8f6a-7eba8e287e5f.png">

**Comment by wwlorey** [comment]
@huaouo Please share the info in the Azure Account Extension's output channel. It would be helpful to see that for 0.10.1 and 0.9.11.

![Screen Shot 2022-04-11 at 4 37 30 PM](https://user-images.githubusercontent.com/22795803/162850195-e0e9fcce-f84a-4c7d-a81c-e7687fb9939a.png)
