### ISSUE TITLE
Can't login to Azure subscription

### ISSUE THREAD

**Issue by villanisaac-kr** [microsoft/vscode-azure-account#515]
Does this occur consistently? 
Repro steps:

1. Installed Azure extension
2. When login in to Azure
3. I get redirected to Azure login page and login successfully 

![image](https://user-images.githubusercontent.com/90802542/158177453-0f992fc6-2e0c-4e54-91b7-342614cfd7b9.png)

4. Then VS code just shows below error message:

![image](https://user-images.githubusercontent.com/90802542/158177630-e38437bf-e219-4055-ae74-e744de2b98b2.png)

Note: I'm behind organization proxy and using spike proxy on my Mac to set up connectivity.

Action: azure-account.login
Error type: Error
Error Message: Get redacted:key returned http error: 302 and server response: ""

Version: 0.10.0
OS: darwin
OS Release: 20.6.0
Product: Visual Studio Code
Product Version: 1.64.2
Language: en

<details>
<summary>Call Stack</summary>

```
Logger.createError extension.bundle.js:2:788524
extension.bundle.js:2:801409
processTicksAndRejections task_queues.js:93:5
```

</details>

**Comment by wwlorey** [comment]
Hi @villanisaac-kr, this extension unfortunately doesn't play nice with proxys because it relies on a local server and requires access to at least one management endpoint. 

https://github.com/microsoft/vscode-azure-account/issues/419 is in our next milestone which will help you configure your proxy to fix problems like this.

**Comment by alexweininger** [comment]
Hi @villanisaac-kr, if you are still experiencing this issue, we have a workaround that has fixed this issue for some users.

See the [Unable to Sign In While Using a Proxy section of our wiki](https://github.com/microsoft/vscode-azure-account/wiki/Troubleshooting#unable-to-sign-in-while-using-a-proxy) for the workaround.
