### ISSUE TITLE
Filter on subscriptions is not working for me

### ISSUE THREAD

**Issue by julielerman** [Microsoft/vscode-azure-account#52]
macOS Sierra (latest)
VS Code (1.21.1)
Azure Account Ext:0.3.3
Azure Functions Ext: 0.8.0
Azure Cosmos DB ext: 0.5.1

I have two azure subs. By default,  both are showing in functions and cosmosdb panes.

When I use the F1 Select Subscriptions, I can't figure out how to make my selection stick. I'm tring to have only one sub show.Starting by deselect all, then If I use the mouse to check an option then hit enter, it then acts as though I chose Select All. If use the mouse to check  the sub I want and then hit tab, the menu closes but my options don't seem to change. Both subs are still listed in the function panes. Even if I close and open VS Code. After that if I F1 to select subscriptions again, it is set to select all.

Is it possible to filter subs using the resource filter setting?

**Comment by julielerman** [comment]
whoa ...now it's working. I don't know what I'm doing it differently. Hitting tab after making the selection does the trick now and it's working consistently. <grumble> sorry. nothing to see here.

**Comment by julielerman** [comment]
p.s. nice feature especially for screenshots! :)

**Comment by chrmarti** [comment]
Thanks :)

Btw., 0.4.0 of the extension is out with an updated subscription selection UI. It requires VS Code 1.22 or later.
