### ISSUE TITLE
WSL - Unknown or unsupported transport “disabled” for address “disabled:”

### ISSUE THREAD

**Issue by sassdawe** [microsoft/vscode-azure-account#525]
Does this occur consistently? Yes
Repro steps:

1. Install `azure-account`
2. Restart VS Code
3. See the error

Action: azure-account.initialize
Error type: Error
Error Message: Unknown or unsupported transport “disabled” for address “disabled:”

Version: 0.10.1
OS: linux
OS Release: 5.10.60.1-microsoft-standard-WSL2
Product: Visual Studio Code
Product Version: 1.65.2
Language: en

**Comment by wwlorey** [comment]
@sassdawe Please try the workaround in this comment: https://github.com/microsoft/vscode-docker/issues/1411#issuecomment-552494457
