### ISSUE TITLE
[Suggestion] It would be better if removing the "Azure Germany" from cloud list and the "Azure: Cloud" setting

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-azure-account#531]
**OS:** All
**Build Version:** 20220303.1
**Regression:** Not a regression

**Repro Steps:**

1. F1 -> Azure: Sign In to Azure Cloud -> Select "Azure Germany".
2. Check whether signs in to "Azure Germany" successfully.

**Actual:**
Sign in to "Azure Germany" failed with an error.
![image](https://user-images.githubusercontent.com/62053665/159832251-2d12077a-99f9-4650-8bb3-f9ad8c9a6968.png)

**Suggestion:**
It would be better if removing the "Azure Germany" from cloud list and the "Azure: CLoud" setting.
> Azure Germany has been nearing its end of service life and we’re not able to access it anymore.

![image](https://user-images.githubusercontent.com/62053665/159833288-dee60572-e898-464a-96e0-81c2ae5b390c.png)
![image](https://user-images.githubusercontent.com/62053665/159833323-7949b1ae-fb93-48dd-a3bf-df24afa7a1aa.png)

**Comment by wwlorey** [comment]
The plug has been pulled on Azure Germany 🔌 So we should remove it

Closing as duplicate as https://github.com/microsoft/vscode-azure-account/issues/533
