### ISSUE TITLE
Cannot sign in my azure account 

### ISSUE THREAD

**Issue by soj2agu** [microsoft/vscode-azure-account#540]
Does this occur consistently? YES
Repro steps:
1. sign in using azure extension

Action: azure-account.loginToCloud
Error type: AzureLoginError
Error Message: Acquiring user code failed

Version: 0.10.1
OS: win32
OS Release: 10.0.19042
Product: Visual Studio Code
Product Version: 1.65.2
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:2:2310074extension.bundle.js:2:2310074
extension.bundle.js:2:814295extension.bundle.js:2:814295
processTicksAndRejections task_queues.js:93:5
```

</details>

**Comment by wwlorey** [comment]
@soj2agu what cloud are you attempting to sign in to? 

Can you verify that your `azure.tenant` setting is what you expect to be?  (it should be blank or set to "common" if you don't use a specific tenant)

Also is there anything in the Azure Account output channel?
<img width="839" alt="Screen Shot 2022-03-28 at 3 24 33 PM" src="https://user-images.githubusercontent.com/22795803/160497173-934c38ad-fdd3-4a83-82e9-fbe41b49d50e.png">

**Comment by soj2agu** [comment]
Hello, now it is solved, thank you, I had to add manually the proxy certificates but now its working, thanks

Best regards

Juan Jose Soto Gaytan

Manufacturing Engineering (AguP/MFE5.1)
Robert Bosch LLC | Circuito Aguascalientes Norte No.141 | Valle de Aguascalientes | San Francisco de los Romo | 20358 Mexico | MEXICO | www.bosch.us
Tel. +52 449 454-2738 | Móvil +52 449 3460404 | ***@***.******@***.***>
​
