### ISSUE TITLE
Can't sign into Azure through VSCode - getaddrinfo ENOTFOUND

### ISSUE THREAD

**Issue by akashjeez** [microsoft/vscode-azure-account#542]
Does this occur consistently? 
Repro steps:

1.
2.

Action: waitForSubscriptions
Error type: REQUEST_SEND_ERROR
Error Message: request to redacted:url failed, reason: getaddrinfo ENOTFOUND redacted:url

Version: 0.10.1
OS: win32
OS Release: 10.0.19042
Product: Visual Studio Code
Product Version: 1.66.0
Language: en

<details>
<summary>Call Stack</summary>

```
new RestError extension.bundle.js:2:65384
NodeFetchHttpClient.<anonymous> extension.bundle.js:2:46552
step extension.bundle.js:2:2184890
Object.throw extension.bundle.js:2:2184995
rejected extension.bundle.js:2:2183720
```

</details>

**Comment by wwlorey** [comment]
@akashjeez this issue tends to be transient. Is it still reproducing for you?
