### ISSUE TITLE
Cannot login to Azure subscription from behind corporate proxy on VPN after authenticating

### ISSUE THREAD

**Issue by TimMarshAU** [microsoft/vscode-azure-account#543]
Not able to connect to Azure subscription after authenticating to corporate IDP via SSO.

This occurs on premise or when connecting to corporate domain via VPN (Windows 10 AOVPN).

Our proxy settings are set by a PAC, but, I have read the .pac to get the actual proxy:port combos (our enterprise has 3 depending on your situation).

Depending on which proxy I use, I am able to authenticate to our corporate AD. It attempts to call back to VS code, and I get 3 different issues (without successful surfacing of my Azure subscriptions) depending on my settings.

**Two key issues:** 
1. Error on callback to VS Code when I set one of the proxies, using proxy input in VS Code (Application section).
localhost:port -> redirects to our SSO -> authenticate -> http://127.0.0.1:53460/
Error: request to https://management.azure.com/subscriptions?api-version=2016-06-01 failed, reason: unable to get local issuer certificate (this is for a particular proxy)

**Error information**
Action: waitForSubscriptions
Error type: UNABLE_TO_GET_ISSUER_CERT_LOCALLY
Error Message: request to redacted:url failed, reason: unable to get local issuer certificate

2. Device code login, call back to VS Code and hands back to VS Code with "Azure sign in" (i.e. Sign in to Azure prompt under Azure RG, Azure Functions, Azure Storage sections). The output in this scenario shows me it calls login.microsoft.com then "Socket is closed". _The blue band at bottom of window shows my Azure account but it won't retrieve the subscriptions._

3. Device code login or SSO login, call back to VS Code and nothing happens ie "Sign in to Azure..." shown under RG, Functions, Storage sections.

![Capture](https://user-images.githubusercontent.com/6721509/161453349-6cd272e5-409c-42ec-a4c1-5bb81538dcc6.PNG)

Environment: Windows 10, VS Code 1.66, extensions Azure Account, Azure Functions, Azure storage, latest versions.
No ENV variables set for http/s proxy.

Does this occur consistently? Yes
Repro steps:

1. Set proxy to one of 3 corporate proxies.
2. Call login via Command Palette.
5. Depending on proxy, either: Error 1 or Error 2 or Error 3 above.

To fix/debug, have tried:
1. Changing between ADAL and MSAL.
2. Adding the tenant ID - makes no difference.
6. Have tried setting proxy (3 different proxies we have) in VS Code, and in environment variables including with u/name and pwd.
7. Have tried all the proxy support settings.
8. Have tried Proxy Strict SSL on/off.
9. Have tried System Certificates on/off.
10. Have read and [followed this](https://github.com/microsoft/vscode-azure-account/wiki/Troubleshooting#unable-to-sign-in-while-using-a-proxy)
11. Have installed the Azure Accounts Alpha which outputs the called URLs.

Version: 0.10.1
OS: win32
OS Release: 10.0.19042
Product: Visual Studio Code
Product Version: 1.66.0
Language: en

<details>
<summary>Call Stack</summary>

```
ClientRequest.<anonymous> extension.bundle.js:2:2630161
```

</details>

**Update**
After installing the alpha version of the Azure Account extension per [this troubleshooting guide](https://github.com/microsoft/vscode-azure-account/wiki/Troubleshooting), the output for Azure Account is as follows. This is all the way through the authentication process, using Device Code (it does not seem possible for VS Code to pop up a browser based modal for SSO - it always redirects to device code in browser).

`Attempting to reach URL "https://login.microsoftonline.com/"...
Socket is closed
Attempting to reach URL "https://login.microsoftonline.com/"...
Socket is closed`

The above output is after about 3 minutes of waiting for subscriptions to be retrieved. 

** Update 8/4/22 **

On VPN, proxy support "on", I can authenticate to MSFT from our Federated SSO to MSFT, but again the call back to VS Code doesn't seem to work (device code login). I just get the looping "Waiting fo Azure Signin"

**Comment by wwlorey** [comment]
Hi @TimMarshAU, thanks for all the details on this. It looks like the extension can't access https://login.microsoftonline.com. Is it possible to add that URL to the allowlist for your proxy?

**Comment by timmo001** [comment]
Try switching off "Proxy Strict SSL". If your coprerate proxy is like ours, the SSL certificates are matipulated by the proxy.

I'm also having issues signing in, but with different errors

**Comment by TimMarshAU** [comment]
> Try switching off "Proxy Strict SSL". If your coprerate proxy is like ours, the SSL certificates are matipulated by the proxy.
> 
> I'm also having issues signing in, but with different errors.
> 
> Turns out our setup works without the proxy and through a PAC file. However node will have issues.. No proxy is the best method, if your company can work using a bypass on the proxy for microsoft services, you would have a much better experience, as I'm sure you'll know

Thanks Timmo. Big Health entity so need to use proxy, though there is a bypass (a Squid proxy) so have asked them to whitelist everything Azure/VS Code/MS. In any case though, it shouldn't be this hard.

 I did turn off Proxy Strict SSL. Makes no difference. Our proxy intercepts requests and signs requests with a self signed cert which also causes issues.

Bit of a nightmare.

Have also asked our state helpdesk to whitelist everything Azure/MS.

**Comment by TimMarshAU** [comment]
> Hi @TimMarshAU, thanks for all the details on this. It looks like the extension can't access https://login.microsoftonline.com. Is it possible to add that URL to the allowlist for your proxy?

I'd be surprised if we blocked it on the proxy. Our state health corp is a MS shop, and we have federated with MSFT so can use our SSO to access MSFT products/services. I can do this no issue on prem and via VPN. It's just the VS Code component - specifically the call back (I think) from MSFT authentication to the VS Code Azure Accounts extension which fails (and basically hangs, trying to receive subs).

On prem, if I use our Squid bypass proxy (which I can't do off prem via VPN) I can do this no issue.

So authentication itself is ok, I think

**Comment by wwlorey** [comment]
Thanks for the info, @TimMarshAU.

> Was on call to MSFT support on this, and we tried az login via AZ cli, to no avail.

Trying to understand this right: was the CLI successful in logging in to `az`? Or did that fail as well? It's expected that logging in via the CLI will not sign you into the VS Code extension.
