### ISSUE TITLE
he name org.freedesktop.secrets was not provided by any .service files

### ISSUE THREAD

**Issue by peteraar** [microsoft/vscode-azure-account#544]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azure-account.initialize
Error type: Error
Error Message: The name org.freedesktop.secrets was not provided by any .service files

Version: 0.10.1
OS: linux
OS Release: 5.4.0-107-generic
Product: Visual Studio Code
Product Version: 1.66.0
Language: en

**Comment by wwlorey** [comment]
Please see this comment for how to fix this issue: https://github.com/microsoft/vscode/issues/131262#issuecomment-903922003

Let us know if you run into any more problems.
