### ISSUE TITLE
Unable to logn to Azure Cloud

### ISSUE THREAD

**Issue by t814960** [microsoft/vscode-azure-account#550]
Does this occur consistently?  Yes
Repro steps:

1. Tried Azure sigin using Azure login vs code extension

Action: azure-account.loginToCloud
Error type: Error
Error Message: No response from the server

Version: 0.10.1
OS: win32
OS Release: 10.0.19042
Product: Visual Studio Code
Product Version: 1.66.2
Language: en

<details>
<summary>Call Stack</summary>

After sigin page, VScode extension does not signin.
```
Logger.createError extension.bundle.js:2:799923
extension.bundle.js:2:812956extension.bundle.js:2:812956
```

</details>

**Comment by wwlorey** [comment]
@t814960 please verify that the values of the following extension settings are what you'd expect them to be:

* `Azure: Cloud`
* `Azure › Custom Cloud: Resource Manager Endpoint Url` (if applicable)
* `Azure: Tenant`

Also please ensure `Azure: Authentication Library` is set to ADAL.

**Comment by nseth314** [comment]
> @t814960 please verify that the values of the following extension settings are what you'd expect them to be:
> 
> * `Azure: Cloud`
> * `Azure › Custom Cloud: Resource Manager Endpoint Url` (if applicable)
> * `Azure: Tenant`
> 
> Also please ensure `Azure: Authentication Library` is set to ADAL.

Hi @wwlorey ,

Thanks for your quick reply.

I have checked the setting in Vscode extension (Azure account) you mentioned above. It is as per your recommendation. No changes made to the setting, all above recommendations were already present.

Logs :

Thu, 21 Apr 2022 21:52:31 GMT:37da7698-b395-484c-a202-242525474122 - OAuth2Client: ERROR: No response from the server
Stack:
Error: No response from the server
    at Logger.createError (c:\Users\T814960\.vscode\extensions\ms-vscode.azure-account-0.10.1\dist\extension.bundle.js:2:799923)
    at c:\Users\T814960\.vscode\extensions\ms-vscode.azure-account-0.10.1\dist\extension.bundle.js:2:812956
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Error: No response from the server
No response from the server

Also, please advise how to check redirect server status?

**Comment by wwlorey** [comment]
Thanks, @nseth314.

The redirect server is currently up & running. This doesn't appear to be a problem with that server if the issue is still reproducing for you.

Are you behind a proxy?

**Comment by nseth314** [comment]
Hi @wwlorey 

Yes I am behind Company 's Proxy. We are currently using webproxy to bypass that,

This arrangement was working fine earlier without any issues, but now suddenly the sign in to Azure is not working from VSCode. See logs above,

**Comment by wwlorey** [comment]
> Yes I am behind Company 's Proxy. We are currently using webproxy to bypass that,

Please follow the steps in this proxy debugging guide and follow up as needed: https://github.com/microsoft/vscode-azure-account/wiki/Troubleshooting#unable-to-sign-in-while-using-a-proxy
