### ISSUE TITLE
Cannot list subscriptions behind corporate proxy

### ISSUE THREAD

**Issue by lukaszstarzak** [microsoft/vscode-azure-account#554]
Hi everyone, 
It seems there are plenty of tickets having similar issues so I thought I'd add something from myself. 

First of all, I was unable to install 0.10.2-alpha as per wiki, so apologies for no detailed debug messages.

Secondly, I must underline that authentication works for AzCLI and PowerShell in both cases with --use-device-code. Issue I am experiencing manifests itself only when it comes to Azure Account extension authentication. (Having #551 could open potential for easy workarounds)

**Case 1** 
- VS Code Version: 1.66.2
- Azure Account Extension Version: 0.10.1
- OS Version: Win Srv 2012R2 

Running any "Sign In" option results in proxy complaining that connection with login.microsoftonline.com cannot be established. Specifically "The SSL handshake could not be performed".  Investigating traffic at the proxy, I wasn't able to conclude anything of essence, traffic arrives and gets forwarded as usual. As stated above console auth works just fine, so I'd consider networking flow as "validated". 

Getting into extension settings, I've tried changing authentication from ADAL to MSAL, which resulted in:
`Socket is closed
endpoints_resolution_error: Error: cloud not resolve endpoints. Please check network and try again. Detail: ClientConfigurationError: untrusted_authority: The provided authority is not a trusted authority. Please include this authority in the knownAuthorities config parameter.`

With that I wasn't able to conclude what authority is untrusted and how to address this issue. But since there must have been some change I decided to trace steps back, this brings me to my hack workaround.

**Case 2** 
- VS Code Version: 1.66.2
- Azure Account Extension Version: 0.9.x
- OS Version: Win Srv 2012R2 

Reverting to version to 0.9.x helped remediate issues with not seeing subscriptions. Authentication against tenant works without any issues. I receive device code and see everything as expected. Although, trying to access or deploy any resources using Azure Functions extensions results in error message "The access token is invalid". As a matter of fact, all subscriptions requests under "Azure" icon result in that error. When I reverted Az Functions extension to v1.6.0 I was able to see functions in my tenant. 

To conclude, I have a workaround that has remediated most pressing issues. Now I turn to you guys. What could we do to address this issue? I suspect that these issues are all tied to MS retiring ADAL in favour of MSAL and extensions introducing breaking changes. I'd be happy to contribute, I could provide more details or run thorough debug, but I'd ask for your help in defining specifics.

**Comment by nixrod** [comment]
Had the same issue as @lukaszstarzak described. His workaround helped me but I am also now stuck on a old version of Azure Account.

**Comment by alexweininger** [comment]
Hi @lukaszstarzak and @nixrod, we've created two development builds with proposed fixes for proxy issues. It would be a huge help if you could test these. #714 contains details and instructions on how to do so.

**Comment by alexweininger** [comment]
See the [Enable and View Logs](https://github.com/microsoft/vscode-azure-account/wiki/Enable-and-view-logs) section of the wiki for how to capture and share Azure Account extension logs. These logs may help diagnose issues with proxies quite a bit.
