### ISSUE TITLE
microsoft/vscode-azure-account/files/8546517

### ISSUE THREAD

**Issue by IngridMi** [microsoft/vscode-azure-account#556]
Does this occur consistently?  Type Yes or No
Repro steps:

1.
2.
[ThirdPartyNotices.zip](https://github.com/microsoft/vscode-azure-account/files/8546517/ThirdPartyNotices.zip)

Action: azure-account.selectSubscriptions
Error type: Error
Error Message: Unable to write into user settings. Please open the user settings to correct errors/warnings in it and try again.

Version: 0.10.1
OS: win32
OS Release: 10.0.22598
Product: Visual Studio Code
Product Version: 1.66.2
Language: en

<details>
<summary>Call Stack</summary>

```
b.toConfigurationEditingError workbench.desktop.main.js:2611:12734
b.updateConfiguration workbench.desktop.main.js:2611:9402
b.doWriteConfiguration workbench.desktop.main.js:2611:9244
async Object.factory workbench.desktop.main.js:2611:8904
```

</details>

**Comment by wwlorey** [comment]
> Error Message: Unable to write into user settings. Please open the user settings to correct errors/warnings in it and try again.

Please follow these steps and let us know if you're still running into issues.
