### ISSUE TITLE
New redirect server is broken for Azure China

### ISSUE THREAD

**Issue by wwlorey** [microsoft/vscode-azure-account#560]
This is likely the case for other *sovereign* clouds as well.
![Screen Shot 2022-04-26 at 4 46 45 PM](https://user-images.githubusercontent.com/22795803/165410532-2544e8b1-08a3-4796-82bb-a303321a081d.png)

**Comment by TylerLeonhardt** [comment]
This should be fixed now... just needs verification

**Comment by TylerLeonhardt** [comment]
This is fixed now confirmed by CTI
