### ISSUE TITLE
Change to MSAL credential.getToken returns different structure

### ISSUE THREAD

**Issue by xiaolang124** [microsoft/vscode-azure-account#563]
- VS Code Version: 1.66.2
- Azure Account Extension Version: 0.10.1
- OS Version: 10.0.22000 Build 22000

Steps to Reproduce:

1. Change Authentication library to MSAL.
![image](https://user-images.githubusercontent.com/13211513/166890850-3bbbc097-39c4-44d0-857d-b0aa2b63ad3b.png)
2. Try to login and get credential, then getToken via credential. The token gets from credential does not match the `api.d.ts` structure.
![image](https://user-images.githubusercontent.com/13211513/166891131-7c51d30f-511b-4107-b8bb-7e032a45f9ed.png)

![image](https://user-images.githubusercontent.com/13211513/166891243-e7f97399-3d27-4279-b93e-0270401bf31e.png)

Do I need to use another `d.ts` or how can I update my code to support MSAL.

**Comment by philliphoff** [comment]
@xiaolang124 Can you show how you're aquiring the exported API instance of the Azure Account extension?  (There are two flavors of API, so I want to make sure which you're using.) Also, where did you get the `d.ts` file from?

**Comment by xiaolang124** [comment]
@philliphoff 
I got `d.ts` from `https://github.com/Microsoft/vscode-azure-account/blob/main/src/azure-account.api.d.ts`. And I find that credentials2 has been extended to `TokenCredentialsBase | TokenCredential`. In my version, credentials2 only can be TokenCredentialsBase type. (History version: https://github.com/microsoft/vscode-azure-account/commit/b2228658a0dbca2414dba4e10b76b6afafa47530#). Does this mean I need to check return type from `Azure account extension`?

Here is the code example. (https://github.com/OfficeDev/TeamsFx/blob/e224b20a1947c2a7a0f3651019037f43416c5b6b/packages/vscode-extension/src/commonlib/azureLogin.ts#L181)
```
  private doGetAccountCredentialAsync(): Promise<TokenCredentialsBase | undefined> {
    if (this.isUserLogin()) {
      const azureAccount: AzureAccount =
        vscode.extensions.getExtension<AzureAccount>("ms-vscode.azure-account")!.exports;
      return new Promise(async (resolve, reject) => {
        await azureAccount.waitForSubscriptions();
        if (azureAccount.subscriptions.length > 0) {
          let credential2 = azureAccount.subscriptions[0].session.credentials2;
          if (AzureAccountManager.tenantId) {
            for (let i = 0; i < azureAccount.sessions.length; ++i) {
              const item = azureAccount.sessions[i];
              if (item.tenantId == AzureAccountManager.tenantId) {
                credential2 = item.credentials2;
                break;
              }
            }
          }
          resolve(credential2);
        } else if (azureAccount.sessions.length > 0) {
          resolve(azureAccount.sessions[0].credentials2);
        } else {
          reject(LoginFailureError());
        }
      });
    }
    return Promise.reject(LoginFailureError());
  }
```

**Comment by philliphoff** [comment]
@xiaolang124 The short answer is that ADAL and MSAL have very different notions of what a credential contains.  In particular, MSAL tends to treat the contents of a credential as opaque and, hence, why only the access token itself is returned.  Aside from the access code itself, are there other properties of the ADAL-based credential you were using?  It looks like our MSAL provider does acquire various "account info" properties but doesn't expose them publicly for whatever reason.

One other thing; it appears as though you're using our "legacy" API; there's a `getApi<AzureAccountExtensionApi>('1.0.0')` that is exported as well, which allows 3rd-parties access to a better versioning API.  (It doesn't solve this particular issue but it should allow better compatibility going forward.) See the [@microsoft/vscode-azext-utils](https://www.npmjs.com/package/@microsoft/vscode-azext-utils) library and its `AzureExtensionApiProvider`.

**Comment by xiaolang124** [comment]
Thanks for the reply, I see for now we can switch ADAL and MSAL library. And ADAL is the default one. Do you have any plan to set MSAL as default or when will ADAL be deprecated?

**Comment by philliphoff** [comment]
We'd love to switch to MSAL but, at the moment, it doesn't support all of the authentication scenarios used by Azure Account.  If and when those scenarios are unblocked, we'll start a move towards MSAL as the default and then deprecating and eventually removing ADAL support.  I don't have a timeline, unfortunately, for when that might happen.

**Comment by xiaolang124** [comment]
Thanks for the reply, this is really helpful.
