### ISSUE TITLE
Cannot list subscriptions

### ISSUE THREAD

**Issue by Sanika2103** [microsoft/vscode-azure-account#564]
- VS Code Version: 1.67
- Azure Account Extension Version:  0.10.1
- OS Version:  21H1

Does your account belong to more than one directory? (see your directories [here](https://aka.ms/AAevnvr)): 

Any other information about your Azure account that may be useful: 
Username :  Sanika.Patil@studentambassadors.com

**Comment by alexweininger** [comment]
Could you try the steps in the [Unable to List Subscriptions section of our wiki](https://github.com/microsoft/vscode-azure-account/wiki/Troubleshooting#unable-to-list-subscriptions) and see if they fix the issue?
