### ISSUE TITLE
The name org.freedesktop.secrets was not provided by any .service files

### ISSUE THREAD

**Issue by lllrdgz** [microsoft/vscode-azure-account#565]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azure-account.initialize
Error type: Error
Error Message: The name org.freedesktop.secrets was not provided by any .service files

Version: 0.10.1
OS: linux
OS Release: 5.17.5-arch1-1
Product: Visual Studio Code
Product Version: 1.66.2
Language: en

**Comment by philliphoff** [comment]
@lllrdgz Do you have `gnome-keyring` installed?
