### ISSUE TITLE
Using bash history ctrl-r destroys rendering

### ISSUE THREAD

**Issue by viblo** [microsoft/vscode-azure-account#57]
When I try to navigate the bash history with reverse-i-search (ctrl-r), or up arrow the text becomes a mess in the terminal window making this kind of navigation impossible to use properly.

Tested on Windows, with VSCode 1.23.0, Azure Account 0.4.0.

**Comment by viblo** [comment]
Sorry, left out the most important part. Yes, this is for Bash in Cloud Shell. If I open a normal Bash in WSL prompt navigation works without issues.

**Comment by chrmarti** [comment]
This might be an issue with the initial size of the shell (or what it believes it's size is). Does it reproduce when you first resize the terminal a little?

**Comment by chrmarti** [comment]
Still an issue on the extension's side. I now know where to look.

**Comment by wwlorey** [comment]
@v-mengwe can you verify if this issue has been resolved?

**Comment by v-mengwe** [comment]
**VS Code Version:** 1.58.2 (user setup)
**Azure Account:** 0.9.9-alpha

**Repro Steps:**

1. Install the azure account extension in VS Code -> F1 -> Type and choose "Azure: Open Bash in Cloud Shell".
2. Open a "Bash in Cloud Shell" terminal.
3. Up/down arrow or CTRL+R -> Check the terminal.

**Actual:**
The terminal shows well.
![bash2](https://user-images.githubusercontent.com/62053665/127449289-fdebb7ce-303b-4340-9dc9-39111380d4a0.gif)
![bash3](https://user-images.githubusercontent.com/62053665/127450209-028f3d1d-9405-4a90-b880-eac323705820.gif)

**Comment by wwlorey** [comment]
Thanks for looking into this @v-mengwe 🙏 Closing as resolved
