### ISSUE TITLE
facing issue

### ISSUE THREAD

**Issue by arpit585** [microsoft/vscode-azure-account#573]
Does this occur consistently? 
Repro steps:

1.
2.

Action: waitForSubscriptions
Error type: REQUEST_SEND_ERROR
Error Message: request to redacted:url failed, reason: getaddrinfo ENOTFOUND redacted:url

Version: 0.10.1
OS: win32
OS Release: 10.0.22000
Product: Visual Studio Code
Product Version: 1.67.2
Language: en

<details>
<summary>Call Stack</summary>

```
new RestError extension.bundle.js:2:65384
NodeFetchHttpClient.<anonymous> extension.bundle.js:2:46552
step extension.bundle.js:2:2184890
Object.throw extension.bundle.js:2:2184995
rejected extension.bundle.js:2:2183720
```

</details>

**Comment by philliphoff** [comment]
@arpit585 Can you provide a little more context as to what your were doing when you encountered this error?  Did it happen only once, or is it reproducable? Thanks!
