### ISSUE TITLE
Can't Sign in

### ISSUE THREAD

**Issue by daastidev** [microsoft/vscode-azure-account#576]
Does this occur consistently? 
Repro steps:

1.
2.

Action: waitForSubscriptions
Error type: REQUEST_SEND_ERROR
Error Message: request to redacted:url failed, reason: getaddrinfo ENOTFOUND redacted:url

Version: 0.10.1
OS: win32
OS Release: 10.0.22000
Product: Visual Studio Code
Product Version: 1.67.2
Language: es

<details>
<summary>Call Stack</summary>

```
new RestError extension.bundle.js:2:65384
NodeFetchHttpClient.<anonymous> extension.bundle.js:2:46552
step extension.bundle.js:2:2184890
Object.throw extension.bundle.js:2:2184995
rejected extension.bundle.js:2:2183720
```

</details>

**Comment by philliphoff** [comment]
@daastidev Can you provide a little more context around the issue you encountered?  For example, what were you trying to do, and did it happen only once or every time you attempt it?
