### ISSUE TITLE
Can't sign-into Azure account using the Azure Extensions from VS Code 

### ISSUE THREAD

**Issue by lalith1997** [microsoft/vscode-azure-account#580]
VS Code Version: 1.68.0
Azure Account Extension Version: 0.10.1
Azure Functions Extension Version: 1.7.3

Trying to deploy my Azure Function to my Azure environment using Visual Studio. But I'm not able to sign into my Azure account from VS Code. I get redirected to a webpage message saying "successful login" and once I close the webpage, I'm not signed in VS Code. Is there something wrong with the Azure extensions or what might be causing this ?

**Comment by lalith1997** [comment]
I was able to sign-in by installing another version of the Azure Account Extension: v0.9.11

**Comment by mbmwlr** [comment]
I have the same issue, any news on this? Additionally, I can't list my resources. I can see the subcriptions, but no resources are shown.

**Comment by alexweininger** [comment]
Are you behind a corporate proxy of some kind? This can often cause issues with sign in. If you are, please see the [Unable to Sign In While Using a Proxy section of our wiki](https://github.com/microsoft/vscode-azure-account/wiki/Troubleshooting#unable-to-sign-in-while-using-a-proxy) for possible fixes.

**Comment by mbmwlr** [comment]
Ah yes, I am behind a corporate proxy. Thank you, this solved it. Already had some of the URL's white-listed, but not all of them.

**Comment by alexweininger** [comment]
> Ah yes, I am behind a corporate proxy. Thank you, this solved it. Already had some of the URL's white-listed, but not all of them.

Great! Thanks for confirming the workaround solved your issue.

**Comment by GodKratos** [comment]
@alexweininger this issue needs to be reopened. I had the exact same problem as OP where the sign in would redirect to a website, authenticate me and say "You are now signed in and can close this page" however I would not be logged in to the extension in VS Code.
After downgrading the Azure Account extension to 0.9.11 like OP mentioned I was able to successfully log in to the extension.

The difference after the downgrade was that the login process performed a 2FA check during authentication, which did not happen at all on the latest version (0.11.3) which is likely why it was not working.

I updated the Azure Account extension to the latest version after authenticating and it stayed logged in ok.

**Comment by alexweininger** [comment]
@GodKratos, sorry about that, closed this issue because I thought the user with the proxy issue was the original poster.

**Comment by bungard** [comment]
> @alexweininger this issue needs to be reopened. I had the exact same problem as OP where the sign in would redirect to a website, authenticate me and say "You are now signed in and can close this page" however I would not be logged in to the extension in VS Code. After downgrading the Azure Account extension to 0.9.11 like OP mentioned I was able to successfully log in to the extension.
> 
> The difference after the downgrade was that the login process performed a 2FA check during authentication, which did not happen at all on the latest version (0.11.3) which is likely why it was not working.
> 
> I updated the Azure Account extension to the latest version after authenticating and it stayed logged in ok.

I had the same experience. 
0.11.3 -> No MFA prompt..and VSCode remains showing that I am not logged in
> You are signed in now and can close this page.
0.9.11 -> MFA prompt and VSCode shows my Subscription. However, I am unable to access any resources in my subscription 

If I update to 0.11.3 and run ">Azure: Sign In with Device Code" from the Command palette, this seems to respect the MFA prompt and everything seems to be working.

**Comment by xuanhai266** [comment]
I'm facing the same error and the problem does not occur in v0.9.11. Please fix it in the next version.

**Comment by at-sttr** [comment]
I am facing the same issue: I can't sign in and I am not behind a proxy but still get the (error) messages as described above (You appear to be offline... and You are now signed in...)

My extension versions are:
Azure Tools v1.1.1
Azure Account v0.11.3

We are also required to use 2FA.

I figured out that it works successfully with the latest extension version, when signing in with Edge instead of Firefox (which is my default browser).

I did this:
1. Clicked on Sign in to Azure
2. VS Code opened a new tab in my default browser (Firefox)
3. I copied the URL
4. Opened a new Edge tab and navigated to the URL that I had copied
5. Clicked on my user account (which was connected to Windows)
6. I am now successfully signed in and can see my subscription under resources

**Comment by hristochr** [comment]
What worked for me:

- downgraded Azure Account to 0.9.11
- opened the command palette and clicked "Azure sign in with device code"

**Comment by alexweininger** [comment]
> Same issue for me since v0.11.5. Downgrading to 0.10.01 worked for me. However there clearly is an issue in this extension... With the newer versions I do not get the MFA Prompt and the Login is not successful. This should get more attention from Microsoft

Are you working behind a proxy? Also, see the [Enable and View Logs](https://github.com/microsoft/vscode-azure-account/wiki/Enable-and-view-logs) section of the wiki for how to capture and share Azure Account extension logs.

**Comment by hbertsch** [comment]
@alexweininger I logged the trace of the login. Please notice that I have masked some IDs in the log.
It definetly has to do with the MFA. However I do not understand why MFA is working when using version `0.10.1` of `Azure Account`

````
2023-06-01 12:28:41.808 [info] MSAL: [Thu, 01 Jun 2023 10:28:41 GMT] : @azure/msal-node@1.14.6 : Info - getTokenCache called
2023-06-01 12:28:41.808 [trace] MSAL: [Thu, 01 Jun 2023 10:28:41 GMT] : @azure/msal-node@1.14.6 : Trace - getAllAccounts called
2023-06-01 12:28:41.809 [trace] MSAL: [Thu, 01 Jun 2023 10:28:41 GMT] : @azure/msal-node@1.14.6 : Trace - Retrieving all cache keys
2023-06-01 12:28:41.809 [trace] MSAL: [Thu, 01 Jun 2023 10:28:41 GMT] : @azure/msal-node@1.14.6 : Trace - Getting cache key-value store
2023-06-01 12:28:41.812 [info] Attempting to reach URL "https://login.microsoftonline.com/"...
2023-06-01 12:28:42.774 [info] Attempting to reach URL "https://vscode.dev/redirect"...
2023-06-01 12:28:42.779 [info] Attempting to reach URL "https://login.microsoftonline.com/common/oauth2/authorize?response_type=code&client_id=aebc6443-996d-45c2-90f0-388ff96faa56&redirect_uri=https%3A%2F%2Fvscode.dev%2Fredirect&state=http%3A%2F%2F127.0.0.1%3A58915%2Fcallback?nonce=nOJePep4P8xzO2LR6gdqbA%3D%3D&prompt=select_account"...
2023-06-01 12:29:00.068 [trace] ADAL: Authority: VERBOSE: Performing instance discovery
2023-06-01 12:29:00.068 [trace] ADAL: Authority: VERBOSE: Performing static instance discovery
2023-06-01 12:29:00.068 [trace] ADAL: Authority: VERBOSE: Authority validated via static instance discovery.
2023-06-01 12:29:00.068 [debug] ADAL: TokenRequest: INFO: Getting token with auth code.
2023-06-01 12:29:00.069 [info] 
┌────── Axios Request POST https://login.microsoftonline.com/common/oauth2/token?api-version=1.0
	Headers (8):
	└ Accept-Charset: "utf-8"
	└ Content-Type: "application/x-www-form-urlencoded"
	└ client-request-id: "3207dba3-267c-........"
	└ return-client-request-id: "true"
	└ x-client-CPU: "x64"
	└ x-client-OS: "darwin"
	└ x-client-SKU: "Node"
	└ x-client-Ver: "0.2.3"
	Query parameters (6):
	└ client_id: "aebc6443-996d-......"
	└ client_secret: ""
	└ code: "0.AS8AD05WVtODUkuS6Ka7nqNlZENkvK5tmcJFkPA4j_lvqlYvAMs........."
	└ grant_type: "authorization_code"
	└ redirect_uri: "https://vscode.dev/redirect"
	└ resource: "https://management.core.windows.net/"
	Proxy configuration: None
└───────────────────────────────────────────────────
2023-06-01 12:29:00.337 [error] Get Token request returned http error: 400 and server response: {"error":"interaction_required","error_description":"AADSTS50076: Due to a configuration change made by your administrator, or because you moved to a new location, you must use multi-factor authentication to access '797f4846-ba00-......'.\r\nTrace ID: b394a6f7-7147-........\r\nCorrelation ID: 3207dba3-267c-4e37-........\r\nTimestamp: 2023-06-01 10:29:00Z","error_codes":[50076],"timestamp":"2023-06-01 10:29:00Z","trace_id":"b394a6f7-7147-458f-92e6-bb8bfb299a00","correlation_id":"3207dba3-267c-4e37-........","error_uri":"https://login.microsoftonline.com/error?code=50076","suberror":"basic_action"}
````

**Comment by GodKratos** [comment]
> What worked for me:
> 
>     * downgraded Azure Account to 0.9.11
> 
>     * opened the command palette and clicked "Azure sign in with device code"

Actually this option works in the latest version, no need to downgrade to do this from command palette.

**Comment by PStoner3** [comment]
I am experiencing he same issue. I am trying to log out of my corporate Azure account and log into my personal account. I've tried downgrading to 0.9.11 - no change. I've tried logging in through Edge, while I was promoted for MFA, there was still no changes. Once logged in (to what should be my personal account, my resources still show the subscriptions from my corporate account.
