### ISSUE TITLE
 REQUEST_SEND_ERROR

### ISSUE THREAD

**Issue by OuchattiKhadija** [microsoft/vscode-azure-account#581]
Does this occur consistently? 
Repro steps:

1.
2.

Action: waitForSubscriptions
Error type: REQUEST_SEND_ERROR
Error Message: request to redacted:url failed, reason: getaddrinfo ENOTFOUND redacted:url

Version: 0.10.1
OS: win32
OS Release: 10.0.19043
Product: Visual Studio Code
Product Version: 1.68.0
Language: fr

<details>
<summary>Call Stack</summary>

```
new RestError extension.bundle.js:2:65384
NodeFetchHttpClient.<anonymous> extension.bundle.js:2:46552
step extension.bundle.js:2:2184890
Object.throw extension.bundle.js:2:2184995
rejected extension.bundle.js:2:2183720
```

</details>

**Comment by nturinski** [comment]
Please provide repro steps.
