### ISSUE TITLE
Can't login, v0.10.2-alpha .vsix link is not accessible on troubleshooting page

### ISSUE THREAD

**Issue by HaroldSussmilch** [microsoft/vscode-azure-account#584]
- VS Code Version:  Version: 1.68.1 (user setup)
- Azure Account Extension Version:  v0.10.1
- OS Version: Win10 Enterprise 20H2 19042.1706

Steps to Reproduce:

1.Trying to login to Azure account behind corporate proxy -> Failing (similar to many issues)
          _Error: No response from the server
          Error: No response from the server
          Acquiring user code failed_
2. Trying to use the v0.10.2-alpha for troubleshooting/whitelisting URL
3.  Link : _https://dev.azure.com/ms-azuretools/534e1e1c-b364-44d0-b5ee-dce879a5106e/_apis/build/builds/44727/artifacts?artifactName=vsix&api-version=7.0&%24format=zip_ 
gives 
_{"$id":"1","innerException":null,"message":"The requested build 44727 could not be found.","typeName":"Microsoft.TeamFoundation.Build.WebApi.BuildNotFoundException, Microsoft.TeamFoundation.Build2.WebApi","typeKey":"BuildNotFoundException","errorCode":0,"eventId":3000}_

Would welcome an accessible  v0.10.2-alpha .vsix for additionnal troubleshooting
Tried reverting to older versions but not fails to work as well.

**Comment by nturinski** [comment]
Hi @HaroldSussmilch,

You can use this link to download the v0.10.2-alpha version of the extension:
https://dev.azure.com/ms-azuretools/534e1e1c-b364-44d0-b5ee-dce879a5106e/_apis/build/builds/48500/artifacts?artifactName=vsix&api-version=7.0&%24format=zip

Is that what you mean by having an accessible version?

**Comment by HaroldSussmilch** [comment]
Perfect, I think the wiki's link just points to an outdated build that cannot be downloaded anymore.
