### ISSUE TITLE
issu

### ISSUE THREAD

**Issue by amir4q** [microsoft/vscode-azure-account#586]
Does this occur consistently? 
Repro steps:

1.
2.

Action: updateSubscriptionsAndTenants
Error type: ETIMEDOUT
Error Message: request to redacted:url failed, reason: connect ETIMEDOUT redacted:id

Version: 0.10.1
OS: win32
OS Release: 10.0.19044
Product: Visual Studio Code
Product Version: 1.68.1
Language: en

<details>
<summary>Call Stack</summary>

```
ClientRequest.<anonymous> extension.bundle.js:2:2630161
```

</details>

**Comment by nturinski** [comment]
Please provide repro steps.
