### ISSUE TITLE
canot login

### ISSUE THREAD

**Issue by MichaelRoger** [microsoft/vscode-azure-account#589]
Issue Type: <b>Bug</b>

clicking on sign in to azure.
after logging in in edge, it is not logged in in visual studio code

Extension version: 0.10.1
VS Code version: Code 1.68.1 (30d9c6cd9483b2cc586687151bcbcd635f373630, 2022-06-14T12:48:58.283Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9850H CPU @ 2.60GHz (6 x 2592)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.85GB (22.63GB free)|
|Process Argv|--crash-reporter-id 1c4c54e0-f389-4581-a5cb-a93b1108f5ee|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vscscmwlcmt:30465135
cppdebug:30492333
vsclangdc:30486549

```

</details>

**Comment by MichaelRoger** [comment]
like in #582  and others... version 0.9.11 works...

**Comment by alexweininger** [comment]
1. Using version 0.10.1, does trying sign-in two times fix the issue?
1. What is the value of the `azure.authenticationLibrary` setting? Try switching to MSAL or ADAL and retrying sign-in.
![image](https://user-images.githubusercontent.com/12476526/178587987-170dda76-bc97-4f5e-838b-c6e9f7c07600.png)
1. Could you try upgrading to the latest version (0.11.0) of the Azure Account extension to see if it fixes the issue?
1. Are you using a proxy of any kind?
1. What email domain is associated with your Azure account? (ex: hotmail.com, gmail.com)
