### ISSUE TITLE
Cannot log in from Kubuntu 18.04

### ISSUE THREAD

**Issue by latitudehopper** [Microsoft/vscode-azure-account#59]
Latest of both VS code and Kubuntu
1. Install service
2. restart
3. Follow link and enter code
4. Return to VS code but nothing has logged in - process needs to be repeated to no effect.

**Comment by balsagoth** [comment]
+1 from OS X.

**Comment by chrmarti** [comment]
Do you by any chance don't have any subscriptions? (Check if any are shown here: https://portal.azure.com/#blade/Microsoft_Azure_Billing/SubscriptionsBlade)

**Comment by chrmarti** [comment]
This is https://github.com/atom/node-keytar/issues/74. Installing `gnome-keyring` works around it.

**Comment by chrmarti** [comment]
Fixing this by catching the errors from `keytar`. You'll have to sign-in again after restarting VS Code. The browser might still have a valid session, so hopefully this won't be too bad.
