### ISSUE TITLE
0.11.0 Azure: Sign in will not let me to select account

### ISSUE THREAD

**Issue by xiaolang124** [microsoft/vscode-azure-account#594]
- VS Code Version: 1.69.0
- Azure Account Extension Version: 0.11.0
- OS Version: win11

Steps to Reproduce:

1. Open VS Code and use `Azure: Sign in` to sign in an account.
2. Use `Azure: Sign out` to sign out the account.
3. Use `Azure: Sign in` to sign in, but it does not let me to select another account. It will sign in the pre sign in account.

**Comment by xiaolang124** [comment]
In 0.10.1, I can select account when using `Azure: Sign in`.

**Comment by philliphoff** [comment]
I can reproduce this on Windows, but not Mac.  It seems related to the elimination of the `prompt` property on the login query string in a prior change.  I'll revert that and see if we get back to the prior behavior.
