### ISSUE TITLE
Cannot list subscriptions

### ISSUE THREAD

**Issue by Shivi1982** [microsoft/vscode-azure-account#596]
- VS Code Version: 1.69.0
- Azure Account Extension Version: 
- OS Version: Windows 

Does your account belong to more than one directory? (see your directories [here](https://aka.ms/AAevnvr)):  No

Any other information about your Azure account that may be useful: 
On and off i am able to see the subscriptions i have and many of the time it does not show any valid subscription even though after logging in and out multiple times

**Comment by alexweininger** [comment]
You can also consult the wiki, we have a troubleshooting guide for this issue: [Troubleshooting: Unable to List Subscriptions](https://github.com/microsoft/vscode-azure-account/wiki/Troubleshooting#unable-to-list-subscriptions)
