### ISSUE TITLE
It's not showing all the azure function in my azure account

### ISSUE THREAD

**Issue by alphaaai** [microsoft/vscode-azure-account#598]
Does this occur consistently? 
Repro steps:

1.
2.

Version: 0.11.0
OS: darwin
OS Release: 21.0.1
Product: Visual Studio Code
Product Version: 1.68.1
Language: en

**Comment by alexweininger** [comment]
Does reverting to version 0.10.1 of the Azure Account extension fix the issue?

What version of the Azure Functions extension do you have installed?

Are you able to see any Azure Function? Perhaps you have some subscriptions filtered out?

You can use the Filter icon on the subscription node to select subscriptions to show in the Azure view.
![image](https://user-images.githubusercontent.com/12476526/178589221-701e5165-370b-41e6-867d-490a347b1191.png)
