### ISSUE TITLE
Can't sign in on version 0.11.0

### ISSUE THREAD

**Issue by 72gm** [microsoft/vscode-azure-account#599]
Click the "sign in to Azure" under resources in VS Code
New window pops up saying you are now signed in and can close this screen
Close screen and nothing has happened in VS Code "sign in to Azure" still being shown

This worked fine until version 0.11.0

Reverting to version 0.10.1 solves the problem

**Comment by alexweininger** [comment]
Things to try:
1. Using version 0.11.0, does trying sign-in two times fix the issue? Some users have reported that they need to sign in twice to get it working.
1. What is the value of the `azure.authenticationLibrary` setting? Try switching to MSAL or ADAL and retrying sign-in.

![image](https://user-images.githubusercontent.com/12476526/178587987-170dda76-bc97-4f5e-838b-c6e9f7c07600.png)


Questions:
1. When you switched to version 0.10.1, were you asked to sign in again?
1. Are you using a proxy of any kind?
1. What email domain is associated with your Azure account? (ex: hotmail.com, gmail.com)

**Comment by 72gm** [comment]
> Things to try:
> 
> 1. Using version 0.11.0, does trying sign-in two times fix the issue? Some users have reported that they need to sign in twice to get it working.

no, doesn't matter how many times

> 2. What is the value of the `azure.authenticationLibrary` setting? Try switching to MSAL or ADAL and retrying sign-in.
> 
currently ADAL

> ![image](https://user-images.githubusercontent.com/12476526/178587987-170dda76-bc97-4f5e-838b-c6e9f7c07600.png)
> 
> Questions:
> 
> 1. When you switched to version 0.10.1, were you asked to sign in again?
Yes
> 2. Are you using a proxy of any kind?
At work so yes I'd imagine so
> 3. What email domain is associated with your Azure account? (ex: hotmail.com, gmail.com)
work domain

**Comment by alexweininger** [comment]
Proxies tend to cause a lot of issues with Azure sign-in with the extension. Our troubleshooting section in our wiki could provide help [Troubleshooting: Unable to sign in while using a proxy](https://github.com/microsoft/vscode-azure-account/wiki/Troubleshooting#unable-to-sign-in-while-using-a-proxy)

**Comment by jg572h** [comment]
This didn't work for me.

**Comment by alexweininger** [comment]
> This didn't work for me.

Just in case: make sure you complete close and restart the VS Code process after adding changing the environment variable.

**Comment by jg572h** [comment]
> 

Yes, I did that.  The NO_PROXY variable even shows up when listing the environment in a Terminal window.

In case this helps, here is what appears in the output channel:

```
Attempting to reach URL "https://login.microsoftonline.com/"...
Attempting to reach URL "https://login.microsoftonline.com/"...
Attempting to reach URL "https://vscode.dev/redirect"...
Attempting to reach URL "https://login.microsoftonline.com/common/oauth2/authorize?response_type=code&client_id=aebc6443-996d-45c2-90f0-388ff96faa56&redirect_uri=https%3A%2F%2Fvscode.dev%2Fredirect&state=http%3A%2F%2F127.0.0.1%3A61478%2Fcallback?nonce=CMjhHiQ7%2BR3FOL8FxD9TUw%3D%3D&prompt=select_account"...
Wed, 25 Jan 2023 22:19:14 GMT:a7729026-9901-48e0-bc18-f1d8739ccd9f - OAuth2Client: ERROR: No response from the server
Stack:
Error: No response from the server
	at Logger.createError (c:\Users\jg572h\.vscode\extensions\ms-vscode.azure-account-0.11.3\dist\extension.bundle.js:2:865070)
	at c:\Users\jg572h\.vscode\extensions\ms-vscode.azure-account-0.11.3\dist\extension.bundle.js:2:878103
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
Error: No response from the server
No response from the server
```

I noticed that the advice in the troubleshooting link suggested adding login.microsoft.com to the NO_PROXY variable, but I see that the extension is actually trying to reach login.microsoftonline.com.  So, I tried adding login.microsoftonline.com to the NO_PROXY variable, and this time it tried for about 30 seconds before failing.  Here is the log output from that attempt:

```
Attempting to reach URL "https://login.microsoftonline.com/"...
Attempting to reach URL "https://login.microsoftonline.com/"...
Attempting to reach URL "https://vscode.dev/redirect"...
Attempting to reach URL "https://login.microsoftonline.com/common/oauth2/authorize?response_type=code&client_id=aebc6443-996d-45c2-90f0-388ff96faa56&redirect_uri=https%3A%2F%2Fvscode.dev%2Fredirect&state=http%3A%2F%2F127.0.0.1%3A56550%2Fcallback?nonce=2t0JDIuBoOv2b3jaKTqAow%3D%3D&prompt=select_account"...
request to https://management.azure.com/tenants?api-version=2016-06-01 failed, reason: tunneling socket could not be established, statusCode=403
Attempting to reach URL "https://login.microsoftonline.com/"...
Attempting to reach URL "https://vscode.dev/redirect"...
Attempting to reach URL "https://login.microsoftonline.com/common/oauth2/authorize?response_type=code&client_id=aebc6443-996d-45c2-90f0-388ff96faa56&redirect_uri=https%3A%2F%2Fvscode.dev%2Fredirect&state=http%3A%2F%2F127.0.0.1%3A56593%2Fcallback?nonce=uUzlh%2FA3IeFA3lQTuj0VMQ%3D%3D&prompt=select_account"...
request to https://management.azure.com/tenants?api-version=2016-06-01 failed, reason: tunneling socket could not be established, statusCode=403
Attempting to reach URL "https://login.microsoftonline.com/"...
Attempting to reach URL "https://vscode.dev/redirect"...
Attempting to reach URL "https://login.microsoftonline.com/common/oauth2/authorize?response_type=code&client_id=aebc6443-996d-45c2-90f0-388ff96faa56&redirect_uri=https%3A%2F%2Fvscode.dev%2Fredirect&state=http%3A%2F%2F127.0.0.1%3A56174%2Fcallback?nonce=I2K7%2Bf9EnbY7oLthZbULAA%3D%3D&prompt=select_account"...
request to https://management.azure.com/tenants?api-version=2016-06-01 failed, reason: tunneling socket could not be established, statusCode=403
```

Getting closer maybe?

**Comment by alexweininger** [comment]
@jg572h 
A bit embarrassing, but I made a typo on the page that explains the workaround. The hostname to add to the `NO_PROXY` environment variable should be `login.microsoftonline.com` and NOT `login.microsoft.com`. Sorry about that, but please let me know if that fixes it.

**Comment by alexweininger** [comment]
Hi @72gm and @jg572h, we've created two development builds with proposed fixes for proxy issues. It would be a huge help if you could test these. #714 contains details and instructions on how to do so.
