### ISSUE TITLE
Use "Sign In" instead of "Login"...

### ISSUE THREAD

**Issue by whiskeyjay** [Microsoft/vscode-azure-account#6]
... In all UI related strings, like commands, prompt text etc, to align with the AAD sign-in page UI. Visual Studio also uses "Sign in" instead of "Log in".

**Comment by chrisdias** [comment]
this seems reasonable, and aligns with the portal. 

![image](https://user-images.githubusercontent.com/1487073/30404486-bfabb4d6-989b-11e7-9155-ccdd78d5200a.png)
