### ISSUE TITLE
Cannot list subscriptions

### ISSUE THREAD

**Issue by wlasiukk** [microsoft/vscode-azure-account#605]
- VS Code Version: 1.69.2
- Azure Account Extension Version: 
- OS Version: Window 10

Does your account belong to more than one directory? (see your directories [here](https://aka.ms/AAevnvr)):  YES

Any other information about your Azure account that may be useful: 
Directories :
85843482-8b9b-47d9-a2b6-4fa338c03953
20bf01a2-c548-4609-ba41-b88570299582

login : krzysztof.wlasiuk@gemini.pl

**Comment by alexweininger** [comment]
Could you try the steps in the [Unable to List Subscriptions section of our wiki](https://github.com/microsoft/vscode-azure-account/wiki/Troubleshooting#unable-to-list-subscriptions) and see if they fix the issue?
