### ISSUE TITLE
Cannot list subscriptions

### ISSUE THREAD

**Issue by harshitajain165** [microsoft/vscode-azure-account#609]
- VS Code Version: 1.69.2
- Azure Account Extension Version: v0.11.0
- OS Version: Windows_NT x64 10.0.19044

Does your account belong to more than one directory? (see your directories [here](https://aka.ms/AAevnvr)): No

Any other information about your Azure account that may be useful: The account being used is a student ambassadors account.

**Comment by alexweininger** [comment]
Could you try the steps in the [Unable to List Subscriptions section of our wiki](https://github.com/microsoft/vscode-azure-account/wiki/Troubleshooting#unable-to-list-subscriptions) and see if they fix the issue?
