### ISSUE TITLE
question

### ISSUE THREAD

**Issue by albertNSBM** [microsoft/vscode-azure-account#613]
Does this occur consistently? 
Repro steps:

1.
2.

Action: updateSubscriptionsAndTenants
Error type: EAI_AGAIN
Error Message: request to redacted:url failed, reason: getaddrinfo EAI_AGAIN redacted:url

Version: 0.11.1
OS: win32
OS Release: 10.0.21996
Product: Visual Studio Code
Product Version: 1.70.0
Language: en

<details>
<summary>Call Stack</summary>

```
ClientRequest.<anonymous> extension.bundle.js:2:2647495
```

</details>

**Comment by nturinski** [comment]
Please provide more details and repro steps.
