### ISSUE TITLE
Not able to sign in into Azure Account

### ISSUE THREAD

**Issue by jt17525** [microsoft/vscode-azure-account#616]
Does this occur consistently? Yes
Repro steps:

1. Click on `Sign in to Azure...` option on the Azure Side panel
2. Do the login in the browser
3. Ends on the `You are signed in now and can close this page.` http://127.0.0.1, tho is not logged in.

Action: azure-account.login
Error type: Error
Error Message: Get redacted:key returned http error: 302 and server response: ""

Version: 0.11.1
OS: darwin
OS Release: 21.6.0
Product: Visual Studio Code
Product Version: 1.70.0
Language: en

<details>
<summary>Extension Output</summary>

```
Attempting to reach URL "https://login.microsoftonline.com/"...
Attempting to reach URL "https://login.microsoftonline.com/"...
Attempting to reach URL "https://vscode.dev/redirect"...
Attempting to reach URL "https://login.microsoftonline.com/common/oauth2/authorize?response_type=code&client_id=AAAAA-AAAAA-11111-111111&redirect_uri=https%3A%2F%2Fvscode.dev%2Fredirect&state=http%3A%2F%2F127.0.0.1%3A58002%2Fcallback?nonce=AAAAA11111111%2FtyeQ%3D%3D&prompt=select_account"...
Get Token request returned http error: 302 and server response: ""
```
</details>

<details>
<summary>Call Stack</summary>

```
Logger.createError extension.bundle.js:2:820371
extension.bundle.js:2:833256
```

</details>

**Comment by jt17525** [comment]
Wanted to add that I tested downgrading to v0.9.11 and sign in worked ok.

**Comment by alexweininger** [comment]
Is this still reproducing on the latest version of the Azure Account extension?

If so, are you behind a proxy of any kind? Proxies often cause issues with sign-in. If you are, we have a guide for [Unable to Sign In While Using a Proxy section of our wiki](https://github.com/microsoft/vscode-azure-account/wiki/Troubleshooting#unable-to-sign-in-while-using-a-proxy) for possible fixes.
