### ISSUE TITLE
No response after clicking 'Sign In' on Command Palette... with 'Azure Account' extension

### ISSUE THREAD

**Issue by v-haiz** [Microsoft/vscode-azure-account#62]
Repro Steps:
 1. Install 'Azure Account' extension only in VS Code.
 2. Press F1, and type "sign in", then select the "Azure: Sign In" command.
 3. Verify whether pop up a dialog with 'Copy & Open' or not.

Expect:
pop up a dialog with 'Copy & Open' in right bottom.

Actual:
No response after clicking 'Sign In' on Command Palette.

**Comment by chrmarti** [comment]
@v-haiz Could you check if there is anything in the console? (Help > Toggle Developer Tools)

**Comment by ransagy** [comment]
I have a similar problem; I do get the dialog, but nothing happens after it (even when approving the sign in via the website that opens up). VSCode 1.24.0, Azure Account 0.4.0, Nothing in console.

**Comment by chrmarti** [comment]
@ransagy This could be #51. Can you check in the portal (https://portal.azure.com) if you have any subscriptions?

**Comment by ransagy** [comment]
That actually seems the case; We recently changed how we work (moved to AD) and for some reason until now i didn't notice i wasn't associated correctly to the subscription - Now it worked well. Sorry for the confusion and thanks for the help!

**Comment by v-haiz** [comment]
There is nothing in the console @chrmarti

**Comment by chrmarti** [comment]
@v-haiz Could you try reinstalling the extension? If it still occurs you could try debugging the extension and place a breakpoint in azure-account.ts login().
