### ISSUE TITLE
Cannot sign in while using proxy

### ISSUE THREAD

**Issue by cincymaco** [microsoft/vscode-azure-account#623]
- VS Code Version: 
    1.70.2 (Universal)
    Commit: e4503b30fc78200f846c62cf8091b76ff5547662
    Date: 2022-08-16T05:36:37.829Z (1 wk ago)
    Electron: 18.3.5
    Chromium: 100.0.4896.160
    Node.js: 16.13.2
    V8: 10.0.139.17-electron.0
    OS: Darwin x64 21.6.0

- Azure Account Extension Version:
    v0.11.1

- OS Version:
    MacOs

Steps to Reproduce:

1. open command 
2. Select Azure Sign in...
3. Get redirected to Azure sign in 
4. Approve sign in

When Attempt to login into Azure using Azure account extension it fails, not matter how i try to login; using with device code, azure cloud, on and off proxy. i alway keep getting this error in the output terminal 

Attempting to reach URL "login.microsoftonline{dot}com/"...
Attempting to reach URL "vscode{dot}dev/redirect"...
Attempting to reach URL "login.microsoftonline{dot}com/{tenatID}/oauth2/authorize?response_type=code&client_id={clientId}&redirect_uri=https%3A%2F%2Fvscode.dev%2Fredirect&state=http%3A%2F%2F127.0.0.1%3A59948%2Fcallback?nonce=Sz6FHh30dYytiUZcFlzIsg%3D%3D&prompt=select_account"...
Get Token request returned http error: 302 and server response: ""

**Comment by alexweininger** [comment]
Hi @cincymaco, thank you for the detailed issue description. Are you still facing this issue?
