### ISSUE TITLE
Sign In completes in browser, but VSCode is never signed in. 

### ISSUE THREAD

**Issue by chartsNgraphs** [microsoft/vscode-azure-account#633]
Does this occur consistently? Yes
Repro steps:
1. Click "Sign In to Azure"
2. Sign in in the browser window
3. Sign in Completes successfully
4. Navigate back to VSCode
5. Observe that VSCode is still not signed in, and a popup appears asking user to sign in again. 

1.
6.

Version: 0.11.1
OS: win32
OS Release: 10.0.22000
Product: Visual Studio Code
Product Version: 1.71.2
Language: en

**Comment by nturinski** [comment]
Are you using a proxy by chance? This workaround may work for you: https://github.com/microsoft/vscode-azure-account/wiki/Troubleshooting#add-loginmicrosoftcom-to-the-no_proxy-environment-variable
