### ISSUE TITLE
Failed To Select Subscription

### ISSUE THREAD

**Issue by LiboniBinmak** [microsoft/vscode-azure-account#634]
Does this occur consistently? 
Repro steps:

1.
2.

Action: waitForSubscriptions
Error type: REQUEST_SEND_ERROR
Error Message: request to redacted:url failed, reason: getaddrinfo ENOTFOUND redacted:url

Version: 0.11.1
OS: win32
OS Release: 10.0.19044
Product: Visual Studio Code
Product Version: 1.69.1
Language: en

<details>
<summary>Call Stack</summary>

```
new RestError extension.bundle.js:2:65384
NodeFetchHttpClient.<anonymous> extension.bundle.js:2:46552
step extension.bundle.js:2:2177383
Object.throw extension.bundle.js:2:2177488
rejected extension.bundle.js:2:2176213
```

</details>

**Comment by nturinski** [comment]
Proxies tend to cause a lot of issues with Azure sign-in with the extension. Our troubleshooting section in our wiki could provide help [Troubleshooting: Unable to sign in while using a proxy](https://github.com/microsoft/vscode-azure-account/wiki/Troubleshooting#unable-to-sign-in-while-using-a-proxy)

The latest release uses a new authentication redirect server, which is hosted on a new url. You may need to allow this url through your proxy.

New url: `https://vscode.dev/redirect`
Old url: `https://vscode-redirect.azurewebsites.net/`

You can also check the "Azure Account" output channel, we log the urls the extension attempts to reach during sign-in. This could help figure out why the proxy is causing issues.
![image](https://user-images.githubusercontent.com/12476526/178589922-01931b32-141b-40b2-8a70-df7d1e6ec9bf.png)
