### ISSUE TITLE
Sign In to Azure using Visual Studio Code

### ISSUE THREAD

**Issue by rajulapatis** [microsoft/vscode-azure-account#635]
Does this occur consistently? Yes
Repro steps:

1. Open Visual Studio Code 1.71.2
2. Install Azure Extensions - Azure Account , Azure Functions , Azure Resources

Action: azure-account.login
Error type: AzureLoginError
Error Message: Acquiring user code failed

Version: 0.10.0
OS: darwin
OS Release: 21.6.0
Product: Visual Studio Code
Product Version: 1.71.2
Language: en

VS code settings.json details
<details>
{
    "http.proxy":  "http://MyProxy:MyPort/",
    "https.proxy": "http://MyProxy:MyPort/",
    "http.proxyAuthorization": null
}

</details>

[2022-09-30 11:13:49.507] [renderer1] [error] RequestService#request (browser) - error https://marketplace.visualstudio.com/_apis/public/gallery/extensionquery {"name":

**Comment by nturinski** [comment]
Are you using a proxy by chance? If that's the case, this workaround for you: https://github.com/microsoft/vscode-azure-account/wiki/Troubleshooting#add-loginmicrosoftcom-to-the-no_proxy-environment-variable

**Comment by jg572h** [comment]
This did not work for me.  Are there any other suggestions?

**Comment by alexweininger** [comment]
There was a typo on the page that explains the workaround. The hostname to add to the `NO_PROXY` environment variable should be `login.microsoftonline.com` and NOT `login.microsoft.com`. Sorry about that, but please let me know if that fixes it.
