### ISSUE TITLE
Acquiring user code failed when login vs VS Code

### ISSUE THREAD

**Issue by ElRuby** [microsoft/vscode-azure-account#636]
Does this occur consistently?  Yes
Repro steps:

1. Install Azure Account
2. >Azure: Sign In

Action: azure-account.loginToCloud
Error type: AzureLoginError
Error Message: Acquiring user code failed
Verifying authentication cause `AttributeError: 'str' object has no attribute 'get_token'`

Version: 0.11.1
OS: win32
OS Release: 10.0.19044
Product: Visual Studio Code
Product Version: 1.71.2
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:2:2302148extension.bundle.js:2:2302148
extension.bundle.js:2:834743extension.bundle.js:2:834743
```

</details>

**Comment by nturinski** [comment]
Are you using a proxy by chance? If so, this workaround may work for you:

https://github.com/microsoft/vscode-azure-account/wiki/Troubleshooting#add-loginmicrosoftcom-to-the-no_proxy-environment-variable
