### ISSUE TITLE
How to use within tasks.json

### ISSUE THREAD

**Issue by kumarharsh** [Microsoft/vscode-azure-account#64]
I have a resource for which I have to toggle the NSG rule on/off quite frequently for maintenance purposes. Right now, I do this from the Azure Portal. I was searching for a way to make this painless and transitioning to the `az cli` command. Then, I chanced upon this extension, and I thought that if I could use it in some way to do my bidding, it'd be great. That way I won't have to open the Azure Portal every time.

To achieve this, I was wondering whether I could create a task in VSCode which directly calls the relevant azure command to change the resource properties. But, I couldn't find a way to specify that the task should use `az cli` bash shell in the `tasks.json` file.

Is there a way to specify the Azure Powershell or Bash shell in the vscode `tasks.json` file?

**Comment by chrmarti** [comment]
You don't need an extension to do that, just the Azure CLI is enough. Make sure you're logged in (`az login`) and add custom tasks: https://code.visualstudio.com/docs/editor/tasks#_custom-tasks

**Comment by kumarharsh** [comment]
Ah, I see. Thanks.

I'm assuming you mean I install the Azure cli via the MSI to run on powershell?

**Comment by chrmarti** [comment]
Yes, this one: https://docs.microsoft.com/en-us/cli/azure/install-azure-cli

**Comment by kumarharsh** [comment]
Thanks. Got it working :-)
