### ISSUE TITLE
z

### ISSUE THREAD

**Issue by dbeckinsale** [microsoft/vscode-azure-account#642]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azure-account.selectSubscriptions
Error type: Error
Error Message: Unable to write into user settings. Please open the user settings to correct errors/warnings in it and try again.

Version: 0.11.1
OS: win32
OS Release: 10.0.22000
Product: Visual Studio Code
Product Version: 1.71.2
Language: en

<details>
<summary>Call Stack</summary>

```
D.toConfigurationEditingError workbench.desktop.main.js:2696:12042
D.updateConfiguration workbench.desktop.main.js:2696:8714
D.doWriteConfiguration workbench.desktop.main.js:2696:8556
async Object.factory workbench.desktop.main.js:2696:8216
```

</details>

**Comment by nturinski** [comment]
It seems like you have invalid JSON in your user settings. We try to write some settings that help us with displaying your subscriptions.

Could you run the following command and fix your settings?
![image](https://user-images.githubusercontent.com/5290572/194130300-5c26a72e-9f97-424d-8c2a-d8b119d5de7f.png)

You can get to the command palette by pressing F1.
