### ISSUE TITLE
Cannot log into Azure

### ISSUE THREAD

**Issue by MJCliffe** [microsoft/vscode-azure-account#648]
Type: <b>Bug</b>

Issues:
- I click on 'sign in to Azure'. 
- Chrome opens.
- It redirects to http://127.0.0.1:51574/ and I see:
'You are signed in now and can close this page.'
- I am not signed in. There is as far as I can tell no debugging information.

I checked the github issues, and none of the existing issues are resolved, and it appears there is a pattern of issues that are not being resolved, just closed. I am behind no proxies.

Azure account v0.11.1, downgrading to 0.10.1 allows me to log in as per https://stackoverflow.com/questions/52468396/azure-sign-in-not-working-using-azure-tools-option-in-vscode/69902136#69902136

Extension version: 0.11.1
VS Code version: Code 1.72.0 (Universal) (64bbfbf67ada9953918d72e1df2f4d8e537d340e, 2022-10-04T23:21:58.256Z)
OS version: Darwin x64 21.6.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz (8 x 2300)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|4, 4, 4|
|Memory (System)|16.00GB (0.47GB free)|
|Process Argv|--crash-reporter-id d277a6b1-113b-46e5-b903-fad96a3eb730|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
2144e591:30553903
vscccc:30566498
pyindex848:30577860
fc301958:30573243

```

</details>

**Comment by axiomitdavid** [comment]
Ran into same issue, has been happening for a week (8 Oct 2022).  Thanks for the tip.

Where is the regression testing MS?  Core function of the extension is broken.

**Comment by alexweininger** [comment]
I apologize for the delayed response.

Is this issue still reproducing on the latest version of the extension (0.11.2)? If sign-in is still failing on the latest version, could you provide the logs displayed in the Azure Account output channel after a failed sign-in attempt?

Additionally, are you behind a proxy of any kind? Proxies often cause issues with sign-in. See the [Unable to Sign In While Using a Proxy section of our wiki](https://github.com/microsoft/vscode-azure-account/wiki/Troubleshooting#unable-to-sign-in-while-using-a-proxy) for possible fixes.
