### ISSUE TITLE
Support all Azure environments

### ISSUE THREAD

**Issue by lirenhe** [Microsoft/vscode-azure-account#65]
Form https://github.com/Azure/azure-sdk-for-node/blob/master/runtime/ms-rest-azure/lib/azureEnvironment.js, there are 4 azure environment supported including Azure, AzureChina, AzureUSGovernment and AzureGermanCloud.
But in vscode-azure-account, the default environment is fixed with 'Azure'.
Please add the support for other Azure environments.

**Comment by chrmarti** [comment]
Tracking this as #23.
