### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by v-mb** [microsoft/vscode-azure-account#656]
- VS Code Version: 1.72.2
- Azure Account Extension Version:  **> 0.9.11**
- OS Version:  Windows_NT x64 10.0.19043

Version: 1.72.2 (user setup)
Commit: d045a5eda657f4d7b676dedbfa7aab8207f8a075
Date: 2022-10-12T22:15:18.074Z
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.19043
Sandboxed: No

Steps to Reproduce:
![image](https://user-images.githubusercontent.com/113507052/197477893-79a2d2e5-a503-4581-a6e8-ddc73b81fbce.png)

Use any version of Azure Account extension above v0.9.11 and do the following

1. Azure Sign In
2. Invalid Access token returned

If I downgrade Azure Account extension to v0.9.11 - seems to sign in but cannot access resources. So i downgrade from Azure Resources Extension v0.5.6 TO v0.4.0 . And i'm able to sign in and see my resources.

I'm behind a Proxy and have tried altering settings in the higher versions of Azure account , to include the proxy, change from ADAL to MSAL, tun ON/OFF/Override etc. Only thing that works is downgrading the versions

**Comment by nturinski** [comment]
Proxies tend to cause a lot of issues with Azure sign-in with the extension. Our troubleshooting section in our wiki could provide help [Troubleshooting: Unable to sign in while using a proxy](https://github.com/microsoft/vscode-azure-account/wiki/Troubleshooting#unable-to-sign-in-while-using-a-proxy)

This specific workaround has been working for some users:
https://github.com/microsoft/vscode-azure-account/wiki/Troubleshooting#add-loginmicrosoftcom-to-the-no_proxy-environment-variable
