### ISSUE TITLE
[Feature Request] Change the static display account name

### ISSUE THREAD

**Issue by wsmelton** [Microsoft/vscode-azure-account#66]
This is strictly cosmetics but was wondering if the visual cue given on the status bar can be changed to show something other than an email address?

![image](https://user-images.githubusercontent.com/11204251/41472992-9e4a1b9c-707d-11e8-8fcc-81c01504e383.png)

Just from the perspective for those that speak (in-person and online) or blog, it saves a good bit of time trying to hide that information.

From the perspective of general use, I already know what my email account is for Azure. It would a bit more informative to show the subscription name.

**Comment by chrmarti** [comment]
There are multiple subscriptions. When you click on that status bar item you get the full list and can select which ones you're interested in.

I see the problem with having your email address there.
