### ISSUE TITLE
Having issues signing to Azure App Services via extension in vs code

### ISSUE THREAD

**Issue by akyani** [microsoft/vscode-azure-account#661]
I am having issues signing to Azure App Services via extension in vs code. I am facing an issue when signing in into VS code, where it doesn’t ask me to authenticate. It will take me to the authenticator app but after completing the sign in, it takes me to edge where it shows me “I am signed in now and can close this page” but after closing it still can’t sign in.

**Comment by alexweininger** [comment]
Which authentication library are you using? You can find out by going to Settings and searching for "Authentication Library"

<img width="813" alt="image" src="https://user-images.githubusercontent.com/12476526/204933042-d298a951-1c5b-4c08-8567-4c4c62f3350d.png">

Also, are you using a Microsoft account, or another email type, like Gmail?
