### ISSUE TITLE
Cannot list subscriptions

### ISSUE THREAD

**Issue by KerenCohen** [microsoft/vscode-azure-account#664]
- VS Code Version: 1.73.0
- Azure Account Extension Version: latest
- OS Version: 

Does your account belong to more than one directory? (see your directories [here](https://aka.ms/AAevnvr)): No

Any other information about your Azure account that may be useful: 
Othe account from my organization has no issues from their work station and I cannot get a list from my computer to none of the accounts

**Comment by alexweininger** [comment]
Could you try the steps in the [Unable to List Subscriptions section of our wiki](https://github.com/microsoft/vscode-azure-account/wiki/Troubleshooting#unable-to-list-subscriptions) and see if they fix the issue?
