### ISSUE TITLE
Can not sign in to Azure with multifactor authentication

### ISSUE THREAD

**Issue by newhardwarefound** [microsoft/vscode-azure-account#667]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azure-account.loginToCloud
Error type: invalid_grant
Error Message: invalid_grant: AADSTS50076: Due to a configuration change made by your administrator, or because you moved to a new location, you must use multi-factor authentication to access 'redacted:id'.
Trace ID: redacted:id
Correlation ID: redacted:id
Timestamp: redacted:id redacted:id01Z

Version: 0.11.2
OS: win32
OS Release: 10.0.19044
Product: Visual Studio Code
Product Version: 1.73.1
Language: en

<details>
<summary>Call Stack</summary>

```
InteractionRequiredAuthError.AuthError [as constructor] extension.bundle.js:2:154988
new InteractionRequiredAuthError extension.bundle.js:2:224089
ResponseHandler.validateTokenResponse extension.bundle.js:2:231175
AuthorizationCodeClient.<anonymous> extension.bundle.js:2:237173
step extension.bundle.js:2:147912
Object.next extension.bundle.js:2:148017
fulfilled extension.bundle.js:2:146681
```

</details>

**Comment by alexweininger** [comment]
Have you ever been able to sign-in using multi-factor authentication with the Azure Account extension before? If not, you may need to setup multi-factor for the first time if this is a new policy as indicated by the error message.
