### ISSUE TITLE
subscription filters issue

### ISSUE THREAD

**Issue by chrisdias** [Microsoft/vscode-azure-account#67]
Windows
![image](https://user-images.githubusercontent.com/1487073/41546728-44e15c3e-72d3-11e8-9cc6-b58f1dde0a1e.png)

Show the azure custom view
click on your name in the status bar to manage subscriptions
pick one or 2 subscriptions

result: the extensions update their list of subscriptions as expected

![image](https://user-images.githubusercontent.com/1487073/41546975-df0fb9e0-72d3-11e8-8e00-2f00e2657d7e.png)

click on your name again to bring up subscription list

![image](https://user-images.githubusercontent.com/1487073/41546992-eaa48c22-72d3-11e8-9ddf-d314b255dd13.png)

don't change anything, just click on OK

result: No subscriptions shown

![image](https://user-images.githubusercontent.com/1487073/41547008-f4a1aa20-72d3-11e8-94a7-cf5f40ec9b6e.png)

 if you click on your name again all of the selected subscriptions are gone from the list.

![image](https://user-images.githubusercontent.com/1487073/41547032-fcd62e8c-72d3-11e8-8376-d69a32eed38c.png)

**Comment by chrmarti** [comment]
Does this happen with other subscriptions too? What does your setting.json look like after selecting the subscriptions? Anything in the console?

**Comment by chrisdias** [comment]
it doesn't matter what the subscriptions are checked or unchecked, it always happens when I bring up the list and just click on OK, without making any changes.  if i have settings.json open while doing this, I can see the persisted subscriptions being removed from the file.  no errors in the console.

**Comment by chrmarti** [comment]
Got it, a bug in QuickPick. Thx.

**Comment by chrmarti** [comment]
6cba561685dd0ebf979558114c7742ef54e76517
