### ISSUE TITLE
wont sign into azure

### ISSUE THREAD

**Issue by zape78** [microsoft/vscode-azure-account#671]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azure-account.initialize
Error type: Error
Error Message: UNIX[No such file or directory]

Version: 0.11.2
OS: darwin
OS Release: 21.6.0
Product: Visual Studio Code
Product Version: 1.73.1
Language: en

**Comment by alexweininger** [comment]
Duplicate of https://github.com/microsoft/vscode-azure-account/issues/614
