### ISSUE TITLE
Azure Sign-In Issue

### ISSUE THREAD

**Issue by AKS2010** [microsoft/vscode-azure-account#673]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azure-account.loginToCloud
Error type: Error
Error Message: Get redacted:key returned http error: 400 and server response: {"error":"interaction_required","error_description":"AADSTS70043: The refresh redacted:key expired or is invalid due to sign-in frequency checks by conditional access. The redacted:key issued on redacted:id17T09redacted:id2972891Z and the maximum allowed lifetime for this request is redacted:id.\r\nTrace ID: redacted:id\r\nCorrelation ID: redacted:id\r\nTimestamp: redacted:id redacted:id01Z","error_codes":[redacted:id],"timestamp":"redacted:id redacted:id01Z","trace_id":"redacted:id","correlation_id":"redacted:id","suberror":"token_expired"}

Version: 0.11.2
OS: win32
OS Release: 10.0.22000
Product: Visual Studio Code
Product Version: 1.73.1
Language: en

<details>
<summary>Call Stack</summary>

```
Logger.createError extension.bundle.js:2:813364
extension.bundle.js:2:826249extension.bundle.js:2:826249
```

</details>

**Comment by alexweininger** [comment]
Please add detailed steps to reproduce this issue.
