### ISSUE TITLE
Getting issue when deploying

### ISSUE THREAD

**Issue by Rgujjar-eagletech** [microsoft/vscode-azure-account#674]
Does this occur consistently? 
Repro steps:

1.
2.

Action: updateSubscriptionsAndTenants
Error type: ETIMEDOUT
Error Message: request to redacted:url failed, reason: connect ETIMEDOUT redacted:id

Version: 0.11.2
OS: win32
OS Release: 10.0.19045
Product: Visual Studio Code
Product Version: 1.73.1
Language: en

<details>
<summary>Call Stack</summary>

```
ClientRequest.<anonymous> extension.bundle.js:2:2629891
```

</details>

**Comment by alexweininger** [comment]
Please add repro steps in order for us to better help you. 

Which Azure resource are you trying to deploy?
