### ISSUE TITLE
Sign in to Azure kept loop back to login screen 

### ISSUE THREAD

**Issue by Erikazhuang** [microsoft/vscode-azure-account#675]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azure-account.loginToCloud
Error type: Error
Error Message: access_denied

Version: 0.10.1
OS: win32
OS Release: 10.0.19044
Product: Visual Studio Code
Product Version: 1.63.2
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:2:2338617extension.bundle.js:2:2338617
extension.bundle.js:2:2336179extension.bundle.js:2:2336179
b extension.bundle.js:2:2335865
callback extension.bundle.js:2:2338265
Server.<anonymous> extension.bundle.js:2:2338654
Server.emit events.js:315:20
parserOnIncoming _http_server.js:874:12
HTTPParser.parserOnHeadersComplete _http_common.js:126:17
```

</details>

**Comment by Bunacadh** [comment]
extension.bundle.js:2:2338617extension.bundle.js:2:2338617
extension.bundle.js:2:2336179extension.bundle.js:2:2336179
b extension.bundle.js:2:2335865
callback extension.bundle.js:2:2338265
Server.<anonymous> extension.bundle.js:2:2338654
Server.emit events.js:315:20
parserOnIncoming _http_server.js:874:12
HTTPParser.parserOnHeadersComplete _http_common.js:126:17

**Comment by alexweininger** [comment]
Please add detailed repro steps to help us address your issue.

Which Azure endpoint are you trying to sign in to? For example, public Azure, Azure China, or Azure Stack?

Note: if you are behind a proxy, please see the [Unable to Sign In While Using a Proxy section of our wiki](https://github.com/microsoft/vscode-azure-account/wiki/Troubleshooting#unable-to-sign-in-while-using-a-proxy) for possible fixes.
