### ISSUE TITLE
Cannot sign in via browser in WSL VSCode

### ISSUE THREAD

**Issue by eduardez** [microsoft/vscode-azure-account#677]
Does this occur consistently? Yes
Repro steps:

1. Install VSCode Azure Account Extension
2. Login via Chromium based browser (Vivaldi)
3. Return to VSCode and keep seeing the "Sign in to Azure" option

Version: 0.11.2
OS: linux
OS Release: 5.10.16.3-microsoft-standard-WSL2
Product: Visual Studio Code
Product Version: 1.73.1
Language: es

Tried to debug via inspector but nothing shows up.

**Comment by alexweininger** [comment]
Does sign-in work if you run VS Code outside of WSL?

**Comment by eduardez** [comment]
I just did some tests and no, it doesn't work in windows either, although if I downgrade to version 9.1 it works in both environments.

**Comment by alexweininger** [comment]
Are you behind a corporate proxy? If so, see the [Unable to Sign In While Using a Proxy section of our wiki](https://github.com/microsoft/vscode-azure-account/wiki/Troubleshooting#unable-to-sign-in-while-using-a-proxy) for possible fixes.

**Comment by eduardez** [comment]
Ok, I used the `Azure: Sign In with Device Code` option and it worked. Thanks!

**Comment by alexweininger** [comment]
Thanks for letting us know that worked.

In order to help others in the future with similar issues, were you behind a proxy?

**Comment by eduardez** [comment]
Yes, I was behind a corporate proxy.
