### ISSUE TITLE
Authenticates incorrectly with Keyvault Certificate SDK

### ISSUE THREAD

**Issue by OliverMKing** [microsoft/vscode-azure-account#679]
- VS Code Version: 1.73.1
- Azure Account Extension Version: v0.11.2
- OS Version: macOS 13.0

Steps to Reproduce:

1. Use this api to get the credentials
```TypeScript
 const api = (<AzureExtensionApiProvider>(
      vscode.extensions.getExtension('ms-vscode.azure-account')!.exports
   )).getApi('1.0.0');

// use sessions and pick a session (not shown but we do that with some business logic)
const session = ...
```
2. Use the keyvault certificate sdk

```TypeScript
const {credentials2} = session;
const client = new CertificateClient(vaultUri, credentials2);
const certs = await listAll(
   client.listPropertiesOfCertificates({includePending: true})
); // this throws an error
```

Something about how this extension is providing the credentials is failing. The error is `RestError: AKV10022: Invalid audience. Expected https://vault.azure.net, found: https://management.core.windows.net/`.

**Comment by alexweininger** [comment]
Thanks for reporting this issue. Has this worked in the past? Could you try reproducing this issue on previous versions of the Azure Account extension?
