### ISSUE TITLE
Cannot Open Bash in Cloud Shell

### ISSUE THREAD

**Issue by andy26nash** [Microsoft/vscode-azure-account#68]
Whilst already logged in to my Azure subscription when I try to Open Bash in Cloud Shell I very briefly see a new integrated terminal that displays '"Select Directory..." but then the terminal is closed after a couple of seconds.

If I log into the cloud shell via the browser I get prompted with a list of directory's that my account is a member of and I can choose the appropriate one for the session. Assuming this is what it needs me to do to get the above to work.

Is there a way of defining the default directory for the cloud shell?

**Comment by chrmarti** [comment]
It should ask you for the directory. Could you check if there is anything logged in the console? (Help > Toggle Developer Tools)

**Comment by andy26nash** [comment]
I see an error in the console window:

[cid:image003.jpg@01D40A28.9878F320]

But don’t get prompted for a directory

**Comment by chrmarti** [comment]
@andy26nash The picture in the mail didn't make it to GitHub. Could you attach it through the website?

**Comment by andy26nash** [comment]
![image](https://user-images.githubusercontent.com/11215495/41780014-6a247dcc-762b-11e8-929e-3bdc0c8ebea7.png)

Thats the image

Andy

**Comment by chrmarti** [comment]
Could you update the extension to version 0.4.1 and retry? If the problem still occurs, could you click that triangle to expand the stacktrace and post that here too?

**Comment by andy26nash** [comment]
tried with 0.4.1 but same result: shows the 'Select Directory...' but then closes the console after a couple of seconds.

Extra detail as requested

![image](https://user-images.githubusercontent.com/11215495/41897460-4fba83fe-791f-11e8-9afb-930c7ca26adc.png)

**Comment by andy26nash** [comment]
just some extra information. When I logon to the shell directly in the browser (shell.azure.com) I normally see the following list. Just in case this is a quantity issue)

![image](https://user-images.githubusercontent.com/11215495/41898522-25329f60-7922-11e8-8bc6-93541f85ee9c.png)

**Comment by andy26nash** [comment]
after a couple of reboots this seem to be working now. The list appears in the command pallete
