### ISSUE TITLE
Same named npm scripts in different folders of the same workspace won't run

### ISSUE THREAD

**Issue by markw65** [microsoft/vscode-azure-account#680]
- VS Code Version: 1.74.0
- OS Version: MacOS 13.0.1

Steps to Reproduce:

1. git clone https://github.com/markw65/multi-workspace.git
2. cd multi-workspace
3. code abc.code-workspace
4. trust the workspace

The workspace has three folders (a, b and c), and each folder has its own watch script, which is configured via tasks.json to run on folder open.

Expected behavior: each folder's watch script should auto run.
Actual behavior: Only a's watch script auto runs.

This works prior to 1.74.0

In addition, attempting to manually start either b's watch, or c's watch (via the triangle in the "npm scripts" side panel) fails, with no error message.

If you rename b's watch script to watchb (in b/package.json), and c's script to watchc, then you can manually start them, but they still don't auto start when opening the workspace.

If you go into `b/.vscode/tasks.json` and change the label to "npm: watchb", and do the same for c, then all three auto start.

It looks like 1.74.0 has added some checks to avoid starting the same script multiple times - but they don't take account of the possibility that there are multiple folders.

**Comment by alexweininger** [comment]
Hi @markw65, I think the right place to file this issue is over on the [VS Code repository](https://github.com/microsoft/vscode/issues). File this issue on that repo to get the proper help and response. Thanks!

This repository is specific to the Azure Account extension for VS Code.

**Comment by markw65** [comment]
Sorry - that is of course where I meant to file it.
