### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by fiifibenjamin22** [microsoft/vscode-azure-account#681]
Does this occur consistently? 
Repro steps:

1.
2.

Action: updateSubscriptionsAndTenants
Error type: REQUEST_SEND_ERROR
Error Message: request to redacted:url failed, reason: getaddrinfo ENOTFOUND redacted:url

Version: 0.11.2
OS: darwin
OS Release: 22.2.0
Product: Visual Studio Code
Product Version: 1.74.1
Language: en

<details>
<summary>Call Stack</summary>

```
new RestError extension.bundle.js:2:65384
NodeFetchHttpClient.<anonymous> extension.bundle.js:2:46552
step extension.bundle.js:2:2151055
Object.throw extension.bundle.js:2:2151160
rejected extension.bundle.js:2:2149885
```

</details>

**Comment by alexweininger** [comment]
Please add detailed reproduction steps so we're able to investigate.
