### ISSUE TITLE
Azure Cloud Shell Terminal successfully launches in local Windows window but fails to launch in remote WSL window

### ISSUE THREAD

**Issue by zombiemaker** [microsoft/vscode-azure-account#682]
- VS Code Version: 1.74.1
- Azure Account Extension Version: v0.11.2
- OS Version: Windows_NT x64 10.0.22621

Steps to Reproduce:

1.  Start VS Code in Microsoft Windows

2.  Select Terminal drop down and select "Azure Cloud Shell (Bash)" (this works)

3.  Select "Open a Remote Window" (lower-left corner of VSC window)

4.  Select "Open Folder in WSL..."

5.  Select directory in WSL and select "Select Folder" (VSC connected to WSL instance)

6.  Select Terminal drop down and select "Azure Cloud Shell (Bash)" 

7.  VSC Terminal panel flashes brief message ("/home/[username]/.vscode-server/bin/1ad8d514439d5077d2b0b7ee64d2ce82a9308e5a/node:  bad option: --ms-enable-electron-run-as-node"

8.  VSC pops an error message box in lower-right of window with this message "The terminal process "/home/[username]/.vscode-server/extensions/ms-vscode.azure-account-0.11.2/bin/node.sh '/home/[username]/.vscode-server/bin/1ad8d514439d5077d2b0b7ee64d2ce82a9308e5a/node', '-e', 'require('/home/[username]/.vscode-server/extensions/ms-vscode.azure-account-0.11.2/dist/cloudConsoleLauncher').main()', '--ms-enable-electron-run-as-node'" failed to launch (exit code: 9)."

**Comment by alexweininger** [comment]
Note: this is the same error as seen in https://github.com/microsoft/vscode-azure-account/issues/391

**Comment by alexweininger** [comment]
Seems like we're mistakenly adding the `--ms-enable-electron-run-as-node` flag when connected to a WSL instance. 

@zombiemaker I'm not sure this matters, but what WSL distro are you using? Ubuntu? Also are you using WSL 2?

**Comment by alexweininger** [comment]
I'm able to reproduce this in an Ubuntu Dev Container.

**Comment by alexweininger** [comment]
@zombiemaker You can try using this development build of the extension which includes a [fix for this issue](https://github.com/microsoft/vscode-azure-account/pull/684). If you can verify that the fix works for you, that'd be awesome!

Download: [azure-account-0.11.2.vsix.zip](https://github.com/microsoft/vscode-azure-account/files/10290972/azure-account-0.11.2.vsix.zip)

---

Steps to install extension development build:
1. Download the extension .VSIX: [azure-account-0.11.2.vsix.zip](https://github.com/microsoft/vscode-azure-account/files/10290972/azure-account-0.11.2.vsix.zip)
1. Unzip the .zip archive
1. From the command palette (`F1` or `Command/Ctrl + Shift + P`), run the "Extensions: Install from VSIX..." command.
1. Select the downloaded .VSIX file, then reload VS Code as prompted.

**Comment by pyromaniac3010** [comment]
@alexweininger I was also hit by this bug. I can confirm, that your fix works. Would be great for everyone, if this can make it in an official release soon. 😄

**Comment by alexweininger** [comment]
> I was also hit by this bug. I can confirm, that your fix works. Would be great for everyone, if this can make it in an official release soon. 😄

@pyromaniac3010 thank you for verifying the fix! We plan on releasing soon.

**Comment by preichelt** [comment]
@alexweininger something is wrong with the current `0.11.4` version. I receive an error that ends with `.vscode-server/extensions/ms-vscode.azure-account-0.11.4/dist/cloudConsoleLauncher').main()'" terminated with exit code: 1`. This occurs on Windows, WSL Ubuntu, and Arch Linux. The only fix I've found is uninstalling, disabling extensions from auto-updating and installing the `0.11.2` VSIX you provided [here](https://github.com/microsoft/vscode-azure-account/issues/682#issuecomment-1363445833).

**Comment by alexweininger** [comment]
I believe the issue you are running into is separate from the original issue posted. Could you file a new issue please?

**Comment by motorbreth** [comment]
same issue for me 0.11.4 
The terminal process "node.exe '-e', 'require('c:\\Users\\username\\.vscode\\extensions\\ms-vscode.azure-account-0.11.4\\dist\\cloudConsoleLauncher').main()'" terminated with exit code: 1.

version 0.11.2 solved the issue for me

**Comment by alexweininger** [comment]
Track the issue launching cloud console in https://github.com/microsoft/vscode-azure-account/issues/808
