### ISSUE TITLE
Cloud shell mkdir command fails

### ISSUE THREAD

**Issue by fiveisprime** [Microsoft/vscode-azure-account#69]
From https://github.com/Microsoft/vscode-azureappservice/issues/470

---

Please examine this astonishing behavior. All I'm trying to do is what's described in this doc:
https://docs.microsoft.com/en-us/azure/app-service/containers/quickstart-nodejs
in the Download the Sample section.

```sh
PS Azure:\> mkdir quickstart
Azure:\
PS Azure:\> cd quickstart
cd : Cannot find path 'Azure:\quickstart' because it does not exist.
At line:1 char:1
+ cd quickstart
+ ~~~~~~~~~~~~~
+ CategoryInfo          : ObjectNotFound: (Azure:\quickstart:String) [Set-Location], ItemNotFoundException
+ FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.SetLocationCommand

Azure:\
PS Azure:\> ls
    Directory: Azure:
Mode SubscriptionName SubscriptionId                       TenantId                             State
---- ---------------- --------------                       --------                             -----
+    Free Trial       Enabled
```

**Comment by chrmarti** [comment]
You probably can't create a folder in that 'Azure:' drive: https://docs.microsoft.com/en-us/azure/cloud-shell/features-powershell#azure-drive-azure.

**Comment by chrmarti** [comment]
I think the behavior is expected in the old 'Azure:' PowerShell (see last comment). It should work now with PowerShell Core on Linux.
