### ISSUE TITLE
Cannot Sign In to Azure Account

### ISSUE THREAD

**Issue by boshamed** [microsoft/vscode-azure-account#691]
1.Open Azure Extension Tab
2.Click on Azure Account Sign In
3.Pop-up appears with log in verification code for the device
4.Copy the verification code and paste in the authentication page and click submit
5.Pick the work account to continue singin in
6. Click Continue on "Are you trying to sign in to Visual Studio Code?" screen
7.See confirmation page that siging in has been successful
8.Going back to VS Code the extension is stuck on "Signing in to Azure..."

Extension version: 0.11.2
VS Code version: Code 1.74.2 (e8a3071ea4344d9d48ef8a4df2c097372b0c5161, 2022-12-20T10:29:14.590Z)

**Comment by nturinski** [comment]
Are you behind a proxy of any kind? Proxies often cause issues with sign-in. Please see the [Unable to Sign In While Using a Proxy section of our wiki](https://github.com/microsoft/vscode-azure-account/wiki/Troubleshooting#unable-to-sign-in-while-using-a-proxy) for possible fixes.
