### ISSUE TITLE
Cannot Sign In using MFA

### ISSUE THREAD

**Issue by nunogabrielmonteiro** [microsoft/vscode-azure-account#695]
- VS Code Version: 1.74.3
- Azure Account Extension Version: 0.11.2
- OS Version: Windows 10 Entreprise 20H2

Steps to Reproduce:

1. In VS Code
a) Ctrl+shift+P
b) Azure : Sign in
c) Enter credentials (I do not get prompted for the second factor)

2.
Error in Azure Account Output:

Get Token request returned http error: 400 and server response: {"error":"interaction_required","error_description":"AADSTS50076: Due to a configuration change made by your administrator, or because you moved to a new location, you must use multi-factor authentication to access '797f4846-ba00-4fd7-ba43-dac1f8f63013'.\r\nTrace ID: 2a6a973a-1229-4af0-aeb7-808384041100\r\nCorrelation ID: eff628b8-98b3-4321-b307-d7ba76d61cae\r\nTimestamp: 2023-01-16 15:49:49Z","error_codes":[50076],"timestamp":"2023-01-16 15:49:49Z","trace_id":"2a6a973a-1229-4af0-aeb7-808384041100","correlation_id":"eff628b8-98b3-4321-b307-d7ba76d61cae","error_uri":"https://login.microsoftonline.com/error?code=50076","suberror":"basic_action"}

**Comment by nunogabrielmonteiro** [comment]
Hi @nturinski ,
This has never worked for me while using the corporate laptop.
Yes, I am using a corporate proxy.
But I can sign in using other tools like: AZ CLI and PowerShell in the same machine, and they are also using the proxy.

**Comment by alexweininger** [comment]
@nunogabrielmonteiro  Since you're behind a proxy, please see the [Unable to Sign In While Using a Proxy section of our wiki](https://github.com/microsoft/vscode-azure-account/wiki/Troubleshooting#unable-to-sign-in-while-using-a-proxy) for possible fixes. 

A lot of users with proxy issues have been having success with the suggested workaround.
