### ISSUE TITLE
Installation of extension fails - 0.4.0

### ISSUE THREAD

**Issue by fl0tschi** [Microsoft/vscode-azure-account#70]
I cannot install the extension on my machines.

I also tried to install it via VSIX installation, but the log says that visual studio code is not available. It just finds the Visual studio 2017 but not the visual studio code. I also re-installed visual studio code, still didn't help.

I'm using Windows 10 x64, Visual Studio Code 1.24.1.

I tried it on two computers, on both it wasnt possible.

**Comment by chrmarti** [comment]
Do you see the extension in the Extension viewlet (View > Extensions) when you search in VS Code? Try installing from there and check what is in the Output panel's (View > Output) 'Log (Shared)' channel.

**Comment by fl0tschi** [comment]
I tried to install it via this view, tried to install it, output in output view is the following:

[2018-06-22 10:40:16.825] [sharedprocess] [info] Failed renaming C:\Users\<user>\.vscode\extensions\.ms-vscode.azure-account-0.4.0 to C:\Users\<user>\.vscode\extensions\ms-vscode.azure-account-0.4.0 with 'EPERM' error. Trying again...

So I guess running in admin mode will solve that issue? The question is, why is it not needed for other extensions.

**Comment by chrmarti** [comment]
@sandy081 What could cause the rename to fail with EPERM?

**Comment by sandy081** [comment]
In Windows, its typically because of the Defender that holds on to the files

**Comment by sandy081** [comment]
Also it could be that `ms-vscode.azure-account-0.4.0` folder is already there in extensions folder?

**Comment by fl0tschi** [comment]
Ok so thanks to your suggestion, I excluded the extensions folder from Windows Defender + I removed the already existing folder.

This did work for meI didn't try out just removing the folder, but I think that is the preferred solution.

Thanks for the hints!
