### ISSUE TITLE
Azure tools extension in VScode

### ISSUE THREAD

**Issue by AlirezaArch** [microsoft/vscode-azure-account#700]
The VS Code azure extension works fine for me on windows and I can easily sign in to azure. However, when I open VS Code in Ubuntu on WSL2, it cannot proceed to the Azure website when I click on sign-in to Azure.
By the way, even in Ubuntu, I am able to sign in to Azure via Azure CLI in the terminal by typing "az login". However, the VS Code extension doesn't work.

**Comment by alexweininger** [comment]
Can you try using the "Sign-in with Device Code" command from the palette?
