### ISSUE TITLE
For some reason Azure is not letting me switch tenants.

### ISSUE THREAD

**Issue by 3amwizard** [microsoft/vscode-azure-account#702]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azure-account.selectTenant
Error type: Error
Error Message: Unable to write into user settings. Please open the user settings to correct errors/warnings in it and try again.

Version: 0.11.3
OS: darwin
OS Release: 21.6.0
Product: Visual Studio Code
Product Version: 1.65.2
Language: en

<details>
<summary>Call Stack</summary>

```
C.toConfigurationEditingError workbench.desktop.main.js:2351:12542
C.updateConfiguration workbench.desktop.main.js:2351:9398
C.doWriteConfiguration workbench.desktop.main.js:2351:9244
async Object.factory workbench.desktop.main.js:2351:8904
```

</details>

**Comment by alexweininger** [comment]
> Error Message: Unable to write into user settings. Please open the user settings to correct errors/warnings in it and try again.

It seems like your settings.json file has errors of some kind. Could you try opening the settings file and fixing these errors and then try again?

**Comment by 3amwizard** [comment]
@alexweininger this is happening when I try and change tenants on VS code, how would the settings.json file be affected by this?

**Comment by alexweininger** [comment]
@3amwizard the tenant is controlled by a setting. So when you switch the tenant using the selectTenant command, we update the value of the `azure.tenant` setting. It looks like it's failing to update the value of this setting for some reason.

**Comment by 3amwizard** [comment]
Thanks for the insight, I do see the issue, I expected the Azure commands to take care of that but they don't. I did find a an easier solution was pushing my work to git and then pulling it to the azure server.
