### ISSUE TITLE
Cannot list subscriptions

### ISSUE THREAD

**Issue by srijak09** [microsoft/vscode-azure-account#705]
- VS Code Version: 1.74.3
- Azure Account Extension Version: 0.11.3
- OS Version: 21H2

Does your account belong to more than one directory? (see your directories [here](https://aka.ms/AAevnvr)): 

Any other information about your Azure account that may be useful:

**Comment by alexweininger** [comment]
Could you try the steps in the [Unable to List Subscriptions section of our wiki](https://github.com/microsoft/vscode-azure-account/wiki/Troubleshooting#unable-to-list-subscriptions) and see if they fix the issue?
