### ISSUE TITLE
After sign in, it cannot show sub list

### ISSUE THREAD

**Issue by adashen** [microsoft/vscode-azure-account#715]
Does this occur consistently? 
Repro steps:

1.
2.

Action: waitForSubscriptions
Error type: MultipleErrorsOccurred
Error Message: Multiple error occurred: . Please see details.

Version: 0.11.3
OS: win32
OS Release: 10.0.22621
Product: Visual Studio Code
Product Version: 1.75.0
Language: en

<details>
<summary>Call Stack</summary>

```
new RestError extension.bundle.js:2:65384
extension.bundle.js:2:52858extension.bundle.js:2:52858
```

</details>

**Comment by alexweininger** [comment]
Could you try the steps in the [Unable to List Subscriptions section of our wiki](https://github.com/microsoft/vscode-azure-account/wiki/Troubleshooting#unable-to-list-subscriptions) and see if they fix the issue?
