### ISSUE TITLE
Vscode cannot list subscriptions after signin in to Azure

### ISSUE THREAD

**Issue by nelalx** [microsoft/vscode-azure-account#717]
Does this occur consistently?  Yes
Repro steps:

1.  After try  signing in to azure using the Azure extension , it fails when at listing subscriptions 
2. request to https://management.azure.com/subscriptions?api-version=2016-06-01 failed, reason: unable to get local issuer certificate is the pop up i recieve.

Action: updateSubscriptionsAndTenants
Error type: UNABLE_TO_GET_ISSUER_CERT_LOCALLY
Error Message: request to redacted:url failed, reason: unable to get local issuer certificate

Version: 0.11.3
OS: win32
OS Release: 10.0.19041
Product: Visual Studio Code
Product Version: 1.75.0
Language: en

<details>
<summary>Call Stack</summary>

```
ClientRequest.<anonymous> extension.bundle.js:2:2789688
```

</details>

**Comment by alexweininger** [comment]
Could you try the steps in the [Unable to List Subscriptions section of our wiki](https://github.com/microsoft/vscode-azure-account/wiki/Troubleshooting#unable-to-list-subscriptions) and see if they fix the issue?
