### ISSUE TITLE
REQUEST_SEND_ERROR after update

### ISSUE THREAD

**Issue by odorikakeru** [microsoft/vscode-azure-account#720]
Does this occur consistently? 
Repro steps:

1.
2.

Action: updateSubscriptionsAndTenants
Error type: REQUEST_SEND_ERROR
Error Message: request to redacted:url failed, reason: getaddrinfo ENOTFOUND redacted:url

Version: 0.11.3
OS: win32
OS Release: 10.0.19045
Product: Visual Studio Code
Product Version: 1.75.1
Language: en

<details>
<summary>Call Stack</summary>

```
new RestError extension.bundle.js:2:65384
NodeFetchHttpClient.<anonymous> extension.bundle.js:2:46552
step extension.bundle.js:2:2310825
Object.throw extension.bundle.js:2:2310930
rejected extension.bundle.js:2:2309655
```

</details>

**Comment by alexweininger** [comment]
Are you behind a proxy of any kind?
