### ISSUE TITLE
Cannot sign in while using proxy

### ISSUE THREAD

**Issue by sanjaypradeep** [microsoft/vscode-azure-account#722]
- VS Code Version: 1.75.1
- Azure Account Extension Version: 0.11.3
- OS Version: Windows 10 Enterprise

Are you connected to a proxy server? Yes (server name: http://autoproxy.sbc.com/autoproxy.cgi)

Steps to Reproduce:

1. Open VS Code
2. Install Azure Account Extension
3. Click "Sign-in" option
4. Authenticate yourself - using login.microsoft.com (with same credentials for Azure)
5. Once authenticated, come back to VSCode
6. Verify the account is logged in or not.
7. For me, it's still showing "Sign-in" option 

Here's the output I see in Terminal (inside output tab)
Attempting to reach URL "https://login.microsoftonline.com/"...
Attempting to reach URL "https://vscode.dev/redirect"...
Attempting to reach URL "https://login.microsoftonline.com/common/oauth2/authorize?response_type=code&client_id=aebc6443-996d-45c2-90f0-388ff96faa56&redirect_uri=https%3A%2F%2Fvscode.dev%2Fredirect&state=http%3A%2F%2F127.0.0.1%3A62883%2Fcallback?nonce=Um3wOx0rsExAwgMipprDDQ%3D%3D&prompt=select_account"...
Get Token request returned http error: 400 and server response: {"error":"interaction_required","error_description":"AADSTS70043: The refresh token has expired or is invalid due to sign-in frequency checks by conditional access. The token was issued on 2022-11-01T13:44:53.3041999Z and the maximum allowed lifetime for this request is 86400.\r\nTrace ID: c26583e2-7708-4d63-94e1-aea1fd419e00\r\nCorrelation ID: cbf6a701-728b-47ee-a858-0adf4200e003\r\nTimestamp: 2023-02-17 21:52:03Z","error_codes":[70043],"timestamp":"2023-02-17 21:52:03Z","trace_id":"c26583e2-7708-4d63-94e1-aea1fd419e00","correlation_id":"cbf6a701-728b-47ee-a858-0adf4200e003","suberror":"token_expired"}

Note: My authentication is successful. I am raising this request, as Microsoft Support Engineer as directed.
![image](https://user-images.githubusercontent.com/18122757/219801782-25b57179-f0e8-4368-9b1a-63257b247f95.png)

**Comment by sanjaypradeep** [comment]
This issue got resolved by trying "az login" in windows powershell. 

Closing this ticket.

**Comment by alexweininger** [comment]
Thank you for filling out a detailed issue report and also following up with the fix. Glad you got it working!
