### ISSUE TITLE
VSCode sign issue

### ISSUE THREAD

**Issue by aliasifzamanfinlab** [microsoft/vscode-azure-account#723]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azure-account.loginToCloud
Error type: Error
Error Message: Get redacted:key returned http error: 400 and server response: {"error":"interaction_required","error_description":"AADSTS50158: External security challenge not satisfied. User will be redirected to another page or authentication provider to satisfy additional authentication challenges.\r\nTrace ID: redacted:id\r\nCorrelation ID: redacted:id\r\nTimestamp: redacted:id redacted:id20Z","error_codes":[redacted:id],"timestamp":"redacted:id redacted:id20Z","trace_id":"redacted:id","correlation_id":"redacted:id","error_uri":"redacted:url

Version: 0.11.3
OS: darwin
OS Release: 22.3.0
Product: Visual Studio Code
Product Version: 1.75.1
Language: en

<details>
<summary>Call Stack</summary>

```
Logger.createError extension.bundle.js:2:865070
extension.bundle.js:2:877955
```

</details>

**Comment by nturinski** [comment]
Please provide detailed repro steps.
