### ISSUE TITLE
Cannot list subscriptions

### ISSUE THREAD

**Issue by ZaidKhan2002** [microsoft/vscode-azure-account#726]
- VS Code Version: `1.75.0`
- Azure Account Extension Version: `v0.11.3`
- OS Version: `macOS 13.2`

Does your account belong to more than one directory? (see your directories [here](https://aka.ms/AAevnvr)): No

Any other information about your Azure account that may be useful: 
<img width="588" alt="Screenshot 2023-02-27 at 8 30 11 PM" src="https://user-images.githubusercontent.com/71960989/221598753-c34426cb-0531-42e2-8509-41cd448e5906.png">

**Comment by alexweininger** [comment]
Could you try the steps in the [Unable to List Subscriptions section of our wiki](https://github.com/microsoft/vscode-azure-account/wiki/Troubleshooting#unable-to-list-subscriptions) and see if they fix the issue?
