### ISSUE TITLE
I am unable to sign in to Azure from VS Code... "You appear to be offline..." 

### ISSUE THREAD

**Issue by rommelchildress** [microsoft/vscode-azure-account#727]
Does this occur consistently? Yes
Repro steps:

1.  In VS Code: F1 -> Azure Sign In

I get a dialog which states "You appear to be offline.  Please check your network connection."  My machine is online.  I am not behind any firewall or VPN.   I can log into Azure Portal from chrome just fine. I've tried specifically entering my tenant ID.  This had been working fine until recently.   I am also able to run Azure Data Studio, from the same machine and it is able to connect to the resources. 

Version: 0.11.3
OS: win32
OS Release: 10.0.19044
Product: Visual Studio Code
Product Version: 1.76.0
Language: en

**Comment by Ectrics** [comment]
I have the same issue 
Mac OS 13.2

Visual Studio Code 
Version: 1.76.1
Date: 2023-03-08T16:32:09.831Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Darwin x64 22.3.0
Sandboxed: Yes

**Comment by alexweininger** [comment]
Other users have successfully fixed this issue by following https://github.com/microsoft/vscode-azure-account/issues/733#issuecomment-1468239088. Could you give that a try and report the results?

**Comment by Ectrics** [comment]
> Other users have successfully fixed this issue by following [#733 (comment)](https://github.com/microsoft/vscode-azure-account/issues/733#issuecomment-1468239088). Could you give that a try and report the results?

Did worked, thanks!

**Comment by joshane1** [comment]
> Other users have successfully fixed this issue by following [#733 (comment)](https://github.com/microsoft/vscode-azure-account/issues/733#issuecomment-1468239088). Could you give that a try and report the results?

This did not work for me. Any other solution?

**Comment by alexweininger** [comment]
@joshane1, which extension(s) are you using with the Azure Account extension?

**Comment by joshane1** [comment]
@alexweininger im using
Azure Functions, Azure Resources, Azure Resource Manager, and a few other non Microsoft extensions such as ARM Template Viewer, GitHub Copilot, Github Copilot Chat, etc. it worked fine up until a few days ago.
