### ISSUE TITLE
Unable to use Azure Tools Extension in VSCode

### ISSUE THREAD

**Issue by arkapatra31** [microsoft/vscode-azure-account#728]
I'm unable to use Azure Tools Extension from VSCode. My company provided asset is not using any VPN or proxies.
And while trying to sign in from the extension it's prompting "Looks you are offline". Please help. I'll share relevant details below -

OS Version : Mac OS Ventura 13.2.1
Version: 1.76.0
Commit: 92da9481c0904c6adfe372c12da3b7748d74bdcb
Date: 2023-03-01T10:23:06.752Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Darwin arm64 22.3.0
Sandboxed: No
Azure Tools Extension Version : 1.1.1

**Comment by alexweininger** [comment]
Hi @arkapatra31, does the workaround mentioned in https://github.com/microsoft/vscode-azure-account/issues/733#issuecomment-1468239088 work for you?
