### ISSUE TITLE
Changing Azure Account (not drectory)

### ISSUE THREAD

**Issue by Phocee** [Microsoft/vscode-azure-account#73]
Hi,
signed-in with the wrong account, I'd like to sign out and sign in again with the correct one. 
Is this possible ? 

I haven't found how, tried to de-install the extensions and installed them again, but the wrong azure account sticked.

Any idea ?

Thanks,

Nicolas

**Comment by StephenWeatherford** [comment]
View -> Command Palette -> Azure: Sign Out

**Comment by chrmarti** [comment]
"Azure: Sign In" will ask you to authenticate through the browser. After entering the device code on the first page, the second page should allow you to "Use another account". Let us know if that doesn't work.

**Comment by Phocee** [comment]
Thank you :-)
