### ISSUE TITLE
Bug report Azure Functions Extension - Bad Request: Invalid URL

### ISSUE THREAD

**Issue by leshicodes** [microsoft/vscode-azure-account#731]
Whenever me or any of my colleagues attempt to utilize/deploy to any Azure Resource(s) with the Azure Accounts / Azure Function Extensions we do not see them populate within Visual Studio code, and the extension simply throws an error saying 

I want to state that we are being **SIGNED IN** just fine, we followed [this guide](https://github.com/microsoft/vscode-azure-account/wiki/Troubleshooting#unable-to-sign-in-while-using-a-proxy), it lists our subscriptions fine, however when trying to interact with the resources within the subscriptions, it simply states "Invalid URL" ?

> 11:31:43 AM: Error: Invalid URL

![Screen Shot 2023-03-10 at 11 33 26 AM](https://user-images.githubusercontent.com/24516995/224388005-5985b78c-756a-4c40-8920-ba619456ba08.png)
![Screen Shot 2023-03-10 at 11 33 34 AM](https://user-images.githubusercontent.com/24516995/224388016-20d61971-48ff-4598-badd-0e467410e949.png)

This is almost assuredly a proxy issue, and maybe even a reproduction of the closed Issue here: https://github.com/microsoft/vscode-azurefunctions/issues/1364

However the error is **super generic**. What URL(s) are invalid? I would need to know so I can add it to the NO_PROXY environment variables.

This is what our current NO_PROXY variable looks like
`localhost,127.0.0.1,login.microsoft.com,login.microsoftonline.com`

Steps to Reproduce:

1. Sign into Azure Account using Visual Studio Code Azure Account Extension (Successful)
2. Attempt to select/view any Function App(s) within our Subscriptions (Failure)

- OS Version: MacOs BigSur Version 11.7 (20G817)
Python: 3.8
- VS Code Version:
`Version: 1.76.1 (Universal)
Commit: 5e805b79fcb6ba4c2d23712967df89a089da575b
Date: 2023-03-08T16:32:09.831Z (2 days ago)
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Darwin x64 20.6.0
Sandboxed: No`
- Azure Account Extension Version:v0.11.3

Are you connected to a proxy server? Yes/No

YES and we followed the proxy sign in guide with no issues there.

**Comment by alexweininger** [comment]
Try adding `management.azure.com` to see if that changes anything. Also, has this worked in the past for you with the same proxy setup?

**Comment by leshicodes** [comment]
@alexweininger Thanks for taking a stab at this!

1. Adding `management.azure.com` to the `NO_PROXY` environment variable didn't relieve the issue unfortunately.
2. Yes, this did work in the past around a year or so ago however it could have stopped working due to proxy changes from our internal proxy team. unfortunately this is a large organization so I am not sure what exactly caused this to stop working.
3. it is worth noting that I had a colleague try this from a Windows 10 Enterprise machine and there were ZERO issues with them accessing / seeing anything. Seems to be an issued scoped to MacOS only, although I believe our Proxy is implemented slightly differently between the two OS-es.

**Comment by alexweininger** [comment]
More detailed logging will help us a lot when investigating issues like this. https://github.com/microsoft/vscode-azuretools/issues/1358

**Comment by alexweininger** [comment]
> So just to confirm I understand, are we waiting until there is a better debugging feature within the Azure VS Extension(s) before continuing to look into this? I'm newer to GitHub issues so tracking all of this is foreign to me.
> 
> Either way I appreciate your time.

Yes, sorry. I was just making a note to myself and the rest of my team that we should revisit this issue once we add more detailed logging within the extension. I don't think there are any action items you can take currently.

**Comment by alexweininger** [comment]
We've released an update to the extension which improves the extension logging. Please follow [this guide](https://github.com/microsoft/vscode-azure-account/wiki/Enable-and-view-logs) for how to collect and share the logs.
