### ISSUE TITLE
Azure: Sign in - error: nothing happens

### ISSUE THREAD

**Issue by shershen08** [Microsoft/vscode-azure-account#74]
I have 2 extensions or VSC installed "Azure Account" and "Azure App Service" installed but when I try to login -  either from `Cmd + Shift + P` or from a menu nothing happens.

OS: MacOs Sierra 10.12
VSC: 1.24.1 

Is there a way to debug the process on what's going wrong?

<img width="598" alt="screen shot 2018-06-30 at 20 44 55" src="https://user-images.githubusercontent.com/1363772/42128212-68bae6e8-7ca6-11e8-8c40-ba09cea0baf3.png">
<img width="1025" alt="screen shot 2018-06-30 at 20 44 47" src="https://user-images.githubusercontent.com/1363772/42128213-68d24194-7ca6-11e8-9ebf-f655c34892a5.png">

**Comment by chrmarti** [comment]
There should be a notification in the lower right of the window, asking you to sign in with the browser. If that notification doesn't show, could you check if there is anything in the console (Help > Toggle Developer Tools)?

**Comment by shershen08** [comment]
@chrmarti you're right, there's an error with locally enabled proxy

```
[Extension Host] Error: tunneling socket could not be established, cause=connect EHOSTUNREACH 0.0.12.56:80 - Local (192.168.x.x:64331)
	at ClientRequest.onError (..../.vscode/extensions/ms-vscode.azure-account-0.4.1/node_modules/tunnel-agent/index.js:177:17)
````
i've tried setting the local user settings to
```
"http.proxy": "http://localhost:<MYLOCAL_PROXY_HOST>",
"http.proxyStrictSSL": false,
```
but that didn't help

is there any extra config parameter to pass by a locally installed proxy?

**Comment by chrmarti** [comment]
The node modules we use do not read the mentioned settings. Could you try setting environment variables like:
```
export HTTPS_PROXY=http://username:password@proxy:8080
export HTTP_PROXY=http://username:password@proxy:8080
```

**Comment by shershen08** [comment]
I already have it set in .profile:
```
$: export
..
declare -x http_proxy="localhost:<MYLOCAL_PROXY_HOST>"
declare -x https_proxy="localhost:<MYLOCAL_PROXY_HOST>"
```
