### ISSUE TITLE
Not letting me sign in into tenant

### ISSUE THREAD

**Issue by Kavaljeetarya** [microsoft/vscode-azure-account#748]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azure-account.selectTenant
Error type: Error
Error Message: Unable to write into user settings. Please open the user settings to correct errors/warnings in it and try again.

Version: 0.11.3
OS: win32
OS Release: 10.0.22621
Product: Visual Studio Code - Insiders
Product Version: 1.77.0-insider
Language: en

<details>
<summary>Call Stack</summary>

```
I.y workbench.desktop.main.js:2297:54988
I.o workbench.desktop.main.js:2297:52265
I.n workbench.desktop.main.js:2297:52156
async Object.factory workbench.desktop.main.js:2297:51906
```

</details>

**Comment by alexweininger** [comment]
Can you check your settings file to make sure there are no syntax errors?
