### ISSUE TITLE
Unable to connect to Azure account from VSC. Getting below error.

### ISSUE THREAD

**Issue by sudheernellore** [microsoft/vscode-azure-account#751]
![VSC_Issue](https://user-images.githubusercontent.com/46022809/227690602-583bfcab-1686-48b6-b044-7f858ca1b6c5.png)

Does this occur consistently? 
Repro steps:

1.
2.

Action: updateSubscriptionsAndTenants
Error type: ECONNRESET
Error Message: request to redacted:url failed, reason: tunneling socket could not be established, cause=getaddrinfo ENOTFOUND proxy

Version: 0.11.3
OS: win32
OS Release: 10.0.22621
Product: Visual Studio Code
Product Version: 1.76.2
Language: en

<details>
<summary>Call Stack</summary>

```
ClientRequest.<anonymous> extension.bundle.js:2:2789688
ClientRequest.onError extension.bundle.js:2:2318786
```

</details>

**Comment by alexweininger** [comment]
Are you behind a proxy of any kind? Proxies often cause issues with sign-in. See the [Unable to Sign In While Using a Proxy section of our wiki](https://github.com/microsoft/vscode-azure-account/wiki/Troubleshooting#unable-to-sign-in-while-using-a-proxy) for possible fixes.
