### ISSUE TITLE
vs code error

### ISSUE THREAD

**Issue by parveenkrraina** [microsoft/vscode-azure-account#752]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azure-account.selectSubscriptions
Error type: Error
Error Message: Unable to write into user settings. Please open the user settings to correct errors/warnings in it and try again.

Version: 0.11.3
OS: win32
OS Release: 10.0.23419
Product: Visual Studio Code
Product Version: 1.76.2
Language: en

<details>
<summary>Call Stack</summary>

```
S.y workbench.desktop.main.js:2271:46363
S.o workbench.desktop.main.js:2271:43640
S.n workbench.desktop.main.js:2271:43531
async Object.factory workbench.desktop.main.js:2271:43281
```

</details>

**Comment by alexweininger** [comment]
This indicates that there is a syntax error in one of your settings files. Please check your settings.json file and fix any errors and try again.
