### ISSUE TITLE
Unable to login to Azure from VS Code

### ISSUE THREAD

**Issue by v-ededios** [microsoft/vscode-azure-account#753]
- VS Code Version: 1.76.2
- Azure Account Extension Version: v0.11.3
- OS Version: Windows 10 Enterprise - 21H2 - 19044.2604; 64 bits
 
Are you connected to a proxy server? Yes

Steps to Reproduce:

1. Attempt to sign-in to Azure Account from VS Code.

<img width="455" alt="Picture1" src="https://user-images.githubusercontent.com/115321547/228323254-b80dc104-a14a-424f-9e94-57d324c2af75.png">

<img width="482" alt="Picture2" src="https://user-images.githubusercontent.com/115321547/228323259-33f774c5-87df-4a56-b0ea-c14d27ad73ff.png">

After search around and configuration twisting, we found a workaround, which is to add our company’s proxy url to Proxy settings in VS Code and delete HTTP_PROXY and HTTPS_PROXY from system environment variable setting. However, this workaround is not sustainable, as based on the description in VS code setting, if proxy setting is not set, it is supposed to be inherited from http_proxy and https_proxy environment variables.  Could you please help us identity the root cause and fix it? Thanks a lot! 

<img width="482" alt="Picture3" src="https://user-images.githubusercontent.com/115321547/228323261-54f48f25-d738-4643-bb3d-9f3c1591090c.png">

**Comment by alexweininger** [comment]
See the [Unable to Sign In While Using a Proxy section of our wiki](https://github.com/microsoft/vscode-azure-account/wiki/Troubleshooting#unable-to-sign-in-while-using-a-proxy) for possible fixes.

**Comment by v-ededios** [comment]
Hey Alex,

Thanks for this but we’ve already tried these.

Best,

Ednalyn C. De Dios
Azure Machine Learning Support Engineer
Azure - AI + Intelligent Devices
Phone: +1 (469) 775-0008
Email: ***@***.******@***.***%0d>
Working hours: M-F 9AM-6PM CST (UTC-6)﻿
Need help outside of my working hours?
Locate an engineer: ***@***.***
Manager: James Fugate / ***@***.******@***.***>
***@***.***

**Comment by alexweininger** [comment]
The VS Code proxy settings do not alter any behavior in the extension itself. So essentially what you did to get it working was remove the proxy altogether.

**Comment by v-ededios** [comment]
@alexweininger adding urls to NO_PROXY as suggested in the troubleshooting page will not work for us when working from corporate network.

As we are behind corporate network using a PROXY which requires to use http/https_proxy and no_proxy for internal stuff, there is no direct connection possible which is required for the hack. Is there any solution can be use to handle this issue from the root? As we don’t have issue connecting to Azure account last year.

**Comment by alexweininger** [comment]
Currently I don't have any further suggestions for fixes for your proxy setup. However, we will be releasing a new version of the extension that has detailed logging capabilities. When this releases I will ask you to share the logs and we can investigate further from there.

**Comment by alexweininger** [comment]
We've released v0.11.4 of the Azure Account extension which includes better logging. Please follow [this guide](https://github.com/microsoft/vscode-azure-account/wiki/Enable-and-view-logs) for how to collect and share the logs.

**Comment by alexweininger** [comment]
From logs provided offline, the current "Azure: Authentication Library" setting value is ADAL. Please change it to MSAL and try again. If it still fails, please provide the trace logs again, they are very helpful.

<img width="803" alt="image" src="https://github.com/microsoft/vscode-azure-account/assets/12476526/2600dc81-c424-41f1-bba2-54a0a1a4c244">

Thanks!

**Comment by v-ededios** [comment]
Thank you @alexweininger . Attached is the log with MSAL. 
[AzureAccountSignInLog-MSAL.log](https://github.com/microsoft/vscode-azure-account/files/11874096/AzureAccountSignInLog-MSAL.log)

**Comment by alexweininger** [comment]
I'm really hoping this can be fixed by our new authentication implementation https://github.com/microsoft/vscode-azureresourcegroups/pull/707
