### ISSUE TITLE
Latest version of Azure Account - Azure Cloud Shell does not login now

### ISSUE THREAD

**Issue by wsmelton** [Microsoft/vscode-azure-account#77]
VS Code: Insiders build, 1.26.0
Extension version: 0.4.2

Steps to reproduce:
1. CTRL + SHIFT, P and select `Azure: Sign In`
2. Go through web prompt to authenticate
3. CTRL + SHIFT, P and select `Azure: Open PowerShell in Cloud Shell`

Expected Behavior:
Azure Cloud shell opens to the `Azure:\` directory.

Result:
Prompted to open a browser, that all it does is open up `shell.azure.com` and starts a shell session.
![image](https://user-images.githubusercontent.com/11204251/42841616-40d90f10-89d0-11e8-8245-0a416140afb7.png)

I already have an Azure Cloud Shell setup and have used it multiple times. Previous version of the extension worked properly so I'm not sure if something has changed with how authentication works in Azure or if the extension changed it.

**Comment by chrmarti** [comment]
`Select directory...` indicates that you were asked which directory to use. How many could you pick from? Does it work when you choose a different directory?

**Comment by wsmelton** [comment]
I have two directories because it picks up that I have one with Power BI service.

When I select a directory it just logs me into the Cloud Shell in the browser, nothing happens from VS Code side.

**Comment by chrmarti** [comment]
Does it always end with 'Setup needed.'? Could you check in the browser's dev tools what the response is for the 'userSettings/cloudconsole' when opening shell.azure.com?

**Comment by wsmelton** [comment]
AH!!! It was (I think) because the prompt did not stay open in VS Code.

Tried it now in VS Code Insiders and it caught the prompt this time:
![image](https://user-images.githubusercontent.com/11204251/42975021-952a792c-8b7f-11e8-9a19-9736e2adbed8.png)

Selecting that and it created the session. I've had few other extensions that if you change focus on VS Code that prompt does not stay "open". I'm not sure if you can adjust for it to stay open, (e.g. know the Sync extension stays open after focus changes).

**Comment by chrmarti** [comment]
Good catch, fixing that.
