### ISSUE TITLE
Bug report Unable to sign in to "Azure Account" extension in VS Code after entering credentials

### ISSUE THREAD

**Issue by RomanshkVolkov** [microsoft/vscode-azure-account#770]
- VS Code Version: 
code -v output 
1.77.0
7f329fe6c66b0f86ae1574c2911b681ad5a45d63
x64
- Azure Account Extension Version: 0.11.3
- OS Version: Debian wsl2 (win11)

Are you connected to a proxy server? Yes/No
No
Steps to Reproduce:

1.- Open VS Code on your machine and make sure you have the "Azure Account" extension installed on version 0.11.3.

2.- Press Ctrl + Shift + P (or Cmd + Shift + P on Mac) to open the VS Code command bar and type "Azure: Sign in" to open the Azure login window.

3.- Enter your Azure credentials in the login window and click "Next" to continue.

4.- If the login is successful, the web page should state "You are signed in now and can close this page." However, the Azure session is not started in the VS Code "Azure Account" extension and you are not prompted for a verification code.

https://stackoverflow.com/questions/52468396/azure-sign-in-not-working-using-azure-tools-option-in-vscode?newreg=0a8731790b32419783dc9981024ee280
"I read on StackOverflow that it worked for me.

I had a similar problem, and for me, it was the latest Azure Account plugin version 0.9.10 that didn't work.

I reinstalled the previous version, 0.9.9, and now the login works again."

**Comment by alexweininger** [comment]
Please see the [Enable and View Logs](https://github.com/microsoft/vscode-azure-account/wiki/Enable-and-view-logs) section of the wiki for how to capture and share Azure Account extension logs.

If you can share the logs with the log level set to Trace, that will help a lot.
