### ISSUE TITLE
Cannot list subscriptions

### ISSUE THREAD

**Issue by hasepravin** [microsoft/vscode-azure-account#772]
- VS Code Version: 1.76.0
- Azure Account Extension Version: 
- OS Version: Window_NT x64 10.0.19044
- 
Does your account belong to more than one directory? (see your directories [here](https://aka.ms/AAevnvr)): Yes

Any other information about your Azure account that may be useful: My other subscription details showing but only one is not.

**Comment by alexweininger** [comment]
Could you try the steps in the [Unable to List Subscriptions section of our wiki](https://github.com/microsoft/vscode-azure-account/wiki/Troubleshooting#unable-to-list-subscriptions) and see if they fix the issue?

**Comment by hasepravin** [comment]
@alexweininger Yes I follow these steps and now I am able to see subscription. We can close this ticket now.
