### ISSUE TITLE
Bug report Unable to login to azure account in VS Code

### ISSUE THREAD

**Issue by samthrusha123** [microsoft/vscode-azure-account#773]
- VS Code Version:
- Azure Account Extension Version:
- OS Version:

Are you connected to a proxy server? Yes/No

Steps to Reproduce:

1.Press cntrl + shift+p 
2.and select azure:signin from the command pallet
getting the below errors again and again
![image](https://user-images.githubusercontent.com/44087954/230042856-6fc97f26-fc32-47d3-8dbd-160f42daf53a.png)

**Comment by alexweininger** [comment]
See https://github.com/microsoft/vscode-azure-account/issues/733#issuecomment-1468239088 for a possible workaround.
