### ISSUE TITLE
Can't use arrow keys or home/end keys in powershell cloud shell in vscode

### ISSUE THREAD

**Issue by SeanGraySage** [Microsoft/vscode-azure-account#78]
Helllo,

If I open a powershell cloud shell in vscode, I do not appear to be able to navigate the history with up/down arrow keys, or move along the line with left/right arrow keys. I also cannot use Home/End.
Pressing arrow keys appears to do nothing, pressing home or end types a ~.

All of these functions work fine in the local powershell terminals in vscode and also work fine if I open a bash cloud shell.

**Comment by chrmarti** [comment]
@Tyriar I can reproduce this on Windows, but not on Mac. On Mac I see, e.g., `ESC``OA` being sent from the Terminal to the shell process, on Windows it is `ESC``[A`. On Mac there is a response to that from the shell, on Windows there isn't.

**Comment by Tyriar** [comment]
The sequence for ctrl+a is send when from the command when home is pressed:

https://github.com/Microsoft/vscode/blob/fb20a9be5656a6f94eb5cc170877b5b147d4333d/src/vs/workbench/parts/terminal/electron-browser/terminalActions.ts#L212

I would expect this issue to be fixed after https://github.com/Microsoft/vscode/issues/45693 is resolved.

**Comment by chrmarti** [comment]
Upstream issue was fixed. Closing. Let me know if you still see this.

**Comment by ABrauser** [comment]
Well seems that this issue is still there. (I have installed the latest Visual Studio Code) But i am still not able to use the arrow keys inside the "Powershell in Cloud Shell" of VS Code Terminal. For the Local powershell terminal it works.

**Comment by Tyriar** [comment]
@ABrauser see https://github.com/Microsoft/vscode/issues/45693#issuecomment-449495252, only Windows Insiders builds have access to the fix currently.

**Comment by dave-007** [comment]
I have same issue, latest vscode, (Get-ComputerInfo).WindowsBuildLabEx is  19041.1.amd64fre.vb_release.191206-1406. Changing the terminal.integrated.windowsEnableConpty doesn't change behavior. No up-arrow is surprisingly limiting! :)
