### ISSUE TITLE
Unable to decrypt password when trying to fetch refresh token from Azure Account Extension API

### ISSUE THREAD

**Issue by shsuman** [microsoft/vscode-azure-account#783]
Azure ML extension uses the Azure Account API to fetch the refresh tokens. But, in a particular case with the customer, initially, the Azure Account was throwing this error  **Unable to parse decrypted password.** 

But, from the logs it seems like after some retries, the refresh token is null.

Note that the user is behind a VNET and is using a Private endpoint where Public network access is disabled.

**Comment by alexweininger** [comment]
Can you retry the operation with this VSIX installed manually? [azure-account-0.11.4-alpha.0.vsix.zip](https://github.com/microsoft/vscode-azure-account/files/11224753/azure-account-0.11.4-alpha.0.1.vsix.zip)

Before you retry set the Log Level of the Azure Account extension to "Trace".

Run "Developer: Set Log Level" command from palette.
<img width="614" alt="image" src="https://user-images.githubusercontent.com/12476526/231835989-1ae4f615-afdd-48c4-9280-3e486d077b0e.png">

Select "Azure Account"
<img width="615" alt="image" src="https://user-images.githubusercontent.com/12476526/231836254-853830e9-3c8e-4e8a-9b0a-1502993f07cd.png">

Select "Trace"
<img width="606" alt="image" src="https://user-images.githubusercontent.com/12476526/231836305-f0d78cb1-8a59-4162-b51d-1f07b71b39f7.png">

**Comment by jgtellez1** [comment]
Hi @alexweininger , customer provided the output:
![image](https://user-images.githubusercontent.com/15677447/234974268-75548467-70cb-4dee-be63-eca33bf8152c.png)

[Debug - 2023-04-27 15:50:04.671] Registering Compute instance remote server provider
[Debug - 2023-04-27 15:50:04.671] Ensuring Jupyter extension is installed
[Debug - 2023-04-27 15:50:04.671] Jupyter extension is already installed
[Debug - 2023-04-27 15:50:04.671] Registering Azure ML Uri Hanlder with path:  /computeInstance/remote
[Debug - 2023-04-27 15:50:04.672] Registering Azure ML Uri Hanlder with path:  /interactiveSession/distributedJob
[Debug - 2023-04-27 15:50:04.672] Registering Azure ML Uri Hanlder with path:  /interactiveSession
[Trace - 2023-04-27 15:50:04.673] DefaultWorkspace.showSelectWorkspacePromptIfNeeded called with arguments: [
    "No default Azure ML Workspace is selected. You need to select a default workspace to enable features such as completions and validations in your YAML files."
]
[Trace - 2023-04-27 15:50:04.673] DefaultWorkspaceService.get called with arguments: []
[Trace - 2023-04-27 15:50:04.674] AuthenticationService.getAzureMLService called with arguments: [
    "<sub-id>"
]
[Trace - 2023-04-27 15:50:04.674] AuthenticationService.getSubscriptionById called with arguments: [
    "<sub-id>"
]
[Trace - 2023-04-27 15:50:04.674] AuthenticationService.listSubscriptions called with arguments: []
[Debug - 2023-04-27 15:50:04.675] Attempting to activate the extension: Jupyter
[Trace - 2023-04-27 15:50:04.676] Telemetry Event: authentication/needsLogin Measures: undefined Props: {
    "result": "false"
}
[Debug - 2023-04-27 15:50:04.707] Getting children for root node
[Trace - 2023-04-27 15:50:04.707] AuthenticationService.listVisibleSubscriptions called with arguments: []
[Trace - 2023-04-27 15:50:04.708] Telemetry Event: authentication/needsLogin Measures: undefined Props: {
    "result": "false"
}
[Debug - 2023-04-27 15:50:04.709] SusbcriptionTreeNodes nodes are being displayed in the tree view
[Trace - 2023-04-27 15:50:04.710] Getting tree item for node id:  <sub-id>-f178ffe3-5e21-4a53-b3cb-7183f487f5f3
[Trace - 2023-04-27 15:50:04.710] Getting tree item for node id:  ce875372-2e68-4231-98c5-37013b2005bf-e7f35ce0-ccb2-4276-94b1-6238648385de
[Trace - 2023-04-27 15:50:04.710] Getting tree item for node id:  9f855df0-5e82-482f-bafd-86d69cada4c1-2454ad72-f46c-4061-8ce9-9a2d21d97773
[Trace - 2023-04-27 15:50:04.710] Getting tree item for node id:  133c573a-b065-4b70-bd3a-d3b07e0d9a4c-88f122c0-235e-4c46-a2b7-aac5e8cd90e9
[Debug - 2023-04-27 15:50:06.120] Getting children for node id:  <sub-id>-f178ffe3-5e21-4a53-b3cb-7183f487f5f3
[Trace - 2023-04-27 15:50:06.120] WorkspaceFilterService.filter called for subscription: /subscriptions/<sub-id>
[Trace - 2023-04-27 15:50:06.121] Subscription.listWorkspaces called with arguments: [
    null
]
[Trace - 2023-04-27 15:50:07.057] DefaultWorkspaceService.set called with arguments: [
    "/subscriptions/<sub-id>/resourceGroups/<rg>/providers/Microsoft.MachineLearningServices/workspaces/<workspace>",
    false,
    false
]
[Trace - 2023-04-27 15:50:07.057] AuthenticationService.getAzureMLService called with arguments: [
    "<sub-id>"
]
[Trace - 2023-04-27 15:50:07.058] AuthenticationService.getSubscriptionById called with arguments: [
    "<sub-id>"
]
[Trace - 2023-04-27 15:50:07.058] AuthenticationService.listSubscriptions called with arguments: []
[Trace - 2023-04-27 15:50:07.147] Telemetry Event: authentication/needsLogin Measures: undefined Props: {
    "result": "false"
}
[Trace - 2023-04-27 15:50:07.179] Telemetry Event: subscription/getChildren/info Measures: undefined Props: {
    "numberOfWorkspaces": "2",
    "subscriptionId": "<sub-id>"
}
[Trace - 2023-04-27 15:50:07.186] Getting tree item for node id:  /subscriptions/<sub-id>/resourceGroups/<rg>/providers/Microsoft.MachineLearningServices/workspaces/<other_workspace>
[Trace - 2023-04-27 15:50:07.186] Getting tree item for node id:  /subscriptions/<sub-id>/resourceGroups/<rg>/providers/Microsoft.MachineLearningServices/workspaces/<workspace>
[Trace - 2023-04-27 15:50:07.540] DefaultWorkspaceService.get called with arguments: []
[Trace - 2023-04-27 15:50:07.540] Refreshing tree view 
[Trace - 2023-04-27 15:50:07.540] DefaultWorkspaceService.get called with arguments: []
[Debug - 2023-04-27 15:50:07.553] Getting children for root node
[Trace - 2023-04-27 15:50:07.553] AuthenticationService.listVisibleSubscriptions called with arguments: []
[Trace - 2023-04-27 15:50:07.569] Telemetry Event: authentication/needsLogin Measures: undefined Props: {
    "result": "false"
}
[Debug - 2023-04-27 15:50:07.579] SusbcriptionTreeNodes nodes are being displayed in the tree view
[Trace - 2023-04-27 15:50:07.591] Getting tree item for node id:  <sub-id>-17db4517-b183-4245-953e-b56e3d7980ab
[Trace - 2023-04-27 15:50:07.591] Getting tree item for node id:  ce875372-2e68-4231-98c5-37013b2005bf-8f6303b2-26c3-4a03-b7e7-c65ba4cde39b
[Trace - 2023-04-27 15:50:07.591] Getting tree item for node id:  9f855df0-5e82-482f-bafd-86d69cada4c1-c523acc5-0b47-425f-8863-b98de6a39401
[Trace - 2023-04-27 15:50:07.591] Getting tree item for node id:  133c573a-b065-4b70-bd3a-d3b07e0d9a4c-0378a070-6adb-4b09-8f7e-c2c4a218579d
[Trace - 2023-04-27 15:50:07.683] DefaultWorkspace.initlializeCache called with arguments: []
[Trace - 2023-04-27 15:50:07.687] AuthenticationService.getSubscriptionById called with arguments: [
    "<sub-id>"
]
[Trace - 2023-04-27 15:50:07.687] AuthenticationService.listSubscriptions called with arguments: []
[Trace - 2023-04-27 15:50:07.719] Telemetry Event: authentication/needsLogin Measures: undefined Props: {
    "result": "false"
}
[Trace - 2023-04-27 15:50:07.740] Refreshing tree view 
[Trace - 2023-04-27 15:50:07.740] DefaultWorkspaceService.get called with arguments: []
[Debug - 2023-04-27 15:50:07.762] Default Workspace has been set from Workspace state
[Trace - 2023-04-27 15:50:07.762] Telemetry Event: defaultWorkspaceService/initialize Measures: undefined Props: {
    "defaultWSSetFrom": "WorkspaceState"
}
[Trace - 2023-04-27 15:50:07.776] AuthenticationService.getSubscriptionById called with arguments: [
    "<sub-id>",
    true
]
[Trace - 2023-04-27 15:50:07.776] AuthenticationService.listVisibleSubscriptions called with arguments: []
[Trace - 2023-04-27 15:50:07.776] DefaultWorkspace.syncCache called with arguments: []
[Trace - 2023-04-27 15:50:07.778] DefaultWorkspace.syncCache called with arguments: []
[Trace - 2023-04-27 15:50:07.805] Telemetry Event: authentication/needsLogin Measures: undefined Props: {
    "result": "false"
}
[Debug - 2023-04-27 15:50:08.135] Getting children for root node
[Trace - 2023-04-27 15:50:08.135] AuthenticationService.listVisibleSubscriptions called with arguments: []
[Trace - 2023-04-27 15:50:08.139] Telemetry Event: authentication/needsLogin Measures: undefined Props: {
    "result": "false"
}
[Debug - 2023-04-27 15:50:08.142] SusbcriptionTreeNodes nodes are being displayed in the tree view
[Trace - 2023-04-27 15:50:08.149] Getting tree item for node id:  <sub-id>-9c6b30c2-4546-4808-91fa-6c73053ea008
[Trace - 2023-04-27 15:50:08.149] Getting tree item for node id:  ce875372-2e68-4231-98c5-37013b2005bf-d707e444-d096-4115-baff-8c78124acc8d
[Trace - 2023-04-27 15:50:08.149] Getting tree item for node id:  9f855df0-5e82-482f-bafd-86d69cada4c1-44080ca2-69b8-494c-8ebe-1da0e9743b01
[Trace - 2023-04-27 15:50:08.149] Getting tree item for node id:  133c573a-b065-4b70-bd3a-d3b07e0d9a4c-24a3cb63-d9e0-4168-8856-9e7fa68b2964
[Info - 2023-04-27 15:50:08.727] Default workspace cache synchronized successfully.
[Info - 2023-04-27 15:50:08.753] Default workspace cache initialized successfully.
[Info - 2023-04-27 15:50:08.864] Default workspace cache synchronized successfully.
[Debug - 2023-04-27 15:50:15.029] Getting children for node id:  <sub-id>-9c6b30c2-4546-4808-91fa-6c73053ea008
[Trace - 2023-04-27 15:50:15.029] WorkspaceFilterService.filter called for subscription: /subscriptions/<sub-id>
[Trace - 2023-04-27 15:50:15.029] Subscription.listWorkspaces called with arguments: [
    null
]
[Trace - 2023-04-27 15:50:15.327] Telemetry Event: subscription/getChildren/info Measures: undefined Props: {
    "numberOfWorkspaces": "2",
    "subscriptionId": "<sub-id>"
}
[Trace - 2023-04-27 15:50:15.329] Getting tree item for node id:  /subscriptions/<sub-id>/resourceGroups/<rg>/providers/Microsoft.MachineLearningServices/workspaces/<other_workspace>
[Trace - 2023-04-27 15:50:15.329] Getting tree item for node id:  /subscriptions/<sub-id>/resourceGroups/<rg>/providers/Microsoft.MachineLearningServices/workspaces/<workspace>
[Debug - 2023-04-27 15:50:16.773] Getting children for node id:  /subscriptions/<sub-id>/resourceGroups/<rg>/providers/Microsoft.MachineLearningServices/workspaces/<workspace>
[Trace - 2023-04-27 15:50:16.775] Getting tree item for node id:  /subscriptions/<sub-id>/resourceGroups/<rg>/providers/Microsoft.MachineLearningServices/workspaces/<workspace>/datasets
[Trace - 2023-04-27 15:50:16.775] Getting tree item for node id:  /subscriptions/<sub-id>/resourceGroups/<rg>/providers/Microsoft.MachineLearningServices/workspaces/<workspace>/experiments
[Trace - 2023-04-27 15:50:16.775] Getting tree item for node id:  /subscriptions/<sub-id>/resourceGroups/<rg>/providers/Microsoft.MachineLearningServices/workspaces/<workspace>/models
[Trace - 2023-04-27 15:50:16.775] Getting tree item for node id:  /subscriptions/<sub-id>/resourceGroups/<rg>/providers/Microsoft.MachineLearningServices/workspaces/<workspace>/endpoints
[Trace - 2023-04-27 15:50:16.775] Getting tree item for node id:  /subscriptions/<sub-id>/resourceGroups/<rg>/providers/Microsoft.MachineLearningServices/workspaces/<workspace>/computes
[Trace - 2023-04-27 15:50:16.775] Getting tree item for node id:  /subscriptions/<sub-id>/resourceGroups/<rg>/providers/Microsoft.MachineLearningServices/workspaces/<workspace>/datastores
[Trace - 2023-04-27 15:50:16.775] Getting tree item for node id:  /subscriptions/<sub-id>/resourceGroups/<rg>/providers/Microsoft.MachineLearningServices/workspaces/<workspace>/environments
[Debug - 2023-04-27 15:50:20.406] Getting children for node id:  /subscriptions/<sub-id>/resourceGroups/<rg>/providers/Microsoft.MachineLearningServices/workspaces/<workspace>/computes
[Trace - 2023-04-27 15:50:20.411] Getting tree item for node id:  /subscriptions/<sub-id>/resourceGroups/<rg>/providers/Microsoft.MachineLearningServices/workspaces/<workspace>/computes/computeInstances
[Trace - 2023-04-27 15:50:20.411] Getting tree item for node id:  /subscriptions/<sub-id>/resourceGroups/<rg>/providers/Microsoft.MachineLearningServices/workspaces/<workspace>/computes/computeClusters
[Trace - 2023-04-27 15:50:20.411] Getting tree item for node id:  /subscriptions/<sub-id>/resourceGroups/<rg>/providers/Microsoft.MachineLearningServices/workspaces/<workspace>/computes/inferenceClusters
[Trace - 2023-04-27 15:50:20.411] Getting tree item for node id:  /subscriptions/<sub-id>/resourceGroups/<rg>/providers/Microsoft.MachineLearningServices/workspaces/<workspace>/computes/attachedCompute
[Debug - 2023-04-27 15:50:21.652] Getting children for node id:  /subscriptions/<sub-id>/resourceGroups/<rg>/providers/Microsoft.MachineLearningServices/workspaces/<workspace>/computes/computeInstances
[Trace - 2023-04-27 15:50:22.187] AuthenticationService.getUserObjectId called with arguments: [
    "<sub-id>"
]
[Trace - 2023-04-27 15:50:22.187] AuthenticationService.getAuthTokenResponse called with arguments: [
    "<sub-id>"
]
[Trace - 2023-04-27 15:50:22.187] AuthenticationService.getCredentials called with arguments: [
    "<sub-id>"
]
[Trace - 2023-04-27 15:50:22.187] AuthenticationService.promptLoginIfNecessary called with arguments: []
[Trace - 2023-04-27 15:50:22.195] Telemetry Event: authentication/needsLogin Measures: undefined Props: {
    "result": "false"
}
[Trace - 2023-04-27 15:50:22.197] AuthenticationService.getSubscriptionById called with arguments: [
    "<sub-id>"
]
[Trace - 2023-04-27 15:50:22.197] AuthenticationService.listSubscriptions called with arguments: []
[Trace - 2023-04-27 15:50:22.209] Telemetry Event: authentication/needsLogin Measures: undefined Props: {
    "result": "false"
}
[Trace - 2023-04-27 15:50:22.874] AuthenticationService.getSubscriptionById called with arguments: [
    "<sub-id>"
]
[Trace - 2023-04-27 15:50:22.874] AuthenticationService.listSubscriptions called with arguments: []
[Trace - 2023-04-27 15:50:22.878] Telemetry Event: authentication/needsLogin Measures: undefined Props: {
    "result": "false"
}
[Trace - 2023-04-27 15:50:22.881] Telemetry Event: authentication/nullUserObjectId Measures: undefined Props: {}
[Error - 2023-04-27 15:50:22.881] Failed to get user object id for the user  xxx@xxx.com
[Info - 2023-04-27 15:50:22.890] [Azure ML JS SDK]User Object id is null. Assuming user can use the Compute instance.
[Info - 2023-04-27 15:50:22.890] [Azure ML JS SDK]User Object id is null. Assuming user can use the Compute instance.
[Info - 2023-04-27 15:50:22.890] [Azure ML JS SDK]User Object id is null. Assuming user can use the Compute instance.
[Info - 2023-04-27 15:50:22.891] [Azure ML JS SDK]User Object id is null. Assuming user can use the Compute instance.
[Info - 2023-04-27 15:50:22.891] [Azure ML JS SDK]User Object id is null. Assuming user can use the Compute instance.
[Info - 2023-04-27 15:50:22.891] [Azure ML JS SDK]User Object id is null. Assuming user can use the Compute instance.
[Trace - 2023-04-27 15:50:22.912] Getting tree item for node id:  /subscriptions/<sub-id>/resourceGroups/<rg>/providers/Microsoft.MachineLearningServices/workspaces/<workspace>/computes/vinay-001-ml
[Trace - 2023-04-27 15:50:22.912] Getting tree item for node id:  /subscriptions/<sub-id>/resourceGroups/<rg>/providers/Microsoft.MachineLearningServices/workspaces/<workspace>/computes/che-001-mlGPU
[Trace - 2023-04-27 15:50:22.912] Getting tree item for node id:  /subscriptions/<sub-id>/resourceGroups/<rg>/providers/Microsoft.MachineLearningServices/workspaces/<workspace>/computes/che-002-mlGPU
[Trace - 2023-04-27 15:50:22.912] Getting tree item for node id:  /subscriptions/<sub-id>/resourceGroups/<rg>/providers/Microsoft.MachineLearningServices/workspaces/<workspace>/computes/yuyu-001-mlGPU
[Trace - 2023-04-27 15:50:22.912] Getting tree item for node id:  /subscriptions/<sub-id>/resourceGroups/<rg>/providers/Microsoft.MachineLearningServices/workspaces/<workspace>/computes/Alex-001-MLGPU
[Trace - 2023-04-27 15:50:22.912] Getting tree item for node id:  /subscriptions/<sub-id>/resourceGroups/<rg>/providers/Microsoft.MachineLearningServices/workspaces/<workspace>/computes/Sam-001-MLGPU
[Trace - 2023-04-27 15:50:27.893] Refreshing tree view at node id: /subscriptions/<sub-id>/resourceGroups/<rg>/providers/Microsoft.MachineLearningServices/workspaces/<workspace>/computes/computeInstances
[Trace - 2023-04-27 15:50:27.893] DefaultWorkspaceService.get called with arguments: []
[Trace - 2023-04-27 15:50:27.898] Getting tree item for node id:  /subscriptions/<sub-id>/resourceGroups/<rg>/providers/Microsoft.MachineLearningServices/workspaces/<workspace>/computes/computeInstances
[Debug - 2023-04-27 15:50:27.899] Ensuring Azure Machine Learning - Remote extension is installed
[Debug - 2023-04-27 15:50:27.899] Azure Machine Learning - Remote extension is already installed
[Debug - 2023-04-27 15:50:27.905] Attempting to activate the extension: Azure Machine Learning - Remote
[Trace - 2023-04-27 15:50:27.907] DefaultWorkspace.syncCache called with arguments: []
[Debug - 2023-04-27 15:50:28.157] Getting children for node id:  /subscriptions/<sub-id>/resourceGroups/<rg>/providers/Microsoft.MachineLearningServices/workspaces/<workspace>/computes/computeInstances
[Trace - 2023-04-27 15:50:28.184] AuthenticationService.promptLoginIfNecessary called with arguments: []
[Trace - 2023-04-27 15:50:28.188] Telemetry Event: authentication/needsLogin Measures: undefined Props: {
    "result": "false"
}
[Debug - 2023-04-27 15:50:28.192] Compute instance is passed.
[Trace - 2023-04-27 15:50:28.192] AuthenticationService.getUserObjectId called with arguments: [
    "<sub-id>"
]
[Trace - 2023-04-27 15:50:28.192] AuthenticationService.getAuthTokenResponse called with arguments: [
    "<sub-id>"
]
[Trace - 2023-04-27 15:50:28.192] AuthenticationService.getCredentials called with arguments: [
    "<sub-id>"
]
[Trace - 2023-04-27 15:50:28.192] AuthenticationService.promptLoginIfNecessary called with arguments: []
[Trace - 2023-04-27 15:50:28.211] Telemetry Event: authentication/needsLogin Measures: undefined Props: {
    "result": "false"
}
[Trace - 2023-04-27 15:50:28.216] AuthenticationService.getSubscriptionById called with arguments: [
    "<sub-id>"
]
[Trace - 2023-04-27 15:50:28.216] AuthenticationService.listSubscriptions called with arguments: []
[Trace - 2023-04-27 15:50:28.224] Telemetry Event: authentication/needsLogin Measures: undefined Props: {
    "result": "false"
}
[Error - 2023-04-27 15:50:28.874] Error: Decryption failed.
[Trace - 2023-04-27 15:50:28.878] Getting tree item for node id:  
[Debug - 2023-04-27 15:50:28.902] Prompting the user for feedback.
[Error - 2023-04-27 15:50:28.932] Error: Unable to parse decrypted password
[Info - 2023-04-27 15:50:29.753] Default workspace cache synchronized successfully.

**Comment by shsuman** [comment]
@jgtellez1 I think @alexweininger meant Azure Account logs :). These are Azure ML Logs :)

**Comment by jgtellez1** [comment]
@shsuman @alexweininger here are the Azure Account logs:
2023-04-28 15:22:51.468 [info] Attempting to reach URL https://login.microsoftonline.com/...
2023-04-28 15:22:54.544 [info] MSAL: [Fri, 28 Apr 2023 19:22:54 GMT] : @azure/msal-node@1.14.6 : Info - getTokenCache called
2023-04-28 15:22:55.399 [info] MSAL: [Fri, 28 Apr 2023 19:22:55 GMT] : [960bb6ae-6876-43e7-86aa-96e053c37d79] : @azure/msal-common@9.0.2 : Info - SilentFlowClient:acquireCachedToken - Cached access token is expired or will expire within 300 seconds.
2023-04-28 15:22:55.671 [info] MSAL: [Fri, 28 Apr 2023 19:22:55 GMT] : [5e2fb4d4-22d9-4fc4-9cd3-e7ca3b3419d2] : @azure/msal-common@9.0.2 : Info - SilentFlowClient:acquireCachedToken - Cached access token is expired or will expire within 300 seconds.
2023-04-28 15:22:55.712 [info] MSAL: [Fri, 28 Apr 2023 19:22:55 GMT] : [1b0e2509-feaa-4760-9c86-53ac608c6e95] : @azure/msal-common@9.0.2 : Info - SilentFlowClient:acquireCachedToken - Cached access token is expired or will expire within 300 seconds.
2023-04-28 15:22:57.445 [info] 
┌────── SubscriptionsClient Request GET https://management.azure.com/tenants?api-version=2020-01-01
    Proxy configuration:
    └ host: http://xxx.xxx.com
    └ password: "undefined"
    └ port: "8080"
    └ username: "undefined"
└───────────────────────────────────────────────────
2023-04-28 15:22:57.744 [info] [SubscriptionsClient Response] 200 - GET https://management.azure.com/tenants?api-version=2020-01-01
2023-04-28 15:23:10.120 [info] MSAL: [Fri, 28 Apr 2023 19:23:10 GMT] : [65dbd553-265e-4d0a-a4b7-5c588504e5d1] : @azure/msal-common@9.0.2 : Info - SilentFlowClient:acquireCachedToken - No access token found in cache for the given properties.
2023-04-28 15:23:15.862 [info] MSAL: [Fri, 28 Apr 2023 19:23:15 GMT] : [91e1ab78-209d-440f-929e-62c326e86faa] : @azure/msal-common@9.0.2 : Info - SilentFlowClient:acquireCachedToken - No access token found in cache for the given properties.
2023-04-28 15:33:23.187 [info] MSAL: [Fri, 28 Apr 2023 19:33:23 GMT] : [395eec07-97ab-462a-bf18-e4939a249eac] : @azure/msal-common@9.0.2 : Info - SilentFlowClient:acquireCachedToken - No access token found in cache for the given properties.
2023-04-28 15:33:27.822 [info] MSAL: [Fri, 28 Apr 2023 19:33:27 GMT] : [4fae9bf5-13c0-4160-950d-d35e36765dd2] : @azure/msal-common@9.0.2 : Info - SilentFlowClient:acquireCachedToken - No access token found in cache for the given properties.
2023-04-28 15:33:27.826 [info] MSAL: [Fri, 28 Apr 2023 19:33:27 GMT] : [1c6e23c5-6fca-46aa-a9b4-14ab66379520] : @azure/msal-common@9.0.2 : Info - SilentFlowClient:acquireCachedToken - No access token found in cache for the given properties.
2023-04-28 15:33:27.828 [info] MSAL: [Fri, 28 Apr 2023 19:33:27 GMT] : [7f654442-f293-4e7e-9ce3-b54424dd1ce9] : @azure/msal-common@9.0.2 : Info - SilentFlowClient:acquireCachedToken - No access token found in cache for the given properties.
2023-04-28 15:33:27.830 [info] MSAL: [Fri, 28 Apr 2023 19:33:27 GMT] : [48d3d394-079c-4237-a3a0-e502f3d8f245] : @azure/msal-common@9.0.2 : Info - SilentFlowClient:acquireCachedToken - No access token found in cache for the given properties.
2023-04-28 15:33:27.831 [info] MSAL: [Fri, 28 Apr 2023 19:33:27 GMT] : [1fb40059-5f89-42a3-bd51-65dcca093142] : @azure/msal-common@9.0.2 : Info - SilentFlowClient:acquireCachedToken - No access token found in cache for the given properties.
2023-04-28 15:33:27.833 [info] MSAL: [Fri, 28 Apr 2023 19:33:27 GMT] : [e826991e-db7e-4e33-882e-349efc99f5c0] : @azure/msal-common@9.0.2 : Info - SilentFlowClient:acquireCachedToken - No access token found in cache for the given properties.
2023-04-28 15:33:27.835 [info] MSAL: [Fri, 28 Apr 2023 19:33:27 GMT] : [235aa8a6-8960-444e-887c-eb4b42dbce7e] : @azure/msal-common@9.0.2 : Info - SilentFlowClient:acquireCachedToken - No access token found in cache for the given properties.
2023-04-28 15:33:28.193 [info] MSAL: [Fri, 28 Apr 2023 19:33:28 GMT] : [55c66e7f-cd1c-4dd3-b50f-4ff9fdb1f142] : @azure/msal-common@9.0.2 : Info - SilentFlowClient:acquireCachedToken - No access token found in cache for the given properties.
2023-04-28 15:33:28.251 [info] MSAL: [Fri, 28 Apr 2023 19:33:28 GMT] : [31f681ba-1baf-4437-b271-43fe7de72ab2] : @azure/msal-common@9.0.2 : Info - SilentFlowClient:acquireCachedToken - No access token found in cache for the given properties.
2023-04-28 15:33:30.994 [info] MSAL: [Fri, 28 Apr 2023 19:33:30 GMT] : [3e788f83-671a-4c1b-8ff3-079ef8bbea29] : @azure/msal-common@9.0.2 : Info - SilentFlowClient:acquireCachedToken - No access token found in cache for the given properties.
2023-04-28 15:33:31.032 [info] MSAL: [Fri, 28 Apr 2023 19:33:31 GMT] : [d334744a-72e6-4e20-a678-d15a2ccb4f7b] : @azure/msal-common@9.0.2 : Info - SilentFlowClient:acquireCachedToken - No access token found in cache for the given properties.
2023-04-28 15:33:31.803 [info] MSAL: [Fri, 28 Apr 2023 19:33:31 GMT] : [52c3646a-0d96-4aba-942c-dbd35e2734fe] : @azure/msal-common@9.0.2 : Info - SilentFlowClient:acquireCachedToken - No access token found in cache for the given properties.

**Comment by alexweininger** [comment]
The logs provided look like they were captured with the default log level "Info", can you collect the logs again and make sure you set the log level to "Trace"?
