### ISSUE TITLE
Unable to Azure Sign In

### ISSUE THREAD

**Issue by 308002184** [microsoft/vscode-azure-account#785]
Type: <b>Bug</b>

I'm behind a proxy. I set the env varibales to HTTP_PROXY=http://User:Password@proxy.com:port. Still unable to login

Extension version: 0.11.3
VS Code version: Code 1.77.3 (704ed70d4fd1c6bd6342c436f1ede30d1cff4710, 2023-04-12T09:16:02.548Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz (8 x 2611)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.69GB (2.75GB free)|
|Process Argv|--crash-reporter-id 9cb3c433-fecb-4280-b4db-cf7dccbb25c7|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
nodejswelcome1:30587005
282f8724:30602487
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
a9j8j154:30646983
vsctsb:30705553
azdwalk:30687957
pythonms35:30701012
pythonfmttext:30716742
pythonclientmv:30713943

```

</details>

**Comment by nturinski** [comment]
Proxies tend to cause a lot of issues with Azure sign-in with the extension. Our troubleshooting section in our wiki could provide help [Troubleshooting: Unable to sign in while using a proxy](https://github.com/microsoft/vscode-azure-account/wiki/Troubleshooting#unable-to-sign-in-while-using-a-proxy)

The latest release uses a new authentication redirect server, which is hosted on a new url. You may need to allow this url through your proxy.

New url: `https://vscode.dev/redirect`
Old url: `https://vscode-redirect.azurewebsites.net/`

You can also check the "Azure Account" output channel, we log the urls the extension attempts to reach during sign-in. This could help figure out why the proxy is causing issues.
![image](https://user-images.githubusercontent.com/12476526/178589922-01931b32-141b-40b2-8a70-df7d1e6ec9bf.png)
