### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by daddela** [microsoft/vscode-azure-account#789]
- Issue Type: `Performance`
- Extension Name: `azure-account`
- Extension Version: `0.11.3`
- OS Version: `Darwin arm64 22.4.0`
- VS Code version: `1.77.3`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`file:///var/folders/hz/wltj2dp525x89pcd7l_y_6kr0000gp/T/ms-vscode.azure-account-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by alexweininger** [comment]
Please attach the cpuprofile as instructed in the issue description.
