### ISSUE TITLE
Cannot sign in to resource with device code. login with any other method than device code not working.

### ISSUE THREAD

**Issue by odellus** [microsoft/vscode-azure-account#790]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azure-account.loginToCloud
Error type: Error
Error Message: Stopped authentication task.

Version: 0.11.3
OS: win32
OS Release: 10.0.22621
Product: Visual Studio Code
Product Version: 1.77.3
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:2:2432554extension.bundle.js:2:2432554
E.invoke extensionHostProcess.js:63:145
h.deliver extensionHostProcess.js:63:2121
n.fire extensionHostProcess.js:63:1729
R.cancel extensionHostProcess.js:63:7782
P.cancel extensionHostProcess.js:63:8196
D.$acceptProgressCanceled extensionHostProcess.js:98:46338
c.N extensionHostProcess.js:108:11655
c.M extensionHostProcess.js:108:11373
c.H extensionHostProcess.js:108:10454
c.G extensionHostProcess.js:108:9432
extensionHostProcess.js:108:8220extensionHostProcess.js:108:8220
E.invoke extensionHostProcess.js:63:145
h.deliver extensionHostProcess.js:63:2121
n.fire extensionHostProcess.js:63:1729
p.fire extensionHostProcess.js:72:14916
extensionHostProcess.js:124:16654extensionHostProcess.js:124:16654
E.invoke extensionHostProcess.js:63:145
h.deliver extensionHostProcess.js:63:2121
n.fire extensionHostProcess.js:63:1729
p.fire extensionHostProcess.js:72:14916
MessagePortMain.<anonymous> extensionHostProcess.js:124:14780
```

</details>

**Comment by alexweininger** [comment]
Are you behind a proxy of any kind? Proxies often cause issues with sign-in. See the [Unable to Sign In While Using a Proxy section of our wiki](https://github.com/microsoft/vscode-azure-account/wiki/Troubleshooting#unable-to-sign-in-while-using-a-proxy) for possible fixes.

Also, see the [Enable and View Logs](https://github.com/microsoft/vscode-azure-account/wiki/Enable-and-view-logs) section of the wiki for how to capture and share Azure Account extension logs.

**Comment by odellus** [comment]
It ended up working itself out. thank you Alex!
