### ISSUE TITLE
Have to click link in AzureML several times to get VS Code to work/connect to compute

### ISSUE THREAD

**Issue by johnNateLee** [microsoft/vscode-azure-account#791]
We have to click link in AzureML several times to get VS Code to work/connect to compute.  It is not signing us in on the first time.

The error we get is "Your vs code window must be reloaded to perform this action."

Additionally, every time we click the link to vs code from the compute it installs vs code (even if we have already used vs code/that compute before).

**Comment by alexweininger** [comment]
I think this issue is best suited for https://github.com/microsoft/vscode-tools-for-ai. Could you file this issue there instead?
