### ISSUE TITLE
cloudshell

### ISSUE THREAD

**Issue by AliRz90** [microsoft/vscode-azure-account#798]
Does this occur consistently? 
Repro steps:

1.
2.

Action: waitForSubscriptions
Error type: REQUEST_SEND_ERROR
Error Message: request to redacted:url failed, reason: getaddrinfo ENOTFOUND redacted:url

Version: 0.11.4
OS: darwin
OS Release: 22.4.0
Product: Visual Studio Code
Product Version: 1.78.0
Language: en

<details>
<summary>Call Stack</summary>

```
new RestError extension.bundle.js:2:65384
NodeFetchHttpClient.<anonymous> extension.bundle.js:2:46552
step extension.bundle.js:2:2353241
Object.throw extension.bundle.js:2:2353346
rejected extension.bundle.js:2:2352071
```

</details>

**Comment by alexweininger** [comment]
Please provide detailed steps to reproduce this issue.
