### ISSUE TITLE
Can't select target tenant at all

### ISSUE THREAD

**Issue by tobiaswi** [Microsoft/vscode-azure-account#80]
Hi,

there is no way for me to select what tenants' subscription i want to see/use at any point using the extension. This leads to me not being able to use depending extensions (storageaccount/cosmosdb/eventgrid). I searched other issues for solutions and the change log mentions an entry that I should be able to do this. The Developer console in vscode doesn't show any errors.
The subscription I want to access are customer tenant/subscriptions (CSP!).

The only choice that is presented to me is the single subscription associated to the tenant my AzureAD user originates from. I have access to multiple tenants, each with multiple subscriptions.
Logging in through the portal at "portal.azure.com/tenant.onmicrosoft.com" works just fine, as does the azure cli (az login -t tenant.onmicrosoft.com).
How do I select the tenant?

I can successfully login with device code auth. Strange is the fact that I have to do this as at all. I'm already logged in locally (azure cli, latest version). The ~/.azure/azureProfile,json is populated with correct tenants/subscriptions and there is a valid/not-expired token in ~/.azure/accessTokens.json. If memory serves me well i remember a point in time where the extension picked this up which lead to me being able to work with it.

Additional information:
Version: 1.25.1
Commit: 1dfc5e557209371715f655691b1235b6b26a06be
Date: 2018-07-11T15:40:20.190Z
Electron: 1.7.12
Chrome: 58.0.3029.110
Node.js: 7.9.0
V8: 5.8.283.38
Architecture: x64

extension version 0.4.2
Ubunut 18.04

**Comment by chrmarti** [comment]
Using the Azure CLI's session is tracked with #61. Having a way to specify a tenant is tracked as #58.

The extension tries to list all tenants, but maybe it doesn't see yours. Does the portal show your other tenants in the "Directory and Subscription" filter in the top right when you sign in without specifying a tenant?

**Comment by tobiaswi** [comment]
#58 sounds like my issue. want me to continue over there and try out your instructions?

No, it does not show other tenants when I sign in without specifying a tenant. Portal and CLI both don't see the tenants without explicit mentioning when I sign in "normal".

**Comment by chrmarti** [comment]
Yes, let's continue in #58. If you could give the instructions a try, that would be great.
