### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by omduragkar** [microsoft/vscode-azure-account#802]
Does this occur consistently? 
Repro steps:

1.
2.

Action: updateSubscriptionsAndTenants
Error type: ETIMEDOUT
Error Message: request to redacted:url failed, reason: connect ETIMEDOUT redacted:id

Version: 0.11.4
OS: win32
OS Release: 10.0.22621
Product: Visual Studio Code
Product Version: 1.78.1
Language: en

<details>
<summary>Call Stack</summary>

```
ClientRequest.<anonymous> extension.bundle.js:2:2840318
```

</details>

**Comment by alexweininger** [comment]
Are you behind a proxy of any kind? Proxies often cause issues with sign-in. See the [Unable to Sign In While Using a Proxy section of our wiki](https://github.com/microsoft/vscode-azure-account/wiki/Troubleshooting#unable-to-sign-in-while-using-a-proxy) for possible fixes.
