### ISSUE TITLE
Issue to connect Azure resources on VScode

### ISSUE THREAD

**Issue by MANakib** [microsoft/vscode-azure-account#812]
Does this occur consistently? 
Repro steps:

1.
2.

Action: waitForSubscriptions
Error type: ETIMEDOUT
Error Message: request to redacted:url failed, reason: read ETIMEDOUT

Version: 0.11.5
OS: darwin
OS Release: 22.5.0
Product: Visual Studio Code
Product Version: 1.78.2
Language: en

<details>
<summary>Call Stack</summary>

```
ClientRequest.<anonymous> extension.bundle.js:2:2859202
```

</details>

**Comment by alexweininger** [comment]
Please add detailed steps to reproduce the issue.

Are you behind a proxy of any kind? Proxies often cause issues with sign-in. See the [Unable to Sign In While Using a Proxy section of our wiki](https://github.com/microsoft/vscode-azure-account/wiki/Troubleshooting#unable-to-sign-in-while-using-a-proxy) for possible fixes.

Also, see the [Enable and View Logs](https://github.com/microsoft/vscode-azure-account/wiki/Enable-and-view-logs) section of the wiki for how to capture and share Azure Account extension logs.
