### ISSUE TITLE
Cannot sign into Azure Cloud Account from VSCode

### ISSUE THREAD

**Issue by apfwwt** [microsoft/vscode-azure-account#813]
I am able to successfully sign into Azure storage account through browser or Azure CLI, so I can verify that my account exists and it is valid. Anytime I try to login using command palette in VScode I get a warning saying I am offline.

![Screenshot 2023-05-25 at 2 26 34 PM](https://github.com/microsoft/vscode-azure-account/assets/97191746/8e7df506-f302-4564-bb0d-2e2ae75a9f8d)
to

Does this occur consistently? Yes
Repro steps:
1. Install Azure Functions extension
2. Open command Palette
3. Select Azure: Sign In option

Action: azure-account.loginToCloud
Error type: AzureLoginError
Error Message: Offline

Version: 0.11.5
OS: darwin
OS Release: 22.1.0
Product: Visual Studio Code
Product Version: 1.78.2
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:2:2542818
```
Logs:

2023-05-25 14:33:30.717 [info] Attempting to reach URL "https://login.microsoftonline.com/"...
2023-05-25 14:33:30.803 [error] certificate has expired

</details>

**Comment by alexweininger** [comment]
Are you behind a proxy of any kind? Proxies often cause issues with sign-in. See the [Unable to Sign In While Using a Proxy section of our wiki](https://github.com/microsoft/vscode-azure-account/wiki/Troubleshooting#unable-to-sign-in-while-using-a-proxy) for possible fixes.

Also, see the [Enable and View Logs](https://github.com/microsoft/vscode-azure-account/wiki/Enable-and-view-logs) section of the wiki for how to capture and share Azure Account extension logs.
