### ISSUE TITLE
Cannot list subscriptions

### ISSUE THREAD

**Issue by kmmcfaul62** [microsoft/vscode-azure-account#818]
- VS Code Version: 1.78.2
- Azure Account Extension Version: v0.11.5
- OS Version: Windows 10 Enterprise for Virtual Desktops 22H2

Does your account belong to more than one directory? (see your directories [here](https://aka.ms/AAevnvr)): 

Any other information about your Azure account that may be useful:

**Comment by kmmcfaul62** [comment]
Basic information
Name
ATECTraining
Tenant ID
3313776b-3891-426c-93ba-23c8cc81350a
Primary domain
ATECTraining.onmicrosoft.us
License
Azure AD Free
Users
1
Groups
1
Applications
0
Devices
0

**Comment by alexweininger** [comment]
Could you try the steps in the [Unable to List Subscriptions section of our wiki](https://github.com/microsoft/vscode-azure-account/wiki/Troubleshooting#unable-to-list-subscriptions) and see if they fix the issue?
