### ISSUE TITLE
just an update to confirm latest version makes no difference...sigh

### ISSUE THREAD

**Issue by lexusean** [microsoft/vscode-azure-account#824]
just an update to confirm latest version 0.11.0 makes no difference...sigh

- VS Code Version: 1.69.0
- Azure Account Extension Version: 0.11.0
- OS Version: Windows 10 Enterprise 19042.1766

Steps to Reproduce:

1. VS Code with 0.9.11 extension
2. Sign out of Azure Account
3. Upgrade extension to 0.11.0
4. `Sign in to Azure with Device Code` VS Code command

In VS Code Output window for Azure Account extension:
`Attempting to reach URL "https://login.microsoftonline.com/"...
Attempting to reach URL "https://login.microsoftonline.com/"...
Fri, 08 Jul 2022 09:16:53 GMT:883d31f8-d142-418a-9af9-30d869c28638 - OAuth2Client: ERROR: No response from the server
Stack:
Error: No response from the server
	at Logger.createError (c:\Users\******\.vscode\extensions\ms-vscode.azure-account-0.11.0\dist\extension.bundle.js:2:820398)
	at c:\Users\*******\.vscode\extensions\ms-vscode.azure-account-0.11.0\dist\extension.bundle.js:2:834933
	at processTicksAndRejections (node:internal/process/task_queues:96:5)
Error: No response from the server
Error: No response from the server
Acquiring user code failed`

Revert to trusty `0.9.11` version, Reload window and all is good again...

====================================================================

**For a while now even downgrading to 0.9.11 does not work. "token is invalid"**

_Originally posted by @anthonywhite in https://github.com/microsoft/vscode-azure-account/issues/447#issuecomment-1178765454_

**Comment by alexweininger** [comment]
Did you try on the latest version of the extension (0.11.5)? If you can try again this time with trace logs enabled, that would be a big help.

See the [Enable and View Logs](https://github.com/microsoft/vscode-azure-account/wiki/Enable-and-view-logs) section of the wiki for how to capture and share Azure Account extension logs.
