### ISSUE TITLE
Too many subscriptions listed, first is not mine

### ISSUE THREAD

**Issue by psegalen** [microsoft/vscode-azure-account#825]
Hi,
I use Azure VS Code extensions daily since 2021 and everything has been fine until last week when I noticed the Resources (Remote) panel of Azure VS Code section was showing 2 subscriptions instead of one, the problem is that the first one is not mine, I've never seen the name before and it is not linked to my Microsoft account:
![bug](https://gcdnb.pbrd.co/images/R6oFy9R7NyZi.png?o=1)
On the plus side: I can't even list the resources included in this new subscription (when I try to, the extension activity indicator just starts and never stops until I quit VS Code) so the fact that I certainly don't have any admin right on the subscription seems respected.
Nevertheless, it is quite disturbing and implies security concerns.
I'm available if you need any help with investigating this issue.

- VS Code Version:
Version: 1.76.2 (user setup)
Commit: ee2b180d582a7f601fa6ecfdad8d9fd269ab1884
Date: 2023-03-14T17:55:54.936Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Windows_NT x64 10.0.19045
Sandboxed: No
- Azure Account Extension Version: v0.11.5
- OS Version: Windows 10 Family 22H2

Are you connected to a proxy server? No

Steps to Reproduce:

1. Sign-in to my Azure Account in VS Code
2. Go to the Resources panel: it shows 2 subscriptions, I don't know anything about the first!

**Comment by alexweininger** [comment]
Are you able to view the unfamiliar subscription in the portal? 
<img width="313" alt="image" src="https://github.com/microsoft/vscode-azure-account/assets/12476526/de30149e-e2c3-4f77-9636-f07c8a99e73f">

**Comment by alexweininger** [comment]
@psegalen yeah that's really strange. Not much we can do from the extension side here since we're simply listing the subscriptions we fetch using the Azure API. Let us know if there is any resolution.

**Comment by psegalen** [comment]
Closing it since it seems I've been added to the subscription by mistake.
Thank you for your answers @alexweininger!
I had an answer from the admin, the issue is under investigation.
