### ISSUE TITLE
Unable to connect to Azure National Clouds from VS Code

### ISSUE THREAD

**Issue by jun-x** [Microsoft/vscode-azure-account#83]
Tried to connect to Azure Government Cloud from VS code and failed.  Azure Account extension version is 0.4.3

Request Id:  3ef35d94-2835-4dcc-8d98-6db54a370200 
 
Correlation Id:  e3e4cb76-4f69-455f-929c-e51502cdf038 

Timestamp:  2018-08-10T21:57:16Z 
 
Message:  AADSTS90023: Couldn't get valid user code.

**Comment by Phydeauxman** [comment]
Any update on this issue? I am sure it is because it is hard coded in the extension to go to Azure Commercial. Similar issue used to exist in Visual Studio until someone wrote the "Environment Switcher" which behind the scenes edits the ini file that controls the target Azure environment. The one drawback of the "Environment Switcher" is the it requires you to restart Visual Studio.

**Comment by yujhongmicrosoft** [comment]
This feature should be formally released sometime next week. 
In the meanwhile you can connect to Azure Government today by following the steps below:
So the new release of the azure account extension now has sovereign support!
However, it is under a hidekey. It will default to public Azure. 
What you need to do to enable sovereign support is edit the user settings.
1.	Navigate to the settings.json file under .vscode folder, or press <Ctrl , >from your VS Code window.
2.	Edit your User settings json file by adding “azure.environment” : <NAME OF ENVIRONMENT> 
a.	Please replace the <> tag above with one of the following environments:
                                                               i.      Azure US Government
                                                             ii.      Azure China
                                                           iii.      Azure Germany
                                                            iv.      Azure 
You must have the azure.environment value be a string, such as “Azure China”, as the json accepts the azure.environment parameter as a string type.
Please let me know if this works for you.

**Comment by jun-x** [comment]
It works by manually adding "azure.environment" in user settings file as described above. Thanks!

**Comment by chrmarti** [comment]
Available in 0.5.0. The setting is `azure.cloud` and there is a command `Sign In to Azure Cloud` that lets you pick from the list of clouds.

**Comment by MysticRyuujin** [comment]
So I have 0.5.1 and when I attempt to use "Sign In to Azure Cloud" that command doesn't appear to be valid. I only have "Azure: Sign In" in my command pallet?
