### ISSUE TITLE
azure

### ISSUE THREAD

**Issue by Haitham103** [microsoft/vscode-azure-account#830]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azure-account.selectTenant
Error type: Error
Error Message: Unable to write into user settings. Please open the user settings to correct errors/warnings in it and try again.

Version: 0.11.5
OS: win32
OS Release: 10.0.21996
Product: Visual Studio Code
Product Version: 1.80.0
Language: en

<details>
<summary>Call Stack</summary>

```
e.$hYb.y workbench.desktop.main.js:2271:45283
e.$hYb.o workbench.desktop.main.js:2271:42678
e.$hYb.n workbench.desktop.main.js:2271:42569
async Object.factory workbench.desktop.main.js:2271:42319
```

</details>

**Comment by alexweininger** [comment]
The error indicates that your settings file is not valid JSON. Please open the settings file and fix these errors and try again.

To do this, run the "Preferences: Open User Settings (JSON)" command from the command palette (`F1`).
