### ISSUE TITLE
Cannot sign into Azure

### ISSUE THREAD

**Issue by sidneymarie116** [microsoft/vscode-azure-account#831]
Type: <b>Bug</b>

Install Azure Tools extension 1.2.0
Try to sign into Azure
Visit login.microsoftonline.com
Says that login was successful
Still shows as not signed in

2023-07-13 15:44:18.088 [info] MSAL: [Thu, 13 Jul 2023 20:44:18 GMT] : @azure/msal-node@1.14.6 : Info - getTokenCache called
2023-07-13 15:44:25.623 [info] MSAL: [Thu, 13 Jul 2023 20:44:25 GMT] : @azure/msal-node@1.14.6 : Info - getTokenCache called
2023-07-13 15:44:25.630 [info] Attempting to reach URL "https://login.microsoftonline.com/"...
2023-07-13 15:44:29.170 [info] Attempting to reach URL "https://vscode.dev/redirect"...
2023-07-13 15:44:29.170 [info] Attempting to reach URL "https://login.microsoftonline.com/common/oauth2/authorize?response_type=code&client_id=aebc6443-996d-45c2-90f0-388ff96faa56&redirect_uri=https%3A%2F%2Fvscode.dev%2Fredirect&state=http%3A%2F%2F127.0.0.1%3A54640%2Fcallback?nonce=peENxWuy0NVbIq%2Bi%2FXjXLw%3D%3D&prompt=select_account"...
2023-07-13 15:44:32.767 [info] [Axios Request] POST https://login.microsoftonline.com/common/oauth2/token?api-version=1.0
2023-07-13 15:44:34.092 [error] Error: No response from the server
	at Logger.createError (c:\Users\senglis\.vscode\extensions\ms-vscode.azure-account-0.11.5\dist\extension.bundle.js:2:917183)
	at c:\Users\senglis\.vscode\extensions\ms-vscode.azure-account-0.11.5\dist\extension.bundle.js:2:930216
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
2023-07-13 15:44:34.094 [error] No response from the server

I have followed the steps listed under multiple GH issues for how to work with VS code + azure tools behind a corporate proxy and am still unable to make any progress

Extension version: 0.11.5
VS Code version: Code 1.80.1 (74f6148eb9ea00507ec113ec51c489d6ffb4b771, 2023-07-12T17:22:07.651Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i7-1265U (12 x 2688)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.69GB (19.06GB free)|
|Process Argv|--folder-uri file:///c%3A/Dev/azure-search-openai-demo-1 --crash-reporter-id 96e61a02-b523-4190-9d3e-6d649514aded|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263cf:30789497
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
vsccc:30610678
3biah626:30602489
pyind779:30671433
f6dab269:30613381
vscrp:30673768
pythonsymbol12:30671437
2i9eh265:30646982
showlangstatbar:30737416
vsctsb:30748421
pythonms35:30701012
03d35959:30757346
pythonfmttext:30731395
pythoncmvfstrcf:30756944
fixshowwlkth:30771522
showindicator:30785052
pythongtdpath:30769146
bgfeh915:30780428
pythonnosmt12:30779714
pythonidxpt:30784022
pythonnoceb:30776495
e537b577:30786199
dsvsc013:30789517

```

</details>

**Comment by alexweininger** [comment]
See the [Enable and View Logs](https://github.com/microsoft/vscode-azure-account/wiki/Enable-and-view-logs) section of the wiki for how to capture and share Azure Account extension logs. Make sure to do this with the log level set to TRACE.

You noted that you followed guidance in GH issues for dealing with proxy issues. Also see the [Unable to Sign In While Using a Proxy section of our wiki](https://github.com/microsoft/vscode-azure-account/wiki/Troubleshooting#unable-to-sign-in-while-using-a-proxy) for possible fixes.

**Comment by sidneymarie116** [comment]
[signintracelogs.txt](https://github.com/microsoft/vscode-azure-account/files/12050551/signintracelogs.txt)

Please see the logs attached. I have tried following the instructions detailed in the wiki, with no success

**Comment by sidneymarie116** [comment]
I was able to resolve this issue on my own. Seems that for our corporate proxy we needed to remove all explicit proxy variable settings (i.e. remove HTTP_PROXY and HTTPS_PROXY environment variables altogether. Running the Test Network Proxy extension was actually fairly helpful

Thank you

**Comment by wouldBeNerd** [comment]
I was able to log in by running bash from windows and using 'az login' command to log in to azure from the terminal, after doing that successfully my account information also appeared in my vscode azure extension. Not sure if that helps anyone.
