### ISSUE TITLE
TSL 1.2 issue, despite forcing TSL 1.2

### ISSUE THREAD

**Issue by screig** [microsoft/vscode-azure-account#832]
- VS Code Version: 1.80.1
- Azure Account Extension Version: v0.11.5
- OS Version: 

Are you connected to a proxy server? I believe so.

Steps to Reproduce:

1. Open VS code and click sign in
2. Take me to organisation page, and I sign in.

I get this error
![image](https://github.com/microsoft/vscode-azure-account/assets/4292074/c81cf58f-056f-4b3d-bb93-6dd8404c597a)

However I have run the script here to enforce tsl1.2

https://learn.microsoft.com/en-us/azure/active-directory/hybrid/connect/reference-connect-tls-enforcement

![image](https://github.com/microsoft/vscode-azure-account/assets/4292074/b55597d0-b191-4837-8ce6-b7f53410a22a)

restarted

I further downloaded and ran this script

https://github.com/microsoft/azure-devops-tls12

![image](https://github.com/microsoft/vscode-azure-account/assets/4292074/e4df8085-80b9-4a32-b022-ab8c5b03943e)

restarted

still I get this error

![image](https://github.com/microsoft/vscode-azure-account/assets/4292074/7781750a-51bc-4ca4-b58b-f9c7448bd2e3)
![image](https://github.com/microsoft/vscode-azure-account/assets/4292074/4dcdfbc1-ef15-4de6-bf60-df3b523adf4a)

quite frustrating

Version info

![image](https://github.com/microsoft/vscode-azure-account/assets/4292074/85e843fa-6307-4b6a-9627-01d84ceb8bcc)

**Comment by alexweininger** [comment]
Also, see the [Enable and View Logs](https://github.com/microsoft/vscode-azure-account/wiki/Enable-and-view-logs) section of the wiki for how to capture and share Azure Account extension logs. Please set the log level to Trace and share the logs here. Make sure to remove any personal information before sharing.
