### ISSUE TITLE
Azure VS Code Account Login Not Working

### ISSUE THREAD

**Issue by shashankpandey2012** [microsoft/vscode-azure-account#834]
1. On Trying to Login Azure Credentials in VS Code it gives this error

Action: azure-account.initialize
Error type: Error
Error Message: The username or passphrase you entered is not correct.

Version: 0.11.5
OS: darwin
OS Release: 18.7.0
Product: Visual Studio Code
Product Version: 1.80.0
Language: en

**Comment by alexweininger** [comment]
Are you still facing this issue?
