### ISSUE TITLE
Not able to select subscriotion after signing in

### ISSUE THREAD

**Issue by wahengbamnanda100** [microsoft/vscode-azure-account#837]
Does this occur consistently? 
Repro steps:

1.
2.

Action: updateSubscriptionsAndTenants
Error type: EADDRINUSE
Error Message: request to redacted:url failed, reason: connect EADDRINUSE redacted:id

Version: 0.11.5
OS: win32
OS Release: 10.0.22623
Product: Visual Studio Code
Product Version: 1.80.1
Language: en

<details>
<summary>Call Stack</summary>

```
ClientRequest.<anonymous> extension.bundle.js:2:2859202
```

</details>

**Comment by alexweininger** [comment]
Are you behind a proxy of any kind? Proxies often cause issues with sign-in. See the [Unable to Sign In While Using a Proxy section of our wiki](https://github.com/microsoft/vscode-azure-account/wiki/Troubleshooting#unable-to-sign-in-while-using-a-proxy) for possible fixes.

Are you behind a proxy of any kind? Proxies often cause issues with sign-in. See the [Unable to Sign In While Using a Proxy section of our wiki](https://github.com/microsoft/vscode-azure-account/wiki/Troubleshooting#unable-to-sign-in-while-using-a-proxy) for possible fixes.
