### ISSUE TITLE
Cannot list subscriptions 

### ISSUE THREAD

**Issue by awkward-abi** [microsoft/vscode-azure-account#840]
I have tried all the instructions but I still get this. Why?

I have sign in and out of my student ambassadors account multiple times. I installed all the necessary extensions on my  vscode but I still cant get to view the list of subscription for my student ambassadors account.

Someone please help.
![Screen Shot 2023-08-01 at 6 10 36 PM](https://github.com/microsoft/vscode-azure-account/assets/79824839/1813dd0f-32b5-42e2-bdea-22956fde1f1f)

**Comment by alexweininger** [comment]
Could you try the steps in the [Unable to List Subscriptions section of our wiki](https://github.com/microsoft/vscode-azure-account/wiki/Troubleshooting#unable-to-list-subscriptions) and see if they fix the issue?

Also, see the [Enable and View Logs](https://github.com/microsoft/vscode-azure-account/wiki/Enable-and-view-logs) section of the wiki for how to capture and share Azure Account extension logs.
