### ISSUE TITLE
 Azure vs code extension doesn't support directory changes 

### ISSUE THREAD

**Issue by Bahri-19** [microsoft/vscode-azure-account#842]
When accessing my azure account in the vs code extension, it is not possible to change the directory at all. I saw this question posted 5 years ago and the only solution was to clone this repo and alter a couple lines. That's not a good way tho

**Comment by alexweininger** [comment]
Hi, by changing directory are you referring to the tenant for your Azure account? If so you can use the "Azure: Select Tenant" command to switch tenants.
