### ISSUE TITLE
can't sign into azure from vscode

### ISSUE THREAD

**Issue by kl5429** [microsoft/vscode-azure-account#845]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azure-account.loginToCloud
Error type: AzureLoginError
Error Message: Offline

Version: 0.11.5
OS: win32
OS Release: 10.0.22000
Product: Visual Studio Code
Product Version: 1.80.0
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:2:2542818extension.bundle.js:2:2542818
```

</details>

**Comment by alexweininger** [comment]
Are you behind a proxy of any kind? Proxies often cause issues with sign-in. See the [Unable to Sign In While Using a Proxy section of our wiki](https://github.com/microsoft/vscode-azure-account/wiki/Troubleshooting#unable-to-sign-in-while-using-a-proxy) for possible fixes.

Also, see the [Enable and View Logs](https://github.com/microsoft/vscode-azure-account/wiki/Enable-and-view-logs) section of the wiki for how to capture and share Azure Account extension logs.
