### ISSUE TITLE
Migrate from AAD graph to MS graph

### ISSUE THREAD

**Issue by bwateratmsft** [microsoft/vscode-azure-account#849]
AAD graph (graph.windows.net) will be retired on or after 30 September without notice. Need to migrate to MS graph (graph.microsoft.com).

**Comment by bwateratmsft** [comment]
Perhaps we should just migrate cloud shell to the Azure Resources extension.

**Comment by alexweininger** [comment]
Cloud shell also needs to be migrated to MSAL. It currently only supports ADAL.
