### ISSUE TITLE
i have problems to setup my azure acc in to visual 

### ISSUE THREAD

**Issue by 0owner0** [microsoft/vscode-azure-account#852]
Does this occur consistently? 
Repro steps:

1.
2.

Version: 0.11.5
OS: win32
OS Release: 10.0.19045
Product: Visual Studio Code
Product Version: 1.81.1
Language: en

**Comment by alexweininger** [comment]
Please add detailed steps to reproduce the issue.

Are you behind a proxy of any kind? Proxies often cause issues with sign-in. See the [Unable to Sign In While Using a Proxy section of our wiki](https://github.com/microsoft/vscode-azure-account/wiki/Troubleshooting#unable-to-sign-in-while-using-a-proxy) for possible fixes.

Also, see the [Enable and View Logs](https://github.com/microsoft/vscode-azure-account/wiki/Enable-and-view-logs) section of the wiki for how to capture and share Azure Account extension logs.
