### ISSUE TITLE
Ability to Login Using a Device Code

### ISSUE THREAD

**Issue by ianmariano** [microsoft/vscode-azure-account#856]
With my work laptop I have a default browser that is opened when doing sign-in to Azure but it's not the browser that is used for the portal or for AZ CLI with --use-device-code due to some device management restrictions, plus the login password is changed daily. It would be nice to be able to have a setting for logging in using a device code.

**Comment by alexweininger** [comment]
You can sign in using a device code by running the "Azure: Sign In with Device Code" command from the command palette.
<img width="630" alt="image" src="https://github.com/microsoft/vscode-azure-account/assets/12476526/898df95b-ceb2-4667-ac7b-6305b57dbaa8">

Access the command palette with <kbd>F1</kbd>.
