### ISSUE TITLE
Azure Account Network requirement

### ISSUE THREAD

**Issue by yudai-yazawa** [microsoft/vscode-azure-account#857]
I'm trying to use VS Code on my corporate network.
I would like to check the communication requirements for Azure Account in order to pass through Firewall and Proxy. Could you please tell me?

**Comment by alexweininger** [comment]
See the [Using a Proxy section of our wiki](https://github.com/microsoft/vscode-azure-account/wiki/Troubleshooting#unable-to-sign-in-while-using-a-proxy) for more information. Allowing `login.microsoftonline.com` should do the trick.

Also, see the [Enable and View Logs](https://github.com/microsoft/vscode-azure-account/wiki/Enable-and-view-logs) section of the wiki for how to view Azure Account extension logs. Viewing the logs after setting the Log Level to Trace will show all the requests the extension is making.
