### ISSUE TITLE
Unable to login to Azure from Code

### ISSUE THREAD

**Issue by omartin2010** [Microsoft/vscode-azure-account#86]
Issue Type: <b>Bug</b>

When entering the code in aka.ms/devicelogin, I get authenticated on the browser and can't select the subscription afterwards.

Extension version: 0.4.3
VS Code version: Code - Insiders 1.27.0-insider (8727085fff33bf7d8f5e27483b10f72508d4167a, 2018-08-14T07:42:59.172Z)
OS version: Linux x64 4.4.0-17134-Microsoft

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: unavailable_software<br>checker_imaging: disabled_off<br>flash_3d: unavailable_software<br>flash_stage3d: unavailable_software<br>flash_stage3d_baseline: unavailable_software<br>gpu_compositing: unavailable_software<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled_readback<br>webgl2: unavailable_off|
|Load (avg)|1, 1, 1|
|Memory (System)|15.93GB (5.23GB free)|
|Process Argv|/usr/share/code-insiders/code-insiders|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by StephenWeatherford** [comment]
See https://github.com/Microsoft/vscode-azurestorage/issues/218 for more info.

**Comment by omartin2010** [comment]
I do see them, yes. I've got access to a few tenants/directories (4-5 I think) and a few subs per directories.

**Comment by omartin2010** [comment]
if you need help for a repro (on my laptop) ping me on Teams (omartin)

**Comment by Webmicke** [comment]
I am having this same issue.
After going through the process of copying in the code and signing in, the waiting for sign-in text disappears from the azure menu, and it returns to Sign-in or create new. I cannot select any subscriptions.
Trying to run Azure: Select Subscriptions command then tells me to sign in, which brings me into this endless loop of signing in and getting told to sign in.

Manjaro Linux x64 4.16.0-1
VS Code 1.27.1
Azure Account 0.4.3
