### ISSUE TITLE
VScode issue

### ISSUE THREAD

**Issue by AckeyGrahamKPMG** [microsoft/vscode-azure-account#863]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azure-account.selectTenant
Error type: Error
Error Message: Unable to write into user settings. Please open the user settings to correct errors/warnings in it and try again.

Version: 0.11.5
OS: win32
OS Release: 10.0.19044
Product: Visual Studio Code
Product Version: 1.82.2
Language: en

<details>
<summary>Call Stack</summary>

```
c.y workbench.desktop.main.js:2299:45428
c.o workbench.desktop.main.js:2299:42789
c.n workbench.desktop.main.js:2299:42680
async Object.factory workbench.desktop.main.js:2299:42430
```

</details>

**Comment by alexweininger** [comment]
The error indicates that your settings json file has a typo in it. Can you open up the file and check it? It could be your `.vscode/settings.json` file or your workspace/user settings.

**Comment by AckeyGrahamKPMG** [comment]
It was sorted, i was using an admin account to run VSCode, this was being aligned to the SSO of that account, which in turned didn't have access to my cloud environment.
