### ISSUE TITLE
Vscode con't connect Azure Cloud Shell

### ISSUE THREAD

**Issue by syuniGo** [microsoft/vscode-azure-account#864]
I can't connect to Azure Cloud Shell 

Azure Tools extension information is
Version v1.2.0
Published 2017-11-3, 09:04:06
Last released 2023-4-22, 06:20:06
Last updated 2023-10-1, 22:40:49
Identifier ms-vscode.vscode-node-azure-pack

Running in vscode-insider
Version: 1.82.2 (user setup)
Commit: abd2f3db4bdb28f9e95536dfa84d8479f1eb312d
Date: 2023-09-14T05:55:25.390Z
Electron: 25.8.1
ElectronBuildId: 23779380
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.22621

On my Pc
Edition	Windows 11 Pro
Version	22H2
Installed on	‎2023/‎9/‎17
OS build	22621.2361
Experience	Windows Feature Experience Pack 1000.22674.1000.0

Default Browser:
chrome Version: 117.0.5938.132

<img width="743" alt="image" src="https://github.com/microsoft/azcode/assets/88898226/f90434fe-f70a-42f9-ae2b-1f12af101496">

**Comment by alexweininger** [comment]
I can reproduce this and we're investigating it. Thanks for reporting it.

**Comment by alexweininger** [comment]
A fix for this issue has been released in [v0.11.6](https://github.com/microsoft/vscode-azure-account/releases/tag/v0.11.6).
