### ISSUE TITLE
Login by VSCode to Azure is not working

### ISSUE THREAD

**Issue by duezito** [microsoft/vscode-azure-account#869]
I´m using last version:

Version: 1.82.0 (user setup)
Commit: 8b617bd08fd9e3fc94d14adb8d358b56e3f72314
Date: 2023-09-06T22:07:07.438Z
Electron: 25.8.0
ElectronBuildId: 23503258
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.22621

When i try to login, the auth2 open and autenticate, but on VSCode keep to Sign in...

![image](https://github.com/microsoft/azcode/assets/33161901/cd8c811a-a234-4e90-a692-27c17bfc52d7)
![image](https://github.com/microsoft/azcode/assets/33161901/7727b52a-6e35-404b-aaf8-fbda24223f6b)

**Comment by alexweininger** [comment]
It seems like this issue is caused when something is cached in the browser. Closing and re-opening your browser, and VS Code can resolve the issue.

You can also try signing out of your account on the portal and then retrying.
