### ISSUE TITLE
500 error when trying to open Azure Cloud Shell in Visual Studio Code 

### ISSUE THREAD

**Issue by Improviser14** [microsoft/vscode-azure-account#870]
- VS Code Version: 1.28.0
- Azure Account Extension Version: 0.11.5
- OS Version: Ventura 13.4

Are you connected to a proxy server? Yes/No
No

Steps to Reproduce:

1. Install and enable Azure Login extension for Visual Studio Code
2. Login to Azure app -m "You have signed in to the Visual Studio Code application on your device. You may now close this window."
3. Click the + symbol in VS Code terminal to add Power Shell in Cloud Shell
4. Output =
 Requesting a Cloud Shell...
 Connecting terminal...
 Error: No referer header. (500)

**Comment by alexweininger** [comment]
We're aware of this bug and the fix has been merged. I'll be working on releasing it soon.

**Comment by alexweininger** [comment]
A fix for this issue has been released in [v0.11.6](https://github.com/microsoft/vscode-azure-account/releases/tag/v0.11.6).
