### ISSUE TITLE
"You must use multi-factor authentication to access" but there is no MFA step in interactive web page

### ISSUE THREAD

**Issue by tonyzep966** [microsoft/vscode-azure-account#874]
Does this occur consistently? 
Yes

Repro steps:

1. Run "Azure: Sign Out" command
2. Then Run "Azure: Sign In" command

Action: azure-account.loginToCloud
Error type: Error
Error Message: Get redacted:key returned http error: 400 and server response: {"error":"interaction_required","error_description":"AADSTS50076: Due to a configuration change made by your administrator, or because you moved to a new location, you must use multi-factor authentication to access 'redacted:id'.\r\nTrace ID: redacted:id\r\nCorrelation ID: redacted:id\r\nTimestamp: redacted:id redacted:id26Z","error_codes":[redacted:id],"timestamp":"redacted:id redacted:id26Z","trace_id":"redacted:id","correlation_id":"redacted:id","error_uri":"redacted:url

Version: 0.11.6
OS: win32
OS Release: 10.0.19045
Product: Visual Studio Code
Product Version: 1.83.1
Language: en

<details>
<summary>Call Stack</summary>

```
Logger.createError extension.bundle.js:2:893444
extension.bundle.js:2:906329extension.bundle.js:2:906329
```

</details>

**Comment by coreyroth** [comment]
I have had the same issue for weeks.  Device code does work, but this issue seems persistent.

**Comment by tonyzep966** [comment]
> You may have better luck using the Sign In with Device Code command. Access it from the command palette. Try that and let me know if it works.
> 
> <img alt="image" width="617" src="https://user-images.githubusercontent.com/12476526/276662637-e4d65817-f2ca-4331-91be-492220d73a42.png">

Yes, it did work. Sorry for slow reply TT

**Comment by tonyzep966** [comment]
> You may have better luck using the Sign In with Device Code command. Access it from the command palette. Try that and let me know if it works.
> 
> <img alt="image" width="617" src="https://user-images.githubusercontent.com/12476526/276662637-e4d65817-f2ca-4331-91be-492220d73a42.png">

Yes, It did work. Sorry
