### ISSUE TITLE
VSCode does not retrieve the Azure subscription - blocker

### ISSUE THREAD

**Issue by Alexon2018** [microsoft/vscode-azure-account#878]
Does this occur consistently? YES
Repro steps:

1. Into Resources panel, sign in to Azure account
2. Browser opens, I am able to enter the sign-in details
3. Browser shows the message: ("You are signed in now and can close this page.")
4. But, nothing happens in VSCode ... still asking to sign in. It seems blocked into a loop asking re-start sign-in in to Azure.

Action: updateSubscriptionsAndTenants
Error type: REQUEST_SEND_ERROR
Error Message: request to redacted:url failed, reason: getaddrinfo ENOTFOUND redacted:url

Version: 0.11.6
OS: win32
OS Release: 10.0.22621
Product: Visual Studio Code
Product Version: 1.82.3
Language: en

<details>
<summary>Call Stack</summary>

```
new RestError extension.bundle.js:2:65384
NodeFetchHttpClient.<anonymous> extension.bundle.js:2:46552
step extension.bundle.js:2:2390802
Object.throw extension.bundle.js:2:2390907
rejected extension.bundle.js:2:2389632
```

</details>

**Comment by Alexon2018** [comment]
Trying to authenticate via CLI:

az login
A web browser has been opened at https://login.microsoftonline.com/organizations/oauth2/v2.0/authorize. Please continue the login in the web browser. If no web browser is available or if the web browser fails to open, use device code flow with `az login --use-device-code`.
<urllib3.connection.HTTPSConnection object at 0x04654880>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed

**Comment by Alexon2018** [comment]
Attempting to reach URL "https://login.microsoftonline.com/"...
Attempting to reach URL "https://login.microsoftonline.com/"...
Attempting to reach URL "https://vscode.dev/redirect"...
Attempting to reach URL "https://login.microsoftonline.com/common/oauth2/authorize?response_type=code&client_id=aebc6443-996d-45c2-90f0-388ff96faa56&redirect_uri=https%3A%2F%2Fvscode.dev%2Fredirect&state=http%3A%2F%2F127.0.0.1%3A54951%2Fcallback?nonce=zhcFht2S%2BU%2BpniXo94DeKg%3D%3D&prompt=select_account"...
invalid_grant: 500202 - [2023-10-22 16:30:26Z]: AADSTS500202: User account '{EmailHidden}' from external identity provider 'live.com' is not supported for API version '2.0'. Microsoft account pass-thru users and guests are not supported by the tenant-independent endpoint.
Trace ID: 58229a6c-8228-48d8-86f0-404cda835200
Correlation ID: e06e19ba-1182-4ed2-91fc-92febc910ce7
Timestamp: 2023-10-22 16:30:26Z - Correlation ID: e06e19ba-1182-4ed2-91fc-92febc910ce7 - Trace ID: 58229a6c-8228-48d8-86f0-404cda835200

**Comment by Alexon2018** [comment]
I have tried even from a different computer - same behavior.
It says all good in browser, but nothing goes back into the VS code applications, still waiting me to sign in.

@Azure team ... it looks like a P1.

**Comment by alexweininger** [comment]
What's selected for the "Azure: Authentication Library" setting?

<img width="818" alt="image" src="https://github.com/microsoft/vscode-azure-account/assets/12476526/75a69b45-1068-4ef5-909e-8277bf1565eb">

Please try changing the setting and try again.

Are you behind a proxy of any kind? Proxies often cause issues with sign-in. See the [Unable to Sign In While Using a Proxy section of our wiki](https://github.com/microsoft/vscode-azure-account/wiki/Troubleshooting#unable-to-sign-in-while-using-a-proxy) for possible fixes.

**Comment by Alexon2018** [comment]
Hello @alexweininger ,

I have already tried to change the ADAL/MSAL (seen that in one of the previous tickets) - still failing.
See the error with MSAL setup (as above):

2023-10-24 08:01:43.131 [error] invalid_grant: 500202 - [2023-10-24 05:01:43Z]: AADSTS500202: User account '{EmailHidden}' from external identity provider 'live.com' is not supported for API version '2.0'. Microsoft account pass-thru users and guests are not supported by the tenant-independent endpoint.
Trace ID: 10df62ff-0b3b-4d5c-9b0d-58c5607c0300
Correlation ID: 5a895e3d-51b2-4243-bd4d-ec543df1f3f7
Timestamp: 2023-10-24 05:01:43Z - Correlation ID: 5a895e3d-51b2-4243-bd4d-ec543df1f3f7 - Trace ID: 10df62ff-0b3b-4d5c-9b0d-58c5607c0300

There is no proxy on my side; I have tried from different machines, and it worked fine until THU last week.

I have also tried to sign in with IntelliJ, see error below:

Azure: Failed to login with (OAUTH2), no such host is known (management.azure.com).
Call Stack:
● Login with (OAUTH2)
● Sign in to Azure

Thanks

**Comment by alexweininger** [comment]
The error message indicates that you need to sign in against a specific tenant, and not against the common login endpoint. Can you try using the "Azure: Select Tenant" command to select a tenant, and then try again?

<img width="611" alt="image" src="https://github.com/microsoft/vscode-azure-account/assets/12476526/d8e88c90-8f40-4c21-ab3e-dae33f76870e">

**Comment by Alexon2018** [comment]
Already tried that ...

2023-10-25 21:28:28.235 [info] Error: request to https://management.azure.com/subscriptions?api-version=2016-06-01 failed, reason: getaddrinfo ENOTFOUND management.azure.com

**Comment by alexweininger** [comment]
> Already tried that ...
> 
> 2023-10-25 21:28:28.235 [info] Error: request to https://management.azure.com/subscriptions?api-version=2016-06-01 failed, reason: getaddrinfo ENOTFOUND management.azure.com

That error indicates that there is a networking configuration issue. If our client cannot reach management.azure.com, then it won't work. Could you download and use the Network Proxy Test extension to maybe diagnose any networking issues? https://marketplace.visualstudio.com/items?itemName=chrmarti.network-proxy-test

**Comment by Alexon2018** [comment]
Network Proxy Test: Test Connection
-------------------------

VS Code 1.83.1 (...)
Network Proxy Test 0.0.8
win32 10.0.22621 x64

Settings:
- http.proxy: 
- http.proxyAuthorization: null
- http.proxyStrictSSL: true
- http.proxySupport: override
- http.systemCertificates: true

Environment variables:

Sending GET request to https://portal.azure.com...
Received response:
- Status: 200 OK
...
...
...

**Comment by Alexon2018** [comment]
I have tried on 3 different machines, and 2 different Internet providers - same behavior. So, I have doubts it's a networking issue at this end.

**Comment by alexweininger** [comment]
Ok, my last suggestion is to try our new authentication experience that we're working on. You can follow the instructions in this issue for how to install and use it: https://github.com/microsoft/vscode-azureresourcegroups/issues/738.

**Comment by Alexon2018** [comment]
Error running command azureResourceGroups.refreshTree: command 'azureResourceGroups.refreshTree' not found. This is likely caused by the extension that contributes azureResourceGroups.refreshTree.

I cannot see any resource in the left panel, so cannot progress to sign in steps.

Can you escalate this case, please?

**Comment by alexweininger** [comment]
That error indicates the dev build wasn't installed properly. Did you make sure to reload the VS Code window after installation?

**Comment by Alexon2018** [comment]
![image](https://github.com/microsoft/vscode-azure-account/assets/34911787/d4c6d193-9d26-4aba-8427-cc7375277496)

still getting errors ... see snapshot attached

**Comment by Alexon2018** [comment]
Any news here? Can anyone escalate this issue, please?

**Comment by nturinski** [comment]
I installed the linked vsix with my WIndows machine and can confirm that the vsix seems to work fine. There may be something wrong with your VS Code installation? 

I'd recommend either completely deleting and re-installing the extension or maybe completely uninstall and reinstall VS Code?

Version: 0.25.1
OS: win32
OS Release: 10.0.22621
Product: Visual Studio Code - Insiders
Product Version: 1.83.0-insider
Language: en

**Comment by Alexon2018** [comment]
ok, I have:

uninstalled the VSCode
deleted: Code from %appdata%
deleted: .vscode from %USERPROFILE%

reinstalled VSCodeUserSetup-x64-1.83.1.exe
added latest Account extension, and Functions extension
tried to sign in, browser opens, all good there
... but it does not return anything back into vscode (same behavior as mentioned above)

next I have installed the extension from VSI archive, as suggested AlexW earlier
... still the same error as the one mentioned above

so ... can you have a look now on my user, and see what is being blocked since ~19 Oct and where,
on the flow from a browser successful authentication back to VSCode? what has been changed, redeployed on your components on this flow?

**Comment by Alexon2018** [comment]
so ... after being blocked for two weeks by this case, 
I have finally seen it working again, after doing the following:

1. Provisioned a new VM instance on Azure
2. Installed latest VSCode and extensions
3. Used Edge as default browser for authentication
4. Configured tenant into Account settings extension

... such a terrible experience !

**Comment by nturinski** [comment]
Sorry that you were blocked for two weeks, but glad that you were able to get it working.
