### ISSUE TITLE
I can't login to my azure from Visual Studio Code

### ISSUE THREAD

**Issue by zitaharry** [microsoft/vscode-azure-account#879]
Does this occur consistently? 
Repro steps:

1.
2.

Version: 0.11.6
OS: win32
OS Release: 10.0.22635
Product: Visual Studio Code - Insiders
Product Version: 1.84.0-insider
Language: en

**Comment by alexweininger** [comment]
Are you behind a proxy of any kind? Proxies often cause issues with sign-in. See the [Unable to Sign In While Using a Proxy section of our wiki](https://github.com/microsoft/vscode-azure-account/wiki/Troubleshooting#unable-to-sign-in-while-using-a-proxy) for possible fixes.

Also, see the [Enable and View Logs](https://github.com/microsoft/vscode-azure-account/wiki/Enable-and-view-logs) section of the wiki for how to capture and share Azure Account extension logs.
