### ISSUE TITLE
Device login failed when trying to connect to Azure China

### ISSUE THREAD

**Issue by lirenhe** [Microsoft/vscode-azure-account#88]
Repro step:
1. add user setting of  "azure.environment": "Azure China"
2. call Azure login and go to the device login page.
3 Enter username/password but got the following error
![capture](https://user-images.githubusercontent.com/9100546/44576467-2ac3e800-a77e-11e8-9e76-92aeee9bd0bb.PNG)

It looks the client id of vscode-azure-account 'aebc6443-996d-45c2-90f0-388ff96faa56' is not registered into Azure China.

**Comment by yujhongmicrosoft** [comment]
Just repro-ed the issue. @chrmarti we can sync up offline on this.

**Comment by lirenhe** [comment]
Is there any update on this issue?

**Comment by chrmarti** [comment]
@lirenhe Not really. There is slow progress on the paperwork for this.

**Comment by chrmarti** [comment]
Fixing with #83.
