### ISSUE TITLE
Azure just not loading. stuck in Pay-As-You-Go menu - one time everything worked as expected, then stopped working.

### ISSUE THREAD

**Issue by ArunEdathadan** [microsoft/vscode-azure-account#880]
It worked once, but later stop working.

![image](https://github.com/microsoft/azcode/assets/16814342/559bb13b-f612-4273-b4fb-dc74189a7e66)

Version: 1.82.2 (system setup)
Commit: abd2f3db4bdb28f9e95536dfa84d8479f1eb312d
Date: 2023-09-14T05:55:25.390Z
Electron: 25.8.1
ElectronBuildId: 23779380
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.19045

**Comment by alexweininger** [comment]
@ArunEdathadan are you still facing this issue? 

Are you behind a proxy of any kind? Proxies often cause issues with sign-in. See the [Unable to Sign In While Using a Proxy section of our wiki](https://github.com/microsoft/vscode-azure-account/wiki/Troubleshooting#unable-to-sign-in-while-using-a-proxy) for possible fixes.

Also, see the [Enable and View Logs](https://github.com/microsoft/vscode-azure-account/wiki/Enable-and-view-logs) section of the wiki for how to capture and share Azure Account extension logs.
