### ISSUE TITLE
Cannot sign in while using proxy

### ISSUE THREAD

**Issue by pentambhavana** [microsoft/vscode-azure-account#882]
- VS Code Version:
- Azure Account Extension Version:
- OS Version:

Are you connected to a proxy server? Yes/No

Steps to Reproduce:

1.i am unable to get my azure account , i m unable to link it kindly help me out
2.

**Comment by alexweininger** [comment]
Are you behind a proxy of any kind? Proxies often cause issues with sign-in. See the [Unable to Sign In While Using a Proxy section of our wiki](https://github.com/microsoft/vscode-azure-account/wiki/Troubleshooting#unable-to-sign-in-while-using-a-proxy) for possible fixes.

Also, see the [Enable and View Logs](https://github.com/microsoft/vscode-azure-account/wiki/Enable-and-view-logs) section of the wiki for how to capture and share Azure Account extension logs.
