### ISSUE TITLE
"Your sign-in was successful but your admin requires the device requesting access to be managed by Microsoft to access this resource" error in Cloud VDI

### ISSUE THREAD

**Issue by Poitt1** [microsoft/vscode-azure-account#883]
(1) az login
Is blocked with below message:
Help us keep your device secure
Your sign-in was successful but your admin requires the device requesting access to be managed by Microsoft to access this resource.

(2) az login --use-device-code
Is blocked with below message:
Help us keep your device secure
Your sign-in was successful but your admin requires the device requesting access to be managed by Microsoft to access this resource.

- VS Code Version: 1.83.1
- Azure Account Extension Version: 0.11.6
- OS Version:

Are you connected to a proxy server? Yes
Checked Network Proxy Test extension and here's the result
Settings:
- http.proxy: 
- http.proxyAuthorization: null
- http.proxyStrictSSL: true
- http.proxySupport: override
- http.systemCertificates: true

Environment variables:

Sending GET request to https://login.microsoftonline.com...
Received response:
- Status: 302 Found
- Location: https://www.office.com/login#
Certificate chain:
- Subject: stamp2.login.microsoftonline.com (Microsoft Corporation)
  Subject alt: DNS:stamp2.login.microsoftonline.com, DNS:login.microsoftonline-int.com, DNS:login.microsoftonline-p.com, DNS:login.microsoftonline.com, DNS:login2.microsoftonline-int.com, DNS:login2.microsoftonline.com, DNS:loginex.microsoftonline-int.com, DNS:loginex.microsoftonline.com, DNS:stamp2.login.microsoftonline-int.com
  Validity: Aug 30 00:00:00 2023 GMT - Aug 30 23:59:59 2024 GMT
  Fingerprint: 03:48:74:D8:40:3A:41:BE:58:51:B6:D1:3A:6D:DB:E6:19:0B:29:A5
- Subject: DigiCert SHA2 Secure Server CA (DigiCert Inc)
  Validity: Sep 23 00:00:00 2020 GMT - Sep 22 23:59:59 2030 GMT
  Fingerprint: 62:6D:44:E7:04:D1:CE:AB:E3:BF:0D:53:39:74:64:AC:80:80:14:2C
- Subject: DigiCert Global Root CA (DigiCert Inc)
  Validity: Nov 10 00:00:00 2006 GMT - Nov 10 00:00:00 2031 GMT
  Fingerprint: A8:98:5D:3A:65:E5:E5:C4:B2:D7:D6:6D:40:C6:DD:2F:B1:9C:54:36
  Self-signed
Local root certificates:
- Subject: C=US O=DigiCert Inc OU=www.digicert.com CN=DigiCert Global Root CA
  Validity: Nov 10 00:00:00 2006 GMT - Nov 10 00:00:00 2031 GMT
  Fingerprint: A8:98:5D:3A:65:E5:E5:C4:B2:D7:D6:6D:40:C6:DD:2F:B1:9C:54:36
  Issuer: C=US O=DigiCert Inc OU=www.digicert.com CN=DigiCert Global Root CA

Steps to Reproduce:

1. Sign-in to Cloud VDI Virtual machine (which is Hybrid Azure AD joined - appears Compliant in Intune)
2. Open VS Code application
3. Install Azure Account extension
4. Sign-in to Azure using the above extension
5. Enter the sign-in code in Edge -> enter the account in UPN format -> enter the password
6. Get the following message:
"Help us keep your device secure
Your sign-in was successful but your admin requires the device requesting access to be managed by Microsoft to access this resource."

We had an internal discussion of this issue with our architecture team and they advised that the app\extension is not MSAL-aware:
"Kindly be informed that HAADJ status of a device cannot be seen from the Azure AD side. This status is being granted to a device at a time when a user account sign-on happens. During this sign-on activity, a background job is being done to confirm that both device and user account satisfy HAADJ requirements. For example, if a signed-in account is not properly licensed, then the device won't get the HAADJ status while it can be granted to the same device when another account is signed on if it is properly licensed. 

Anyway, most probably, the issue you're facing is related to the fact that the client app is not MSAL-aware. On the screenshot #6 (Device Info), you see that the device wasn't identified as HAADJ, Compliant, or managed. Usually, it happens, because a client app which triggered such authentication doesn't pass a Primary Refresh Token cached on the device. Inability to work with PRT happens, because the client doesn't use MSAL library for authentication. Such issues should be reported to the Vendor of the client app. In this case I see it's a Visual Studio Code app. So, you can report this to Microsoft."

So, the main question is - is the extension is MSAL-aware or not?

**Comment by Poitt1** [comment]
Our main question is - is the extension is MSAL-aware or not?

**Comment by jinglouMSFT** [comment]
The extension does support MSAL but it defaults to ADAL.  Have you tried to use MSAL via the Azure: Authentication Library setting?  Under Files->Preferences->Settings, search for "Azure: Authentication Library", change it to MSAL.

**Comment by Poitt1** [comment]
Yes, thank you very much for this advice - this resolved our issue, and sorry for bothering you, especially if this information was already written somewhere in the Knowledge Base article
