### ISSUE TITLE
not able to use VScode to push azure function to azure.

### ISSUE THREAD

**Issue by rakesh-silswal** [microsoft/vscode-azure-account#884]
Does this occur consistently? 
Repro steps:

1.
2.

Action: updateSubscriptionsAndTenants
Error type: FetchError
Error Message: request to redacted:url failed, reason: Failed to establish a socket connection to proxies: ["PROXY redacted:id"]

Version: 0.11.6
OS: win32
OS Release: 10.0.19044
Product: Visual Studio Code
Product Version: 1.83.1
Language: en

<details>
<summary>Call Stack</summary>

```
ClientRequest.<anonymous> extension.bundle.js:2:2820316
```

</details>

**Comment by alexweininger** [comment]
Are you behind a proxy of any kind? Proxies often cause issues with sign-in. See the [Unable to Sign In While Using a Proxy section of our wiki](https://github.com/microsoft/vscode-azure-account/wiki/Troubleshooting#unable-to-sign-in-while-using-a-proxy) for possible fixes.

Also, see the [Enable and View Logs](https://github.com/microsoft/vscode-azure-account/wiki/Enable-and-view-logs) section of the wiki for how to capture and share Azure Account extension logs.
