### ISSUE TITLE
Can't sign to azure through VS Code REQUEST_SEND_ERROR

### ISSUE THREAD

**Issue by mannybuildstech** [microsoft/vscode-azure-account#885]
Does this occur consistently? YES
Repro steps:
1. Use command palette to sign in to Azure
2. Enter your azure credentials in the browser window
3. Close browser or switch back to VSCode
4. Bottom right corner displays the error below and you can't continue

Action: updateSubscriptionsAndTenants
Error type: REQUEST_SEND_ERROR
Error Message: request to redacted:url failed, reason: getaddrinfo ENOTFOUND redacted:url

Version: 0.11.6
OS: win32
OS Release: 10.0.22621
Product: Visual Studio Code
Product Version: 1.83.1
Language: en

<details>
<summary>Call Stack</summary>

```
new RestError extension.bundle.js:2:65384
NodeFetchHttpClient.<anonymous> extension.bundle.js:2:46552
step extension.bundle.js:2:2390802
Object.throw extension.bundle.js:2:2390907
rejected extension.bundle.js:2:2389632
```

</details>

**Comment by alexweininger** [comment]
Are you behind a proxy of any kind? Proxies often cause issues with sign-in. See the [Unable to Sign In While Using a Proxy section of our wiki](https://github.com/microsoft/vscode-azure-account/wiki/Troubleshooting#unable-to-sign-in-while-using-a-proxy) for possible fixes.

Also, see the [Enable and View Logs](https://github.com/microsoft/vscode-azure-account/wiki/Enable-and-view-logs) section of the wiki for how to capture and share Azure Account extension logs. If you can capture the trace or debug logs and share them, that will help us the most.

**Comment by mannybuildstech** [comment]
Hey @alexweininger , adding the proxy environment variable did the trick!
Thanks a lot.

**Comment by mannybuildstech** [comment]
Unfortunately it got me past the initial step, but then i try to create an azure function and now thats failing with similar errors

**Comment by alexweininger** [comment]
Hi, we just released v0.8.0 of the Azure Resources extension which fixes a lot of issues related to proxies and sign in. Update and try it again and see if that works. 

https://github.com/microsoft/vscode-azureresourcegroups/releases/tag/v0.8.0

**Comment by mannybuildstech** [comment]
YES!!! thank you so much!
it works now

**Comment by alexweininger** [comment]
> YES!!! thank you so much! it works now

That is great news, thanks!
