### ISSUE TITLE
Azure: Sign In - Unable to get local issuer certificate

### ISSUE THREAD

**Issue by LeeMotley** [Microsoft/vscode-azure-account#89]
When I select the Azure: Sign In command nothing happens and I receive the following errors in the Developer Tools console:

![image](https://user-images.githubusercontent.com/1306610/44860372-ef3d8800-ac6d-11e8-9ed6-ca6198ffea74.png)

I am also behind a proxy if that makes a difference, however I have the HTTP_PROXY and HTTPS_PROXY env variables set as follows:

HTTPS_PROXY=http://myProxy:8080
HTTP_PROXY=http://myProxy:8080

Versions:

VS Code version: 1.26.1
Azure Account extension: 0.4.3
Node: 8.9.3
Chrome: 61

**Comment by chrmarti** [comment]
Some users have reported success on Windows when using this extension: https://marketplace.visualstudio.com/items?itemName=ukoloff.win-ca

**Comment by LeeMotley** [comment]
I've tried installing win-ca, but still the same errors shown unfortunately.

**Comment by chrmarti** [comment]
Maybe the certificate chain is somehow broken. Not sure if the proxy should make a difference, but one way to investigate further is to (install and) run:
```
proxytunnel -p myProxy:8080 -d login.microsoftonline.com:443 -a 7000
```
And then in a new terminal:
```
openssl s_client -connect localhost:7000 -showcerts
```

I get the following (with and without a simple proxy):
[showcerts.txt](https://github.com/Microsoft/vscode-azure-account/files/2339513/showcerts.txt)
