### ISSUE TITLE
Am getting an extension error.

### ISSUE THREAD

**Issue by OkeyAmy** [microsoft/vscode-azure-account#892]
Does this occur consistently? 
Repro steps:

1.
2.

Action: updateSubscriptionsAndTenants
Error type: REQUEST_SEND_ERROR
Error Message: request to redacted:url failed, reason: getaddrinfo ENOTFOUND redacted:url

Version: 0.11.6
OS: win32
OS Release: 10.0.19045
Product: Visual Studio Code
Product Version: 1.84.2
Language: en

<details>
<summary>Call Stack</summary>

```
new RestError extension.bundle.js:2:65384
NodeFetchHttpClient.<anonymous> extension.bundle.js:2:46552
step extension.bundle.js:2:2390802
Object.throw extension.bundle.js:2:2390907
rejected extension.bundle.js:2:2389632
```

</details>

**Comment by nturinski** [comment]
Please provide repro steps.
