### ISSUE TITLE
error selecting subscription in Azure Tools

### ISSUE THREAD

**Issue by jarustech** [microsoft/vscode-azure-account#893]
Does this occur consistently? 
Repro steps:

1.
2.

Action: waitForSubscriptions
Error type: ENOMEM
Error Message: request to redacted:url failed, reason: connect ENOMEM redacted:id - Local (redacted:id)

Version: 0.11.6
OS: darwin
OS Release: 23.0.0
Product: Visual Studio Code
Product Version: 1.84.2
Language: en

<details>
<summary>Call Stack</summary>

```
ClientRequest.<anonymous> extension.bundle.js:2:2820316
```

</details>

**Comment by nturinski** [comment]
Please provide detailed information about the issue and provide repro steps.

If you're using a proxy, they tend to cause a lot of issues with Azure sign-in with the extension. Our troubleshooting section in our wiki could provide help [Troubleshooting: Unable to sign in while using a proxy](https://github.com/microsoft/vscode-azure-account/wiki/Troubleshooting#unable-to-sign-in-while-using-a-proxy)

The latest release uses a new authentication redirect server, which is hosted on a new url. You may need to allow this url through your proxy.

New url: `https://vscode.dev/redirect`
Old url: `https://vscode-redirect.azurewebsites.net/`

You can also check the "Azure Account" output channel, we log the urls the extension attempts to reach during sign-in. This could help figure out why the proxy is causing issues.
![image](https://user-images.githubusercontent.com/12476526/178589922-01931b32-141b-40b2-8a70-df7d1e6ec9bf.png)

**Comment by jarustech** [comment]
i restarted VS code and it is connecting now. so the problem is resolved.
thanks.
