### ISSUE TITLE
UNABLE TO LOUGOUT USING AZURE: SIGN OUT

### ISSUE THREAD

**Issue by hozefatankiwala** [microsoft/vscode-azure-account#899]
Does this occur consistently? 
Repro steps:

1.
2.

Version: 0.11.6
OS: darwin
OS Release: 21.6.0
Product: Visual Studio Code
Product Version: 1.84.2
Language: en

**Comment by nishantattrey07** [comment]
Have you got any solution for this?

**Comment by nturinski** [comment]
Closing as a duplicate of https://github.com/microsoft/vscode-azure-account/issues/901

Please refer to this https://github.com/microsoft/vscode-azure-account/issues/901#issuecomment-1830939576 to log out with the new auth provider that we are leveraging.
