### ISSUE TITLE
'Copy and Open' doesn't work on linux

### ISSUE THREAD

**Issue by EricJizbaMSFT** [Microsoft/vscode-azure-account#9]
Repro:
1. Run 'Azure Login'
1. Click 'Copy and Open' when prompted

Expected:
It opens the browser and I paste the code

Actual: It opens the browser, but nothing is pasted. The code was not copied to the clipboard and the prompt is gone so I can't copy the code manually.

Tested on Ubuntu 16.04. It sounds like the copy-paste package doesn't work if xclip is not installed on the OS by default https://github.com/xavi-/node-copy-paste/issues/56

**Comment by EricJizbaMSFT** [comment]
Supposedly Storage Explorer uses the [clipboard api](https://github.com/electron/electron/blob/master/docs/api/clipboard.md) exposed by Electron and it works on Linux. But I don't think VS Code exposes that for extensions to use?

**Comment by chrisdias** [comment]
@tyriar can you help?

**Comment by Tyriar** [comment]
I believe we don't expose the Electron clipboard API as community packages exist and we wanted to keep the API slim. Maybe we should if they're less reliable @jrieken?

**Comment by jrieken** [comment]
Yes that is correct - the API surface of copy&paste is quite huge
