### ISSUE TITLE
Cannot list subscriptions: Not able to see the subscription listed in Visual studio code

### ISSUE THREAD

**Issue by soumyajitaccenture** [microsoft/vscode-azure-account#902]
- VS Code Version: 1.84.2 (Universal)
- Azure Account Extension Version: v0.11.6
- OS Version: MacOS 14.0

Does your account belong to more than one directory? (see your directories [here](https://aka.ms/AAevnvr)): Yes

Any other information about your Azure account that may be useful:

**Comment by alexweininger** [comment]
Which extensions are you trying to use with Azure Account? Most Azure extensions have moved off of Azure Account for authentication, and moved to the built-in VS Code Microsoft authentication provider. The Azure Account extension will be deprecated soon. If you're able, uninstall the Azure Account extension.

If you can, try out the new command you can access from the Azure Resources view: <img alt="image" width="432" src="https://private-user-images.githubusercontent.com/12476526/338682216-a8f81504-50a8-4189-93aa-8f6a156cebd6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ5Mzc4ODcsIm5iZiI6MTcyNDkzNzU4NywicGF0aCI6Ii8xMjQ3NjUyNi8zMzg2ODIyMTYtYThmODE1MDQtNTBhOC00MTg5LTkzYWEtOGY2YTE1NmNlYmQ2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI5VDEzMTk0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTczNDA4NjI5MThlYzM0N2M0ZjJkNmE1ZTRmZjE3NDk1OWEzMWJhNmE3YWY0Y2Q2Y2QzMDllZjZlMzUxZDkxYTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.luaFR1l_67JlwxwH8ja7vUOD3-Z2WfB4e3oTTk5GiXg">

* [Read here for more info on the move from Azure Account](https://github.com/microsoft/vscode-azureresourcegroups/releases/tag/v0.8.0)
* And read here about the deprecation: https://github.com/microsoft/vscode-azure-account/issues/964
