### ISSUE TITLE
Cannot change tenant

### ISSUE THREAD

**Issue by 10gler** [microsoft/vscode-azure-account#909]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azure-account.selectTenant
Error type: Error
Error Message: Unable to write into user settings. Please open the user settings to correct errors/warnings in it and try again.

Version: 0.11.6
OS: win32
OS Release: 10.0.19045
Product: Visual Studio Code
Product Version: 1.85.1
Language: en

<details>
<summary>Call Stack</summary>

```
l.y workbench.desktop.main.js:2128:55124
l.o workbench.desktop.main.js:2128:52485
l.n workbench.desktop.main.js:2128:52376
async Object.factory workbench.desktop.main.js:2128:52126
```

</details>

**Comment by nturinski** [comment]
We use your user settings in order to change the tenant. Could you open the user settings and confirm that the JSON file isn't corrupt?

![image](https://github.com/microsoft/vscode-azure-account/assets/5290572/6aff63d6-e514-43f7-9833-da9676e23c62)
