### ISSUE TITLE
Consume token

### ISSUE THREAD

**Issue by arcotek-ltd** [Microsoft/vscode-azure-account#91]
Not an issue per se, more of a feature request / how to.

I am assuming (and it's a big assumption) that there is some sort of session cookie / token dropped to allow me to authenticate to Azure which survives PC reboots.

The extension lets me authenticated into Azure, but how do I / is there a way to consume the token for other requests where I need a `PSCredential` object. For example, lets say I would normally use `$Cred = Get-Credential`, which generates a prompt where I enter my details, saving to $cred that I can use in other cmdlets. 

As I am already authenticated, is there a way to store the authentication in a variable?

Is there any documentation on the API / system that this extension consumes?

Thanks

**Comment by chrmarti** [comment]
There is an API, but no documentation: https://github.com/Microsoft/vscode-azure-account/blob/master/src/azure-account.api.d.ts

If you make the Azure Account extension a dependency of your extension, you can access that API like (copy the above `.d.ts` to your extension's src folder):
```ts
import { ExtensionContext, extensions } from 'vscode';
import { AzureAccount } from './azure-account.api';

export function activate(context: ExtensionContext) {
	const azureAccount = extensions.getExtension<AzureAccount>('ms-vscode.azure-account')!.exports;
	// ...
}
```

The `AzureSession` objects have a `credentials` property that can be used with the Azure SDK for Node.js.

**Comment by chrmarti** [comment]
@fiveisprime Do you have any additional documentation?

**Comment by fiveisprime** [comment]
Nothing formal. We have a docs sprint coming up that we'll use to add some more detail on consuming this extension.
