### ISSUE TITLE
I am unable to select the subscription 

### ISSUE THREAD

**Issue by ZeeshanAdilButt** [microsoft/vscode-azure-account#911]
Does this occur consistently?  Yes 

I am unable to select the subscription despite installing and reinstalling extensions, logging out and logging back in, removing the extensions folder. but my azure extensions just doesn't show any subscription associated with my account

Version: 0.11.6
OS: win32
OS Release: 10.0.22621
Product: Visual Studio Code
Product Version: 1.85.1
Language: en

**Comment by alexweininger** [comment]
As of v0.8.0 of the Azure Resources extension, the Azure Account extension is no longer used for authentication. Read more about this change [here](https://github.com/microsoft/vscode-azureresourcegroups/releases/tag/v0.8.0).

Make sure you are using the "Azure: Select Subscriptions..." command, and not the "Azure: Select Subscriptions" command. The second one is contributed by the Azure Account extension which is no longer used by the Azure Resources extension.
<img width="613" alt="image" src="https://github.com/microsoft/azcode/assets/12476526/fefd3813-8750-4c5d-90b2-24e54587ea83">
