### ISSUE TITLE
Logged into Azure but cannot access subscription or resources

### ISSUE THREAD

**Issue by lee-40square** [microsoft/vscode-azure-account#916]
I am logged into Azure USGov but it keeps asking to choose a subscription but doesn't show my subscriptions so I can't select anything and therefore no resources are loaded. 

![Screenshot 2024-01-14 at 14 57 31 (2)](https://github.com/microsoft/vscode-azure-account/assets/683267/222903ce-324c-49ea-b07a-4088b8a44ce0)

However, if I click on the account (at the bottom) I can see and select the subscriptions:

![Screenshot 2024-01-14 at 14 57 54 (2)](https://github.com/microsoft/vscode-azure-account/assets/683267/ff60a314-69ca-432a-8425-a5882b788796)

No matter what I do, I simply cannot get the resources to load.

MacOS Sonoma 14.2.1 (23C71)
Visual Studio Code 1.85.1

**Comment by alexweininger** [comment]
As of v0.8.0 of the Azure Resources extension, the Azure Account extension is no longer used for authentication. Read more about this change [here](https://github.com/microsoft/vscode-azureresourcegroups/releases/tag/v0.8.0).

The account indicator at the bottom is from Azure Account and is no longer connected to the Azure Resource extension.

For Azure US Gov, make sure you follow the instructions on the [Azure Resources readme](https://github.com/microsoft/vscode-azureresourcegroups?tab=readme-ov-file#move-to-built-in-vs-code-authentication). Specifically about setting the `microsoft-sovereign-cloud.environment` setting.
