### ISSUE TITLE
why my azure quorum blockchain resource is not showing in vs code? Infact few of other are appering. 

### ISSUE THREAD

**Issue by MMSKHAN** [microsoft/vscode-azure-account#922]
Does this occur consistently? 
Repro steps:

1.
2.

Version: 0.11.6
OS: win32
OS Release: 10.0.19045
Product: Visual Studio Code
Product Version: 1.85.2
Language: en

**Comment by alexweininger** [comment]
Hi, I'm not sure what resource types you are referring to. Can you please clarify? Include screenshots if possible.
