### ISSUE TITLE
"Azure: Open Bash in Cloud Shell" seems to ignore proxy settings

### ISSUE THREAD

**Issue by aglees** [Microsoft/vscode-azure-account#93]
I'm able to login to Azure just fine from VSC, but am struggling with the "Azure: Open Bash in Cloud Shell". Getting the following in the terminal:

```
Requesting a Cloud Shell...
Connecting terminal...
Socket error: {"errno":"ETIMEDOUT","code":"ETIMEDOUT","syscall":"connect","address":"40.118.150.251","port":443}
Socket closed
```

Also seeing the following in netstat whilst VSC attempts to connect. I would expect that the connection would be to the defined proxy:

```
TCP    xxx.xxx.xxx.xxx:64518   40.118.150.251:https   SYN_SENT
TCP    xxx.xxx.xxx.xxx:64526   65.55.44.109:https     SYN_SENT
```

Could this be an issue of VSC ignoring the local proxy settings?

**Comment by chrmarti** [comment]
Do you have the `HTTP_PROXY` and `HTTPS_PROXY` environment variables set?

**Comment by aglees** [comment]
yes, both those environment variables are set.

**Comment by ejazr83** [comment]
I seem to be having the same issue as well. I have the HTTP and HTTPS proxy variables set and am behind a corporate proxy. Is there any other setting that I should look into to allow this to work?

Connecting terminal...
Socket error: {"errno":"ETIMEDOUT","code":"ETIMEDOUT","syscall":"connect","address":"23.101.22.128","port":443}
Socket closed

**Comment by chrmarti** [comment]
That should do it. Make sure the environment variables are set before you start VS Code and check they are there in the integrated terminal.

**Comment by ejazr83** [comment]
Just clarify, these are the` http.proxy` and `https.proxy` variables in the `settings.json` file right?

I have these configured and I can for example sign-in to Azure and access my subscriptions. Its only the bash shell part that doesn't seem to work with error above

**Comment by chrmarti** [comment]
`HTTP_PROXY` and `HTTPS_PROXY` are environment variables, not settings.

**Comment by ejazr83** [comment]
Thanks @chrmarti that worked!

For others who are trying to get this working

run this to set the "Environment variables" on your system

```
setx HTTP_PROXY <proxy>
setx HTTPS_PROX <proxy>
```

**Comment by shannuvijaya** [comment]
I have setup the variable in my command Line,Sill i am getting the issue. Any Thoughts please ?

![image](https://user-images.githubusercontent.com/28883096/121358856-d5efbd00-c92a-11eb-82af-fd4393cf6ddb.png)
