### ISSUE TITLE
azure-account.manageAccount

### ISSUE THREAD

**Issue by marreiro23** [microsoft/vscode-azure-account#931]
Does this occur consistently? 
Repro steps:

1.

Action: azure-account.manageAccount
Error type: Error
Error Message: Não é possível gravar nas configurações do usuário porque o arquivo tem alterações não salvas. Salve o arquivo de configurações do usuário primeiro e tente novamente.

Version: 0.11.6
OS: win32
OS Release: 10.0.26058
Product: Visual Studio Code
Product Version: 1.87.0
Language: pt-br

<details>
<summary>Call Stack</summary>

```
f.y workbench.desktop.main.js:2295:15834
f.E workbench.desktop.main.js:2295:18980
f.n workbench.desktop.main.js:2295:12947
Object.factory workbench.desktop.main.js:2295:12847
M.j workbench.desktop.main.js:148:17729
vscode-file:/workbench.desktop.main.js:148:17639
M.queue workbench.desktop.main.js:148:17578
f.writeConfiguration workbench.desktop.main.js:2295:12816
B.Hb workbench.desktop.main.js:2295:37624
async Object.ne [as settled] workbench.desktop.main.js:148:24000
async B.updateValue workbench.desktop.main.js:2295:25775
```

</details>

**Comment by nturinski** [comment]
Please provide repro steps and details about your issue.
