### ISSUE TITLE
I can't view my resources no matter what I do

### ISSUE THREAD

**Issue by rbarton124** [microsoft/vscode-azure-account#932]
Does this occur consistently? Yes
Repro steps:
1. I sign in and select my subscription and nothing happens no resources show up and so I can't deploy to my web app.

Version: 0.11.6
OS: win32
OS Release: 10.0.22621
Product: Visual Studio Code
Product Version: 1.87.0
Language: en

**Comment by nturinski** [comment]
@rbarton124 Sorry that you're dealing with this. 

Let me ask a few questions to help you with your issue.

- What command are you using to sign in? You should be using `azureResourceGroups.login`
![image](https://github.com/microsoft/vscode-azure-account/assets/5290572/c883c036-d60d-496e-83cb-e5f8aec0058e)

- What does your resources view look like? 
- Are you able to see any subscriptions?
