### ISSUE TITLE
Azure Automation extension issue

### ISSUE THREAD

**Issue by cloudmindsab** [microsoft/vscode-azure-account#934]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azure-account.selectSubscriptions
Error type: TypeError
Error Message: (v.get(...) || ["all"]).slice is not a function

Version: 0.11.6
OS: darwin
OS Release: 23.3.0
Product: Visual Studio Code
Product Version: 1.87.0
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:2:2525797
fulfilled extension.bundle.js:2:2525015
```

</details>

**Comment by alexweininger** [comment]
Hi @cloudmindsab, are you still facing this issue? Can you provide any additional details?
