### ISSUE TITLE
says I am offline, but I am online

### ISSUE THREAD

**Issue by vegardsangolt** [microsoft/vscode-azure-account#935]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azure-account.loginToCloud
Error type: AzureLoginError
Error Message: Offline

Version: 0.11.6
OS: win32
OS Release: 10.0.19045
Product: Visual Studio Code
Product Version: 1.87.0
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:2:2503924extension.bundle.js:2:2503924
```

</details>

**Comment by nturinski** [comment]
Can you please provide repro steps?
