### ISSUE TITLE
Azure Device Code Login in VS Code causing error - "Cannot read properties of undefined (reading 'userId')"

### ISSUE THREAD

**Issue by sreejithr** [microsoft/vscode-azure-account#939]
Does this occur consistently? Yes
Repro steps:
1. Press Ctrl + Shift + P in VS Code.
2. Pick "Azure: Sign In with Device Code" option.
3. You will see an error dialog in the bottom right of the screen with this error - `Cannot read properties of undefined (reading 'userId')`.

Action: azure-account.manageAccount
Error type: TypeError
Error Message: Cannot read properties of undefined (reading 'userId')

Version: 0.11.6
OS: win32
OS Release: 10.0.22631
Product: Visual Studio Code
Product Version: 1.87.2
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:2:2483498extension.bundle.js:2:2483498
extension.bundle.js:2:2482998extension.bundle.js:2:2482998
b extension.bundle.js:2:2482684
manageAccount extension.bundle.js:2:2483170
extension.bundle.js:2:438046extension.bundle.js:2:438046
extension.bundle.js:2:389407extension.bundle.js:2:389407
extension.bundle.js:2:388225extension.bundle.js:2:388225
b extension.bundle.js:2:387911
callWithTelemetryAndErrorHandling extension.bundle.js:2:389314
extension.bundle.js:2:437764extension.bundle.js:2:437764
extension.bundle.js:2:437300extension.bundle.js:2:437300
b extension.bundle.js:2:436986
extension.bundle.js:2:437575extension.bundle.js:2:437575
l.h extensionHostProcess.js:150:184839
l.$executeContributedCommand extensionHostProcess.js:150:185699
s.S extensionHostProcess.js:147:5519
s.Q extensionHostProcess.js:147:5285
s.M extensionHostProcess.js:147:4375
s.L extensionHostProcess.js:147:3454
w.value extensionHostProcess.js:147:2241
n.y extensionHostProcess.js:80:1902
n.fire extensionHostProcess.js:80:2119
r.fire extensionHostProcess.js:105:14091
w.value extensionHostProcess.js:173:8050
n.y extensionHostProcess.js:80:1902
n.fire extensionHostProcess.js:80:2119
r.fire extensionHostProcess.js:105:14091
MessagePortMain.<anonymous> extensionHostProcess.js:173:6330
```

</details>

**Comment by alexweininger** [comment]
Which extensions are you trying to use with Azure Account? Most Azure extensions have moved off of Azure Account for authentication, and moved to the built-in VS Code Microsoft authentication provider. The Azure Account extension will be deprecated soon. If you're able, uninstall the Azure Account extension.

If you can, try out the new command you can access from the Azure Resources view: <img alt="image" width="432" src="https://private-user-images.githubusercontent.com/12476526/338682216-a8f81504-50a8-4189-93aa-8f6a156cebd6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ5Mzc4ODcsIm5iZiI6MTcyNDkzNzU4NywicGF0aCI6Ii8xMjQ3NjUyNi8zMzg2ODIyMTYtYThmODE1MDQtNTBhOC00MTg5LTkzYWEtOGY2YTE1NmNlYmQ2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI5VDEzMTk0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTczNDA4NjI5MThlYzM0N2M0ZjJkNmE1ZTRmZjE3NDk1OWEzMWJhNmE3YWY0Y2Q2Y2QzMDllZjZlMzUxZDkxYTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.luaFR1l_67JlwxwH8ja7vUOD3-Z2WfB4e3oTTk5GiXg">

* [Read here for more info on the move from Azure Account](https://github.com/microsoft/vscode-azureresourcegroups/releases/tag/v0.8.0)
* And read here about the deprecation: https://github.com/microsoft/vscode-azure-account/issues/964
