### ISSUE TITLE
Attempting to reach URL "https://login.microsoftonline.com/" [error] certificate has expired

### ISSUE THREAD

**Issue by uahmad85** [microsoft/vscode-azure-account#945]
Does this occur consistently? Yes, ever since i have enabled githut autopilot extension 
Repro steps:

1. Enable gitHub autopilot extension
2. login to gitHub.
3. it works for a little bit but then it will start throwing this error. it wasted my three days. i spent first two days troubleshooting it, playing with https and certificate setting, then i end up removing all the extension and complete clean up of vscode from my laptop and reinstall it, that did the trick. However, i installed gitHub autopilot extension again and the issue resurfaced. it is extremely annoying and i cant do my job without vscode. please help!!!

Action: azure-account.loginToCloud
Error type: AzureLoginError
Error Message: Offline

Version: 0.11.6
OS: darwin
OS Release: 23.4.0
Product: Visual Studio Code
Product Version: 1.88.0
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:2:2503924
```

</details>

**Comment by alexweininger** [comment]
Hi @uahmad85, are you still facing this issue? Can you share which extensions you are trying to use alongside the Azure Account extension?

Most Azure extensions no longer use the Azure Account extension for authentication.
