### ISSUE TITLE
report

### ISSUE THREAD

**Issue by LLotme** [microsoft/vscode-azure-account#956]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azure-account.selectTenant
Error type: Error
Error Message: Unable to write into user settings. Please open the user settings to correct errors/warnings in it and try again.

Version: 0.11.6
OS: darwin
OS Release: 23.5.0
Product: Visual Studio Code
Product Version: 1.88.1
Language: en

<details>
<summary>Call Stack</summary>

```
p.y workbench.desktop.main.js:2237:15727
p.o workbench.desktop.main.js:2237:13088
p.n workbench.desktop.main.js:2237:12979
async Object.factory workbench.desktop.main.js:2237:12729
```

</details>

**Comment by alexweininger** [comment]
Please check your user settings file for any JSON formatting errors. You can access this file by running the "Preferences: Open User Settings (JSON)" command.
