### ISSUE TITLE
fix

### ISSUE THREAD

**Issue by alnaimi-github** [microsoft/vscode-azure-account#957]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azure-account.loginToCloud
Error type: AzureLoginError
Error Message: Acquiring user code failed

Version: 0.11.7
OS: win32
OS Release: 10.0.22631
Product: Visual Studio Code
Product Version: 1.88.1
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:2:2515553extension.bundle.js:2:2515553
extension.bundle.js:2:907970extension.bundle.js:2:907970
```

</details>

**Comment by alexweininger** [comment]
Please add repro steps.

**Comment by alnaimi-github** [comment]
> This issue has been closed automatically because it needs more information and has not had recent activity. See also our [issue reporting](https://aka.ms/azcodeissuereporting) guidelines.
> 
> Happy Coding!



> Please add repro steps.

where
