### ISSUE TITLE
Add "Run Active File In Active Cloud Shell" command

### ISSUE THREAD

**Issue by Ayanmullick** [Microsoft/vscode-azure-account#96]
Currently, one cannot run Powershell script open in the VSC editor directly in the Azure Cloud Shell since both Cloud Shell and Powershell run in separate workspaces in VSC, this is why a ps1 script will try to open a Powershell terminal, it doesn’t see the Cloud Shell as a Powershell process.

The only option is to 'Run selected text' in the Cloud Shell terminal. This limitation shouldn't be there. Please enhance the extension to get rid of this limitation.

**Comment by chrmarti** [comment]
Moving this to the Powershell extension because the relevant code is there.

**Comment by chrmarti** [comment]
There is an "Upload to Cloud Shell" command with which you can upload the file and you can then start it manually in the Cloud Shell.

I will keep this as a feature request to have a command to automate this. Similar to "Run Active File In Active Terminal", but for the Cloud Shell.

**Comment by Ayanmullick** [comment]
Is there a tentative timescale for ETA? weeks, months or quarters?

**Comment by Ayanmullick** [comment]
> Upload to Cloud Shell

If we load the SHIPS module on PowerShell ISE we don't need to upload a file to the Cloud Shell container to run it in the Cloud Shell. We shouldn't have to upload anything for VSC either.

Is there a tentative timescale for ETA? weeks, months or quarters?

**Comment by chrmarti** [comment]
@Ayanmullick There is no ETA at the moment.

**Comment by chrmarti** [comment]
How does this work in ISE? Is this opening a remote session and you can then send files through that?

**Comment by Ayanmullick** [comment]
`Install-Module AzurePSDrive,SHiPS`
`Import-Module AzurePSDrive`
`New-PSDrive -Name Azure -PSProvider SHiPS -root 'AzurePSDrive#Azure'`
`Set-Location Azure:`

The above code runs the Cloud Shell in ISE on the same terminal and one doesn't need to upload files to run code in the Cloud Shell.

**Comment by chrmarti** [comment]
@Ayanmullick The Cloud Shell is a container running in the cloud, that might not be what you want. You can use SHiPS from a local terminal.

**Comment by Ayanmullick** [comment]
@chrmarti , Messaged on the 'Azure Cloud Shell Group' on 'Azure Advisors' on Yammer.

**Comment by chrmarti** [comment]
@Ayanmullick I might have missed your message. Is there anything left to do here?

**Comment by Ayanmullick** [comment]
No, the new PowerShell Preview solved this too. I can run "Azure:Open PowerShell in Cloud Shell' and run lines from the script pane on the active terminal running Cloud Shell.
