### ISSUE TITLE
azure-account.loginToCloud

### ISSUE THREAD

**Issue by singsum-gwam** [microsoft/vscode-azure-account#967]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azure-account.loginToCloud
Error type: Error
Error Message: No response from the server

Version: 0.12.0
OS: win32
OS Release: 10.0.22631
Product: Visual Studio Code
Product Version: 1.89.1
Language: en

<details>
<summary>Call Stack</summary>

```
Logger.createError extension.bundle.js:2:893444
extension.bundle.js:2:906477extension.bundle.js:2:906477
```

</details>

**Comment by nturinski** [comment]
Please provide detailed repro steps.
