### ISSUE TITLE
Cannot list subscriptions in VS code

### ISSUE THREAD

**Issue by neelamsoni26** [microsoft/vscode-azure-account#969]
- VS Code Version: 1.84.2
- Azure Account Extension Version: v0.11.6
- OS Version: Mac OS 14.5

Azure resources are not loading for particular subscription in VS code, the subscription is just keep loading. While other subscriptions are loading.

We have reinstall VS code and also azure extension but did not helped and also tried with lower and higher version 
We have also added the setting http.systemCertificates in VS code but did not help.
For one of the user it is taking hours of load the subscription resources [Around 6 hours].

why VS code is taking much time to load the azure resources for particular subscription

**Comment by alexweininger** [comment]
Hi @neelamsoni26, can you provide a screenshot of the issue? Also, please try updating VS Code to the latest version.
