### ISSUE TITLE
late activation for Azure account

### ISSUE THREAD

**Issue by VenkattaPidikiti** [Microsoft/vscode-azure-account#97]
- Extension Name: azure-account
- Extension Version: 0.4.3
- OS Version: Windows_NT x64 10.0.14393
- VSCode version: 1.28.0

 We have written the needed data into your clipboard. Please paste:```json 
{
	"activationTimes": {
		"startup": true,
		"codeLoadingTime": 138868,
		"activateCallTime": 670,
		"activateResolvedTime": 5364,
		"activationEvent": "*"
	}
}
```

**Comment by chrmarti** [comment]
Tracked with #87.
