### ISSUE TITLE
Not able to see the subscription in VS code

### ISSUE THREAD

**Issue by kulkarniew** [microsoft/vscode-azure-account#975]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azure-account.loginToCloud
Error type: ERR_HTTP_HEADERS_SENT
Error Message: Cannot write headers after they are sent to the client

Version: 0.12.0
OS: win32
OS Release: 10.0.22631
Product: Visual Studio Code
Product Version: 1.90.2
Language: en

<details>
<summary>Call Stack</summary>

```
AdalAuthProvider.<anonymous> extension.bundle.js:2:2494214
rejected extension.bundle.js:2:2491945
```

</details>

**Comment by alexweininger** [comment]
Hi, which extensions are you trying to use alongside Azure Account? As announced in https://github.com/microsoft/vscode-azure-account/issues/964, the Azure Accounts extension is being deprecated, and not many extensions still rely on it for authentication. If you can provide us with more information about what you're doing to run into this, we can help out more.
