### ISSUE TITLE
Unable to login on azure cli

### ISSUE THREAD

**Issue by himsoftware** [microsoft/vscode-azure-account#979]
Does this occur consistently? 
Repro steps:
1. ctrl + shft+p and select AZ CLI and the new popup open --> login with my credential -> approved the notification through authenticator app ---> and the successfully login and then close the browser---> then VS code unable to login -> Report and issue in vs code flashes.

Action: azure-account.loginToCloud
Error type: Error
Error Message: No response from the server

Version: 0.12.0
OS: win32
OS Release: 10.0.22631
Product: Visual Studio Code
Product Version: 1.87.2
Language: en

<details>
<summary>Call Stack</summary>

```
Logger.createError extension.bundle.js:2:893444
extension.bundle.js:2:906477extension.bundle.js:2:906477
```

</details>

**Comment by alexweininger** [comment]
Which extensions are you using with Azure Account? Please see the new guidance for how to sign in to Azure in VS Code. https://github.com/microsoft/vscode-azureresourcegroups/releases/tag/v0.8.0
