### ISSUE TITLE
Delayed startup causes unresponsive Extension Hots

### ISSUE THREAD

**Issue by davekbell** [Microsoft/vscode-azure-account#98]
- Extension Name: azure-account
- Extension Version: 0.4.3
- OS Version: Darwin x64 18.0.0
- VSCode version: 1.28.0

 We have written the needed data into your clipboard. Please paste:

```json 
{
	"activationTimes": {
		"startup": true,
		"codeLoadingTime": 8389,
		"activateCallTime": 6,
		"activateResolvedTime": 21,
		"activationEvent": "*"
	}
}
```

**Comment by chrmarti** [comment]
Tracked with #97.
