### ISSUE TITLE
not able to login

### ISSUE THREAD

**Issue by seli-equinix** [microsoft/vscode-azure-account#981]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azure-account.loginToCloud
Error type: ERR_HTTP_HEADERS_SENT
Error Message: Cannot write headers after they are sent to the client

Version: 0.12.0
OS: win32
OS Release: 10.0.22631
Product: Visual Studio Code
Product Version: 1.91.1
Language: en

<details>
<summary>Call Stack</summary>

```
AdalAuthProvider.<anonymous> extension.bundle.js:2:2494214
rejected extension.bundle.js:2:2491945
```

</details>

**Comment by alexweininger** [comment]
Hi, please clarify which login method you're using. Also please see [these release notes for how to sign in.](https://github.com/microsoft/vscode-azureresourcegroups/releases/tag/v0.8.0)
