### ISSUE TITLE
Certificate Not Valid Issue on a embedded device

### ISSUE THREAD

**Issue by Shivanshu182002** [microsoft/vscode-azure-account#984]
Does this occur consistently? 
Repro steps:

1.
2.

Action: waitForSubscriptions
Error type: CERT_NOT_YET_VALID
Error Message: request to redacted:url failed, reason: certificate is not yet valid

Version: 0.12.0
OS: linux
OS Release: 5.10.120-tegra
Product: Visual Studio Code
Product Version: 1.91.1
Language: en

<details>
<summary>Call Stack</summary>

```
ClientRequest.<anonymous> extension.bundle.js:2:2819966
```

</details>

**Comment by alexweininger** [comment]
Hi, which extension are you using Azure Account with? Could you share a screenshot?
