### ISSUE TITLE
Azure Sign In to Azure Cloud from Command Palette

### ISSUE THREAD

**Issue by mmentella** [microsoft/vscode-azure-account#985]
Does this occur consistently? Yes
Repro steps:

1. Show Command Palette
2. Choose Azure Sign In to Azure Cloud

Action: azure-account.loginToCloud
Error type: ERR_HTTP_HEADERS_SENT
Error Message: Cannot write headers after they are sent to the client

Version: 0.12.0
OS: win32
OS Release: 10.0.19045
Product: Visual Studio Code
Product Version: 1.91.1
Language: en

<details>
<summary>Call Stack</summary>

```
AdalAuthProvider.<anonymous> extension.bundle.js:2:2494214
rejected extension.bundle.js:2:2491945
```

</details>

**Comment by alangarrison-cbts** [comment]
I'm getting this as well for trying to log in to Azure.

Version: 1.91.1 (user setup)
Commit: f1e16e1e6214d7c44d078b1f0607b2388f29d729
Date: 2024-07-09T22:06:49.809Z
Electron: 29.4.0
ElectronBuildId: 9728852
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Windows_NT x64 10.0.19045

**Comment by alexweininger** [comment]
Hi, @mmentella are you trying to sign into public Azure or a sovereign cloud?

Most extensions have switched away from using Azure Account for authentication and now use the VS Code built-in authentication provider. [Please see these release notes for how to sign in using this new method](https://github.com/microsoft/vscode-azureresourcegroups/releases/tag/v0.8.0).
