### ISSUE TITLE
Azure sign in error "certificate has expired"

### ISSUE THREAD

**Issue by bpwc** [microsoft/vscode-azure-account#989]
Does this occur consistently? Yes
**Repro steps:**
Azure account login. Output console shows
```
[info] Attempting to reach URL "https://login.microsoftonline.com/"...
[error] certificate has expired
```

**Things I tried:**
Just about every related solution to this issue that has been posted in this repo including but not limited to:
1. disabled all extensions and reinstalled MS account and Azure Pipelines extensions
2. used both of these authentication libraries
![image](https://github.com/user-attachments/assets/b2ba95ae-672a-4f96-bba4-9a44e938cd2e)
4. disabled/enabled this setting then restarted VS Code
![image](https://github.com/user-attachments/assets/3dcd6ff5-7070-43ac-9365-113d5ab26c73)
5. disabled/enabled corporate VPN
6. jiggled the power cord
7. tapped the floor with my feet 3 times and clapped once, then clapped 3 times and tapped once.
8. knocked on wood
9. crossed my fingers
10. Wore my lucky socks
11. made a wish and blew out a candle

Note that I'm signed in to my cloud sync account just fine. The issue lies in the Azure sign in. I guess different certificates/IPs/authentication methods for whatever reason are used

Action: azure-account.loginToCloud
Error type: AzureLoginError
Error Message: Offline

Version: 0.12.0
OS: win32
OS Release: 10.0.22621
Product: Visual Studio Code
Product Version: 1.92.0
Language: en

<summary>Call Stack</summary>

```
extension.bundle.js:2:2503574extension.bundle.js:2:2503574
```

**Comment by alexweininger** [comment]
Which extensions are you trying to use with Azure Account? Most Azure extensions have moved off of Azure Account for authentication, and moved to the built-in VS Code Microsoft authentication provider. The Azure Account extension will be deprecated soon. If you're able, uninstall the Azure Account extension.

If you can, try out the new command you can access from the Azure Resources view: <img alt="image" width="432" src="https://private-user-images.githubusercontent.com/12476526/338682216-a8f81504-50a8-4189-93aa-8f6a156cebd6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ5Mzc4ODcsIm5iZiI6MTcyNDkzNzU4NywicGF0aCI6Ii8xMjQ3NjUyNi8zMzg2ODIyMTYtYThmODE1MDQtNTBhOC00MTg5LTkzYWEtOGY2YTE1NmNlYmQ2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI5VDEzMTk0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTczNDA4NjI5MThlYzM0N2M0ZjJkNmE1ZTRmZjE3NDk1OWEzMWJhNmE3YWY0Y2Q2Y2QzMDllZjZlMzUxZDkxYTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.luaFR1l_67JlwxwH8ja7vUOD3-Z2WfB4e3oTTk5GiXg">

* [Read here for more info on the move from Azure Account](https://github.com/microsoft/vscode-azureresourcegroups/releases/tag/v0.8.0)
* And read here about the deprecation: https://github.com/microsoft/vscode-azure-account/issues/964
