### ISSUE TITLE
VSCode Azure Extension Unable to Display Resource Eventhough Logged In

### ISSUE THREAD

**Issue by faidhi066** [microsoft/vscode-azure-account#992]
Does this occur consistently? Yes
Reproduce steps:

1. Open VSCode and azure extension
2. It will load infinitely

<img width="775" alt="image" src="https://github.com/user-attachments/assets/5b12e790-3e1e-4d38-ad82-4094295643c2">

Also, you can see that I managed to login down below in the picture. I'm also behind a corporate vpn and proxy.

Version: 0.12.0
OS: win32
OS Release: 10.0.19045
Product: Visual Studio Code
Product Version: 1.92.1
Language: en

**Comment by alexweininger** [comment]
Which extensions are you trying to use with Azure Account? Most Azure extensions have moved off of Azure Account for authentication, and moved to the built-in VS Code Microsoft authentication provider. The Azure Account extension will be deprecated soon. If you're able, uninstall the Azure Account extension.

The account indicator in the status bar is from Azure Account and should be disregarded. It will go away and stop contradicting the extensions if you uninstall the Azure Account extension.
![image](https://github.com/user-attachments/assets/b1c70b5c-878a-42f0-ad1d-e259087406cc)

* [Read here for more info on the move from Azure Account](https://github.com/microsoft/vscode-azureresourcegroups/releases/tag/v0.8.0)
* And read here about the deprecation: https://github.com/microsoft/vscode-azure-account/issues/964

For the login issues with a corp vpn and proxy, please make sure you've set the related VS Code settings.
<img width="1231" alt="image" src="https://github.com/user-attachments/assets/9cb07926-fdb8-4278-997c-24f40c0ef237">
