### ISSUE TITLE
Cannot list subscriptions

### ISSUE THREAD

**Issue by J3Myers3** [microsoft/vscode-azure-account#993]
- VS Code Version: 1.92.0
- Azure Account Extension Version: 0.12.0
- OS Version: Windows 11

Does your account belong to more than one directory? (see your directories [here](https://aka.ms/AAevnvr)): 

Any other information about your Azure account that may be useful:

**Comment by alexweininger** [comment]
Which extensions are you trying to use with Azure Account? Most Azure extensions have moved off of Azure Account for authentication, and moved to the built-in VS Code Microsoft authentication provider. The Azure Account extension will be deprecated soon. If you're able, uninstall the Azure Account extension.

* [Read here for more info on the move from Azure Account](https://github.com/microsoft/vscode-azureresourcegroups/releases/tag/v0.8.0)
* And read here about the deprecation: https://github.com/microsoft/vscode-azure-account/issues/964
