### ISSUE TITLE
Unable to login azure by vscode

### ISSUE THREAD

**Issue by madanpatakota** [microsoft/vscode-azure-account#999]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azure-account.loginToCloud
Error type: Error
Error Message: AADSTS50139: Session is invalid due to missing an external refresh token. Trace ID: redacted:id Correlation ID: redacted:id Timestamp: redacted:id redacted:id05Z

Version: 0.12.0
OS: win32
OS Release: 10.0.22631
Product: Visual Studio Code
Product Version: 1.93.1
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:2:2545456extension.bundle.js:2:2545456
extension.bundle.js:2:2543039extension.bundle.js:2:2543039
b extension.bundle.js:2:2542725
callback extension.bundle.js:2:2545151
Server.<anonymous> extension.bundle.js:2:2545493
```

</details>

**Comment by alexweininger** [comment]
Hi @madanpatakota, please use 

Which extensions are you trying to use with Azure Account? Most Azure extensions have moved off of Azure Account for authentication, and moved to the built-in VS Code Microsoft authentication provider. The Azure Account extension will be deprecated soon. If you're able, uninstall the Azure Account extension.

If you can, try out the new command you can access from the Azure Resources view or use the "Azure: Sign In" command: 
<img width="436" alt="image" src="https://github.com/user-attachments/assets/44690912-d83b-4ad2-9c99-ccd938ef9740">

* [Read here for more info on the move from Azure Account](https://github.com/microsoft/vscode-azureresourcegroups/releases/tag/v0.8.0)
* And read here about the deprecation: https://github.com/microsoft/vscode-azure-account/issues/964
